### ISSUE TITLE
Calling mktx or mksendmanytx with Trezor results in AttributeError

### ISSUE THREAD

**Issue by chrisrico** [spesmilo/electrum#1056]
I used to get this error when calling wallet.sign_transaction, but I could work around that by setting tx.error = None after construction but before signing. It appears that mktx and mksendmanytx now attempts to sign and complete the transaction? I don't think they used to.

```
>> mktx('some bitcoin address', 1)
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Temp\_MEI61642\gui\qt\main_window.py", line 1757, in <lambda>
    return lambda *args: apply( f, (method, args, self.password_dialog ))
  File "C:\Users\Chris\AppData\Local\Temp\_MEI61642\lib\commands.py", line 130, in _run
    result = f(*args)
  File "C:\Users\Chris\AppData\Local\Temp\_MEI61642\lib\commands.py", line 325, in mktx
    tx = self._mktx([(to_address, amount)], fee, change_addr, domain)
  File "C:\Users\Chris\AppData\Local\Temp\_MEI61642\lib\commands.py", line 322, in _mktx
    return self.wallet.mktx(final_outputs, self.password, fee , change_addr, domain)
  File "C:\Users\Chris\AppData\Local\Temp\_MEI61642\lib\wallet.py", line 757, in mktx
    self.sign_transaction(tx, password)
  File "C:\Users\Chris\AppData\Local\Temp\_MEI61642\plugins\trezor.py", line 326, in sign_transaction
    if tx.error:
AttributeError: Transaction instance has no attribute 'error'
```

**Comment by ecdsa** [comment]
fixed in 21ccb1e82de79ec5277e2f9ec55c30166d7c1475
