### ISSUE TITLE
Load Transaction does not load raw transaction

### ISSUE THREAD

**Issue by will123195** [spesmilo/electrum#1084]
Electrum 2.0.2
OSX 10.9.5

I've tried both:
Tools > Load Transaction > From file
Tools > Load Transaction > From text

I have an unsigned 2-of-3 multisig raw transaction created with a public key from my electrum wallet.  But when I try to load the transaction, nothing happens.

It seems the transaction is successfully parsed (since there is no transaction parse error). 

I'm expecting a window to appear to display the parsed transaction along with a "sign" button, but there is no visible response.

Is this supposed to work? Is there a log file that I can check?

**Comment by ecdsa** [comment]
you can run electrum in verbose mode: "electrum -v" from a terminal

**Comment by ecdsa** [comment]
can you publish the partially signed transaction?

**Comment by will123195** [comment]
raw unsigned transaction:
```
0100000001dc16fbf1902896a7f71ba6c0968d7a49ee022a392c28d0a959b97c43198ef6310000000017a914d251ef996db69d3f876345c8d5abb57c83a4b8db87ffffffff0130e60200000000001976a914209f3febdd4a1969db4728ed8575a847c106183d88ac00000000
```

error message:
```
Dec 31 17:59:59 gadget Electrum[78967] <Notice>: 2015-03-16 11:53:50.835 Electrum[78967:507] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Dec 31 17:59:59 gadget Electrum[78967] <Notice>: cannot find address in input script a914d251ef996db69d3f876345c8d5abb57c83a4b8db87
Dec 31 17:59:59 gadget Electrum[78967] <Notice>: Traceback (most recent call last):
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/main_window.py", line 2280, in do_process_from_text
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:     self.show_transaction(tx)
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/main_window.py", line 601, in show_transaction
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:     d = transaction_dialog.TxDialog(tx, self)
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/transaction_dialog.py", line 108, in __init__
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:     self.update()
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/transaction_dialog.py", line 138, in update
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:     if self.wallet.can_sign(self.tx):
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1015, in can_sign
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:     for x in tx.inputs_to_sign():
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 690, in inputs_to_sign
Dec 31 17:59:59 gadget Electrum[78967] <Notice>:     if len(signatures) == txin['num_sig']:
Dec 31 17:59:59 gadget Electrum[78967] <Notice>: KeyError: 'num_sig'
```

The address `14ZdQYCT3ZQPye8L1PuupGhhQ5APdeJvix` is a "Receiving Address" in Electrum and its pubkey is one of the three pubkeys used to create this 2-of-3 multisig address: `3Ls5yqUvRJQhKdYidZVatioMk6gHJHq3vt`.

**Comment by ecdsa** [comment]
how did you create that transaction? with Electrum?

**Comment by will123195** [comment]
I used bitcoinjs-lib to create the transaction.  I was able to sign the transaction by exporting the private key from electrum. I thought I would be able to sign it using electrum, but maybe I'm doing something wrong?

**Comment by will123195** [comment]
Oh, actually I used the Chain.com API to create this transaction.
https://chain.com/docs/v2/node/#bitcoin-transaction-build

**Comment by ecdsa** [comment]
you have to create it with electrum.
