### ISSUE TITLE
UsbError not found after removing PyUSB dependency

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1104]
After commit 3ae2fb2e90b0296066509d1934d1c24b6333260f fomr @drizzt  was merged, I can't use the HW1 hardware wallet anymore.  I always get a message box telling me that USBError was not found.

**Comment by ecdsa** [comment]
do you have the latest version of btchip-python ?

**Comment by ulrichard** [comment]
Just upgraded python-btchip to the latest version, but the prolem persists. It happens wether the dongle uses the hidapi of the winusb transport.

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 54, in run_hook
    r = f(*args)
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 85, in load_wallet
    if not self.wallet.check_proper_device():
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 449, in check_proper_device
    self.give_error(e, True)
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 133, in give_error
    raise Exception(message)
Exception: global name 'USBError' is not defined

**Comment by ecdsa** [comment]
reverted 3ae2fb2e90b0296066509d1934d1c24b6333260f
