### ISSUE TITLE
stdio gui fails on ubuntu 14.04 server

### ISSUE THREAD

**Issue by Minthos** [spesmilo/electrum#1118]
It works fine with the "text" ui but I get this error when I try to run it with the "stdio" ui:

electrum -g stdio
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 252, in <module>
    gui.main(url)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 170, in main
    while self.done == 0: self.main_command()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 54, in main_command
    self.print_balance()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 119, in print_balance
    print(self.get_balance())
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 122, in get_balance
    if self.wallet.network.interface and self.wallet.network.interface.is_connected:
AttributeError: 'NetworkProxy' object has no attribute 'interface'

**Comment by ecdsa** [comment]
fixed 9e5cf68e93b9b7ab7b534cb4dce2fb6dabe86ca2
