### ISSUE TITLE
merchant.py: Error when requesting payment

### ISSUE THREAD

**Issue by Minthos** [spesmilo/electrum#1122]
```
$ python merchant.py request 0.1 1 2
Traceback (most recent call last):
  File "merchant.py", line 255, in <module>
    ret = send_command(cmd, params)
  File "merchant.py", line 165, in send_command
    out = f(*params)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 225, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 529, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/Electrum-2.1-py2.7.egg/electrum/account.py", line 43, in get_address | IndexError: list index out of range')
```

```
$ cat merchant.conf
[main]
host = 192.168.1.115
port = 8081
password = kek

[sqlite3]
database = /home/www/bmmerchant/db.sqlite

[electrum]
xpub = xpub661MyMwAqRbcFkcGVePtTdcEK1tL7jQeJrjimM1b4BMRDgMUfkupR4k6f68qrLBssoGF4k2xpkJSqUUcnQQUmGkahpZwrxdqioqtqA9LCta
wallet_path = /home/www/bmmerchant/hotwallet1

[callback]
received = http://10.0.0.9/gotpaid
expired = http://10.0.0.9/notpaid
password = kek
```

**Comment by Minthos** [comment]
Never mind, duplicate.
