### ISSUE TITLE
Can't start electrum - '/etc/ssl/certs/' is a directory

### ISSUE THREAD

**Issue by etam** [spesmilo/electrum#1196]
I'm using electrum 2.1.1 on openSUSE 13.2 from https://build.opensuse.org/package/show/home:marec2000:cryptocoins/electrum

And this is what happens:

    etam@etam-laptop:~> electrum 
    Traceback (most recent call last):
      File "/usr/bin/electrum", line 234, in <module>
        gui = __import__('electrum_gui.' + gui_name, fromlist=['electrum_gui'])
      File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 49, in <module>
        from main_window import ElectrumWindow
      File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 81, in <module>
        from electrum.paymentrequest import PR_UNPAID, PR_PAID, PR_EXPIRED
      File "/usr/lib/python2.7/site-packages/electrum/paymentrequest.py", line 47, in <module>
        ca_list, ca_keyID = x509.load_certificates(ca_path)
      File "/usr/lib/python2.7/site-packages/electrum/util.py", line 90, in <lambda>
        return lambda *args: do_profile(func, args)
      File "/usr/lib/python2.7/site-packages/electrum/util.py", line 86, in do_profile
        o = apply(func, args)
      File "/usr/lib/python2.7/site-packages/electrum/x509.py", line 205, in load_certificates
        with open(ca_path, 'r') as f:
    IOError: [Errno 21] Is a directory: '/etc/ssl/certs/'

**Comment by ecdsa** [comment]
please use the official packages.

**Comment by etam** [comment]
It is the official package, packed nicely into rpm. There are no patches nor any modifications.

**Comment by etam** [comment]
Hmm... I've downloaded the official package, unpacked and run from unpacked sources (without installation) and it works. I'll try to gather more info, why the packaged version does not work.

**Comment by etam** [comment]
I've found the problem. Reported on openSUSE bugzilla: https://bugzilla.opensuse.org/show_bug.cgi?id=929773
