### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by winsvega** [spesmilo/electrum#1274]
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 482, in timer_actions
    self.update_wallet()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 547, in update_wallet
    self.update_status()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 523, in update_status
    text =  _("Balance" ) + ": %s "%(self.format_amount(c)) + self.base_unit()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)

Using Ubuntu x64

**Comment by Perlover** [comment]
After upgrade from 2.0.4 to 2.2 my Electrum doesn't work
locale is ru_RU.UTF-8
I think i use russian langauge characters in labels
But it's not prohhibeted

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 482, in timer_actions
    self.update_wallet()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 547, in update_wallet
    self.update_status()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 523, in update_status
    text =  _("Balance" ) + ": %s "%(self.format_amount(c)) + self.base_unit()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 482, in timer_actions
    self.update_wallet()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 547, in update_wallet
    self.update_status()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 523, in update_status
    text =  _("Balance" ) + ": %s "%(self.format_amount(c)) + self.base_unit()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 482, in timer_actions
    self.update_wallet()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 547, in update_wallet
    self.update_status()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 523, in update_status
    text =  _("Balance" ) + ": %s "%(self.format_amount(c)) + self.base_unit()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3: ordinal not in range(128)
^CTraceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 482, in timer_actions
    self.update_wallet()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 547, in update_wallet
    self.update_status()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 523, in update_status
    text =  _("Balance" ) + ": %s "%(self.format_amount(c)) + self.base_unit()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3: ordinal not in range(128)
```

**Comment by ecdsa** [comment]
@kyuupichan this is probably caused by the changes to format_amount (using locale)

**Comment by kyuupichan** [comment]
I'll take a look in the next 24 hrs.

**Comment by ecdsa** [comment]
I pushed a fix, but it will work only if the locale is utf8
(ru_RU.utf8 in the present case)
It still fails with ru_RU
