### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'lower'

### ISSUE THREAD

**Issue by pymander** [spesmilo/electrum#1283]
I just installed the latest version of Electrum via the website instructions on my Ubuntu box, like so:

    sudo pip install https://download.electrum.org/Electrum-2.2.tar.gz

However, the resulting program causes this backtrace and won't run:

```
$ electrum
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 244, in <module>
    network = NetworkProxy(s, config)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network_proxy.py", line 57, in __init__
    self.network = Network(config)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 172, in __init__
    self.set_proxy(deserialize_proxy(self.config.get('proxy')))
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 97, in deserialize_proxy
    if s.lower() == 'none':
AttributeError: 'dict' object has no attribute 'lower'

**Comment by pymander** [comment]
Ah, it appears this was a result of upgrading from Electrum 1.9. However, a nicer error message would be great.

**Comment by iceTwy** [comment]
@pymander: what did you do to fix this issue?

**Comment by pymander** [comment]
I removed my proxy configuration manually from the config file.
