### ISSUE TITLE
Electrum 2.3.3 - after a quit there are more errors in console

### ISSUE THREAD

**Issue by Perlover** [spesmilo/electrum#1325]
```
Traceback (most recent call last):Traceback (most recent call last):


  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_innerTraceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Traceback (most recent call last):


  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 323, in run  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 323, in run
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner


  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 302, in get_and_process_response  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 323, in run  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 302, in get_and_process_response
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 323, in run


<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 302, in get_and_process_response<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 302, in get_and_process_response



<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'

**Comment by Perlover** [comment]
The OS is Ubuntu 14.04 LTS with last updates
Today i upgraded Electrum to 2.3.3 by sudo pip install...
After i recreated new hardware wallet (Trezor) and after quit i got these errors (above)

**Comment by kyuupichan** [comment]
This is after shutdown right?  This is expected, but harmless, as we don't wait for network threads to shutdown cleanly.  We could do so, but that might mean a wait of 10 or more seconds whilst a connection times out.

**Comment by ecdsa** [comment]
I reintroduced a time.sleep e2185da0942e3d5d57bc76d38498269ffb27a735

**Comment by Perlover** [comment]
May be is the best way to cover the code (closing sockets) in try/cathc constructions? This timeout may be small for some situations but if some exceptions will occur here and they are not critical may be they shuold be ignored?
