### ISSUE TITLE
'ImportedAccount' object has no attribute 'get_master_pubkeys'

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1344]
trying to open a wallet with view-only addresses I get this error:

```
No systemtrayicon available
Traceback (most recent call last):
  File "./electrum", line 410, in <module>
    args.func(config)
  File "./electrum", line 129, in run_gui
    gui.main(url)
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/__init__.py", line 219, in main
    w.load_wallet(wallet)
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/main_window.py", line 207, in load_wallet
    self.update_wallet_format()
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/main_window.py", line 258, in update_wallet_format
    if self.wallet.get_master_public_keys() and self.wallet.addresses() == []:
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/wallet.py", line 1523, in get_master_public_keys
    mpk_text = '\n\n'.join( account.get_master_pubkeys() )
AttributeError: 'ImportedAccount' object has no attribute 'get_master_pubkeys'
```

**Comment by ecdsa** [comment]
@molecular please test this fix

**Comment by molecular** [comment]
fix fixed the issue, thanks!
