### ISSUE TITLE
Transport endpoint not connected

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1351]
After having electrum run for roughly a day, I noticed the network info status line says: "server is lagging 191 blocks" and the indicator icon is reddish color. I see loads of these (different thread ids):

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/interface.py", line 324, in run
    s.shutdown(socket.SHUT_RDWR)
  File "/usr/lib64/python2.7/ssl.py", line 760, in shutdown
    socket.shutdown(self, how)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/interface.py", line 324, in run
    s.shutdown(socket.SHUT_RDWR)
  File "/usr/lib64/python2.7/ssl.py", line 760, in shutdown
    socket.shutdown(self, how)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/interface.py", line 324, in run
    s.shutdown(socket.SHUT_RDWR)
  File "/usr/lib64/python2.7/ssl.py", line 760, in shutdown
    socket.shutdown(self, how)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```

After restarting electrum, all is fine (server is not really lagging)

Note: I'm on a dynamic IP dsl line that reconnects every 24 hours, in case that's somehow relevant.

I'm on 0368a2cd5e48e98c34bce13aa5f9a15f3ab806d5

**Comment by molecular** [comment]
this just reoccured after about 3 days of idle client

**Comment by EagleTM** [comment]
Do you have auto-connect enabled or do you use one specific server like electrum.be (which had some lagging issues lately)

**Comment by kyuupichan** [comment]
Doors this still happen? I recall fixing that socket close a while ago. I suspect this can be closed.

**Comment by EagleTM** [comment]
I'm seconding to close for now and am doing it...
