### ISSUE TITLE
Fixup keys UnicodeDecodeError

### ISSUE THREAD

**Issue by skrat** [spesmilo/electrum#1358]
This is what I get after upgrading to git HEAD version

```
￼ Traceback (most recent call last):
  File "/usr/bin/electrum", line 399, in <module>
    config = SimpleConfig(config_options)
  File "/usr/lib/python2.7/site-packages/electrum/simple_config.py", line 68, in __init__
    self.fixup_keys({'auto_cycle': 'auto_connect'})
  File "/usr/lib/python2.7/site-packages/electrum/simple_config.py", line 101, in fixup_keys
    self.save_user_config()
  File "/usr/lib/python2.7/site-packages/electrum/simple_config.py", line 130, in save_user_config
    s = json.dumps(self.user_config, indent=4, sort_keys=True)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa8 in position 0: invalid start byte
```

**Comment by skrat** [comment]
Found this in `.electrum/config`
```
... 'web_password': '\xa8\xe4Q\x0cG\...
```
What is `web_password`? Can I simply delete that K/V from `config`?

**Comment by ecdsa** [comment]
I don't know what that is.
I would try to delete it, indeed

**Comment by skrat** [comment]
I just did and it solved the issue. No idea how it got there.

**Comment by ecdsa** [comment]
maybe you installed a plugin not in the official repo?

**Comment by skrat** [comment]
No idea, something is telling me that long long time ago I attempted to create web UI on top of Electrum.
