### ISSUE TITLE
Daemon prone to dying

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1373]
Here's one such log I'll fix:

[blockchain] connected at height: 366205
pipe: socket error [Errno 54] Connection reset by peer
[erbium1.sytes.net] connection closed remotely
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/neil/src/electrum/lib/network.py", line 671, in run
    self.wait_on_sockets()
  File "/home/neil/src/electrum/lib/network.py", line 665, in wait_on_sockets
    self.process_responses(interface)
  File "/home/neil/src/electrum/lib/network.py", line 452, in process_responses
    self.connection_down(interface.server)
  File "/home/neil/src/electrum/lib/network.py", line 512, in connection_down
    self.close_interface(self.interfaces[server])
  File "/home/neil/src/electrum/lib/network.py", line 390, in close_interface
    interface.close()
  File "/home/neil/src/electrum/lib/interface.py", line 238, in close
    self.socket.shutdown(socket.SHUT_RDWR)
  File "/usr/local/lib/python2.7/ssl.py", line 760, in shutdown
    socket.shutdown(self, how)

**Comment by kyuupichan** [comment]
Just noticed this is with my select changes; this may not occur normally

**Comment by kyuupichan** [comment]
This looks to be select-specific; so I'm closing
