### ISSUE TITLE
Timeout while waiting for magic character, Exception: got PublicKey, expected Success

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1374]
tried to make a tx and got a popup saying " Got <class 'trezorlib.messages_pb2.PublicKey'>, expected (<class 'trezorlib.messages_pb2.Success'>,)"
```
Traceback (most recent call last):
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/plugins.py", line 121, in _run_hook
    r = f(*args)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 146, in load_wallet
    if self.wallet.addresses() and not self.wallet.check_proper_device():
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 495, in check_proper_device
    self.get_client().ping('t')
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 68, in wrapped_f
    ret = f(*args, **kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 82, in wrapped_f
    ret = f(*args, **kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 413, in ping
    return self.call(msg)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 120, in call
    resp = self.call_raw(msg)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 659, in call_raw
    resp = BaseClient.call_raw(self, msg)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 110, in call_raw
    resp = self.transport.read_blocking()
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/transport.py", line 90, in read_blocking
    data = self._read()
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/transport_hid.py", line 112, in _read
    (msg_type, datalen) = self._read_headers(FakeRead(self._raw_read))
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/transport.py", line 117, in _read_headers
    raise Exception("Timed out while waiting for the magic character")
Exception: Timed out while waiting for the magic character
Traceback (most recent call last):
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/util.py", line 41, in run
    self.result = self.run_task()
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/main_window.py", line 1248, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 467, in sign_transaction
    if not self.check_proper_device():
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 495, in check_proper_device
    self.get_client().ping('t')
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 68, in wrapped_f
    ret = f(*args, **kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 84, in wrapped_f
    raise Exception("Got %s, expected %s" % (ret.__class__, self.expected))
Exception: Got <class 'trezorlib.messages_pb2.PublicKey'>, expected (<class 'trezorlib.messages_pb2.Success'>,)
```

when trying to sign a transaction.

up to that point everything was fine (pin entry, passphrase entry, synchronizing)

I'm up-to-date:

electrum: master a1f67e3fff385d965da1f9d30c1653a17383146e
python-trezor: 80723b370d7c6351c2c1fd4510a60c7c0e44da96
trezor firmware: 1.3.3

**Comment by molecular** [comment]
sorry, seems I forgot to build trezorlib, now I get a different error
