### ISSUE TITLE
trezor: tag had invalid wire type

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1375]
trying to make a tx, I get a popup:

![2015-07-23-070748_236x97_scrot](https://cloud.githubusercontent.com/assets/589745/8843503/88e5282a-3109-11e5-8197-4bb53c2f7e42.png)

```
Traceback (most recent call last):
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/util.py", line 41, in run
    self.result = self.run_task()
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/main_window.py", line 1248, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 467, in sign_transaction
    if not self.check_proper_device():
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 495, in check_proper_device
    self.get_client().ping('t')
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 70, in wrapped_f
    ret = f(*args, **kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 84, in wrapped_f
    ret = f(*args, **kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 415, in ping
    return self.call(msg)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 122, in call
    resp = self.call_raw(msg)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 659, in call_raw
    resp = BaseClient.call_raw(self, msg)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 112, in call_raw
    resp = self.transport.read_blocking()
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/transport.py", line 94, in read_blocking
    return self._parse_message(data)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/transport.py", line 102, in _parse_message
    inst.ParseFromString(data)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/message.py", line 182, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/internal/python_message.py", line 795, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib64/python2.7/site-packages/google/protobuf/internal/python_message.py", line 819, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/internal/decoder.py", line 716, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/internal/decoder.py", line 685, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
DecodeError: Tag had invalid wire type.
```

electrum: master a1f67e3fff385d965da1f9d30c1653a17383146e
python-trezor: 80723b370d7c6351c2c1fd4510a60c7c0e44da96
trezor firmware: 1.3.3
protobuf: 2.5.0-r2

**Comment by molecular** [comment]
I went back to my beloved tag 2.0b3 and everything works fine (same python-trezor and firmware, of course)

**Comment by ecdsa** [comment]
do you still have this with recent git head?
I never reproduced that

**Comment by nomnombtc** [comment]
If it is the same issue I had earlier: https://bitcointalk.org/index.php?topic=973768.msg10872035#msg10872035

Try to create a new electrum wallet from your trezor, that worked for me.
Somehow there was a change, in the wallet file nextaccount was renamed to nextaccount2, which caused this somehow.

**Comment by ecdsa** [comment]
ok, I will just assume it is the same issue, and close that bug.
