### ISSUE TITLE
Cant sweep priv-key in 2.4

### ISSUE THREAD

**Issue by aprekates** [spesmilo/electrum#1387]
Trying to sweep a private key (that i got from a bitcoin core wallet ) i get:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 2482, in sweep_key_dialog
    self.show_transaction(tx)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 589, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/transaction_dialog.py", line 37, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/transaction_dialog.py", line 48, in __init__
    self.tx.deserialize()
AttributeError: 'NoneType' object has no attribute 'deserialize'

**Comment by ecdsa** [comment]
I guess your coins were unconfirmed. 
see fix
