### ISSUE TITLE
cannot initialize Keepkey and Trezor plugins at the same time

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#1414]
@dstanchfield can you fix that please?

```
Loading plugin by constructor: keepkey
Traceback (most recent call last):
  File "/home/voegtlin/electrum/lib/plugins.py", line 57, in plugin_loader
    p = loader(name)
  File "/home/voegtlin/electrum/lib/plugins.py", line 71, in <lambda>
    loader = lambda name: imp.load_source('electrum_plugins.' + name, os.path.join(pathname, name + '.py'))
  File "/home/voegtlin/electrum/plugins/keepkey.py", line 29, in <module>
    from keepkeylib.client import types
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/client.py", line 7, in <module>
    import mapping
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/mapping.py", line 1, in <module>
    import messages_pb2 as proto
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/messages_pb2.py", line 12, in <module>
    import types_pb2
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/types_pb2.py", line 979, in <module>
    google.protobuf.descriptor_pb2.EnumValueOptions.RegisterExtension(wire_in)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 569, in RegisterExtension
    cls.DESCRIPTOR.full_name, extension_handle.number))
AssertionError: Extensions "wire_in" and "wire_in" both try to extend message type "google.protobuf.EnumValueOptions" with field number 50002.
```

**Comment by ecdsa** [comment]
it occured in tests where I am trying to initialize hardware wallets plugins, in order to display only the ones that are available in the install wizard.

it also occurs if I open a trezor wallet, then a keepkey wallet, in the same GUI session.

**Comment by dstanchfield** [comment]
This is being caused by our protocol buffers colliding with Trezor's trying to extend the same field numbers.  I adjusted our protocol buffers to a different range.  You'll need to pull the latest python-keepkey to see this issue resolved.  Good find!

**Comment by ecdsa** [comment]
thanks
