### ISSUE TITLE
Invalid Fee error message when creating new Tx 

### ISSUE THREAD

**Issue by albrechta** [spesmilo/electrum#1416]
I have set up a two-factor authentication wallet with electrum 2.4.3, which currently has a balance of 10 mBTC. Electrum shows the following error message when I try sending 5 mBTC:
"Invalid Fee".

The following exceptions are thrown:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 542, in timer_actions
    self.do_update_fee()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 1112, in do_update_fee
    tx = self.wallet.make_unsigned_transaction(self.get_coins(), outputs, self.config, fee)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 910, in make_unsigned_transaction
    fee = fixed_fee if fixed_fee is not None else self.estimated_fee(tx, fee_per_kb)
TypeError: estimated_fee() takes exactly 2 arguments (3 given)
 ```

Screenshot:
![electrum](https://cloud.githubusercontent.com/assets/8121823/9427892/853df83e-4994-11e5-9ca1-6429e443d113.png)

**Comment by ecdsa** [comment]
fixed; I will do a bugfix release

**Comment by ecdsa** [comment]
done. see version 2.4.4
