### ISSUE TITLE
listrequests crashes

### ISSUE THREAD

**Issue by tl121** [spesmilo/electrum#1455]
Attempting to have electrum  accept bitcoin from a website, per the wiki.
The functions addrequest and listrequest work OK with daemon.  However, when I perform an addrequest from the jsonRPC the request works OK and generates the web page, but a subsequent attempt to run listrequests crashes.  (This after exiting electrum and running it with the daemon again.). The requests database has been put into such a state that listrequests will not work until the wallet is restored to its original condition. 

The PhP code was 
require_once 'jsonRPCClient.php';
 $electrum  = new jsonRPCClient('http://127.0.0.1:7777/');
$foo = $electrum->addrequest("6");

The following is a traceback
$ electrum listrequests
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 343, in run_cmdline
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/commands.py", line 70, i                          n func_wrapper
    return func(*args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/commands.py", line 569,                           in listrequests
    out = self.wallet.get_sorted_requests(self.config)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1358, i                          n get_sorted_requests
    return sorted(map(lambda x: self.get_payment_request(x, config), self.receiv                          e_requests.keys()), key=lambda x: x.get('time', 0))
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1358, i                          n <lambda>
    return sorted(map(lambda x: self.get_payment_request(x, config), self.receiv                          e_requests.keys()), key=lambda x: x.get('time', 0))
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1264, i                          n get_payment_request
    out['URI'] = 'bitcoin:' + addr + '?amount=' + util.format_satoshis(out.get('                          amount'))
  File "/usr/local/lib/python2.7/dist-packages/electrum/util.py", line 124, in f                          ormat_satoshis
    x = int(x)  # Some callers pass Decimal
ValueError: invalid literal for int() with base 10: '6. BTC'

**Comment by tl121** [comment]
If one or two payment requests have been made since the wallet was created, then a similar problem exists when trying to run electrum from the GUI off the same wallet.  Nothing happens when starting from an icon.  When starting from a command prompt, the error traceback mentioned above appears.

(Deleting the wallet file and recovering from the master public key allows electrum to run again, but of course any new requests will hit duplicate addresses.)

**Comment by ecdsa** [comment]
should be fixed now
