### ISSUE TITLE
IPv6 address

### ISSUE THREAD

**Issue by petrkr** [spesmilo/electrum#1463]
There is bug while setting IPv6 address:

```
[Network] starting ::1:50001:t; will switch once connected
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/electrum/network.py", line 602, in run
    self.check_interfaces()
  File "/usr/lib/python2.7/site-packages/electrum/network.py", line 516, in check_interfaces
    self.switch_to_interface(self.default_server)
  File "/usr/lib/python2.7/site-packages/electrum/network.py", line 362, in switch_to_interface
    self.start_interface(server)
  File "/usr/lib/python2.7/site-packages/electrum/network.py", line 286, in start_interface
    i = interface.Interface(server, self.queue, self.config)
  File "/usr/lib/python2.7/site-packages/electrum/interface.py", line 46, in Interface
    host, port, protocol = server.split(':')
ValueError: too many values to unpack
```

**Comment by abitfan** [comment]
electrum doesn't support IPV6 yet
