### ISSUE TITLE
stuck after error in transaction

### ISSUE THREAD

**Issue by zkpznpm** [spesmilo/electrum#1520]
electrum 2.5.1 / 2.4.0

electrum 2.4.0 last send transaction didn’t finish.
Stuck at "synchronising". No network traffic.
Several restarts did not change anything.
Things I tried to get my wallet working again:
- Upgrade electrum to 2.5.1
- Deleted and reloaded  blockchain_headers

2.5.1 verbose output:

[xxxxxxx.xxx] connected
[Blockchain] validated chunk 182 to height 368927
[electrum.be] requesting chunk 183
[Synchronizer] receiving history xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[default_wallet] removing tx from history zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 723, in run
    self.wait_on_sockets()
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 717, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 531, in process_responses
    self.process_response(interface, response, callback)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 493, in process_response
    callback(response)
  File "/usr/local/lib/python2.7/dist-packages/electrum/synchronizer.py", line 110, in addr_history_response
    self.wallet.receive_history_callback(addr, hist)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 791, in receive_history_callback
    self.remove_transaction(tx_hash)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 775, in remove_transaction
    except KeyErrror:
NameError: global name 'KeyErrror' is not defined

How can I fix my wallet ?

**Comment by ecdsa** [comment]
that was fixed here: fc141cba289421a8349d2d68b4ffdfccf47d2a57
in the electrum console, type wallet.clear_history() and restart electrum

**Comment by zkpznpm** [comment]
wallet.clear_history() at console & restart electrum fixed the problem.
Thanks a lot.
Wouldn’t it a good idea to make this fix somehow better visible and probable find-able from Google ?

**Comment by ecdsa** [comment]
I will do a bugfix release, probably today
