### ISSUE TITLE
getaddressbalance exception

### ISSUE THREAD

**Issue by NiExTy** [spesmilo/electrum#1524]
When trying to get address balance with Electrum 2.5.2 it is giving error.

``$ electrum getaddressbalance ADDRESS``

```python
Traceback (most recent call last):File "/usr/local/bin/electrum", line 319, in run
    response = run_command(config, self.network, password)
  File "/usr/local/bin/electrum", line 265, in run_command
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/commands.py", line 70, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/electrum/commands.py", line 296, in getaddressbalance
    out = self.network.synchronous_get(('blockchain.address.get_balance', [address]))
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 760, in synchronous_get
    raise BaseException(r.get('error'))
BaseException: 'Node' object is not subscriptable
```

**Comment by ecdsa** [comment]
this is a server bug. it's fixed with ecdsa.net 61310e3f6a51102b75466f357568327b4a9260df
