### ISSUE TITLE
cannot load ledger wallet with current git head

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1565]
When trying to load a wallet for my HW1, I get a message box and when I click ok, the application closes. 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/richi/sourcecode/electrum/lib/network.py", line 747, in run
    self.wait_on_sockets()
  File "/home/richi/sourcecode/electrum/lib/network.py", line 736, in wait_on_sockets
    rout, wout, xout = select.select(rin, win, [], 0.1)
error: (4, 'Unterbrechung w\xc3\xa4hrend des Betriebssystemaufrufs')

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./electrum", line 339, in run
    connection, address = s.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 4] Unterbrechung während des Betriebssystemaufrufs

"sni-qt/7570" WARN  21:06:21.119 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Error: cannot initialize plugin ledger
Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 64, in load_plugin
    p = pkgutil.find_loader(full_name).load_module(full_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/richi/sourcecode/electrum/plugins/ledger/qt.py", line 5, in <module>
    class Plugin(LedgerPlugin):
NameError: name 'LedgerPlugin' is not defined
Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/__init__.py", line 147, in load_wallet_file
    wallet = Wallet(storage)
  File "/home/richi/sourcecode/electrum/lib/wallet.py", line 1969, in __new__
    return WalletClass(storage)
  File "/home/richi/sourcecode/electrum/lib/wallet.py", line 1954, in <lambda>
    WalletClass = lambda storage: apply(loader().constructor, (storage,))
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 116, in <lambda>
    x += (lambda: self.wallet_plugin_loader(config, name),)
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 112, in wallet_plugin_loader
    return self.plugins[name]
KeyError: 'ledger'

The last good revision where I can load the wallet is : git#2c0489c8094b2ba9409ae0e36bfe674ce327d883

**Comment by ecdsa** [comment]
fixed in d5f43610ed73cbe58c796d698929c67dbefbd598

**Comment by ecdsa** [comment]
thanks for testing, btw
