### ISSUE TITLE
cannot import name make_password_dialog  [btchip]

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1591]
When I try to start electrum regardless of which wallet file I choose or was last opened, I get the following : 

Traceback (most recent call last):
  File "./electrum", line 328, in <module>
    plugins = Plugins(config, is_bundle or is_local or is_android, gui_name)
  File "/home/richi/sourcecode/electrum/lib/util.py", line 165, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/home/richi/sourcecode/electrum/lib/util.py", line 161, in do_profile
    o = func(*args, **kw_args)
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 45, in __init__
    m = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 10, in <module>
ImportError: cannot import name make_password_dialog

**Comment by ulrichard** [comment]
Hmmm, interesting ...   I had to      rm plugins/*.pyc

**Comment by kyuupichan** [comment]
Yeah I've had similar recently.  It's because I've been moving code around.  I'm closing as it doesn't sound like this issue is permanent.
