### ISSUE TITLE
Restore from trezor seed results in: TypeError: must be unicode, not str

### ISSUE THREAD

**Issue by nomnombtc** [spesmilo/electrum#1620]
Hello,

if you create a new wallet, select restore -> hardwarewallet -> trezor
It asks for the trezor seed, I enter it, click next, I have no passphrase so click ok, I don't want to set a password for the electrum wallet and click ok again and it results in this:

Plugin error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/electrum/plugins.py", line 169, in _run_hook
    r = f(*args)
  File "/usr/lib64/python2.7/site-packages/electrum_plugins/trezor.py", line 169, in installwizard_restore
    wallet.add_cosigner_seed(seed, 'x/', password, passphrase)
  File "/usr/lib64/python2.7/site-packages/electrum/wallet.py", line 1641, in add_cosigner_seed
    xprv, xpub = bip32_root(self.mnemonic_to_seed(seed, passphrase))
  File "/usr/lib64/python2.7/site-packages/electrum_plugins/trezor.py", line 401, in mnemonic_to_seed
    passphrase = unicodedata.normalize('NFKD', passphrase)
TypeError: must be unicode, not str
no wallet
Daemon exiting
[Network] stopping network
[Network] stopped

Electrum version is: 2.5.4.

**Comment by nomnombtc** [comment]
Ok sorry, issue seems already fixed in current git. Closing.
