### ISSUE TITLE
electrum create problem

### ISSUE THREAD

**Issue by tonymontana** [spesmilo/electrum#1622]
Hi. I just installed electrum 2.6 on my server where Debian wheezy installed. I try to set up the merchant on my web site. After install I run electrum create and see:
```
electrum create
Error: Cannot read config file. /root/.electrum
Password (hit return if you do not wish to encrypt your wallet):
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 5, in <module>
    pkg_resources.run_script('Electrum==2.6', 'electrum')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.6-py2.7.egg/EGG-INFO/scripts/electrum", line 330, in <module>
    run_non_RPC(config)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.6-py2.7.egg/EGG-INFO/scripts/electrum", line 145, in run_non_RPC
    wallet.create_main_account(password)
TypeError: create_main_account() takes exactly 1 argument (2 given)
```

**Comment by ecdsa** [comment]
thanks, fixed
