### ISSUE TITLE
A couple of exceptions I've seen recently

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1624]
The network code hasn't changed for a while, so these are surprising.  Just noting them here for later reference:

[JElectrum.jdubya.info] requesting chunk 194
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/neil/src/electrum/lib/network.py", line 754, in run
    self.wait_on_sockets()
  File "/Users/neil/src/electrum/lib/network.py", line 748, in wait_on_sockets
    self.process_responses(interface)
  File "/Users/neil/src/electrum/lib/network.py", line 544, in process_responses
    self.process_response(interface, response, callbacks)
  File "/Users/neil/src/electrum/lib/network.py", line 491, in process_response
    self.on_get_chunk(interface, response)
  File "/Users/neil/src/electrum/lib/network.py", line 663, in on_get_chunk
    idx = self.blockchain.connect_chunk(req_idx, response['result'])
KeyError: 'result'

Another one:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/neil/src/electrum/lib/network.py", line 753, in run
    self.maintain_sockets()
  File "/home/neil/src/electrum/lib/network.py", line 614, in maintain_sockets
    self.connecting.remove(server)
KeyError: 'Electrum.hsmiths.com:995:s'

**Comment by kyuupichan** [comment]
I wonder if the first was fixed by https://git.io/v2Nvv ?

**Comment by bauerj** [comment]
I think these should be fixed by now 😃
