### ISSUE TITLE
can't sign with trezor on current git head

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1632]
When I try to sign a tx with trezor, I get the following : 

"sni-qt/8812" WARN  22:12:20.465 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 232, in run
    self.result = self.task()
  File "/home/richi/sourcecode/electrum/gui/qt/main_window.py", line 1269, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 161, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 353, in sign_transaction
    signed_tx = client.sign_tx('Bitcoin', inputs, outputs)[1]
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 178, in wrapped
    raise e
Exception: TX_API not defined

I figured out that I had an old python-trezor, but upgrading to the newest version didn't change this behavior.

**Comment by kyuupichan** [comment]
Thanks for the report; this is mine.
