### ISSUE TITLE
v2.6 - Trezor file won't load on startup

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1637]
OSX 10.11.2 (El Capitan) - Electrum latest git pull (v2.6).  

Upon starting Electrum, if the default wallet is a Trezor type - Electrum crashes with:

v2.5.4 works ok. 

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 5, in <module>
   pkg_resources.run_script('Electrum==2.6', 'electrum')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/EGG-INFO/scripts/electrum", line 350, in <module>
    gui.main()
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/__init__.py", line 185, in main
    self.config.get('url')):
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/__init__.py", line 157, in start_new_window
    wallet = self.daemon.load_wallet(path, self.get_wizard)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/daemon.py", line 131, in load_wallet
    wallet = Wallet(storage)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/wallet.py", line 1948, in __new__
    wallet = WalletClass(storage)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/plugins.py", line 125, in dynamic_constructor
    return self.wallet_plugin_loader(name).wallet_class(storage)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/plugins.py", line 135, in wallet_plugin_loader
    return self.plugins[name]
KeyError: 'trezor'

**Comment by kyuupichan** [comment]
Can you try again or provide the backtrace that appeared before that one?  When a plugin fails to load there are typically 2, and the 1st is the interesting one.  I just tried opening a trezor wallet and it was fine (with commit 144f53be1845db3fc839fd0c9509602c6a8f4693 on HEAD).

**Comment by ELM4Ever** [comment]
Sorry about that.  Here it is, after performing the latest pull this morning:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/plugins.py", line 71, in load_plugin
    p = pkgutil.find_loader(full_name).load_module(full_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/qt.py", line 1, in <module>
    from ..trezor.qt_generic import qt_plugin_class
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/qt_generic.py", line 3, in <module>
    from PIL import Image
ImportError: No module named PIL
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/__init__.py", line 157, in start_new_window
    wallet = self.daemon.load_wallet(path, self.get_wizard)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/daemon.py", line 131, in load_wallet
    wallet = Wallet(storage)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/wallet.py", line 1946, in __new__
    wallet = WalletClass(storage)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/plugins.py", line 125, in dynamic_constructor
    return self.wallet_plugin_loader(name).wallet_class(storage)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/plugins.py", line 135, in wallet_plugin_loader
    return self.plugins[name]
KeyError: 'trezor'

**Comment by ELM4Ever** [comment]
I have never seen this module "PIL" being mentioned before...   I went and installed py-pil, but it didn't change anything.

**Comment by usezfsyo** [comment]
Try installing from http://pythonware.com/products/pil/

**Comment by usezfsyo** [comment]
Here is the commit that added the PIL import: https://github.com/spesmilo/electrum/commit/a3bced210d8b66fc52ecf6ddaae63daa4fae0f44

**Comment by ELM4Ever** [comment]
Ok - installed PIL directly from pythonware.  Got rid of the errors above, but now it can't see the Trezor when I try to load the wallet.  I have checked the communication independently with the python-trezor commands and it works - but not with Electrum.  I get this instead:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/plugins.py", line 160, in run_hook
    r = f(*args)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/qt_generic.py", line 235, in load_wallet
    self.get_client(wallet)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/plugin.py", line 242, in get_client
    raise DeviceDisconnectedError(msg)
DeviceDisconnectedError: Could not connect to your Trezor.  Verify the cable is connected and that no other app is using it.
Continuing in watching-only mode until the device is re-connected.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/main_window.py", line 511, in timer_actions
    self.update_wallet()
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/main_window.py", line 588, in update_wallet
    self.check_next_account()
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/main_window.py", line 1953, in check_next_account
    self.create_next_account()
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/main_window.py", line 1154, in request_password
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_gui/qt/main_window.py", line 1960, in create_next_account
    self.wallet.create_next_account(password)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum/wallet.py", line 1726, in create_next_account
    xpub, xprv = self.derive_xkeys(root_name, derivation, password)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/plugin.py", line 104, in derive_xkeys
    xpub = self.get_public_key(derivation)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/plugin.py", line 108, in get_public_key
    client = self.get_client()
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/plugin.py", line 90, in get_client
    return self.plugin.get_client(self, force_pair)
  File "/Library/Python/2.7/site-packages/Electrum-2.6-py2.7.egg/electrum_plugins/trezor/plugin.py", line 242, in get_client
    raise DeviceDisconnectedError(msg)
electrum_plugins.trezor.plugin.DeviceDisconnectedError: Could not connect to your Trezor.  Verify the cable is connected and that no other app is using it.
Continuing in watching-only mode until the device is re-connected.

**Comment by kyuupichan** [comment]
I thought PIL was already a dependency. I'll look into avoiding that.

The disconnected exception happens after it asks for your PIN. Can you confirm you are being asked for your PIN and that you're not cancelling the request?  Sometimes the device gets in a funny state that is solved by reinserting it.

The watching only warning is misleading as after you enter your PIN it goes out of watching only mode - check the window title bar.

**Comment by ELM4Ever** [comment]
Electrum just doesn't see it.  I tried to start Electrum, then connect the Trezor.  I tried by connecting to USB port first, then starting Electrum.  Nothing.  I tried by starting with default_wallet (normal type wallet) and then switching to Trezor wallet - watch-only again.  I can't create a new Trezor wallet either.  I doesn't ask me for my PIN.

**Comment by ELM4Ever** [comment]
Found something... If I revert to an older version of the python-trezor library (0.6.6 for example) - Trezor now works with Electrum v2.6   The python-library is now at 0.6.11.   0.6.6 uses protobuf 2.5.0  and 0.6.11 uses protobuf 2.6.1.  Electrum uses protobuf 3.0.0  - don't know if this makes any difference.

**Comment by kyuupichan** [comment]
Thanks for the info.  FYI I have trezor 0.6.7 installed, protobuf 2.6.1.  Once I've resolved other issues I'll look into updating my trezor library version and trying to reproduce.  So I understand the following:

trezor 0.6.11 and protobuf 2.6.1 not working for ELM4Ever
trezor 0.6.7 and protobuf 2.6.1 is working for me

If you could test trezor 0.6.7 so we have a common good version that would be good.

**Comment by ELM4Ever** [comment]
I don't have trezor 0.6.7 - they don't list older versions on their github repo.  It just happened that I found a copy of 0.6.6 in my download folder.   BTW, when you "sudo python setup.py install" Electrum, the setup.py will swap your protobuf to v.3.0.0 automatically.  

- Electrum 2.6, python-Trezor 0.6.6 and protobuf at any flavor (2.5.0 / 2.6.1 / 3.0.0) works for me 
- Electrum 2.6, python-Trezor 0.6.11 and protobuf at 2.6.1 or 3.0.0 does not work for me.
- Command line for python-Trezor 0.6.11 and protobuf at 2.6.1 works for me (execute small python code listed in readme file of python-trezor repo).  
- Command line python-Trezor 0.6.11 and protobuf at 3.0.0 does not work for me

**Comment by kyuupichan** [comment]
OK that's very useful thanks. Seeing as command line Trezor has an issue this seems to be more an incompatibility of protobuf 3 and newer Trezor rather than specifically an Electrum issue. Can you inform them?

**Comment by ELM4Ever** [comment]
I can. 

Protobuf 2.6.1 is the last stable version.  It would be wise to also restrict Electrum to that version in the setup.py file.

**Comment by ELM4Ever** [comment]
BTW:  Electrum 2.5.4,  Python-Trezor 0.6.11 and protobuf 2.6.1 work well together.

**Comment by kyuupichan** [comment]
Yes trezor 0.6.11 seems to have a problem.  Let me update and avoid the issue in Electrum

**Comment by kyuupichan** [comment]
@ELM4Ever - please confirm if this solves the issue for you.  I've updated to 0.6.11 locally and it is now fine.  Unfortunately 0.6.11 is broken on the Mac, but I've made Electrum avoid the broken function so it works for me now on Mac.

**Comment by ELM4Ever** [comment]
Excellent!  Electrum 2.6 now works with phyton-trezor 0.6.11.

So many new functions available for Trezor!

Thanks.
