### ISSUE TITLE
FX plugin throwing exceptions

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1661]
I fixed a bug similar to this (though the actual traceback is new) recently; you seem to have reverted my fix:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/neil/src/electrum/plugins/exchange_rate/exchange_rate.py", line 60, in update_safe
    self.on_quotes()
  File "/Users/neil/src/electrum/plugins/exchange_rate/qt.py", line 63, in on_quotes
    self.app.emit(SIGNAL('new_fx_quotes'))
AttributeError: 'Plugin' object has no attribute 'app'

Just got a different one on a different machine.  This is new:

[Plugins] stopped
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/home/neil/src/electrum/plugins/exchange_rate/exchange_rate.py", line 56, in update_safe
  File "/home/neil/src/electrum/plugins/exchange_rate/exchange_rate.py", line 164, in get_rates
  File "/home/neil/src/electrum/plugins/exchange_rate/exchange_rate.py", line 40, in get_json
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 411, in send
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by ecdsa** [comment]
I have reverted your commit because it was breaking the plugin, as described by yourself here:

> <kyuupichan>   ThomasV: Well, I didn't come away with anything actionable.  So I'd rather you went first and made it what you want.  Last time I started an Electrum wallet the FX plugin was unusable unless you were willing to restart the app at least once.  If you can make it better, great.

it would be great to hear you acknowledge about it, before you ask me to fix things.

second, it would be nice if you could help me this bug, because I cannot observe it; I guess it's a timing issue.

**Comment by kyuupichan** [comment]
No, you did not fix that, and my change did not cause it.  What was broken?

Have you tried starting a new electrum (without config) and enabling FX plugin?  I have, and it doesn't work without restarting - that was what I was referring to.  Nothing to do with my commit.

My commit had 3 benefits: it used new signals, it fixed a race condition, and fixed using member variables on other objects that you complain about.  What did reverting it fix?

**Comment by ecdsa** [comment]
well, before your commit, when I enable the plugin, the exchange rate and fiat balance are displayed in the status line. after your commit, this is no longer the case. I need to restart Electrum in order to see the fiat balance.

when I read your IRC message, I thought it was referring to that. sorry if you don't hve the same behavior.

**Comment by ecdsa** [comment]
sorry I was wrong about your commit. restored it

**Comment by ecdsa** [comment]
well, I got confused, and I reverted the wrong commit.
I checked again, and my initial satement was right: commit e20369bf94a2c2c8c22dd9472be3767e90c5774e broke the abillity to display the exchange rate again, after the plugin is disabled. this is because you removed tyhe init_qt hook.

**Comment by ecdsa** [comment]
... and you are right about the fact that if the gui is started with the plugin disabled, it still needs a restart.
we were not looking at the same thing.

I think it is nice to send signals from the plugin object, but we still need init_qt to connect the existing windows

**Comment by ecdsa** [comment]
fixed in c0ef60aa50e5729828e5152d3504aec069a6881a
it keeps the benefits of locally emited signals, but it fixes init_qt instead of removing it.

**Comment by kyuupichan** [comment]
OK, I'm not at my computer now.  Not sure what your changes affect.  I didn't notice the status bar effect, sorry for that (we've had that before; I think you notice that more than me.  I wish there were a way to test this other than human vision).

I don't think your changes affect the 2nd of my two backtraces, however.  That may be a rare fluke, I've only seen it once so I suspect it relates to recent changes but can't be sure.  But I use FX plugin on 2 machines and recently I've seen several backtraces I didn't used to see, which is why I opened this.

**Comment by ecdsa** [comment]
ok, I can see the 2nd backtrace too.
