### ISSUE TITLE
coin control "privacy" doesn't work with dynamic fees

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#1703]
Setting coin control to "privacy" (rather than "priority") breaks dynamic fees.
To reproduce just try creating a tx with some amount with settings mentioned above. 

Normally it calculates dynamic fees but in this case just leaves the fee input line empty with the following traceback: http://pastebin.com/xQQDQRn5 
The traceback is spammed repeatetly until you revert to either priority coin control or disable dynamic fees or clear the created tx

**Comment by kyuupichan** [comment]
I cannot reproduce this.

**Comment by EagleTM** [comment]
It's only reproducible with certain wallets. I'll try to investigate when I find the time and will post results here.

**Comment by ecdsa** [comment]
can you repost the traceback? your pastebin expired

**Comment by ecdsa** [comment]
@EagleTM did it occur with multisig wallets, as in #1729 ?

**Comment by ecdsa** [comment]
http://pastebin.com/mJxALC6E

**Comment by fortran77** [comment]
Here is another traceback for the same or similar issue, in case it helps. Generated on Ubuntu 12.04, Electrum 2.6.2. 
 
This happens if Tools => Preferences => Coin Selection is set to Privacy and then the Send tab is used to do any send. The traceback then repeatedly appears as if the program is in a rapid loop.

    struct.error: unpack requires a string argument of length 4
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 542, in timer_actions
        self.do_update_fee()
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 1117, in do_update_fee
        tx = self.wallet.make_unsigned_transaction(self.get_coins(), outputs, self.config, fee)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 981, in make_unsigned_transaction
        fee_estimator, dust_threshold)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 196, in make_tx
        self.penalty_func(tx))
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 268, in choose_buckets
        candidates = self.bucket_candidates(buckets, sufficient_funds)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 254, in bucket_candidates
        self.p.shuffle(permutation)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 68, in shuffle
        j = int(self.random() * (i+1))
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 56, in random
        return struct.unpack("I", four)[0] / 4294967296.0
    struct.error: unpack requires a string argument of length 4

**Comment by kyuupichan** [comment]
What would be helpful is if someone who can reproduce this could insert a couple of print statements to reveal what's happening, such as

print len(four), four

Before the line 56. Four is supposed to be 4 bytes long and I cannot see how it is happening to be something else. Knowing its actual length is the first step.

**Comment by fortran77** [comment]
I added debugging lines as shown in the diffs below. Changes are relative to the pristine coinchooser.py as it came with Electrum 2.6.2.

    RCS file: RCS/coinchooser.py,v
    retrieving revision 1.3
    diff -u -r1.3 coinchooser.py
    --- coinchooser.py  2016/04/07 07:47:27     1.3
    +++ coinchooser.py  2016/04/07 08:18:27
    @@ -53,6 +53,8 @@
         def random(self):
             # Returns random double in [0, 1)
             four = self.get_bytes(4)
    +        print "DEBUG:", "four =", four, "len(four) =", len(four)
    +        print "DEBUG:", 'struct.calcsize("I") =', struct.calcsize("I")
             return struct.unpack("I", four)[0] / 4294967296.0
      
         def randint(self, start, end):
      
Traceback, two iterations shown below. For some reason Python does not consider 'four' to be a string of length 4. Note the traceback begins to appear as soon as I enter any value in the Amount box.
        
    DEBUG: four = ��n� len(four) = 4
    DEBUG: struct.calcsize("I") = 4
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 542, in timer_actions
        self.do_update_fee()
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 1117, in do_update_fee
        tx = self.wallet.make_unsigned_transaction(self.get_coins(), outputs, self.config, fee)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 981, in make_unsigned_transaction
        fee_estimator, dust_threshold)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 198, in make_tx
        self.penalty_func(tx))
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 270, in choose_buckets
        candidates = self.bucket_candidates(buckets, sufficient_funds)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 256, in bucket_candidates
        self.p.shuffle(permutation)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 70, in shuffle
        j = int(self.random() * (i+1))
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 58, in random
        return struct.unpack("I", four)[0] / 4294967296.0
    struct.error: unpack requires a string argument of length 4
    DEBUG: four = ��n� len(four) = 4
    DEBUG: struct.calcsize("I") = 4
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 542, in timer_actions
        self.do_update_fee()
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 1117, in do_update_fee
        tx = self.wallet.make_unsigned_transaction(self.get_coins(), outputs, self.config, fee)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 981, in make_unsigned_transaction
        fee_estimator, dust_threshold)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 198, in make_tx
        self.penalty_func(tx))
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 270, in choose_buckets
        candidates = self.bucket_candidates(buckets, sufficient_funds)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 256, in bucket_candidates
        self.p.shuffle(permutation)
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 70, in shuffle
        j = int(self.random() * (i+1))
      File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 58, in random
        return struct.unpack("I", four)[0] / 4294967296.0
    struct.error: unpack requires a string argument of length 4

**Comment by ecdsa** [comment]
I bet it's because of unicode encoding found in the string

**Comment by fortran77** [comment]
I tried a shot in the dark and it seemed to work. The change shown below eliminates the error and the Send proceeds as expected. Please double-check and/or correct my logic before using this. Diffs relative to pristine coinchooser.py as it came in Electrum 2.6.2.

    RCS file: RCS/coinchooser.py,v
    retrieving revision 1.1
    diff -u -r1.1 coinchooser.py
    --- coinchooser.py  2016/03/16 02:05:41     1.1
    +++ coinchooser.py  2016/04/08 06:42:36
    @@ -53,7 +53,11 @@
         def random(self):
             # Returns random double in [0, 1)
             four = self.get_bytes(4)
    -        return struct.unpack("I", four)[0] / 4294967296.0
    +        sum = four[3]
    +        sum = 256 * sum + four[2]
    +        sum = 256 * sum + four[1]
    +        sum = 256 * sum + four[0]
    +        return sum / 4294967296.0
 
         def randint(self, start, end):
             # Returns random integer in [start, end)

**Comment by ecdsa** [comment]
thanks..
to be honest, I don't see why that "prng" uses floats in order to generate random integers
