### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-XXXXXX-build/

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [spesmilo/electrum#1712]
```
me@me:~$ sudo pip install https://download.electrum.org/2.6.2/Electrum-2.6.2.tar.gz
[sudo] password for me: 
The directory '/home/me/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/me/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://download.electrum.org/2.6.2/Electrum-2.6.2.tar.gz
  Downloading https://download.electrum.org/2.6.2/Electrum-2.6.2.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 170kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-rQD77d-build/setup.py", line 86, in <module>
        long_description="""Lightweight Bitcoin Wallet"""
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/me/.local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/me/.local/lib/python2.7/site-packages/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2395, in require
        reqs = self.dist.requires(self.extras)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2640, in requires
        dm = self._dep_map
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2864, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2881, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-rQD77d-build/
me@me:~$ uname -a
Linux me 4.4.0-11-generic #26-Ubuntu SMP Sat Mar 5 14:25:21 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
me@me:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu Xenial Xerus (development branch)"
```

**Comment by ecdsa** [comment]
this is not a bug in Electrum.
probably something wrong with your pip
