### ISSUE TITLE
Broadcast from command line do not work

### ISSUE THREAD

**Issue by Zotil** [spesmilo/electrum#1759]
I did search on fixes, i applied, i even downloaded the /lib directory from git here, but the problem is still there.
I can't move my coins since its an autmated system on a dedicated server.
Thanks.

```
root@linux:/# electrum payto xxxxSSd1F8m2xj48twhZKj3ExN8vAixxxx 0.002
{
    "complete": true, 
    "hex": "xxxxx00001eb077de1771d8f22ec75d573d72d2677966fb7c6fe76ce314bf63d555af6cd25000000006a47304402206bb8e006c785a3589a19d2df9508e7fb6c9c05518ce5e5f02c236407658f701202206331eecbc507589013c179c83ae6298a299b4e7e8abb7d600dd6ed487e0e92c50121026988eafafd8f9e08936ab490a89d9f8891f8efb09e1ed1df57646d44047ce995ffffffff02400d0300000000001976a91476f0ff61b797f934e42b651a80f80ea036bacc6a88ac4c8b0f00000000001976a9146f49b5585b728fad047deb0a024e62fb09ff299788ac00000000"
}
root@linux:/# electrum broadcast xxxxx00001eb077de1771d8f22ec75d573d72d2677966fb7c6fe76ce314bf63d555af6cd25000000006a47304402206bb8e006c785a3589a19d2df9508e7fb6c9c05518ce5e5f02c236407658f701202206331eecbc507589013c179c83ae6298a299b4e7e8abb7d600dd6ed487e0e92c50121026988eafafd8f9e08936ab490a89d9f8891f8efb09e1ed1df57646d44047ce995ffffffff02400d0300000000001976a91476f0ff61b797f934e42b651a80f80ea036bacc6a88ac4c8b0f00000000001976a9146f49b5585b728fad047deb0a024e62fb09ff299788ac00000000
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 371, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 836, in broadcast | AttributeError: \'unicode\' object has no attribute \'hash\'')

```

**Comment by dabura667** [comment]
Your raw transaction has your addresses written in there for anyone to see by the way.

**Comment by Zotil** [comment]
nevermind, is weird the case because I did watch the code and the hash() method should be there since is passed as Transaction()... but I don't know very well the electrum code, I am just working with it less than 1 week

**Comment by ecdsa** [comment]
that bug was fixed recently.
did you restart the electrum daemon after you updated the code?

**Comment by Zotil** [comment]
Oh, i was, but i mistyped the stop.... human error, its working well. Sorry for the time.

**Comment by ecdsa** [comment]
what did you mistype? having that kind of error message if the user does a typo is probably not good

**Comment by Zotil** [comment]
`electrum daemon stoop; electrum daemon start`
(note the two o)
probably I did not read the return of command, since i'm rushing on this project
