### ISSUE TITLE
paytomany cammand

### ISSUE THREAD

**Issue by html5-ninja** [spesmilo/electrum#1771]
hi , first time I got this error , it was perfectly working when this happen 

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 5, in <module>
    pkg_resources.run_script('Electrum==2.6.3', 'electrum')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.6.3-py2.7.egg/EGG-INFO/scripts/electrum", line 371, in <module>
    result = server.run_cmdline(config_options)
  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 288, in __call__
  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 238, in _request
  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "build/bdist.linux-x86_64/egg/dns/resolver.py", line 910, in query | NXDOMAIN')
```

I have not made any change , so where is the problem , thank you

**Comment by html5-ninja** [comment]
wops my fault , wrong address pattern ,

**Comment by arcaelas** [comment]
> wops my fault , wrong address pattern ,

¿Could you do it?
