### ISSUE TITLE
electrum server not joining IRC when python irc module 14.2 is used. (use older version)

### ISSUE THREAD

**Issue by Atmos01** [spesmilo/electrum#1791]
```
INFO:electrum:mempool_update 6.22133016586 9996 11646
INFO:electrum:bitcoind is responding
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/electrum/electrum-server/src/ircthread.py", line 143, in run
    irc.client.ServerConnection.buffer_class = irc.buffer.LenientDecodingLineBuffer
AttributeError: 'module' object has no attribute 'buffer'
```

Solution is to use an older version of the module.. 

https://pypi.python.org/packages/41/d7/9ad1efea5d2e9b452178bc7e5c838b81e92a7c04a0c59d8bab07a7924063/irc-13.3.1.tar.gz#md5=14070bb5c4dece6262852256da006fcd

unpack and run python setup.py install

**Comment by ecdsa** [comment]
thanks, but that's a server bug
