### ISSUE TITLE
Fix wizard hardware wallet flow

### ISSUE THREAD

**Issue by iancoleman** [spesmilo/electrum#1793]
When setting up a new wallet using the 'hardware wallet' option an error thrown and electrum quits.

Steps to reproduce:

* Fresh install of Electrum 2.6.4 on Ubuntu 16.04 from source.

* Start electrum: `$ ./electrum`

* From the 'Install Wizard' dialog, select 'Create a new wallet' and 'Hardware wallet', then press next.

* Select 'Use a device you have already set up'.

* Note there are no wallets shown in the dialog under 'Select the type of hardware wallet:'. Press next. 

* Error dialog shows 'list index out of range'. Press OK and electrum exits.

Traceback in console is

```
Error: Cannot read config file. /home/ian/.electrum
Traceback (most recent call last):
  File "/home/ian/Downloads/Electrum-2.6.4/gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/home/ian/Downloads/Electrum-2.6.4/lib/wizard.py", line 151, in run
    cr, wallet = self.create_or_restore(storage)
  File "/home/ian/Downloads/Electrum-2.6.4/lib/wizard.py", line 225, in create_or_restore
    wallet_type = hw_wallet_types[choice]
IndexError: list index out of range
Traceback (most recent call last):
  File "electrum", line 332, in <module>
    d.init_gui(config, plugins)
  File "/home/ian/Downloads/Electrum-2.6.4/lib/daemon.py", line 235, in init_gui
    self.gui.main()
  File "/home/ian/Downloads/Electrum-2.6.4/gui/qt/__init__.py", line 185, in main
    self.config.get('url')):
  File "/home/ian/Downloads/Electrum-2.6.4/gui/qt/__init__.py", line 163, in start_new_window
    wallet = self.daemon.load_wallet(path, self.get_wizard)
  File "/home/ian/Downloads/Electrum-2.6.4/lib/daemon.py", line 188, in load_wallet
    wallet = wizard.run(self.network, storage)
  File "/home/ian/Downloads/Electrum-2.6.4/gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/home/ian/Downloads/Electrum-2.6.4/lib/wizard.py", line 151, in run
    cr, wallet = self.create_or_restore(storage)
  File "/home/ian/Downloads/Electrum-2.6.4/lib/wizard.py", line 225, in create_or_restore
    wallet_type = hw_wallet_types[choice]
IndexError: list index out of range
```

**Comment by iancoleman** [comment]
Possibly (almost certainly) related to https://github.com/spesmilo/electrum/issues/1786

**Comment by ecdsa** [comment]
if no hardware wallet support is available, that screen should not be reachable at all.

**Comment by kyuupichan** [comment]
https://github.com/spesmilo/electrum/commit/11ef0f5489f0df8812cc2e9cad1d70aab2a72fbe fixes this I believe

**Comment by ecdsa** [comment]
reopening. your commit does not address my comment

**Comment by ecdsa** [comment]
I would like to have the following logical flow:
First, there is no point sending users to the second screen if no hardware support is available.
Second, the 'Restore Electrum' choice should not be proposed if the user selected 'create'.
Third, if they selected 'restore' in the first screen, only the hardware wallet choices should be shown, and hardware support is not required in order to show them.

**Comment by kyuupichan** [comment]
The 2nd part of your 3rd point is true in 2.6; it was broken in 2.5.

**Comment by kyuupichan** [comment]
Unfortunately this is worse than before.
