### ISSUE TITLE
Electrum on Ubuntu 16.04 - 'CompiledFFI' object has no attribute 'def_extern'

### ISSUE THREAD

**Issue by stuaxo** [spesmilo/electrum#1813]
This is a different error to the other Ubuntu 16.04 error
```
 tmp  Electrum-2.6.4  $ ./electrum 
Traceback (most recent call last):
  File "./electrum", line 75, in <module>
    check_imports()
  File "./electrum", line 51, in check_imports
    import requests
  File "/tmp/Electrum-2.6.4/packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/tmp/Electrum-2.6.4/packages/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in <module>
    error=-1)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 57, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
```

**Comment by ecdsa** [comment]
try this http://stackoverflow.com/questions/35259538/why-did-conda-and-pip-just-stop-working-compiledffi-object-has-no-attribute

**Comment by ecdsa** [comment]
closing, since this is probably not an Electrum issue

**Comment by stuaxo** [comment]
I'm pretty sure I did try those and they didn't work - I haven't had a chance to do it again, but will over the weekend, will post here if it still doesn't.

**Comment by stuaxo** [comment]
Finally got time to test this.   Not sure about the 'fix' of uninstalling 'python-cryptography', it would uninstall enough packages, not sure my desktop will work.

At the moment, kind of stuck, since I transfered bitcoin to my electrum wallet when I installed it, but they only the transfers show up, no balance.

**Comment by stuaxo** [comment]
OK, tried it and got a bit further
```

$ sudo pip install https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz
The directory '/mnt/data/home/stu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/stu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz
  Downloading https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 205kB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 600, in _prepare_file
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by stuaxo** [comment]
Looks like this is a change in the internal api of pip, as they consider it internal, they consider it not a bug:
https://github.com/pypa/pip/issues/3673
