### ISSUE TITLE
socket.error: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by l29ah** [spesmilo/electrum#1830]
I'm using 2.6.4 and it fails to start. 2.5.4 used to work fine.
```
‰ electrum 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/electrum", line 330, in <module>
    d = daemon.Daemon(config, fd)
  File "/usr/lib64/python2.7/site-packages/electrum/daemon.py", line 120, in __init__
    requestHandler=RequestHandler)
  File "/usr/lib64/python2.7/site-packages/jsonrpclib/SimpleJSONRPCServer.py", line 215, in __init__
    self, addr, requestHandler, bind_and_activate)
  File "/usr/lib64/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
```

**Comment by ecdsa** [comment]
maybe you have rpcpost set in your config file?
try to delete the config file and restart

**Comment by l29ah** [comment]
On Sun, Jun 12, 2016 at 10:55:00PM -0700, ThomasV wrote:
> maybe you have rpcpost set in your config file?
> try to delete the config file and restart

No effect.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ecdsa** [comment]
what operating system are you using?

**Comment by l29ah** [comment]
On Tue, Jun 14, 2016 at 12:34:01AM -0700, ThomasV wrote:
> what operating system are you using?

Gentoo Linux.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ecdsa** [comment]
I beieve this has been fixed in git head. (same bug as #1932)
