### ISSUE TITLE
restore hardly working

### ISSUE THREAD

**Issue by murrayrothbard2** [spesmilo/electrum#1859]
In more than 50% of the cases this error is returned:

Traceback (most recent call last): File "/usr/local/bin/electrum", line 5, in pkg_resources.run_script('Electrum==2.7.0', 'electrum') File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script self.require(requires)[0].run_script(script_name, ns) File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script execfile(script_filename, namespace, namespace) File "/usr/local/lib/python2.7/dist-packages/Electrum-2.7.0-py2.7.egg/EGG-INFO/scripts/electrum", line 319, in run_non_RPC(config) File "/usr/local/lib/python2.7/dist-packages/Electrum-2.7.0-py2.7.egg/EGG-INFO/scripts/electrum", line 167, in run_non_RPC wallet.storage.write() File "/usr/local/lib/python2.7/dist-packages/Electrum-2.7.0-py2.7.egg/electrum/wallet.py", line 160, in write os.rename(temp_path, self.path) OSError: [Errno 2] No such file or directory

**Comment by murrayrothbard2** [comment]
The problem is that self_path is not set!

**Comment by ecdsa** [comment]
I encountered that issue too, with large wallets. 
I don't think that self.path is not set.

**Comment by ecdsa** [comment]
probably fixed in f061fe047d9a6ac82ccca5e6d0911b7e088bf2f0
please confirm

**Comment by murrayrothbard2** [comment]
Awesome!
