### ISSUE TITLE
payto request stopped working

### ISSUE THREAD

**Issue by murrayrothbard2** [spesmilo/electrum#1860]
Ubuntu 14.04

payto worked without any flaws dozens of times. Now suddenly and without any changes I get this :

Traceback (most recent call last): File "/usr/local/bin/electrum", line 5, in <module> pkgresources.run_script('Electrum==2.6.3', 'electrum') File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script self.require(requires)[0].run_script(script_name, ns) File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script execfile(script_filename, namespace, namespace) File "/usr/local/lib/python2.7/dist-packages/Electrum-2.6.3-py2.7.egg/EGG-INFO/scripts/electrum", line 371, in <module> result = server.run_cmdline(config_options) File "/usr/local/lib/python2.7/dist-packages/jsonrpclib-0.1.7-py2.7.egg/jsonrpclib/jsonrpc.py", line 288, in __call_ return self.send(self.name, args) File "/usr/local/lib/python2.7/dist-packages/jsonrpclib-0.1.7-py2.7.egg/jsonrpclib/jsonrpc.py", line 238, in _request check_for_errors(response) File "/usr/local/lib/python2.7/dist-packages/jsonrpclib-0.1.7-py2.7.egg/jsonrpclib/jsonrpc.py", line 567, in check_for_errors raise ProtocolError((code, message)) jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error: File "/usr/local/lib/python2.7/dist-packages/Electrum-2.6.3-py2.7.egg/electrum/coinchooser.py", line 56, in random | error: unpack requires a string argument of length 4')

**Comment by ecdsa** [comment]
please try with the latest release.

**Comment by murrayrothbard2** [comment]
I will notify you when this error should appear again.

**Comment by ecdsa** [comment]
it was fixed long ago...
before reporting a new bug, always check that it still exists on git master
