### ISSUE TITLE
Cannot preview some txs with watch-only wallet

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1865]
Traceback (most recent call last):
  File "/Users/neil/src/electrum/gui/qt/main_window.py", line 1166, in do_preview
    self.do_send(preview = True)
  File "/Users/neil/src/electrum/gui/qt/main_window.py", line 1190, in do_send
    if tx.get_fee() < self.wallet.relayfee() * tx.estimated_size() / 1000 and tx.requires_fee(self.wallet):
  File "/Users/neil/src/electrum/lib/transaction.py", line 862, in requires_fee
    age = wallet.get_confirmations(txin["prevout_hash"])[0]
AttributeError: 'Imported_Wallet' object has no attribute 'get_confirmations'

**Comment by ecdsa** [comment]
this should fix it.
