### ISSUE TITLE
Cannot sign h/w tx on git head

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1899]
The following is the traceback.  This was done from the TX window.

Traceback (most recent call last):
  File "/Users/neil/src/electrum/gui/qt/util.py", line 575, in run
    result = task.task()
  File "/Users/neil/src/electrum/lib/wallet.py", line 1045, in sign_transaction
    keystore.sign_transaction(tx, password)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 73, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 229, in sign_transaction
    outputs = self.tx_outputs(keystore.get_derivation(), tx)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 315, in tx_outputs
    address_path = "%s/%d/%d/"%(derivation, change, index)
TypeError: %d format: a number is required, not tuple

**Comment by kyuupichan** [comment]
Here's the traceback when I try to sign a message:

Traceback (most recent call last):
  File "/Users/neil/src/electrum/gui/qt/util.py", line 575, in run
    result = task.task()
  File "/Users/neil/src/electrum/lib/wallet.py", line 280, in sign_message
    keys = self.get_private_key(address, password)
  File "/Users/neil/src/electrum/lib/wallet.py", line 273, in get_private_key
    return [ self.keystore.get_private_key(sequence, password) ]
AttributeError: 'KeepKey_KeyStore' object has no attribute 'get_private_key'

**Comment by ecdsa** [comment]
thanks, both are fixed in b87c5d12fa09c6d0a53bb34c4d43a957e7c23a0e
