### ISSUE TITLE
IndexError when trying to setup a trezor wallet.

### ISSUE THREAD

**Issue by F483** [spesmilo/electrum#1902]
I am using electrum version 2.6.4 on Ubuntu and installed the trezor-bridge_1.1.5_amd64.deb package.

https://wallet.mytrezor.com/ works well.

```
$ electrum 

(python:4206): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

(python:4206): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 151, in run
    cr, wallet = self.create_or_restore(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 225, in create_or_restore
    wallet_type = hw_wallet_types[choice]
![error](https://cloud.githubusercontent.com/assets/977605/17776069/5808856c-655b-11e6-8507-8dcf78556b73.png)

IndexError: list index out of range

```

**Comment by F483** [comment]
Screenshot of the error above.

![error](https://cloud.githubusercontent.com/assets/977605/17776213/ce8b52b4-655b-11e6-9cfd-a89036102c5b.png)

**Comment by ecdsa** [comment]
this is fixed in git head
