### ISSUE TITLE
Electrum 2.64 not running on opensuse Tumbleweed

### ISSUE THREAD

**Issue by Rewarp** [spesmilo/electrum#1905]
Executing electrum in the terminal gives me this output without starting:

```
Traceback (most recent call last):
  File "/usr/bin/electrum", line 75, in <module>
    check_imports()
  File "/usr/bin/electrum", line 49, in check_imports
    import aes
  File "/usr/lib/python3.5/site-packages/aes.py", line 643
    raise ValueError, emsg % keysize
                    ^
SyntaxError: invalid syntax
```

**Comment by ecdsa** [comment]
use python2
