### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__' at xpub = self.get('master_public_keys')["x/"]

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#1907]
in git-head can no longer open wallet with imported keys. 
```
Traceback (most recent call last):
  File "C:\Users\x\GitHub\spesmilo\electrum\gui\qt\__init__.py", line 163, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "C:\Users\x\GitHub\spesmilo\electrum\gui\qt\installwizard.py", line 179, in run_and_get_wallet
    self.storage.upgrade()
  File "C:\Users\x\GitHub\spesmilo\electrum\lib\storage.py", line 219, in upgrade
    self.convert_wallet_type(False)
  File "C:\Users\x\GitHub\spesmilo\electrum\lib\storage.py", line 244, in convert_wallet_type
    xpub = self.get('master_public_keys')["x/"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
this is on a wallet that was split from old format via yesterday's git-head

**Comment by JBDC18** [comment]
Hi, is there a solution for this? I have the same problem, I will really appreciate if someone can help...

**Comment by ecdsa** [comment]
@JBDC18 please upgrade to the latest version of Electrum

**Comment by JBDC18** [comment]
Hi,
Thank you for your reply,I already upgraded to the latest version, after I didmy account turned into "imported, watching only".Is there any way I can solve this?
Thanks,Barry    On Sunday, 7 January 2018, 7:57:03 PM GMT+8, ThomasV <notifications@github.com> wrote:  
 
 
@JBDC18 please upgrade to the latest version of Electrum
