### ISSUE TITLE
Wallet upgrades failing

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1912]
Latest git HEAD no longer accepted a split wallet it itself created about 10 days ago.
so I went back to the original 2.6.4 keepkey wallet and did the split again.
Then opening account 0 I get another message saying the format is out of date (this seems to be wrong - why write an out of date split file?)  And when I click yes, update it, on the account 0 split file I get this backtrace:

Traceback (most recent call last):
  File "./electrum", line 343, in <module>
    d.init_gui(config, plugins)
  File "/Users/neil/src/electrum/lib/daemon.py", line 249, in init_gui
    self.gui.main()
  File "/Users/neil/src/electrum/gui/qt/__init__.py", line 186, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/Users/neil/src/electrum/gui/qt/__init__.py", line 163, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/Users/neil/src/electrum/gui/qt/installwizard.py", line 174, in run_and_get_wallet
    self.storage.upgrade()
  File "/Users/neil/src/electrum/lib/storage.py", line 219, in upgrade
    self.convert_wallet_type(False)
  File "/Users/neil/src/electrum/lib/storage.py", line 255, in convert_wallet_type
    xprv = xprvs["x/"]
KeyError: 'x/'

The above is at HEAD as I write this, commit 19e62ba

**Comment by ecdsa** [comment]
fixed in ab67a03
