### ISSUE TITLE
signing multisig transactions with ledger hw wallet

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1922]
@btchip 
Signing regular transactions with the ledger nano s works nicely, but I didn't succeed in partially signing multisig transactions.

Workflow A:
* construct a watch only multisig wallet with xpubs from different hardware wallets
* fund one of the addresses
* construct an outgoing tx, and save it as a file
* open the wallet that corresponds to the ledger
* load the tx from file
* try to partially sign it

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 581, in run
    result = task.task()
  File "/home/richi/sourcecode/electrum/lib/wallet.py", line 1020, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 265, in sign_transaction
    hwAddress = "%s/%d/%d" % (self.get_derivation()[2:], txinput['derivation'][0], txinput['derivation'][1])
KeyError: 'derivation'

Workflow B:
* construct a multisig wallet with hardware wallets directly.
* fund one of the addresses
* send coins to another address
* partially signing with other hw wallets works
* but when it comes to the ledger, and it is recognized:

Traceback (most recent call last):
File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 581, in run
 result = task.task()
  File "/home/richi/sourcecode/electrum/lib/wallet.py", line 1020, in sign_transaction
   k.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 382, in sign_transaction
    self.give_error(e, True)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 183, in give_error
    raise Exception(message)
Exception: 'trustedInput'

**Comment by btchip** [comment]
Before checking further, are you running with the latest https://github.com/ledgerhq/btchip-python ?

**Comment by ulrichard** [comment]
I'm using the  0.1.18  package from https://launchpad.net/~richi-paraeasy/+archive/ubuntu/bitcoin/

**Comment by ecdsa** [comment]
@ulrichard the first part if this bug is fixed.
the second exception likely comes from an outdated library or firmware

**Comment by ulrichard** [comment]
Yes, signing works now with all three hardware wallets.
There is a minor issue with too many pin entry dialogs, that I will log separately.
