### ISSUE TITLE
electrum crash on launch (ubuntu)

### ISSUE THREAD

**Issue by repsorp** [spesmilo/electrum#1937]
Hi,

electrum crash on lauch with following infos:

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 75, in <module>
    check_imports()
  File "/usr/local/bin/electrum", line 49, in check_imports
    import aes
  File "/usr/local/lib/python3.5/dist-packages/aes.py", line 643
    raise ValueError, emsg % keysize

uninstall, reinstall, no change

Ubuntu 16.04
Electrum 2.6.4

**Comment by repsorp** [comment]
electrum was in both /usr/bin & /usr/local/bin directories
just have to delete /usr/local/bin/electrum
It's working now
my mistake 
sorry
