### ISSUE TITLE
too many pin entry dialogs when multi-signing with hw wallets

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1938]
The setting is a 3 of 3 wallet with trezor + keepkey + ledger nano S.
When I sign a tx, I get on average two pin entry dialogs per device. Most of the time I have to enter the pin of trezor and keepkey twice. 
Electrum even brings up a pin entry dialog for the ledger nano s, which handles the pin on the device.
When I was done with signing, there were two pin dialogs still open. I had to cancel both of them before I could go back to the main screen.

**Comment by ecdsa** [comment]
should be fixed in 9f7ca3d

**Comment by ulrichard** [comment]
For trezor and keepkey it improved a bit, but for the ledger it is worse now. 

For the keepkey I still have to enter the pin twice. But the two pin entry dialogs now come one after another, and none stays open orphaned.

But when the ledger should sign, I get an empty message box with the following console output:

Traceback (most recent call last):
File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 581, in run
result = task.task()
File "/home/richi/sourcecode/electrum/lib/wallet.py", line 1021, in sign_transaction
k.sign_transaction(tx, password)
File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 267, in sign_transaction
xpub, s = parse_xpubkey(txin['x_pubkeys'][0])
File "/home/richi/sourcecode/electrum/lib/keystore.py", line 579, in parse_xpubkey
assert x_pubkey[0:2] == 'ff'
AssertionError

So, essentially, with the current state (git#2e0d55e25e5dbea31c77c6e912dfb359f54b3b66), I'm unable to sign the tx.

**Comment by ecdsa** [comment]
it works fine for me.. are you sure your ledger firmware is up to date?

**Comment by ecdsa** [comment]
ok, I can reproduce the fact that keepkey asks for PIN twice.

**Comment by ecdsa** [comment]
please test

**Comment by ulrichard** [comment]
I still get this traceback for the ledger:
With git#94988bd3f70949b531ed92935f5b798c0a9e8302

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 581, in run
    result = task.task()
  File "/home/richi/sourcecode/electrum/lib/wallet.py", line 1022, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 267, in sign_transaction
    xpub, s = parse_xpubkey(txin['x_pubkeys'][0])
  File "/home/richi/sourcecode/electrum/lib/keystore.py", line 579, in parse_xpubkey
    assert x_pubkey[0:2] == 'ff'
AssertionError
