### ISSUE TITLE
KeepKey restore from seed

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1952]
keepkey firmware upgraded today
python-keepkey v. 0.7.3 (https://launchpad.net/~richi-paraeasy/+archive/ubuntu/bitcoin/+files/python-keepkey_0.7.3-1~xenial_all.deb)
###### 

behaviour with 2.6.4:
- Datei -> Neu/Wiederherstellen
- Create a new wallet  / Hardware Geldbörse
- Initialize a new or wiped device  / KeepKey wallet
- Recover from a seed you have previously written down
- enable pin / no passphrase
- enter pin twice
- enter the 24 seed words
- when it asks for the 25th, press cancel (I saw no obvious way to stop)
- application crashes with "Speicherzugriffsfehler (Speicherabzug geschrieben)"
###### 

behaviour with git#df6dae90d6ecc54f990d0cbfe116708c96d57fd5 (2016-10-05 10:53 ThomasV)
- file -> new/restore
- standard wallet
- use a hardware device
- Recover from a seed you have previously written down
- enable pin / no passphrase
- enter pin twice
- no more response from the GUI, but the following console:
  Exception in thread Thread-14:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 196, in 
  _initialize_device
  pin_protection, label, language)
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 224$
  in wrapped
    return func(self, _args, *_kwargs)
  File "/home/richi/sourcecode/electrum/plugins/keepkey/client.py", line 11, in 
  recovery_device
  ProtocolMixin.recovery_device(self, False, _args)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 106, in wra
  pped_f
  ret = f(_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 120, in wra
  pped_f

... lots of lines in between ....

File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line[43/1873]
setup_device
    client.get_xpub('m')
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 153,
 in get_xpub
    node = self.get_public_node(address_n, creating).node
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 224,
 in wrapped
    return func(self, _args, *_kwargs)
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 201,
 in get_public_node
    return super(TrezorClientBase, self).get_public_node(address_n)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 120, in wra
pped_f
    ret = f(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 488, in get
_public_node
    return self.call(proto.GetPublicKey(address_n=n, ecdsa_curve_name=ecdsa_curv
e_name, show_display=show_display))
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 169, in call
    msg = handler(resp)
File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", [21/1873]
in callback_Failure
    raise UserCancelled()
electrum.util.UserCancelled
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 196, in 
_initialize_device
    pin_protection, label, language)
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 224,
 in wrapped
    return func(self, _args, *_kwargs)
  File "/home/richi/sourcecode/electrum/plugins/keepkey/client.py", line 11, in 
recovery_device
    ProtocolMixin.recovery_device(self, False, _args)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 106, in wra
pped_f
    ret = f(_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 120, in wrapped_f
    ret = f(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 774, in recovery_device
    use_character_cipher=bool(not use_trezor_method)))
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 173, in call
    resp = self.call(msg)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 173, in call
    resp = self.call(msg)
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 169, in call
    msg = handler(resp)
  File "/home/richi/sourcecode/electrum/plugins/trezor/clientbase.py", line 34, in callback_Failure
    raise UserCancelled()
**UserCancelled[**

**Comment by ulrichard** [comment]
I tried some more with v 2.6.4

I usually hit enter for accepting the word. Because it was the 12th, this was interpreted as "Enter seed". So it failed because my seed has 24 words. 
At the first try, the opposite happened. I always clicked "accept word". After I did that for the 24th word, I had no way to go back, when it asked for the 25th word.
Only at the third try I hit "enter seed" at the right moment. But then electrum disappeared with this:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:179: dequeue_pending_request: Zusicherung »!xcb_xlib_unknown_req_in_deq« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)

**Comment by ulrichard** [comment]
When I initialize it with the keepkey chromium app, I can use it with electrum for signing without any problems.

**Comment by kyuupichan** [comment]
You shouldn't have to press cancel.  On the 24th word you should press the "Seed Entered" button which will be enabled (only enabled at 12th, 18th and 24th words).

**Comment by kyuupichan** [comment]
This should work in 2.6.4 (not tried 2.7 but I doubt the code has changed)

**Comment by ecdsa** [comment]
this is deprecated; you restore by selecting bip39
