### ISSUE TITLE
" 'NoneType' object has no attribute 'encode' " in watch-only wallet

### ISSUE THREAD

**Issue by bobbyb500** [spesmilo/electrum#1959]
When attempting to create a transaction in my watch-only wallet, I'm presented with this error. The wallet does not even appear to be recognized as a watch-only wallet at all. The header bar refers to it as "[standard]"; and the Seed icon appears, clicking on the icon also presents the same NoneType object error.

Currently running version 2.7.2 OS X binary, originally upgraded from 2.6.4 to 2.7.0

**Comment by ecdsa** [comment]
do you remember how you created the watching only wallet ?

**Comment by bobbyb500** [comment]
It was years ago, sometime in 2012-2013, using version 1.x. I’m pretty sure I just grabbed the Master Public Key and used that to create the watch-only wallet, definitely did it thru the GUI, not in the console.


On Oct 8, 2016, at 12:50 AM, ThomasV <notifications@github.com> wrote:

do you remember how you created the watching only wallet ?

**Comment by ecdsa** [comment]
I believe there is a 'seed' value equal to None in your wallet file, instead of no seed at all.
I will fix it.
in the meantime, you should be fine if you create a new watching only wallet

**Comment by bobbyb500** [comment]
I'm still getting the error when creating a transaction. On the 'Send' tab, the option reads 'Send' rather than 'Save'. Also, the usual warning on open about it being a watching-only wallet does not pop up.

I have tried opening my backup wallet from 2.6.4, but the same thing happens.

**Comment by ecdsa** [comment]
can you check if there is a 'seed' line in your wallet file?

**Comment by bobbyb500** [comment]
In the 2.6.4 version, no, there is not. In the 2.7.3 version, there is a line:  
> "seed": null, 
in "keystore:"

**Comment by ecdsa** [comment]
open it with 2.7.3, it should work

**Comment by bobbyb500** [comment]
Still getting the same error. So I ran from the source, and here's the terminal output when I try to send a transaction:

>Traceback (most recent call last):
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/util.py", line 581, in run
    result = task.task()
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/wallet.py", line 1059, in sign_transaction
    k.sign_transaction(tx, password)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/keystore.py", line 103, in sign_transaction
    self.check_password(password)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/keystore.py", line 452, in check_password
    seed = self.get_seed(password)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/keystore.py", line 228, in get_seed
    return pw_decode(self.seed, password).encode('utf8')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by bobbyb500** [comment]
Seeing all those references to 'password', I guess I should mention that the watching only wallet doesn't have a password

**Comment by ecdsa** [comment]
that's weird. what happens if you try to re-create the watching-only wallet?

**Comment by bobbyb500** [comment]
Actually the install wizard seems to stall out on "Please wait..."

>Traceback (most recent call last):
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/main_window.py", line 374, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/__init__.py", line 163, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/installwizard.py", line 192, in run_and_get_wallet
    self.run(action)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 59, in run
    apply(f, args)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 87, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 105, in on_wallet_type
    self.run(action)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 59, in run
    apply(f, args)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 137, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 59, in run
    apply(f, args)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 160, in restore_from_key
    self.add_xpub_dialog(title=title, message=message, run_next=self.on_restore_from_key, is_valid=v)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 168, in on_restore_from_key
    self.on_keystore(k)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 308, in on_keystore
    self.run('create_wallet')
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 59, in run
    apply(f, args)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 326, in create_wallet
    self.request_password(run_next=self.on_password)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/base_wizard.py", line 334, in on_password
    k.update_password(None, password)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/keystore.py", line 485, in update_password
    self.check_password(old_password)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/keystore.py", line 453, in check_password
    self.check_seed(seed)
  File "/Users/Bobby/Downloads/Electrum-2.7.3/lib/keystore.py", line 449, in check_seed
    raise InvalidPassword()
electrum.util.InvalidPassword: Incorrect password

**Comment by ecdsa** [comment]
thanks, I got it

**Comment by bobbyb500** [comment]
Yep, that fixed it. Thanks so much, great work :)

On Oct 8, 2016, at 7:03 PM, ThomasV <notifications@github.com> wrote:

thanks, I got it
