### ISSUE TITLE
Exception in connect_header

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#2012]
I've not looked into this (yet); I'm getting this connecting to several servers. 

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "/home/neil/src/electrum/lib/network.py", line 824, in run
    self.wait_on_sockets()
  File "/home/neil/src/electrum/lib/network.py", line 813, in wait_on_sockets
    self.process_responses(interface)
  File "/home/neil/src/electrum/lib/network.py", line 603, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/neil/src/electrum/lib/network.py", line 550, in process_response
    self.on_get_header(interface, response)
  File "/home/neil/src/electrum/lib/network.py", line 745, in on_get_header
    next_height = self.blockchain.connect_header(data['chain'], response['result'])
  File "/home/neil/src/electrum/lib/blockchain.py", line 198, in connect_header
    previous_height = header['block_height'] - 1
TypeError: 'NoneType' object has no attribute '__getitem**'

**Comment by ecdsa** [comment]
probably not relevant anymore
