### ISSUE TITLE
Cannot sign a message using Electrum 2.7.12: KeyError:  False, 0

### ISSUE THREAD

**Issue by birdie-github** [spesmilo/electrum#2048]
Here's console output:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/util.py", line 575, in run
    result = task.task()
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1410, in sign_message
    return self.keystore.sign_message(sequence, message, password)
  File "/usr/lib/python2.7/site-packages/electrum/keystore.py", line 87, in sign_message
    sec = self.get_private_key(sequence, password)
  File "/usr/lib/python2.7/site-packages/electrum/keystore.py", line 154, in get_private_key
    pk = pw_decode(self.keypairs[pubkey], password)
KeyError: (False, 0)
```
OS: Fedora 24 64
```
$ python --version
Python 2.7.12
```

**Comment by ecdsa** [comment]
duplicate

**Comment by birdie-github** [comment]
Duplicate of what?
