### ISSUE TITLE
Not run without root privileges

### ISSUE THREAD

**Issue by DeadNumbers** [spesmilo/electrum#2061]
```
$ sudo pip2 install https://download.electrum.org/2.7.12/Electrum-2.7.12.tar.gz          
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://download.electrum.org/2.7.12/Electrum-2.7.12.tar.gz
  Downloading https://download.electrum.org/2.7.12/Electrum-2.7.12.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 141kB/s 
Requirement already satisfied (use --upgrade to upgrade): slowaes>=0.1a1 in /usr/local/lib/python2.7/dist-packages/slowaes-0.1a1-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.9 in /usr/local/lib/python2.7/dist-packages/ecdsa-0.13-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): pbkdf2 in /usr/local/lib/python2.7/dist-packages/pbkdf2-1.3-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages/requests-2.12.3-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): qrcode in /usr/local/lib/python2.7/dist-packages/qrcode-5.3-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): protobuf in /usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): dnspython in /usr/local/lib/python2.7/dist-packages/dnspython-1.15.0-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): jsonrpclib in /usr/local/lib/python2.7/dist-packages/jsonrpclib-0.1.7-py2.7.egg (from Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from qrcode->Electrum===2.7.12)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from protobuf->Electrum===2.7.12)
Installing collected packages: Electrum
  Running setup.py install for Electrum ... done
Successfully installed Electrum-2.7.12
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
user:bin/ $ electrum
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 90, in <module>
    check_imports()
  File "/usr/local/bin/electrum", line 70, in check_imports
    import google.protobuf
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg/google/__init__.py", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2513, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2503, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1477, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg/EGG-INFO/namespace_packages.txt'
```

**Comment by cluelessperson** [comment]
You need root to install.  It can then run as a restricted user.

**Comment by ecdsa** [comment]
protobuf was installed read-only on your system, before you installed electrum.
this is not an electrum issue.
reinstall protobuf, and it should work.

**Comment by mudhan** [comment]
I solved the problem with:

chmod -R o+r /usr/local/lib/python2.7/dist-packages
