### ISSUE TITLE
Crash when selecting "Receiving" in Text or Stdio GUI

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2065]
Running electrum gui -g text or electrum gui -g stdio will crash when you select the "receive" function.

electrum gui -g stdio crash:

> enter command: r
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 338, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 253, in init_gui
    self.gui.main()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 160, in main
    while self.done == 0: self.main_command()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 63, in main_command
    elif c == "r" : self.print_addresses()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/stdio.py", line 130, in print_addresses
    messages = map(lambda addr: "%30s    %30s       "%(addr, self.wallet.labels.get(addr,"")), self.wallet.addresses())
AttributeError: 'Standard_Wallet' object has no attribute 'addresses'

electrum gui -g text crash:

> Traceback (most recent call last):
File "/usr/local/bin/electrum", line 338, in <module>
   d.init_gui(config, plugins)
File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 253, in init_gui
   self.gui.main()
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 291, in main
   self.run_tab(2, self.print_receive, self.run_receive_tab)
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 229, in run_tab
   print_func()
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 151, in print_receive
   self.print_qr(addr)
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 190, in print_qr
   self.stdscr.addstr(i+5, 5, l, curses.color_pair(3))
_curses.error: addstr() returned ERR

This happens with 2.7.12.

**Comment by ecdsa** [comment]
I can reproduce the error with stdio, not with curses

**Comment by shsmith** [comment]
Agreed. I did a fresh test under a clean install of Ubuntu Server 14.04, over ssh. Did not install python-qt4. Was not able to reproduce the crash in -g text mode. Must have been something specific to my other environment.

The original report of this crash was in #electrum on freenet.
>[12/3 20:46] dreamer!~henk@melange.soleus.nu has joined
[12/3 20:47] <dreamer> ohai. finally got my coins from buggy bitc to electrum. I see there's an ncurses interface for electrum. hope it gets to be as nice as bitc is/was
[12/3 20:48] <dreamer> otherwise totally new to electrum and using btc regularly. so cheers :)
[12/3 20:51] <tnkflx_> Hmmm, no idea how good or bad the electrum ncurses interface is tbh
[12/3 21:15] <dreamer> tnkflx_: it crashed when I had a read-only wallet as default and went to the receive tab hehe

**Comment by shsmith** [comment]
BTW, I tested using a fresh wallet created via "electrum create" command. Did not try any other kind of wallet.

**Comment by ecdsa** [comment]
fixed stdio in 46c3fe4efaeba48644729969160cb2ed1ad96a53
