### ISSUE TITLE
[2.7.13] Cannot run locally without installing first

### ISSUE THREAD

**Issue by birdie-github** [spesmilo/electrum#2095]
```
[birdie@localhost electrum-2.7.13]$ ./electrum
Error: Could not find icons file.
Please run 'pyrcc4 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum
Traceback (most recent call last):
  File "/home/birdie/Temp/electrum-2.7.13/lib/plugins.py", line 80, in load_plugins
    self.load_plugin(name)
  File "/home/birdie/Temp/electrum-2.7.13/lib/plugins.py", line 99, in load_plugin
    p = loader.load_module(full_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/birdie/Temp/electrum-2.7.13/plugins/exchange_rate/qt.py", line 4, in <module>
    from electrum_gui.qt.util import *
  File "/home/birdie/Temp/electrum-2.7.13/gui/qt/__init__.py", line 56, in <module>
    sys.exit(1)
SystemExit: 1
Error: Could not find icons file.
Please run 'pyrcc4 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum
```

**Comment by ecdsa** [comment]
it works for me.
where did you download the package from?

**Comment by birdie-github** [comment]
https://github.com/spesmilo/electrum/archive/2.7.13.tar.gz

**Comment by ecdsa** [comment]
please download from electrum.org
github provides only the development version.
