### ISSUE TITLE
exception on opening a bitcoin: url

### ISSUE THREAD

**Issue by fauno** [spesmilo/electrum#2118]
when i open a bitcoin: url i get this error and the "please wait" message stays there forever. using 2.7.13 at first but then i realized there was 2.7.17 and it was the same, only thing that changes is the thread number, to 12.

```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/electrum/util.py", line 454, in get_payment_request_thread
    request = pr.get_payment_request(r)
  File "/usr/lib/python2.7/site-packages/electrum/paymentrequest.py", line 93, in get_payment_request
    pr = PaymentRequest(data, error)
UnboundLocalError: local variable 'error' referenced before assignment
```

**Comment by fauno** [comment]
2.6.4 works

**Comment by ecdsa** [comment]
this commit broke it: c666070af430e096d734328eb630cf573017d951
