### ISSUE TITLE
Linux Debian error after upgrade 2.7.18

### ISSUE THREAD

**Issue by danilomoretto** [spesmilo/electrum#2147]
hi, i always use Electrum wallet, recently i upgrade from an early version to 2.7.18 and open it without problems, after close and reopen the wallet doesnt working anymore.
I run it at the console to see some verbose logs and a have it:
Traceback (most recent call last):
  File "./electrum", line 343, in <module>
    d.init_gui(config, plugins)
  File "/home/danilo/carteras/Electrum-2.7.18/lib/daemon.py", line 257, in init_gui
    self.gui.main()
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/__init__.py", line 208, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/__init__.py", line 174, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/__init__.py", line 147, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/main_window.py", line 179, in __init__
    self.load_wallet(wallet)
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/main_window.py", line 307, in load_wallet
    self.utxo_list.update()
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/util.py", line 478, in update
    self.on_update()
  File "/home/danilo/carteras/Electrum-2.7.18/gui/qt/utxo_list.py", line 44, in on_update
    self.utxos = self.wallet.get_utxos()
  File "/home/danilo/carteras/Electrum-2.7.18/lib/wallet.py", line 545, in get_utxos
    utxos = self.get_addr_utxo(addr)
  File "/home/danilo/carteras/Electrum-2.7.18/lib/wallet.py", line 496, in get_addr_utxo
    coins.pop(txi)
KeyError: u'59f24a3f2d47073ef7c04581598c5bbdd132b40d903decc5463d90f94d25bfa3:170'

I reinstaleed it using pip, and also, downloaded the tar.gz but sam error

Help please
thanks

**Comment by ecdsa** [comment]
unfortunately I do not know why this happened.
you can clear your history from the console, by typing "wallet.clear_history()"
then restart electrum, it will rebuild its history.

**Comment by danilomoretto** [comment]
Hi,
I made a downgrade to 2.7.13 and worked again, but im going to try the
cleaning fix. Thanks

**Comment by ecdsa** [comment]
are you sure that what you are reporting is reproducible, or is it just a coincidence?
I don't see anything between 2.7.13 and 2.7.18 that could explain that..

**Comment by danilomoretto** [comment]
Hi Thomas, i just try today again and wallet opened without problem ver
2.7.18. Only after open it before with a early version (2.7.13) the same
version i was using before upgrade...

Thanks a lot for the support and answer.

2017-02-05 8:54 GMT-04:00 ThomasV <notifications@github.com>:

**Comment by prof7bit** [comment]
please reopen this bug

electrum
Traceback (most recent call last):
  File "/home/bernd/.local/bin/electrum", line 373, in <module>
    d.init_gui(config, plugins)
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum/daemon.py", line 284, in init_gui
    self.gui.main()
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/__init__.py", line 248, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/__init__.py", line 209, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/__init__.py", line 174, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/main_window.py", line 196, in __init__
    self.load_wallet(wallet)
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/main_window.py", line 331, in load_wallet
    self.utxo_list.update()
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/util.py", line 473, in update
    self.on_update()
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum_gui/qt/utxo_list.py", line 43, in on_update
    self.utxos = self.wallet.get_utxos()
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum/wallet.py", line 534, in get_utxos
    utxos = self.get_addr_utxo(addr)
  File "/home/bernd/.local/lib/python3.5/site-packages/electrum/wallet.py", line 484, in get_addr_utxo
    coins.pop(txi)
KeyError: '9e9ef2573b6192d5bc9419f58559dde5c1fca0e03624c3d0566b4632b0051f65:0'

This is with the latest version 3.0.2

The wallet file contains a few dozen random keys, no seed. I used it as a container for all my old Multibit and Schildbach keys of which some still receive some mBTC every now and then. It used to work fine until today :-(

It does not even start the gui anymore, it immediately crashes.
