### ISSUE TITLE
Electrum doesn't start anymore - this is the output!

### ISSUE THREAD

**Issue by ananassaft** [spesmilo/electrum#2182]
Hey guys!
I hope I am in the correct subforum. If not, please move. 
I am using Kali Linux and Mint. On Kali I have installed electrum and did the mistake to NOT write dowen the seed. The next time, I will!!

So I have 300€ on my electrum wallet. My electrum version is:

`
sudo apt-get install electrum
electrum is already installed the newest version (2.7.9-1).`

It worked all the time, untill I installed w3af via "pip".

Since then it gives me this output:

[quote]
tuxy@kali:~$ sudo electrum
Traceback (most recent call last):
  File "/usr/bin/electrum", line 75, in <module>
    check_imports()
  File "/usr/bin/electrum", line 51, in check_imports
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 59, in <module>
    vendored('urllib3.contrib.pyopenssl')
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 32, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
tuxy@kali:~$ 

[/quote]

Does anyone know what the  problem could be? Or how to fix it? I need this money at my wallet. 

I would give the person who has the solution 100€ in btc. 

pls help me.

thanks.

**Comment by ananassaft** [comment]
why is my output lined?
I try it again:

> tuxy@kali:~$ sudo electrum
Traceback (most recent call last):
  File "/usr/bin/electrum", line 75, in <module>
    check_imports()
  File "/usr/bin/electrum", line 51, in check_imports
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 59, in <module>
    vendored('urllib3.contrib.pyopenssl')
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 32, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'


ok..worked


pls help me if u can... thanks a lot

**Comment by dabura667** [comment]
What version of openSSL you using?

**Comment by ecdsa** [comment]
that's an issue with your linux distribution; do not report it here.
download electrum from electrum.org
