### ISSUE TITLE
init_network() in __init__.py doesn't work

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#2235]
The "None" in this line:

wizard = InstallWizard(self.config, self.app, self.plugins, None)

causes this:

Traceback (most recent call last):
  File "/home/neil/src/electrum/gui/qt/__init__.py", line 209, in main
    self.init_network()
  File "/home/neil/src/electrum/gui/qt/__init__.py", line 203, in init_network
    wizard = InstallWizard(self.config, self.app, self.plugins, None)
  File "/home/neil/src/electrum/gui/qt/installwizard.py", line 100, in __init__
    BaseWizard.__init__(self, config, storage)
  File "/home/neil/src/electrum/lib/base_wizard.py", line 38, in __init__
    self.storage = WalletStorage(path)
  File "/home/neil/src/electrum/lib/storage.py", line 70, in __init__
    self.file_exists = os.path.exists(self.path)
  File "/usr/local/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

I'm not sure what the purpose of this function is, but if I just leave it empty everything is fine.

**Comment by ecdsa** [comment]
this is related to the recent changes in storage.py
