### ISSUE TITLE
BaseException: wallet format requires update

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2257]
Attempted to open an older wallet file using File > Open 
There was no visible error message and the wallet window did not open.
This traceback was logged:
```
Traceback (most recent call last):
  File "electrum\gui\qt\__init__.py", line 166, in start_new_window
    wallet = Wallet(storage)
  File "electrum\lib\wallet.py", line 1751, in __new__
    wallet = WalletClass(storage)
  File "electrum\lib\wallet.py", line 1563, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "electrum\lib\wallet.py", line 1408, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "electrum\lib\wallet.py", line 104, in __init__
    self.load_keystore()
  File "electrum\lib\wallet.py", line 1530, in load_keystore
    self.keystore = load_keystore(self.storage, 'keystore')
  File "electrum\lib\keystore.py", line 610, in load_keystore
    raise BaseException('wallet format requires update')
BaseException: wallet format requires update
```
This happened in git-head.
I could not reproduce in 2.7.18. Perhaps a recent regression.

**Comment by shsmith** [comment]
This logic 
https://github.com/spesmilo/electrum/blob/master/gui/qt/__init__.py#L157-L166

Seems to be missing the conversion checks in this similar code block: https://github.com/spesmilo/electrum/blob/master/lib/daemon.py#L206-L221

**Comment by ecdsa** [comment]
thanks for looking that up

**Comment by shsmith** [comment]
Fix confirmed. I can successfully open (and convert) the old wallet now. Thank you.
