### ISSUE TITLE
Error in payto command

### ISSUE THREAD

**Issue by angelsilva** [spesmilo/electrum#2278]
Hi friends, already install the latest version of electrum "2.8", I am trying to run the following command:

electrum payto -f 0.0003 -F 19LYUf4NSvmAq5ZbJKTAHWYbMFz4uj2AYf 1E1vDcXnYEnhP8jaJWbSnLDThEM5rmXLFn 0.001 --unsigned

But the following error is displayed:

Traceback (most recent call last)
  File "/ usr / local / bin / electrum", line 5, in <module>
    Pkg_resources.run_script ('Electrum == 2.8.0', 'electrum')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    Self.require (requires) [0] .run_script (script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    Execfile (script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.8.0-py2.7.egg/EGG-INFO/scripts/electrum", line 420, in <module>
    Result = server.run_cmdline (config_options)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    Return self .__ send (self .__ name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    Check_for_errors (response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    Raise ProtocolError ((code, message))
Jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error: File "/usr/local/lib/python2.7/dist-packages/electrum/coinchooser.py", line 232, in choose_buckets | TypeError: unsupported operand type (S) for +: \ 'int \' and \ 'unicode \' ')

Can you help me?

**Comment by ecdsa** [comment]
make sure you restarted your daemon after you upgraded electum.
maybe the daemon is running an older version

**Comment by angelsilva** [comment]
Yes, that was the problem, thank you very much, you are a genius!
