### ISSUE TITLE
Exception in is_segwit_input

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2321]
I did some testnet-segwit mining, and when I right-click a coinbase transaction and select 'details' I get this traceback:
```
Traceback (most recent call last):
  File "electrum\gui\qt\history_list.py", line 158, in <lambda>
    menu.addAction(_("Details"), lambda: self.parent.show_transaction(tx))
  File "electrum\gui\qt\main_window.py", line 710, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "electrum\gui\qt\transaction_dialog.py", line 45, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "electrum\gui\qt\transaction_dialog.py", line 128, in __init__
    self.update()
  File "electrum\gui\qt\transaction_dialog.py", line 181, in update
    tx_hash, status, label, can_broadcast, can_rbf, amount, fee, height, conf, timestamp, exp_n = self.wallet.get_tx_info(self.tx)
  File "electrum\lib\wallet.py", line 435, in get_tx_info
    tx_hash = tx.txid()
  File "electrum\lib\transaction.py", line 754, in txid
    all_segwit = all(self.is_segwit_input(x) for x in self.inputs())
  File "electrum\lib\transaction.py", line 754, in <genexpr>
    all_segwit = all(self.is_segwit_input(x) for x in self.inputs())
  File "electrum\lib\transaction.py", line 636, in is_segwit_input
    return txin['type'] in ['p2wpkh-p2sh']
KeyError: 'type'
```
This happened in git-head.

At least I think this is a coinbase transaction. The amount seems odd, so maybe it is something else:
![image](https://cloud.githubusercontent.com/assets/859149/24128142/2aabcd2e-0d97-11e7-85b1-0b56e8f444cd.png)

**Comment by shsmith** [comment]
I tried to view details on other transactions and some give this other traceback:
```
Traceback (most recent call last):
  File "electrum\gui\qt\history_list.py", line 158, in <lambda>
    menu.addAction(_("Details"), lambda: self.parent.show_transaction(tx))
  File "electrum\gui\qt\main_window.py", line 710, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "electrum\gui\qt\transaction_dialog.py", line 45, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "electrum\gui\qt\transaction_dialog.py", line 128, in __init__
    self.update()
  File "electrum\gui\qt\transaction_dialog.py", line 181, in update
    tx_hash, status, label, can_broadcast, can_rbf, amount, fee, height, conf, timestamp, exp_n = self.wallet.get_tx_info(self.tx)
  File "electrum\lib\wallet.py", line 435, in get_tx_info
    tx_hash = tx.txid()
  File "electrum\lib\transaction.py", line 757, in txid
    ser = self.serialize(witness=False)
  File "electrum\lib\transaction.py", line 739, in serialize
    txins = var_int(len(inputs)) + ''.join(self.serialize_input(txin, self.input_script(txin, estimate_size)) for txin in inputs)
  File "electrum\lib\transaction.py", line 739, in <genexpr>
    txins = var_int(len(inputs)) + ''.join(self.serialize_input(txin, self.input_script(txin, estimate_size)) for txin in inputs)
  File "electrum\lib\transaction.py", line 653, in input_script
    redeem_script = segwit_script(pubkeys[0])
  File "electrum\lib\transaction.py", line 484, in segwit_script
    pkh = hash_160(pubkey.decode('hex')).encode('hex')
  File "Python27x86\lib\encodings\hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

```

If you need a test case, you can use the mpk of this testnet wallet: tpubD6NzVbkrYhZ4XKbstkbLqxAEQr3abXMd4MD3VxM8ACP6Aj7uBWmvt7ESffxiszLsqiZtNNNCZetbADhKQmizLdy8uxkJdgT88Ye1n33EKpS

The first tx on 2017-03-20 and the last tx on 2017-03-19 give these two tracebacks.
