### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 34; 2 is required

### ISSUE THREAD

**Issue by Yamakaky** [spesmilo/electrum#2338]
```
[SimpleConfig] electrum directory /home/yamakaky/.electrum
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', u'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', u'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', u'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', u'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0082
[Network] starting network
[Network] connecting to electrum.dragonzone.net:50002:s as new interface
[FxThread] using exchange BitcoinAverage
[electrum.online] cannot resolve hostname
[WalletStorage] wallet path /home/yamakaky/.electrum/wallets/default_wallet
[profiler] load_transactions 0.0035
[profiler] build_reverse_history 0.0001
[profiler] save_transactions 0.0007
[profiler] check_history 0.0009
Traceback (most recent call last):
  File "/usr/bin/electrum", line 378, in <module>
    d.init_gui(config, plugins)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 200, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 157, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 220, in load_wallet
    wallet = Wallet(storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1757, in __new__
    wallet = WalletClass(storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1564, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1409, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 134, in __init__
    self.contacts = Contacts(self.storage)
  File "/usr/lib/python2.7/site-packages/electrum/contacts.py", line 41, in __init__
    self.update(d)
ValueError: dictionary update sequence element #0 has length 34; 2 is required
[BitcoinAverage] getting fx quotes for EUR
[Plugins] stopped
[Network] stopping network
[Network] stopped
[Daemon] shutting down network
[Daemon] stopped
```
My config:
```
{
    "alias": "", 
    "auto_connect": true, 
    "console-history": [], 
    "fee_level": 2, 
    "gui_last_wallet": "/home/yamakaky/.electrum/wallets/default_wallet", 
    "is_maximized": false, 
    "language": "fr_FR", 
    "proxy": null, 
    "recently_open": [
        "/home/yamakaky/.electrum/wallets/default_wallet"
    ], 
    "server": "electrum.dragonzone.net:50002:s", 
    "use_exchange_rate": true
}
```
I'm on python 2.7.13 and electrum 2.8.1 on Archlinux.

**Comment by Yamakaky** [comment]
Thanks. Do you know when it will be released?
