### ISSUE TITLE
Multisig with Ledger Nano S failed

### ISSUE THREAD

**Issue by yinyunqiao** [spesmilo/electrum#2352]
Electrum 2.8.2, Ubuntu 16.04,  with Ledger Nano S and KeepKey multisig wallet.   Got the following exception (after keepkey signed successfully):

> 

RECEIVED PART OF SERIALIZED TX (191 BYTES)
RECEIVED PART OF SERIALIZED TX (33 BYTES)
RECEIVED PART OF SERIALIZED TX (38 BYTES)
SIGNED IN 16.858 SECONDS, CALLED 16 MESSAGES, 262 BYTES
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 341, in sign_transaction
    redeemScripts.append(bytearray(utxo[2].decode('hex')))
AttributeError: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1118, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 382, in sign_transaction
    self.give_error(e, True)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 197, in give_error
    raise Exception(message)
Exception: 'NoneType' object has no attribute 'decode'

**Comment by MaDeRkAn** [comment]
I get also same error.
