### ISSUE TITLE
Unable to sweep compressed private key

### ISSUE THREAD

**Issue by bauerj** [spesmilo/electrum#2353]
This is using 2.8.2:

I tried to sweep this private key: `L2ydjUcdmR2J5yeyKukYrd1aLxGWxStByMaCeLDvchMpNJyDE1iA` (there's only dust in it).

After confirming the dialog, it closes without further notice. The following traceback appears in the console:

```
Traceback (most recent call last):
  File "C:/Users/bauerj/Documents/GitHub/electrum\gui\qt\main_window.py", line 2309, in sweep_key_dialog
    tx = self.wallet.sweep(get_pk(), self.network, self.config, get_address(), None)
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\wallet.py", line 905, in sweep
    tx.sign(keypairs)
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\transaction.py", line 825, in sign
    pre_hash = Hash(self.serialize_preimage(i).decode('hex'))
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\transaction.py", line 728, in serialize_preimage
    txouts = var_int(len(outputs)) + ''.join(self.serialize_output(o) for o in outputs)
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\transaction.py", line 728, in <genexpr>
    txouts = var_int(len(outputs)) + ''.join(self.serialize_output(o) for o in outputs)
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\transaction.py", line 699, in serialize_output
    s = int_to_hex(amount, 8)
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\bitcoin.py", line 162, in int_to_hex
    return rev_hex(s)
  File "C:/Users/bauerj/Documents/GitHub/electrum\lib\bitcoin.py", line 156, in rev_hex
    return s.decode('hex')[::-1].encode('hex')
  File "C:\Python27\lib\encodings\hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
```

Since it's possible to import this, it should be possible to sweep it too.

**Comment by dabura667** [comment]
What is your fee setting at on your preferences?
