### ISSUE TITLE
stdio/text GUIs suffering from code rot

### ISSUE THREAD

**Issue by twopir** [spesmilo/electrum#2354]
I don't have a GUI installed on my Bitcoin machine (FreeBSD 9.3, Python 2.7.13, Electrum 2.8.2 downloaded as of today), so I rely on the stdio/text interfaces to Electrum.

These interfaces have multiple issues

* Neither the text/stdio UIs properly upgrade the wallet storage format, they just dump out with a stack trace saying that the format requires upgrade. I added a `pdb.set_trace()` in `gui/text.py` and called `storage.upgrade()` myself.
* in the stdio UI, requesting history bombs out with
```
Traceback (most recent call last):
  File "./electrum", line 379, in <module>
    d.init_gui(config, plugins)
  File "/usr/home/pi/Electrum-2.8.2/lib/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 163, in main
    while self.done == 0: self.main_command()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 62, in main_command
    elif c == "i" : self.print_history()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 93, in print_history
    tx_hash, confirmations, value, timestamp, balance = item
ValueError: too many values to unpack
```
* The text/curses UI is just barely usable: 
  *  Hitting Enter on a transaction gives a useless dialog:
<img width="444" alt="screen shot 2017-04-05 at 11 18 09" src="https://cloud.githubusercontent.com/assets/377384/24720311/a274769c-19f1-11e7-8d74-181c35b28523.png">
  * this is what the Receive window looks like for me:
<img width="815" alt="screen shot 2017-04-05 at 11 19 39" src="https://cloud.githubusercontent.com/assets/377384/24720534/3ccec74c-19f2-11e7-9f11-39a0d56b3717.png">
  * Too many operations in the text/curses UI just pop up a dialog box with the keycode.

**Comment by twopir** [comment]
With the stdio UI, storing a payment order works fine. Sending it does not:
```
Traceback (most recent call last):
  File "./electrum", line 379, in <module>
    d.init_gui(config, plugins)
  File "/usr/home/pi/Electrum-2.8.2/lib/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 163, in main
    while self.done == 0: self.main_command()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 65, in main_command
    elif c == "s" : self.send_order()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 147, in send_order
    self.do_send()
  File "/usr/home/pi/Electrum-2.8.2/gui/stdio.py", line 180, in do_send
    if self.wallet.use_encryption:
AttributeError: 'Standard_Wallet' object has no attribute 'use_encryption'
```

Entering Unicode into the Curses UI generates similar `M-BM-BLAH BLAH` barf.

**Comment by SomberNight** [comment]
Some of the mentioned issues should be fixed on master now, namely at least
- storage upgrades
- "requesting history bombs out with..."
- "storing a payment order works fine. Sending it does not"
