### ISSUE TITLE
Error message in restore command

### ISSUE THREAD

**Issue by bsbits** [spesmilo/electrum#2388]
Usage of electrum on Ubuntu server

`electrum restore XPUB
`
```
Recovering wallet...
Recovery successful
Wallet saved in '/home/ubuntu/.electrum/wallets/default_wallet'
Exception in thread Thread-10 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/electrum/blockchain.py", line 119, in init_headers_file
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
  File "/usr/lib/python2.7/urllib.py", line 279, in retrieve
  File "/usr/lib/python2.7/urllib.py", line 975, in close
  File "/usr/lib/python2.7/socket.py", line 282, in close
  File "/usr/lib/python2.7/ssl.py", line 397, in close
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'close'
```
The wallet was created and saved, but would like to know more about the error.

**Comment by bsbits** [comment]
I deleted the wallet and imported again, no error message.
