### ISSUE TITLE
Plot history fails silently

### ISSUE THREAD

**Issue by rkfg** [spesmilo/electrum#2430]
I created a watch-only wallet with 3 addresses in it. Here's what happens on plot history:

```python
Traceback (most recent call last):
  File "/home/rkfg/.local/lib/python2.7/site-packages/Electrum-2.9.0-py2.7.egg/electrum_gui/qt/main_window.py", line 2230, in plot_history_dialog
    plt = plot_history(self.wallet, history)
  File "/home/rkfg/.local/lib/python2.7/site-packages/Electrum-2.9.0-py2.7.egg/electrum/plot.py", line 51, in plot_history
    dates, values = zip(*sorted(hist_out.items()))
ValueError: need more than 0 values to unpack
```

Export to CSV works fine, by the way.

**Comment by ecdsa** [comment]
how many items are there in your history?

**Comment by rkfg** [comment]
Only one transaction for each address totalling in three.

**Comment by rkfg** [comment]
Uhh, now it says "need more than 0 values to unpack" in a message box, not a very clear message about what exactly went wrong and why.
