### ISSUE TITLE
while sending btc, python error

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2510]
I got this error.
What is the problem?

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 421, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/dns/name.py", line 154, in encode | LabelTooLong: A DNS label is > 63 octets long.')

**Comment by ecdsa** [comment]
you probanly want to upgrade jsonrpclib

**Comment by zottirik** [comment]
When I try to sent paytomany, I got this error.
My jsonrpclib is 0.1.7 and any upgrade didn't work.
Do you have any idea?

**Comment by zottirik** [comment]
I solved. Thanks,
