### ISSUE TITLE
deserialize problem

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2517]
When I type electrum daemon load_wallet, I get this error;
[Synchronizer] cannot deserialize transaction, skipping c2251c9e4938882c3479235c3c42af9dae7a41b5603cf23ab66ec69015e192d6

wallet not synchronizing and when i type electrum history, i get this error:

jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/lib/python2.7/site-packages/electrum/commands.py", line 454, in history | AttributeError: \'NoneType\' object has no attribute \'deserialize\'')

line 454 is tx.deserialize()

@ecdsa I think there is a bug in deserialize command. This txid(c2251c9e4938882c3479235c3c42af9dae7a41b5603cf23ab66ec69015e192d6) can not be processed

electrum deserialize 0100000002b01f4b7aed57d81c38787d1742d4f609ae2abf36371d66defda5c3555e08c0b2ea0100006b483045022100e0ab57bf21718cfe31b8ad799b3e2495dc34a17b55b7161d06a76f828302413202205a8ac99fc0c4fc441d90664dc1c40e8587f9b3cc1503bd8a35b8faa7d063cf48012102e1df9b80b04a6e641c7212da01dc0f16be35a20224587dfb82b1fcda87add8edffffffff09b28e07e420c8462785423afc372715e6b01ec059f14d143b5782e316fe36f600000000da0047304402203e31fe85916e8e0475b06c5f16de5eb1097ba8a446961e97d98850af7191ba0902202f2054f4f3378142636453c6569e44f32d701b05be8a1f51d626cb950077877a81483045022100f8795774d4a5d23ef2dba42d589416bfc8d01826f9e461fc8b8512d2f82c406a02201c12a6e2a29edaed3fdf3594bfcd268980e249645f3af1f8914c6c6edcb848500147522102114524827e46f58fff8959e1eac73ff96a16d23d53516a96b021c89ff9a692f321029e974d16bc36d8b4ba78e830a180380523e461243c984475f57371a73dad878052aeffffffff02ce0f2101000000001976a91493ae842c1c6f4384d26bc3441bc264b937c3aa4688acd0610000000000001976a91475eac11f3cfda3e79c90469dac0ebaaaacde701488ac00000000

gives an error

**Comment by zottirik** [comment]
wallet not synchronizing and when i type electrum history, i get this error:

jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/lib/python2.7/site-packages/electrum/commands.py", line 454, in history | AttributeError: \'NoneType\' object has no attribute \'deserialize\'')

**Comment by ecdsa** [comment]
that command works for me. please upgrade electrum.

**Comment by zottirik** [comment]
Hi @ecdsa , my version is 2.8.3, I tried it on Linux daemon and OS X Gui. It gives error only this raw tx.

Can you try to run this:

deserialize('0100000002b01f4b7aed57d81c38787d1742d4f609ae2abf36371d66defda5c3555e08c0b2ea0100006b483045022100e0ab57bf21718cfe31b8ad799b3e2495dc34a17b55b7161d06a76f828302413202205a8ac99fc0c4fc441d90664dc1c40e8587f9b3cc1503bd8a35b8faa7d063cf48012102e1df9b80b04a6e641c7212da01dc0f16be35a20224587dfb82b1fcda87add8edffffffff09b28e07e420c8462785423afc372715e6b01ec059f14d143b5782e316fe36f600000000da0047304402203e31fe85916e8e0475b06c5f16de5eb1097ba8a446961e97d98850af7191ba0902202f2054f4f3378142636453c6569e44f32d701b05be8a1f51d626cb950077877a81483045022100f8795774d4a5d23ef2dba42d589416bfc8d01826f9e461fc8b8512d2f82c406a02201c12a6e2a29edaed3fdf3594bfcd268980e249645f3af1f8914c6c6edcb848500147522102114524827e46f58fff8959e1eac73ff96a16d23d53516a96b021c89ff9a692f321029e974d16bc36d8b4ba78e830a180380523e461243c984475f57371a73dad878052aeffffffff02ce0f2101000000001976a91493ae842c1c6f4384d26bc3441bc264b937c3aa4688acd0610000000000001976a91475eac11f3cfda3e79c90469dac0ebaaaacde701488ac00000000')

**Comment by ecdsa** [comment]
please paste the error you get

**Comment by zottirik** [comment]
This is OS X error:
Traceback (most recent call last):
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 105, in _run
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 83, in func_wrapper
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 244, in deserialize
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 581, in deserialize
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 454, in deserialize
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 454, in <genexpr>
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 424, in parse_input
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 372, in parse_scriptSig
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/transaction.py", line 292, in parse_sig
AssertionError
>> 

This is Linux Error:

Traceback (most recent call last):
  File "/usr/bin/electrum", line 421, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/lib/python2.7/site-packages/electrum/transaction.py", line 292, in parse_sig | AssertionError')

**Comment by ecdsa** [comment]
ok, that bug is fixed in master, but not in 2.8.3, that's why I could not reproduce it.

**Comment by zottirik** [comment]
Which file must I update?

**Comment by ecdsa** [comment]
you can use git master, or wait for the next release
