### ISSUE TITLE
Exception in network.py (2.8.3, line 745, KeyError: 'result')

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2533]
I compiled Electrum 2.8.3 from source on Debian 9.0.
```
user@debian:~/wspace/electrum$ git checkout tags/2.8.3
```

While playing around in the GUI, the following exception was thrown (printed in terminal):
```
user@debian:~/wspace/electrum$ ./electrum --testnet
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/wspace/electrum/lib/network.py", line 845, in run
    self.wait_on_sockets()
  File "/home/user/wspace/electrum/lib/network.py", line 839, in wait_on_sockets
    self.process_responses(interface)
  File "/home/user/wspace/electrum/lib/network.py", line 625, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/user/wspace/electrum/lib/network.py", line 572, in process_response
    self.on_get_chunk(interface, response)
  File "/home/user/wspace/electrum/lib/network.py", line 745, in on_get_chunk
    idx = self.blockchain.connect_chunk(req_idx, response['result'])
KeyError: 'result'
```
No error was visible in the GUI and Electrum kept functioning.

**Comment by ecdsa** [comment]
server side issue, but I think the client should be robust to that, so the issue is worth fixing
