### ISSUE TITLE
Failure trying to sign with keepkey

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#2562]
Current git head:

Traceback (most recent call last):
  File "/Users/neil/src/electrum/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/Users/neil/src/electrum/lib/wallet.py", line 1125, in sign_transaction
    k.sign_transaction(tx, password)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 238, in sign_transaction
    client = self.get_client(keystore)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 142, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/Users/neil/src/electrum/lib/plugins.py", line 391, in client_for_keystore
    handler.update_status(False)
AttributeError: 'NoneType' object has no attribute 'update_status'

**Comment by kyuupichan** [comment]
Just noticed I didn't have the keepkey package installed.  A clear error would be nice.
