### ISSUE TITLE
Cannot open electrum [Linux]

### ISSUE THREAD

**Issue by asspounder** [spesmilo/electrum#2563]
When i open electrum, nothing shows up. It's there in the processes, and when i type 'electrum' in terminal nothing happens. When i then cancel i get this traceback:

 electrum
^CTraceback (most recent call last):
  File "/usr/local/bin/electrum", line 374, in <module>
    fd, server = daemon.get_fd_or_server(config)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 63, in get_fd_or_server
    server = get_server(config)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 85, in get_server
    time.sleep(1.0)
KeyboardInterrupt

any ideas? I tried restarting the computer, and uninstalling and reinstalling electrum by 'pip2'.

**Comment by ecdsa** [comment]
can you check if you have permisions to write the 'daemon' file in your electrum directory?

**Comment by ptilancelot** [comment]
ok, je deviens fou..

2017-06-30 13:07 GMT+02:00 ThomasV <notifications@github.com>:

**Comment by bsbits** [comment]
Can you make sure you did not load the wallet in electrum daemon via command line ?

If you did, electrum GUI won't start till you close it.

Try 
`electrum daemon close_wallet -w wallet-filename`  or  `electrum daemon stop`

**Comment by ecdsa** [comment]
@bsbits no, that would not cause what he describe.

**Comment by clonmac** [comment]
I'm not sure if this is the same issue or not, but I think it might be related, so I figured I'd post this. I'm having an issue where it takes an extremely long time to load the electrum gui on Linux. I'm wondering if the OP is just not giving it enough time to launch since it is showing in his processes and therefore he/she cancels the command. 

What I found is that if I delete the 'daemon' file, it launches instantly, but if the 'daemon' file is there and exists, it takes forever to launch (but does eventually launch). The contents of my daemon file list the local loopback address and a random local port. It seems like it tries to connect to that local port and takes a long time to time out. I've tried forcing a launch in gui mode, but it still seems like it is trying to connect to that port or something and that's why it takes so long to launch. 

All I know is if I delete that daemon file and run electrum in the gui, it launches immediately, but then the 'daemon' file gets created automatically and the next time I launch it in the gui it takes a long time again unless I delete that 'daemon' file.

Also, if I run electrum from the command line to, for example, 'listaddresses' then it runs the command instantly if that 'daemon' file isn't there, but then never creates the 'daemon' file. However, it is there, the command line option takes for ever to return results.

Hopefully this helps narrow down if there is an issue or not.

**Comment by LorenzoAncora** [comment]
@clonmac I have the same issue with the AppImage of Electrum on Debian 10.
Removing `~/.electrum/daemon` allows a clear start-up but the file is created again.

@spesmilo can you label this Issue as a **bug**, please?

**Comment by SomberNight** [comment]
@LorenzoAncora anything relevant in the [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging)?
Could you perhaps test with git master?

**Comment by LorenzoAncora** [comment]
Hi @SomberNight ,

> anything relevant in the debug logs?

Logs do not contain useful information. The process is stuck waiting for I/O, nothing is written after the few introductory lines.
To compensate, I've straced it:

```connect(5, {sa_family=AF_INET, sin_port=htons(45653), sin_addr=inet_addr("127.0.0.1")}, 16) = ?```

When the problem happens, Electrum does not proceed after this instruction. It is clearly trying to create a TCP connection to localhost and the connection cannot proceed further. This is the reason because deleting the daemon file (which contains the directives to create the connection) allows for a clear start-up.

>  Could you perhaps test with git master?

I am only interested in using the AppImage version, for logistical reasons.

> Also, how long does it take for Electrum to start if you don't delete the daemon file?

The eternity.
In addition, if I start other instances, these won't exclude each other, creating a series of hanging processes.

**Comment by af7567** [comment]
I have been having this same problem sometimes over the years, but it doesn't seem to matter about the daemon file. I never knew that file existed until I read the earlier comment.
I just have to kill Electrum and start it again and then it works.

I always assumed it was something that happened when Electrum was slow to start up because of the system being under heavy load. Especially when it was the first time running anything in python since the machine booted so none of the required libraries had been loaded into memory already.

**Comment by af7567** [comment]
I had the problem again today and checked the logs. I had got this error when quitting Electrum (Using File>Quit) and then the process stayed running and never quit.
```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/electrum/util.py", line 879, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/lib64/python3.8/site-packages/electrum/daemon.py", line 330, in run
    self.network.stop()
  File "/usr/lib64/python3.8/site-packages/electrum/network.py", line 1170, in stop
    fut.result(timeout=2)
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 441, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
```
If I don't kill electrum then I can't start it up again.

**Comment by natrius** [comment]
Same here with Ubuntu. I'm using KDE Neon, but still. If i just use a new appimage, it opens, but when including the app image to the system and starting with the launcher and not the console, the symbol appears for a short time and then everything is gone. There is no electrum process to see in htop 

When going to `~/Applications` there is an `electrum-3.3.8-x86_64_096096f375bbac2ba6f47fb307e148f2.AppImage` and i'm able to start from there normally.
