### ISSUE TITLE
Cannot parse pubkey , KeyError: 'type'

### ISSUE THREAD

**Issue by boxxiet** [spesmilo/electrum#2565]
try a watch wallet with:   1comboyNsev2ubWRbPZpxxNhghLfonzuN

Traceback (most recent call last):
  File "/Electrum-2.8.3/lib/transaction.py", line 337, in parse_scriptSig
    pubkey, address = xpubkey_to_address(x_pubkey)
  File "/Electrum-2.8.3/lib/keystore.py", line 584, in xpubkey_to_address
    raise BaseException("Cannot parse pubkey")
BaseException: Cannot parse pubkey
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Electrum-2.8.3/lib/network.py", line 845, in run
    self.wait_on_sockets()
  File "/Electrum-2.8.3/lib/network.py", line 839, in wait_on_sockets
    self.process_responses(interface)
  File "/Electrum-2.8.3/lib/network.py", line 625, in process_responses
    self.process_response(interface, response, callbacks)
  File "/Electrum-2.8.3/lib/network.py", line 577, in process_response
    callback(response)
  File "/Electrum-2.8.3/lib/synchronizer.py", line 146, in tx_response
    self.wallet.receive_tx_callback(tx_hash, tx, tx_height)
  File "/Electrum-2.8.3/lib/wallet.py", line 663, in receive_tx_callback
    self.add_transaction(tx_hash, tx)
  File "/Electrum-2.8.3/lib/wallet.py", line 585, in add_transaction
    is_coinbase = tx.inputs()[0]['type'] == 'coinbase'
KeyError: 'type'

**Comment by ecdsa** [comment]
this is harmless; I removed the message to prevent further people opening an issue

**Comment by ecdsa** [comment]
note: the second error you had is not harmless, but I cannot reproduce it, I think it's fixed in master (2.9)
