### ISSUE TITLE
[Android] apk build fails with No file to patch

### ISSUE THREAD

**Issue by taro-k** [spesmilo/electrum#2578]
Could anyone help to solve the following fail?

```
[~/code/electrum/gui/kivy]$ make apk

(...)

[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /home/taro/code/electrum/.b...(and 218 more)
[INFO]:    Prebuilding jpeg for armeabi-v7a
[INFO]:    jpeg has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for jpeg[armeabi-v7a]
[INFO]:    Applying patch build-static.patch
[INFO]:    -> running patch -t -d /home/taro/code/el...(and 216 more)
           working: 9 out of 9 hunks ignored                Exception in thread background thread for pid 7594:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:

  RAN: /usr/bin/patch -t -d /home/taro/code/electrum/.buildozer/android/platform/build/build/other_builds/jpeg/armeabi-v7a/jpeg -p1 -i /home/taro/code/electrum/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/jpeg/build-static.patch

  STDOUT:
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -Naur jpeg/Android.mk b/Android.mk
|--- jpeg/Android.mk    2015-12-14 11:37:25.900190235 -0600
|+++ b/Android.mk       2015-12-14 11:41:27.532182210 -0600
--------------------------
No file to patch.  Skipping patch.
9 out of 9 hunks ignored


  STDERR:

(...)

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=Electrum --bootstrap=sdl2 --requirements=hostpython2,android,openssl,pycrypto,pil,plyer,kivy==master --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/taro/code/electrum/.buildozer/android/platform/build

(...)
```

**Comment by ecdsa** [comment]
no idea. ask in the kivy project.
