### ISSUE TITLE
Command Line do not work

### ISSUE THREAD

**Issue by ibred** [spesmilo/electrum#2592]
Version: 2.8.2
OC: Windows 7

Environment variable:
![2017-07-10_21-58-52](https://user-images.githubusercontent.com/19796511/28034940-6c390b2c-65bb-11e7-92e8-5879ac685de5.png)

Cmd Prompt:
![2017-07-10_22-00-16](https://user-images.githubusercontent.com/19796511/28034960-7e02bcfe-65bb-11e7-9a44-b712a611cb3b.png)

electrum is not a command

**Comment by bauerj** [comment]
Try `electrum-2.8.2` instead.

**Comment by ibred** [comment]
The list of commands does not appear:
![2017-07-10_23-01-21](https://user-images.githubusercontent.com/19796511/28037423-e6a34c9e-65c3-11e7-8c8c-8c90fc241996.png)

**Comment by HellsChicken** [comment]
Same issue here on 2.8.3.  Even running in the electrum directory directly.  Tried both the installer & portable versions.

**Comment by ibred** [comment]
Really no one will help?

**Comment by bauerj** [comment]
As a workaround, you can run Electrum from source to use the CLI.

**Comment by ibred** [comment]
Is there any instruction?

**Comment by hamid67fathi** [comment]
This is my problem too.
I have searched a lot but there is no answer.
some people say there is no command line mode in windows for electrum.
If its true please add it or give me some help to build it by myself.

**Comment by sschleicher** [comment]
Any update on when the windows command line interface will be working?  Thanks.

**Comment by bauerj** [comment]
For instructions on how to run Electrum from source (and be able to use the command line interface), see the "Installation from Python sources" section on https://electrum.org/#download.

Of course it would be better if that would be possible from the official binaries but we don't have any news on that yet.

**Comment by SomberNight** [comment]
This would either need to be solved upstream https://github.com/pyinstaller/pyinstaller/issues/2117; or we would need to use some other tool to create the binaries, which just for this issue, won't happen.

**Comment by turcol** [comment]
In case you need to start Electrum as daemon in Windows, run it from the console:
".\electrum.exe daemon"

**Comment by cculianu** [comment]
You guys may want to check out this pre for Electron Cash: https://github.com/Electron-Cash/Electron-Cash/pull/1295

It's pretty easily adapted/put into Electrum too.  We'll probably merge it later today.  It solves the problem perfectly for windows.  Requires psutils be installed in the windows built at least.

**Comment by EchterAgo** [comment]
It is only almost perfect, but as good as it is going to get. `sys.stdin` is not working when attaching to a console.

**Comment by cculianu** [comment]
Oh so the password prompt may fail.. hmm.  Not a huge deal, I hope.

**Comment by turcol** [comment]
If you want to start electrum from Windows in console mode, you can download (if you do not have it already) Git for Windows (https://git-scm.com/download/win).

The default installation has the Windows Explorer integration selected (Git Bash and Git GUi here). 

During the installation select "Use MinTTY (the default terminal of MSYS2)" that will provide what you need to run electrum from the console.

Once installed, open the File Explorer, right click on the file's area, and select Git Bash Here

You can run electrum like this:
```
"C:\Program Files (x86)\Electrum\electrum-3.3.4.exe" -v
```
or like this
```
"C:\Program Files (x86)\Electrum\electrum-3.3.4.exe" help
```

![image](https://user-images.githubusercontent.com/29822687/56372344-ca7e2c80-61cc-11e9-8c96-f6cef0212354.png)

![image](https://user-images.githubusercontent.com/29822687/56372533-306ab400-61cd-11e9-99ab-0c8a038f82bf.png)

**Comment by cculianu** [comment]
@turcol Nice advice.  Yes, MSYS does a better job of passing the console on to child processes, even if they declare themselves as 'windowed' (which is what Electrum and Electron Cash declare via pyinstaller).  Windows `cmd.exe` doesn't then pass on the console to a 'windowed' process because it would break some legacy programs ... (I presume).

So yes, a workaround is to use MSYS or MINGW on Windows (or cygwin, probably).  Definitely.

Still -- if the Electrum programmers get time -- the ideal solution is to also support `cmd.exe` -- our recent commit to Electron Cash does this quite nicely, and I think it can be ported to Electrum with close to 0 code changes.  /end advertisement for EC. :)

**Comment by EchterAgo** [comment]
MSYS does not correctly load hid libraries yet, but I've made a pull request for this here:

https://github.com/apmorton/pyhidapi/pull/22

**Comment by omidkrad** [comment]
Try this, in a PowerShell terminal run:

```powershell
set-alias electrum (get-item "C:\Program Files (x86)\Electrum\electrum-*-debug.exe")
electrum help
```

**Comment by Dibbyo456** [comment]
@omidkrad perfect. Thank you so much.

**Comment by desirepl** [comment]
@omidkrad, didn't work.
Also with MSYS too. 4.4.2.exe and 4.4.2-portable.exe
But -portable.exe daemon -d throws an error:
Traceback (most recent call last):
  File "run_electrum", line 524, in <module>
  File "run_electrum", line 416, in main
AttributeError: module 'os' has no attribute 'fork'
