### ISSUE TITLE
preferences not showing up

### ISSUE THREAD

**Issue by n0-m4d** [spesmilo/electrum#2603]
hi!

i did 

`sudo snap install electrum`
on ubuntu 16.04.

when starting electrum logs say

```
(process:24198): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
```
but electrum opens and seems to be fine. until i click the preferences icon, then these logs are added 

```
Traceback (most recent call last):
  File "/snap/electrum/2/gui/qt/main_window.py", line 82, in onPress
    self.func()
  File "/snap/electrum/2/gui/qt/main_window.py", line 2773, in settings_dialog
    system_cameras = qrscanner._find_system_cameras()
  File "/snap/electrum/2/lib/qrscanner.py", line 70, in _find_system_cameras
    name = open(os.path.join(device_root, device, 'name')).read()
IOError: [Errno 13] Permission denied: '/sys/class/video4linux/video0/name'
```

and nothing happens. 

**expected behaviour:** 
clicking preferences icon (or _Tools -> Preferences_) opens preferences

**actual behaviour:** 
see above

any help?

**Comment by ecdsa** [comment]
thanks for the info. it seems easy to fix

**Comment by n0-m4d** [comment]
great. but how? and why closed?
