### ISSUE TITLE
Error when initializing new wallet from 2FA wallet seed

### ISSUE THREAD

**Issue by Infrag** [spesmilo/electrum#2608]
When I try to init my wallet from 12-word seed of my previous 2FA protected wallet the window freezes.
In console I see:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 422, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 161, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 259, in run_and_get_wallet
    self.run(action)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 60, in run
    apply(f, args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 87, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 105, in on_wallet_type
    self.run(action)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 60, in run
    apply(f, args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 137, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 60, in run
    apply(f, args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 273, in restore_from_seed
    self.restore_seed_dialog(run_next=self.on_restore_seed, test=test)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 90, in func_wrapper
    apply(run_next, out)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 291, in on_restore_seed
    self.run('on_restore_seed', seed, is_ext)
  File "/usr/local/lib/python2.7/dist-packages/electrum/base_wizard.py", line 60, in run
    apply(f, args)
TypeError: on_restore_seed() takes exactly 4 arguments (3 given)

```
I use Electrum 2.8.3.
If I use standard wallet it works without problems.

**Comment by ecdsa** [comment]
looks like you removed the plugins directory from your code

**Comment by Infrag** [comment]
It's plain electrum instalation. I didn't modify it in any way.

**Comment by ecdsa** [comment]
try removing /usr/local/lib/python2.7/dist-packages/electrum manually, and reinstall.

**Comment by ecdsa** [comment]
any news on that?

**Comment by Infrag** [comment]
I wil try it on weekend.

**Comment by ecdsa** [comment]
closing, no answer

**Comment by vavkamil** [comment]
I'm getting exactly the same error, using fresh installation of electrum 2.9.3 on Linux. Installed via pip2. After removing "/usr/local/lib/python2.7/dist-packages/electrum", with "sudo pip uninstall electrum" and reinstalling it, nothing changed.
[log.txt](https://github.com/spesmilo/electrum/files/1370165/log.txt)

**Comment by vavkamil** [comment]
Instead of creating new "standard" wallet from 2FA seed, I have created a new 2FA wallet, but disabled 2FA when asked about it. Then I was able to create a new "standard" wallet and transferred BTC to it.
