### ISSUE TITLE
Cannot use WalletStorage with encrypted wallet nor can I user wallet class

### ISSUE THREAD

**Issue by deveshaggrawal19** [spesmilo/electrum#2613]
python: python v2.7
os: ubuntu 16.04
electrum: latest
using testnet

Code:
>>>from electrum import WalletStorage
>>>from electrum.wallet import Wallet
>>>storge = WalletStorage('<wallet path>')
>>>wallet = Wallet(storage)

If the wallet is encrypted storage cannot get the values, how can I input a password parameter to decrypt it first? 
If I use a wallet without encryption wallet object gives the following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1757, in __new__
    wallet = WalletClass(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1564, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1409, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 104, in __init__
    self.load_keystore()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1532, in load_keystore
    self.is_segwit = self.keystore.is_segwit()
  File "/usr/local/lib/python2.7/dist-packages/electrum/keystore.py", line 339, in is_segwit
    return bool(deserialize_xpub(self.xpub)[0])
  File "/usr/local/lib/python2.7/dist-packages/electrum/bitcoin.py", line 779, in deserialize_xpub
    return deserialize_xkey(xkey, False)
  File "/usr/local/lib/python2.7/dist-packages/electrum/bitcoin.py", line 773, in deserialize_xkey
    raise BaseException('Invalid header')
BaseException: Invalid header

What could be the problem here?

**Comment by bauerj** [comment]
Check out `storage.is_encrypted` and `storage.decrypt(password)`.

**Comment by deveshaggrawal19** [comment]
that solves the storage problem, but still getting error the invalid header with testnet wallets. Mainnet wallets are working fine.

**Comment by bauerj** [comment]
Are you sure you are in testnet mode?

**Comment by deveshaggrawal19** [comment]
how can I? I am in a different python console.
Do you mean that I should start a daemon in testnet and check again

**Comment by bauerj** [comment]
Yes, if you are using the daemon.

Otherwise, this should work:
    
    from electrum import bitcoin
    bitcoin.set_testnet()

**Comment by deveshaggrawal19** [comment]
thanks a lot for the quick reply. Can you also telle me what set_nolnet() does? And If I set bitcoin to testnet, and exit the console, would the config reset to the previous known or stays to testnet?

**Comment by bauerj** [comment]
> Can you also telle me what set_nolnet() does?

nolnet is the no-limits testnet.

> And If I set bitcoin to testnet, and exit the console, would the config reset to the previous known or stays to testnet?

No.
