### ISSUE TITLE
ValueError: invalid literal for int() with base 16: '0x'

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2634]
Getting this traceback in git-head on testnet:
```
[Network] no height for main interface
[SPV] redoing 5c9a23c33c2ced90c04f3079757901beba2541366dafa71ec692e2fd6ca0ec97
[electrum-btc-testnet.petrkr.net] failed to connect 0x05: Connection refused
[profiler] on_update 0.0180
Exception in thread Thread-3:
Traceback (most recent call last):
  File "Python27x86\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "electrum\lib\network.py", line 974, in run
    self.wait_on_sockets()
  File "electrum\lib\network.py", line 944, in wait_on_sockets
    self.process_responses(interface)
  File "electrum\lib\network.py", line 640, in process_responses
    self.process_response(interface, response, callbacks)
  File "electrum\lib\network.py", line 560, in process_response
    self.on_notify_header(interface, result)
  File "electrum\lib\network.py", line 989, in on_notify_header
    b = blockchain.check_header(header)
  File "electrum\lib\blockchain.py", line 86, in check_header
    if b.check_header(header):
  File "electrum\lib\blockchain.py", line 130, in check_header
    return header_hash == self.get_hash(height)
  File "electrum\lib\blockchain.py", line 267, in get_hash
    return bitcoin.GENESIS if height == 0 else hash_header(self.read_header(height))
  File "electrum\lib\blockchain.py", line 264, in read_header
    return deserialize_header(h, height)
  File "electrum\lib\blockchain.py", line 49, in deserialize_header
    h['version'] = hex_to_int(s[0:4])
  File "electrum\lib\blockchain.py", line 47, in <lambda>
    hex_to_int = lambda s: int('0x' + s[::-1].encode('hex'), 16)
ValueError: invalid literal for int() with base 16: '0x'


```

**Comment by kyuupichan** [comment]
I had the same earlier; had to blow away the forks directory

**Comment by ecdsa** [comment]
fixed in last commit
