### ISSUE TITLE
Electrum can't open up 

### ISSUE THREAD

**Issue by danpatins** [spesmilo/electrum#2639]
OS am using kali linux.
Am not able to open electrum GUI ,Either from applications or terminal,my OS is upto date. As i was trying a few tweaks, trial & error i opened 'electrum -w update' from terminal which opens electrum well.
From terminal i get this error: 

Traceback (most recent call last):
  File "/usr/bin/electrum", line 323, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 200, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 157, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 220, in load_wallet
    wallet = Wallet(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1757, in __new__
    wallet = WalletClass(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1661, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1409, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 104, in __init__
    self.load_keystore()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1680, in load_keystore
    self.keystores[name] = load_keystore(self.storage, name)
  File "/usr/local/lib/python2.7/dist-packages/electrum/keystore.py", line 610, in load_keystore
    raise BaseException('wallet format requires update')
BaseException: wallet format requires update

Any help i'll  appreciate.

**Comment by SomberNight** [comment]
Have you managed to resolve this?
Seems to me, that the wallet file (storage) format had a related change in 2.7.0. Maybe the upgrade failed for your wallet? You should (have) be(en) able to restore from seed words.

**Comment by danpatins** [comment]
it failed completely,i can't restore from seed coz UI can't load. 
https://imgur.com/a/a0wEu
Am now thinking of installing the OS.

**Comment by bauerj** [comment]
Before doing that you can try to rename your wallet file `~/.electrum/wallets/default_wallet` to e.g. `~/.electrum/wallets/default_wallet.bak`, then start Electrum again.

**Comment by SomberNight** [comment]
Or, start Electrum with the -w flag so it does not try to open that wallet.
e.g. `electrum -w ~/.electrum/wallets/asdasd`

**Comment by SomberNight** [comment]
Also, please update to the latest release, and try with that, if you haven't already.

**Comment by danpatins** [comment]
It worked by renaming to .bak then created standard wallet again. Thanks bauerj & sombernight for your help.

**Comment by calhroub** [comment]
Hi. I am having the same issue but on Mac OS X El Capitan. Currently Even when updating to the  latest Electrum 3.1.3 I keep getting this error:

> Cannot load wallet (1):
> Wallet format requires update.
> Cannot find keystore for name x1/
https://i.imgur.com/DsRyCeg.png

It was working fine until last night when I was trying to import an old Dark Wallet seed and private keys of a multi-sig address created from 3 stealth addresses... Any idea how to fix this, would be appreciated. Thanks.
