### ISSUE TITLE
Ledger Nano S: signing transaction loaded from file does not work

### ISSUE THREAD

**Issue by yura-pakhuchiy** [spesmilo/electrum#2645]
Signing transaction loaded from file does not work. Transaction was created with the same version of electrum (2.9.0) and saved to file without signing. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 351, in sign_transaction
    trustedInput = self.get_client().getTrustedInput(txtmp, utxo[1])
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 188, in get_client
    return self.plugin.get_client(self).dongleObject
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 500, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/usr/local/lib/python2.7/dist-packages/electrum/plugins.py", line 397, in client_for_keystore
    info = self.select_device(plugin, handler, keystore, devices)
  File "/usr/local/lib/python2.7/dist-packages/electrum/plugins.py", line 466, in select_device
    infos = self.unpaired_device_infos(handler, plugin, devices)
  File "/usr/local/lib/python2.7/dist-packages/electrum/plugins.py", line 455, in unpaired_device_infos
    client = self.create_client(device, handler, plugin)
  File "/usr/local/lib/python2.7/dist-packages/electrum/plugins.py", line 338, in create_client
    client = plugin.create_client(device, handler)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 471, in create_client
    client = self.get_btchip_device(device)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 464, in get_btchip_device
    dev.open_path(device.path)
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
IOError: open failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 422, in sign_transaction
    self.give_error(e, True)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 201, in give_error
    raise Exception(message)
Exception: open failed
```

**Comment by yura-pakhuchiy** [comment]
@btchip

**Comment by ecdsa** [comment]
I believe this is because you have an old version of hidapi

**Comment by yura-pakhuchiy** [comment]
@ecdsa with electrum-2.9.2 and hidapi-0.7.99.post20 (the latest version in pip)
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 394, in sign_transaction
    format_satoshis_plain(tx.get_fee()), changePath, bytearray(rawTx.decode('hex')))
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 782, in get_fee
    return self.input_value() - self.output_value()
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 776, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 776, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 422, in sign_transaction
    self.give_error(e, True)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 201, in give_error
    raise Exception(message)
Exception: 'value'
```

**Comment by yura-pakhuchiy** [comment]
@ecdsa btchip-python is also the latest version (0.1.20)

**Comment by ecdsa** [comment]
that error is known and fixed.  (either in 2.9.3 or  in git master)

**Comment by yura-pakhuchiy** [comment]
@ecdsa with electrum 2.9.3
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 394, in sign_transaction
    format_satoshis_plain(tx.get_fee()), changePath, bytearray(rawTx.decode('hex')))
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 782, in get_fee
    return self.input_value() - self.output_value()
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 776, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 776, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 422, in sign_transaction
    self.give_error(e, True)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 201, in give_error
    raise Exception(message)
Exception: 'value'
```

**Comment by ecdsa** [comment]
well, try git master

**Comment by yura-pakhuchiy** [comment]
@ecdsa can not make it run, getting strange error about xmlrpclib, `pip3 search` shows it, but `pip3 install` does not find it
```
ins root@asus-N751JK:~# pip3 install xmlrpclib
Collecting xmlrpclib
  Could not find a version that satisfies the requirement xmlrpclib (from versions: )
No matching distribution found for xmlrpclib
ins root@asus-N751JK:~# pip3 search xmlrpclib
jabberxmlrpclib (0.0.2)  - Library to do XMLRPC over a jabber transport
lxmlrpc_monkey (1.0.0)   - xmlrpclib patch to reduce its memory consumption
pymessagefocus2 (1.0.0)  - Thinner wrapper around xmlrpclib to provide complete API coverage
                           for Adestra MessageFocus
spreadxmlrpclib (0.3.0)  - Library to do XMLRPC over a spread transport
xmlrpclib-to (0.1.1)     - XMLRPC Client with timeout
  INSTALLED: 0.1.1 (latest)
xmlrpcauth (1.1)         - [deprecated] HTTP Basic-Auth transport for xmlrpclib.Server
xmlrpclib (1.0.1)        - Stand-alone distribution of xmlrpclib.
xmlrpclibex (0.1.0)      - A Python xmlrpc client library with proxy and timeout support.
  INSTALLED: 0.1.0 (latest)
ins root@asus-N751JK:~# 
```
```
ins ✗ ~/electrum/electrum-git(master).$ ./electrum --testnet
Traceback (most recent call last):
  File "./electrum", line 70, in check_imports
    import jsonrpclib
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/__init__.py", line 5, in <module>
    from jsonrpclib.jsonrpc import Server, MultiCall, Fault
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 50, in <module>
    from xmlrpclib import Transport as XMLTransport
ImportError: No module named 'xmlrpclib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./electrum", line 86, in <module>
    check_imports()
  File "./electrum", line 72, in check_imports
    sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%e.message)
AttributeError: 'ImportError' object has no attribute 'message'
```

**Comment by ecdsa** [comment]
uninstall jsonrpclib, and install jsonrpclib-pelix
the dependencies are listed in setup.py

**Comment by yura-pakhuchiy** [comment]
@ecdsa electrum-git with btchip-python-git fails to sign transaction even in regular way (without loading frmo file):
```
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 352, in sign_transaction
    trustedInput = self.get_client().getTrustedInput(txtmp, utxo[1])
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchip.py", line 137, in getTrustedInput
    params = bytearray(("%.8x" % (index)).decode('hex'))
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 352, in sign_transaction
    trustedInput = self.get_client().getTrustedInput(txtmp, utxo[1])
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchip.py", line 137, in getTrustedInput
    params = bytearray(("%.8x" % (index)).decode('hex'))
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/gui/qt/util.py", line 588, in run
    result = task.task()
  File "/home/yura/electrum/electrum-git/lib/wallet.py", line 1138, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 423, in sign_transaction
    self.give_error(e, True)
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 202, in give_error
    raise Exception(message)
Exception: 'str' object has no attribute 'decode'
```

Maybe that is because python3 support still wip in btchip-python.

**Comment by btchip** [comment]
Yes you need to install it from git - I'll push the updated package to pip in the coming days

**Comment by yura-pakhuchiy** [comment]
@btchip yes, I did already. 
```
ins root@asus-N751JK:~# pip3 install  git+https://github.com/LedgerHQ/btchip-python.git
Collecting git+https://github.com/LedgerHQ/btchip-python.git
  Cloning https://github.com/LedgerHQ/btchip-python.git to /tmp/pip-kfbs6nya-build
Requirement already satisfied: hidapi>=0.7.99 in /usr/local/lib/python3.5/dist-packages (from btchip-python==0.1.21)
Requirement already satisfied: setuptools>=19.0 in /usr/local/lib/python3.5/dist-packages (from hidapi>=0.7.99->btchip-python==0.1.21)
Installing collected packages: btchip-python
  Running setup.py install for btchip-python ... done
Successfully installed btchip-python-0.1.21
```
Stack trace above is from git version

**Comment by btchip** [comment]
Sorry, just pushed a missing fix. Should be better now

**Comment by yura-pakhuchiy** [comment]
@btchip Still does not work :-(
```
ins ✓ ~/electrum/electrum-git(master).$ ./electrum --testnet
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 392, in sign_transaction
    chipInputs, redeemScripts[inputIndex])
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchip.py", line 225, in startUntrustedTransaction
    sequence = bytearray(passedOutput['sequence'].decode('hex'))
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 392, in sign_transaction
    chipInputs, redeemScripts[inputIndex])
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchip.py", line 225, in startUntrustedTransaction
    sequence = bytearray(passedOutput['sequence'].decode('hex'))
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/gui/qt/util.py", line 588, in run
    result = task.task()
  File "/home/yura/electrum/electrum-git/lib/wallet.py", line 1138, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 423, in sign_transaction
    self.give_error(e, True)
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 202, in give_error
    raise Exception(message)
Exception: 'str' object has no attribute 'decode'
```

**Comment by btchip** [comment]
ok, pushed another change for that

**Comment by yura-pakhuchiy** [comment]
@btchip great, regular signing works now!
@ecdsa signing from file still does not
```
ins ✓ ~/electrum/electrum-git(master).$ ./electrum --testnet
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 395, in sign_transaction
    format_satoshis_plain(tx.get_fee()), changePath, bfh(rawTx))
  File "/home/yura/electrum/electrum-git/lib/transaction.py", line 781, in get_fee
    return self.input_value() - self.output_value()
  File "/home/yura/electrum/electrum-git/lib/transaction.py", line 775, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/home/yura/electrum/electrum-git/lib/transaction.py", line 775, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 395, in sign_transaction
    format_satoshis_plain(tx.get_fee()), changePath, bfh(rawTx))
  File "/home/yura/electrum/electrum-git/lib/transaction.py", line 781, in get_fee
    return self.input_value() - self.output_value()
  File "/home/yura/electrum/electrum-git/lib/transaction.py", line 775, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/home/yura/electrum/electrum-git/lib/transaction.py", line 775, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yura/electrum/electrum-git/gui/qt/util.py", line 588, in run
    result = task.task()
  File "/home/yura/electrum/electrum-git/lib/wallet.py", line 1138, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 423, in sign_transaction
    self.give_error(e, True)
  File "/home/yura/electrum/electrum-git/plugins/ledger/ledger.py", line 202, in give_error
    raise Exception(message)
Exception: 'value'
```

**Comment by btchip** [comment]
Yes, that one is probably caused by a wider problem (the value not being accessible when you sign offline, but being mandatory for Segwit signing).

**Comment by yura-pakhuchiy** [comment]
@btchip I'm not signing offline in this test, it is the same laptop with internet connection, with the same electrum copy, just transaction saved to file and then loaded again. BTW, it is normal wallet, not SegWit, if it matters.

**Comment by ecdsa** [comment]
I can reproduce that issue; sorry I thought it had been fixed previously.
note: the "open failed" exception is caused by missing permissions in udev rules. we should probably handle it better.
