### ISSUE TITLE
Fresh Electrum crashes when starting on Mac

### ISSUE THREAD

**Issue by markus-k** [spesmilo/electrum#2654]
First time running Electrum 2.9.0 (at least I can't remember ever having tried it before) on macOS 10.11.6. I'm using the Application Bundle from https://electrum.org/#download.

When starting Electrum, it just shows a dialog with "Electrum Error" after a few seconds, the following logs are written to the console:

```
29/07/17 21:56:32,915 Electrum[38812]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.6 instead of 10.11.6. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
29/07/17 21:56:32,917 Electrum[38812]: 0   CarbonCore                          0x00007fff8f2df6df ___Gestalt_SystemVersion_block_invoke + 113
29/07/17 21:56:32,917 Electrum[38812]: 1   libdispatch.dylib                   0x00007fff9294b40b _dispatch_client_callout + 8
29/07/17 21:56:32,918 Electrum[38812]: 2   libdispatch.dylib                   0x00007fff9294b303 dispatch_once_f + 67
29/07/17 21:56:32,918 Electrum[38812]: 3   CarbonCore                          0x00007fff8f26bfbc _Gestalt_SystemVersion + 987
29/07/17 21:56:32,918 Electrum[38812]: 4   CarbonCore                          0x00007fff8f26b7d0 Gestalt + 139
29/07/17 21:56:32,918 Electrum[38812]: 5   QtCore                              0x0000000104e94ae4 _ZN19QProcessEnvironment17systemEnvironmentEv + 31524
29/07/17 21:56:32,918 Electrum[38812]: 6   QtCore                              0x0000000104e7a94a _ZN9QSettingsC1ERK7QStringS2_P7QObject + 34
29/07/17 21:56:34,005 Electrum[38812]: Traceback (most recent call last):
29/07/17 21:56:34,005 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/__boot__.py", line 77, in <module>
29/07/17 21:56:34,005 Electrum[38812]:     _run()
29/07/17 21:56:34,005 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/__boot__.py", line 62, in _run
29/07/17 21:56:34,005 Electrum[38812]:     exec(compile(source, path, 'exec'), globals(), globals())
29/07/17 21:56:34,005 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/electrum.py", line 378, in <module>
29/07/17 21:56:34,005 Electrum[38812]:     d.init_gui(config, plugins)
29/07/17 21:56:34,005 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/daemon.py", line 283, in init_gui
29/07/17 21:56:34,007 Electrum[38812]:     self.gui.main()
29/07/17 21:56:34,007 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 215, in main
29/07/17 21:56:34,008 Electrum[38812]:     if not self.start_new_window(path, self.config.get('url')):
29/07/17 21:56:34,009 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 171, in start_new_window
29/07/17 21:56:34,009 Electrum[38812]:     wallet = self.daemon.load_wallet(path, None)
29/07/17 21:56:34,009 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/daemon.py", line 217, in load_wallet
29/07/17 21:56:34,009 Electrum[38812]:     storage.upgrade()
29/07/17 21:56:34,009 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/storage.py", line 251, in upgrade
29/07/17 21:56:34,009 Electrum[38812]:     self.convert_wallet_type()
29/07/17 21:56:34,009 Electrum[38812]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/storage.py", line 321, in convert_wallet_type
29/07/17 21:56:34,010 Electrum[38812]:     for key in xpubs.keys():
29/07/17 21:56:34,010 Electrum[38812]: AttributeError: 'NoneType' object has no attribute 'keys'
29/07/17 21:56:34,023 Electrum[38812]: Electrum Error
29/07/17 21:56:34,024 Electrum[38812]: 2017-07-29 21:56:34.023 Electrum[38812:3032265] Electrum Error
```

**Comment by shsmith** [comment]
Appears you already had an older version wallet. 
Open terminal and 
 ` mv ~/.electrum ~/.electrum.old`
That should allow you to create a new wallet.

**Comment by markus-k** [comment]
That helped. So I had it installed before, but that has to be a long time ago.

**Comment by ecdsa** [comment]
closing, inactive issue.
probable duplicate of #4256
