### ISSUE TITLE
Not enough funds

### ISSUE THREAD

**Issue by n0n0n0n0** [spesmilo/electrum#2656]
When i'm trying to use payto command i got error:
```
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/Electrum-2.9.0-py2.7.egg/electrum/wallet.py", line 818, in make_unsigned_transaction | NotEnoughFunds')
```
```
electrum --testnet getbalance
{
    "confirmed": "1.099934", 
    "unconfirmed": "-0.000025"
}
```
Command:
`electrum --testnet payto msvu37KZJ7aXccUXseBgyChhxJiz835snE 0.00001`

Looked for this line but didnt understand what's wrong and what i should do and why electrum returning "not enought funds" error, how to fix it or it's a bug?
 https://github.com/spesmilo/electrum/blob/ab5a9f3ce461040e52bf3caca376a26f5ff9d0c3/lib/wallet.py#L816

**Comment by n0n0n0n0** [comment]
It started to work after 30 mins, how to avoid this error in future?

**Comment by n0n0n0n0** [comment]
Also sometimes face with this error in another file:
```
root@mixer:/home/vagrant# electrum --testnet payto msvu37KZJ7aXccUXseBgyChhxJiz835snE 0.000$(( $RANDOM/256|bc ))
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 4, in <module>
    __import__('pkg_resources').run_script('Electrum==2.9.0', 'electrum')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.9.0-py2.7.egg/EGG-INFO/scripts/electrum", line 419, in <module>
    result = server.run_cmdline(config_options)
  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 288, in __call__
  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 238, in _request
  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/Electrum-2.9.0-py2.7.egg/electrum/coinchooser.py", line 235, in choose_buckets | NotEnoughFunds')
root@mixer:/home/vagrant# electrum --testnet payto msvu37KZJ7aXccUXseBgyChhxJiz835snE 0.000$(( $RANDOM/256|bc ))
{
    "complete": true, 
    "final": true, 
    "hex": "0100000002edc38230b083338fd059d1a4171993ec258732df2f33558de384bb5d6eb10a34000000006b483045022100ab21bf69e1aa19228e772bcd486ad4f995f39f4f44eab815cbe144bb19988a3d0220220f57aad92c7759e9851cb89a13998d9e3041f082bd9cd8ddadf1a203764b7501210242497e244f09d093dc9afd135b91811536f0ece70a11b5d43919b9c100958df1feffffff65043697a7aa38b69ec3b50c7252e3834d6cb465c62b015d09d51d0cb0535fd2000000006a47304402200c1ece368749a6aeefd0b969916f257e4cd16973140bfe071d1057dd0623ac7302206fe57846934dce4affcb40bafe177b421dbf3956fccb9e1d8e8d3a46fda98d6d01210267e47b3519ea0a46744b188ab823a62f92cabc6ad4e7d75e1ad6edb1340222effeffffff02b2200000000000001976a9144df38fd404cf136719f1af7ae2cada2c0147ec9388ac302a0000000000001976a9142626f3c4f02ea5a71afc3d235c507eef8bb0364a88ac00000000"
}
```

**Comment by dabura667** [comment]
Before running these commands are you running daemon start and loadwallet?

That error you linked only shows when there are no inputs given, so maybe you aren't loading the wallet properly.

**Comment by n0n0n0n0** [comment]
Yes daemon is running and wallet is loaded, as you can see above it correcly shows confirmed funds.

**Comment by ecdsa** [comment]
there is a new preference that prevents from spending unconfirmed coins

**Comment by n0n0n0n0** [comment]
Uhm okay. So it seems getbalance sometimes returning wrong data?
```
electrum --testnet getbalance
{
    "confirmed": "1.099934", 
    "unconfirmed": "-0.000025"
}
```
```
electrum --testnet getaddressbalance muEETg2kS2aNiZhSqadKcJt9Fv4L3D66tL
{
    "confirmed": "0.496938", 
    "unconfirmed": "-0.496938"
}

```
How is it possible?

**Comment by n0n0n0n0** [comment]
understood sry

**Comment by fresheneesz** [comment]
@ecdsa I got this problem too. Can you please add some information about the preference into the warning message when you're trying to send? Also, the note at the bottom saying "Not enough funds" should also be clearer, saying "not enough confirmed funds".

ALSO, if I don't have enough funds because an unconfirmed transaction used my entire balance (with most of it coming back to me as change), it should still allow me to send money, right? Can you please reopen this ticket?

**Comment by ecdsa** [comment]
I changed the default value of that setting
08fab753e88f1b24a8e76f9262eb64b38ffc2572

**Comment by ricardo85x** [comment]
I have the same error today. But with new confirmed funds.
The workaround is click on Max, after that you can edit the value
