### ISSUE TITLE
-g text doesnt work

### ISSUE THREAD

**Issue by buzztiaan** [spesmilo/electrum#2661]
Starting electrum with -g text results in a crash ; 

```
buzz@electrum:~$ electrum -g text
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 377, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 282, in init_gui
    self.gui = gui.ElectrumGui(config, self, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 27, in __init__
    self.wallet = Wallet(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1783, in __new__
    WalletClass = Wallet.wallet_class(wallet_type)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1797, in wallet_class
    if multisig_type(wallet_type):
  File "/usr/local/lib/python2.7/dist-packages/electrum/storage.py", line 58, in multisig_type
    match = re.match('(\d+)of(\d+)', wallet_type)
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

Either fix, or just remove the functionality if you dont care about it :)
(and also remove the ncurses screenshots from electrum.org in the second case)

**Comment by buzztiaan** [comment]
or, maybe someone knows what the last version of electrum was that had functional ncurses output? it greatly increases accessibility for those unable to do graphical guis

**Comment by dromer** [comment]
You have to create a wallet first.

Seems the text gui cannot do this off the bat, would be a nice feature indeed.

**Comment by buzztiaan** [comment]
without a .electrum directory there's a different error : 

buzz@electrum:~$ electrum -g text
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 377, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 282, in init_gui
    self.gui = gui.ElectrumGui(config, self, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 27, in __init__
    self.wallet = Wallet(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1783, in __new__
    WalletClass = Wallet.wallet_class(wallet_type)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1797, in wallet_class
    if multisig_type(wallet_type):
  File "/usr/local/lib/python2.7/dist-packages/electrum/storage.py", line 58, in multisig_type
    match = re.match('(\d+)of(\d+)', wallet_type)
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
Exception in thread Thread-10 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 208, in run
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 129, in get_socket
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'SSLError'
Exception in thread Thread-12 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 958, in download_thread
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
  File "/usr/lib/python2.7/urllib.py", line 216, in open
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 208, in run
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 123, in get_socket
  File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 107, in get_simple_socket
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'socket'

**Comment by dromer** [comment]
Make sure you generate the wallet with the same client, try with x-forwarding if you're working on a remote machine.

Also, the curses gui tends to crash if the terminal is too small.

I found a bunch of other annoying behaviors/bugs that should be looked at. Would be great to have a fully usable terminal client.

**Comment by buzztiaan** [comment]
this was the magic tip! with a premade wallet (from gui) -g text starts
and having terminal big enough (somewhat of an issue) it doesnt even crash on the 'receive' tab \o

maybe we could cooperate in making the ncurses stuff better? :)

**Comment by ecdsa** [comment]
feel free to adopt/update that gui

**Comment by buzztiaan** [comment]
i was trying to adopt it , but atm its pretty nonfunctional or at least very difficult :)
