### ISSUE TITLE
Python console not working on 2.9.0 ( Windows )

### ISSUE THREAD

**Issue by sleepndevelop** [spesmilo/electrum#2684]
When i launch help() in the Console, i get:
>> help()
Traceback (most recent call last):
  File "C:\Users\DEVELO~1\AppData\Local\Temp\_MEI73482\gui\qt\main_window.py", line 1711, in <lambda>
    return lambda *args: apply( f, (method, args, self.password_dialog ))
  File "C:\Users\DEVELO~1\AppData\Local\Temp\_MEI73482\lib\commands.py", line 104, in _run
    result = f(*args, **{'password':password})
UnboundLocalError: local variable 'password' referenced before assignment
>>

**Comment by sleepndevelop** [comment]
Tried also getbalance

`>> 
Welcome to Anduck.net Electrum!
>> getbalance()
Traceback (most recent call last):
  File "C:\Users\DEVELO~1\AppData\Local\Temp\_MEI73482\gui\qt\main_window.py", line 1711, in <lambda>
    return lambda *args: apply( f, (method, args, self.password_dialog ))
  File "C:\Users\DEVELO~1\AppData\Local\Temp\_MEI73482\lib\commands.py", line 104, in _run
    result = f(*args, **{'password':password})
UnboundLocalError: local variable 'password' referenced before assignment
>> help()
Traceback (most recent call last):
  File "C:\Users\DEVELO~1\AppData\Local\Temp\_MEI73482\gui\qt\main_window.py", line 1711, in <lambda>
    return lambda *args: apply( f, (method, args, self.password_dialog ))
  File "C:\Users\DEVELO~1\AppData\Local\Temp\_MEI73482\lib\commands.py", line 104, in _run
    result = f(*args, **{'password':password})
UnboundLocalError: local variable 'password' referenced before assignment`

**Comment by bauerj** [comment]
This will be fixed by #2683.
