### ISSUE TITLE
BaseException: wallet format requires update

### ISSUE THREAD

**Issue by mbuchove** [spesmilo/electrum#2700]
This is similar to issue #2257, but is occurring in version 2.8.3 and 2.8.2 
This wallet was created with a previous version of electrum, and it causes a crash of the application after entering my password correctly. I've tried this on Mac, Linux, and Windows machines

Traceback (most recent call last):
  File "./Electrum-2.8.3/electrum", line 379, in <module>
    d.init_gui(config, plugins)
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/home/mbuchove/Downloads/Electrum-2.8.3/gui/qt/__init__.py", line 200, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/mbuchove/Downloads/Electrum-2.8.3/gui/qt/__init__.py", line 161, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/mbuchove/Downloads/Electrum-2.8.3/gui/qt/installwizard.py", line 262, in run_and_get_wallet
    self.wallet = Wallet(self.storage)
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/wallet.py", line 1757, in __new__
    wallet = WalletClass(storage)
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/wallet.py", line 1661, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/wallet.py", line 1409, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/wallet.py", line 104, in __init__
    self.load_keystore()
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/wallet.py", line 1680, in load_keystore
    self.keystores[name] = load_keystore(self.storage, name)
  File "/home/mbuchove/Downloads/Electrum-2.8.3/lib/keystore.py", line 610, in load_keystore
    raise BaseException('wallet format requires update')
BaseException: wallet format requires update

**Comment by mbuchove** [comment]
This also occurs in versio 2.9.2

**Comment by ecdsa** [comment]
can you email me the wallet? (assuming it has a strong password or no coins)

**Comment by mbuchove** [comment]
Sure, it's password-protected. Thanks for your help!

**Comment by ecdsa** [comment]
closing, no email received.

**Comment by mbuchove** [comment]
Sorry I responded to the github thread, I just sent directly to your email

**Comment by ecdsa** [comment]
the users's wallet is encrypted. this error message should not happen, reopening

**Comment by ecdsa** [comment]
@mbuchove how did you create this wallet? please provide as much detail as possible

**Comment by ecdsa** [comment]
what does " encrypted it with a password on the prompt." mean?

**Comment by mbuchove** [comment]
When creating a wallet with Electrum, it explicitly asks you would you like to

**Comment by ecdsa** [comment]
do you still have the seed for your wallet?

**Comment by mbuchove** [comment]
i don't believe so, but i will look

**Comment by ecdsa** [comment]
closing, no answer
