### ISSUE TITLE
trezor: unable to initialize

### ISSUE THREAD

**Issue by fireduck64** [spesmilo/electrum#2733]
When telling electrum to have a trezor generate a new seed:

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/google/home/jgleason/t/electrum.git/plugins/trezor/plugin.py", line 197, in _initialize_device
    pin_protection, label, language)
  File "/usr/local/google/home/jgleason/t/electrum.git/plugins/trezor/clientbase.py", line 221, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
TypeError: reset_device() takes exactly 9 arguments (7 given)

electrum from github as of today (2017.08.11) and 
trezor                    - Python library for communicating with TREZOR Hardware Wallet
  INSTALLED: 0.7.16 (latest)

**Comment by ecdsa** [comment]
looks like they added new parameters
fixed in 6cf10e54d0b34224c1a5c189ddc04981c2c334f3
