### ISSUE TITLE
Unicode issues (non-ASCII $HOME dir)

### ISSUE THREAD

**Issue by davispuh** [spesmilo/electrum#2784]
I'm using latest Git version on ArchLinux with Python 2.7.13 and I've non-ASCII `$HOME` dir (eg. `/home/dāvis/`), using `LANG=lv_LV.UTF-8`

```
Traceback (most recent call last):
  File "/usr/bin/electrum", line 377, in <module>
    d.init_gui(config, plugins)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 215, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 181, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 156, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 193, in __init__
    self.load_wallet(wallet)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 322, in load_wallet
    self.update_recently_visited(wallet.storage.path)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 404, in update_recently_visited
    filename = filename.decode('utf8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 7: ordinal not in range(128)
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 1272, in request_password
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 2118, in export_privkeys_dialog
    hbox, filename_e, csv_button = filename_field(self, self.config, defaultname, select_msg)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/util.py", line 338, in filename_field
    directory = config.get('io_dir', unicode(os.path.expanduser('~')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 7: ordinal not in range(128)
```

**Comment by davispuh** [comment]
Also
```
/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py:167: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if w.wallet.storage.path == path:
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 2205, in do_export_labels
    self.show_message(_("Your labels were exported to") + " '%s'" % str(fileName))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 7: ordinal not in range(128)
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 2228, in export_history_dialog
    self.do_export_history(self.wallet, filename, csv_button.isChecked())
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 2273, in do_export_history
    with open(fileName, "w+") as f:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 7: ordinal not in range(128)
```

This seems to fix these all (basically use Unicode type internally)

```diff
diff --git a/gui/qt/main_window.py b/gui/qt/main_window.py
index 2a2fa9c8..fc3f90eb 100644
--- a/gui/qt/main_window.py
+++ b/gui/qt/main_window.py
@@ -25,6 +25,7 @@

 import sys, time, threading
 import os, json, traceback
+import locale
 import shutil
 import socket
 import weakref
@@ -401,7 +402,6 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
                 self.show_critical(_("Electrum was unable to copy your wallet file to the specified location.") + "\n" + str(reason), title=_("Unable to create backup"))
 
     def update_recently_visited(self, filename):
-        filename = filename.decode('utf8')
         recent = self.config.get('recently_open', [])
         try:
             sorted(recent)
@@ -416,7 +416,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
         for i, k in enumerate(sorted(recent)):
             b = os.path.basename(k)
             def loader(k):
-                return lambda: self.gui_object.new_window(k.encode('utf8'))
+                return lambda: self.gui_object.new_window(k)
             self.recently_visited_menu.addAction(b, loader(k)).setShortcut(QKeySequence("Ctrl+%d"%(i+1)))
         self.recently_visited_menu.setEnabled(len(recent))
 
@@ -573,14 +573,14 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
 
     # custom wrappers for getOpenFileName and getSaveFileName, that remember the path selected by the user
     def getOpenFileName(self, title, filter = ""):
-        directory = self.config.get('io_dir', unicode(os.path.expanduser('~')))
+        directory = self.config.get('io_dir', os.path.expanduser('~').decode(locale.getpreferredencoding()))
         fileName = unicode( QFileDialog.getOpenFileName(self, title, directory, filter) )
         if fileName and directory != os.path.dirname(fileName):
             self.config.set_key('io_dir', os.path.dirname(fileName), True)
         return fileName
 
     def getSaveFileName(self, title, filename, filter = ""):
-        directory = self.config.get('io_dir', unicode(os.path.expanduser('~')))
+        directory = self.config.get('io_dir', os.path.expanduser('~').decode(locale.getpreferredencoding()))
         path = os.path.join( directory, filename )
         fileName = unicode( QFileDialog.getSaveFileName(self, title, path, filter) )
         if fileName and directory != os.path.dirname(fileName):
@@ -2151,6 +2151,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
         if not filename:
             return
 
+        filename = unicode(filename.toUtf8(), 'utf8')
         try:
             self.do_export_privkeys(filename, private_keys, csv_button.isChecked())
         except (IOError, os.error) as reason:
@@ -2201,7 +2202,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
             if fileName:
                 with open(fileName, 'w+') as f:
                     json.dump(labels, f, indent=4, sort_keys=True)
-                self.show_message(_("Your labels were exported to") + " '%s'" % str(fileName))
+                self.show_message(_("Your labels were exported to") + " '%s'" % fileName)
         except (IOError, os.error), reason:
             self.show_critical(_("Electrum was unable to export your labels.") + "\n" + str(reason))
@@ -2210,7 +2211,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
         d = WindowModalDialog(self, _('Export History'))
         d.setMinimumSize(400, 200)
         vbox = QVBoxLayout(d)
-        defaultname = os.path.expanduser('~/electrum-history.csv')
+        defaultname = os.path.expanduser('~/electrum-history.csv').decode(locale.getpreferredencoding())
         select_msg = _('Select file to export your wallet transactions to')
         hbox, filename_e, csv_button = filename_field(self, self.config, defaultname, select_msg)
         vbox.addLayout(hbox)
@@ -2224,6 +2225,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
         filename = filename_e.text()
         if not filename:
             return
+        filename = unicode(filename.toUtf8(), 'utf8')
         try:
             self.do_export_history(self.wallet, filename, csv_button.isChecked())
         except (IOError, os.error), reason:
diff --git a/gui/qt/util.py b/gui/qt/util.py
index 1a2b8f49..b8ecb1d5 100644
--- a/gui/qt/util.py
+++ b/gui/qt/util.py
@@ -1,4 +1,5 @@
 import os.path
+import locale
 import time
 import traceback
 import sys
@@ -335,7 +336,7 @@ def filename_field(parent, config, defaultname, select_msg):
 
     hbox = QHBoxLayout()
 
-    directory = config.get('io_dir', unicode(os.path.expanduser('~')))
+    directory = config.get('io_dir', os.path.expanduser('~').decode(locale.getpreferredencoding()))
     path = os.path.join( directory, defaultname )
     filename_e = QLineEdit()
     filename_e.setText(path)
```

**Comment by ecdsa** [comment]
thanks for the fix.
there's a pyhon3_new branch that is going to be merged soon.
since unicode is handled differently there, could you test if that branch has the same issue?

**Comment by davispuh** [comment]
FYI: even in that branch `contrib/make_locale` is python2 only

But it doesn't have these issues, only found one different, when trying to export private key it says
`'dict_keys' object does not support indexing`

**Comment by ecdsa** [comment]
thanks for testing. python3 will be merged soon
