### ISSUE TITLE
Cannot sign messages with this type of address.

### ISSUE THREAD

**Issue by mc388** [spesmilo/electrum#2800]
Hi,

I want to sign message, but I always get this error:

```
Cannot sign messages with this type of address.

Signing with an address actually means signing with the corresponding private key, and verifying with the corresponding public key. The address you have entered does not have a unique public key, so these operations cannot be performed.
```

I also tried this with the console

```
>> signmessage("3NfP....", "Hello World")
Traceback (most recent call last):
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 105, in _run
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 83, in func_wrapper
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 399, in signmessage
AttributeError: 'Wallet_2fa' object has no attribute 'sign_message'
```

I need this for stellar lumens.

**Comment by dabura667** [comment]
Sorry. Not possible.

**Comment by ecdsa** [comment]
you can shoy that you own a p2sh address, but that does not work like that.
they probably have a proof of ownership that involves you publishing the redeem script of the address

**Comment by yameyamo** [comment]
I have the same problem, what is the solution?
