### ISSUE TITLE
Doesn' launch when default wallet cointains unicode chars

### ISSUE THREAD

**Issue by stallmantington** [spesmilo/electrum#2823]
config file contains this entry:
"gui_last_wallet": "/home/xxx/.electrum/wallets/M\u00f6bious wallet", 

when I run electrum I get this:
$ electrum 
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 377, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 215, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 181, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 156, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 189, in __init__
    self.load_wallet(wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 318, in load_wallet
    self.update_recently_visited(wallet.storage.path)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 400, in update_recently_visited
    filename = filename.decode('utf8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 30: ordinal not in range(128)

If I change wallet to another one it runs fine.

**Comment by ecdsa** [comment]
this is fixed in master, wait for 3.0 release
