### ISSUE TITLE
Electrum fails to start on Ubuntu 17.04

### ISSUE THREAD

**Issue by achow101** [spesmilo/electrum#2825]
I am having some problems with starting Electrum from source on Ubuntu 17.04 with Python 3.5.3. It keeps failing with this error:

```
Traceback (most recent call last):
  File "./electrum", line 70, in check_imports
    import jsonrpclib
  File "/home/andy/bitcoin/electrum/packages/jsonrpclib/__init__.py", line 5, in <module>
    from jsonrpclib.jsonrpc import Server, MultiCall, Fault
  File "/home/andy/bitcoin/electrum/packages/jsonrpclib/jsonrpc.py", line 50, in <module>
    from xmlrpclib import Transport as XMLTransport
ImportError: No module named 'xmlrpclib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./electrum", line 86, in <module>
    check_imports()
  File "./electrum", line 72, in check_imports
    sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%e.message)
AttributeError: 'ImportError' object has no attribute 'message'
```

**Comment by ecdsa** [comment]
run setup

**Comment by SomberNight** [comment]
If you are working in an older electrum directory which you used before the python3 migration, delete the `packages` folder. You might have the python2 version of jsonrpclib in there.

If after this the trace changes from 
'''
*/electrum/packages/jsonrpclib/*
'''
to e.g.
```
/usr/local/lib/python3.5/dist-packages/jsonrpclib/*
```
Then try
```
sudo pip3 uninstall jsonrpclib
sudo pip3 install jsonrpc
```

**Comment by achow101** [comment]
@ecdsa I did that many times. It didn't help

@SomberNight That worked. Thanks!
