### ISSUE TITLE
Electrum crashes on launch (Ubuntu 16.04)

### ISSUE THREAD

**Issue by nathanwallh** [spesmilo/electrum#2826]
After entering the password, the software crashes immediately. Was probably triggered when I played with the settings of the fees.

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 377, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 215, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 181, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 156, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 124, in __init__
    self.send_tab = self.create_send_tab()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 1053, in create_send_tab
    self.fee_slider = FeeSlider(self, self.config, fee_cb)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/fee_slider.py", line 19, in __init__
    self.update()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/fee_slider.py", line 53, in update
    pos = min(fee_rate / self.fee_step, 10)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by ecdsa** [comment]
upgrade
