### ISSUE TITLE
Electrum Daemon constantly crashing

### ISSUE THREAD

**Issue by ShockwaveHF** [spesmilo/electrum#2842]
Hi,

I am currently using "getaddressbalance", "getunusedaddress" and "payto" to create an automated payment system with json rpc, it works great, although after 1- 2 successful payments the daemon starts looping this error 

`Exception happened during processing of request from ('127.0.0.1', 51683)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 185, in do_POST
    self.connection.shutdown(1)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
----------------------------------------
`

Until it crashes, which then I have to restart the daemon.

What seems to be the issue?

Thanks.

**Comment by ecdsa** [comment]
no idea. I suggest you try with git master, because it uses python3

**Comment by ShockwaveHF** [comment]
Thanks for the response. I've updated to the master version & I'll let you know how it goes. (just for the record I was previously using the version from https://electrum.org/ (2.9.3)

Just a small question, I am generating a new address per transaction using "self.wallet.create_new_address(False)", and am going way above the gap limit, and forwarding payments to a main address, will this be okay in the long run?

Thanks.

**Comment by ShockwaveHF** [comment]
Seems to have fixed the issue, thanks for the help.

**Comment by ShockwaveHF** [comment]
Apologies, it seems as if, this in fact didn't fix it, it crashed after about 2 days of running perfectly, nothing seemed different before the crash, is there a log file I can check? Thanks.
