### ISSUE TITLE
ImportError: No module named 'xmlrpclib'

### ISSUE THREAD

**Issue by htgoebel** [spesmilo/electrum#2844]
I installed Electrum using
```
$ pip3 install --user https://github.com/spesmilo/electrum/archive/2.9.3.tar.gz
…
Successfully installed Electrum-2.9.3 PySocks-1.6.7 dnspython-1.15.0 ecdsa-0.13 jsonrpclib-0.1.7
pbkdf2-1.3 protobuf-3.4.0 pyaes-1.6.0 qrcode-5.3
```
Now when I start electrum, I get an ImportError: No module named 'xmlrpclib':
```
$ electrum 
Traceback (most recent call last):
  File "/home/hartmut/.local/bin/electrum", line 71, in check_imports
    import jsonrpclib
  File "/…/.local/lib/python3.5/site-packages/jsonrpclib/__init__.py", line 5, in <module>
    from jsonrpclib.jsonrpc import Server, MultiCall, Fault
  File "/…/.local/lib/python3.5/site-packages/jsonrpclib/jsonrpc.py", line 50, in <module>
    from xmlrpclib import Transport as XMLTransport
ImportError: No module named 'xmlrpclib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/…/.local/bin/electrum", line 90, in <module>
    check_imports()
  File "/…/.local/bin/electrum", line 73, in check_imports
    sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%e.message)
AttributeError: 'ImportError' object has no attribute 'message'
```
Python 3.5.3

Alternatively I tried with Python 2.7, but this failed to find `ecdsa`.

**Comment by htgoebel** [comment]
Closing:
- 2.9.3 is not for Python3
- For python 2.7, ecdsa was wrongly installed on my system.

**Comment by ecdsa** [comment]
use git master if you want to use electrum with python3

**Comment by JikkuJose** [comment]
Am still having this issue, I installed via `brew`

**Comment by bitTHINK** [comment]
I too am having this issue. I cannot install electrum-cash because of this. 

anyone have work-around?

**Comment by sh4dowb** [comment]
the following fixed it for me:
```
pip3 uninstall jsonrpclib
pip3 install jsonrpclib-pelix
```

jsonrpclib is for python2.
