### ISSUE TITLE
Electrum fails to complete synchronization.

### ISSUE THREAD

**Issue by na1Quoh7ie** [spesmilo/electrum#2856]
My last transaction is "Not Verified", in amount column there is just: +0,
During the synchronization (never-ending) this message appears in console:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/electrum/network.py", line 819, in run
    self.wait_on_sockets()
  File "/usr/lib/python2.7/dist-packages/electrum/network.py", line 813, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/lib/python2.7/dist-packages/electrum/network.py", line 603, in process_responses
    self.process_response(interface, response, callbacks)
  File "/usr/lib/python2.7/dist-packages/electrum/network.py", line 555, in process_response
    callback(response)
  File "/usr/lib/python2.7/dist-packages/electrum/synchronizer.py", line 139, in tx_response
    assert tx_hash == hash_encode(Hash(result.decode('hex')))
AssertionError

I use electrum 2.7.9-1 on debian stable.
Transaction appears in blockchain.info with 197 Confirmations 24 hours after.
I have reinstalled electrum, restaured wallet just before this transaction (synchronization works
until this transaction), recreated wallet with the seed in new virgin session, tried many servers, rebooted electrum many times... Nothing works.
(Note: I reused an old receiving adress.)

Thank you.
na1Quoh7ie

**Comment by RusAlex** [comment]
had similar issue. This happens when you have segwit transaction. 2.7.x does not support it. Please update your electrum

**Comment by na1Quoh7ie** [comment]
Actually it works fine with  Electrum 2.9.3.
Thank you.
