### ISSUE TITLE
GUI can't show details for old P2PK coinbase transaction

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2858]
On git master (afa1a4d22a31d23d088c6670e1588eed32f7114d).

**Steps to reproduce**:

- Create a watching-only wallet for the address `1F85WoacT1mDtXZCahNfFMnVLJfyufXLNn`.
- In QT GUI, in the `History` tab, there is a coinbase transaction paying to a P2PK output.
- Right-click the tx, and choose `Details`
- The operation silently fails, and the following trace is printed in terminal:

```
user@debian:~/wspace/electrum$ ./electrum 
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/history_list.py", line 173, in <lambda>
    menu.addAction(_("Details"), lambda: self.parent.show_transaction(tx))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 737, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 51, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 134, in __init__
    self.update()
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 186, in update
    tx_hash, status, label, can_broadcast, can_rbf, amount, fee, height, conf, timestamp, exp_n = self.wallet.get_tx_info(self.tx)
  File "/home/user/wspace/electrum/lib/wallet.py", line 440, in get_tx_info
    tx_hash = tx.txid()
  File "/home/user/wspace/electrum/lib/transaction.py", line 752, in txid
    ser = self.serialize(witness=False)
  File "/home/user/wspace/electrum/lib/transaction.py", line 735, in serialize
    txouts = var_int(len(outputs)) + ''.join(self.serialize_output(o) for o in outputs)
  File "/home/user/wspace/electrum/lib/transaction.py", line 735, in <genexpr>
    txouts = var_int(len(outputs)) + ''.join(self.serialize_output(o) for o in outputs)
  File "/home/user/wspace/electrum/lib/transaction.py", line 697, in serialize_output
    script = self.pay_script(output_type, addr)
  File "/home/user/wspace/electrum/lib/transaction.py", line 595, in pay_script
    raise TypeError('Unknown output type')
TypeError: Unknown output type
```

**Comment by SomberNight** [comment]
On git master (f0fe84d959d16c090cfd793efebf6af7d2d06a04), the problem is again present, though due to a new cause (introduced by d9f2edf6b0c8d8e1b5219bfa5cfeac903b6a2561).

New trace:
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/history_list.py", line 173, in <lambda>
    menu.addAction(_("Details"), lambda: self.parent.show_transaction(tx))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 737, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 51, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 134, in __init__
    self.update()
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 186, in update
    tx_hash, status, label, can_broadcast, can_rbf, amount, fee, height, conf, timestamp, exp_n = self.wallet.get_tx_info(self.tx)
  File "/home/user/wspace/electrum/lib/wallet.py", line 440, in get_tx_info
    tx_hash = tx.txid()
  File "/home/user/wspace/electrum/lib/transaction.py", line 801, in txid
    ser = self.serialize(witness=False)
  File "/home/user/wspace/electrum/lib/transaction.py", line 783, in serialize
    txins = var_int(len(inputs)) + ''.join(self.serialize_input(txin, self.input_script(txin, estimate_size)) for txin in inputs)
  File "/home/user/wspace/electrum/lib/transaction.py", line 783, in <genexpr>
    txins = var_int(len(inputs)) + ''.join(self.serialize_input(txin, self.input_script(txin, estimate_size)) for txin in inputs)
  File "/home/user/wspace/electrum/lib/transaction.py", line 673, in input_script
    return txin['scriptSig']
KeyError: 'scriptSig'
```
