### ISSUE TITLE
AttributeError: 'Old_KeyStore' object has no attribute 'xpub'

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2912]
I have a 2013 vintage watch-only wallet that will no longer open in git HEAD version.
I get a popup with the message 
```
Cannot load wallet:
  AttributeError: 'Old_KeyStore' object has no attribute 'xpub'
```

I tried to restore the wallet from MPK and the UI hung on "Please wait...".
I see this traceback in the verbose console: 
```
Traceback (most recent call last):
  File "electrum\gui\qt\main_window.py", line 436, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "electrum\gui\qt\__init__.py", line 183, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "electrum\gui\qt\installwizard.py", line 274, in run_and_get_wallet
    self.run(action)
  File "electrum\lib\base_wizard.py", line 61, in run
    f(*args)
  File "electrum\lib\base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "electrum\gui\qt\installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "electrum\lib\base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "electrum\lib\base_wizard.py", line 61, in run
    f(*args)
  File "electrum\lib\base_wizard.py", line 138, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "electrum\gui\qt\installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "electrum\lib\base_wizard.py", line 61, in run
    f(*args)
  File "electrum\lib\base_wizard.py", line 161, in restore_from_key
    self.add_xpub_dialog(title=title, message=message, run_next=self.on_restore_from_key, is_valid=v)
  File "electrum\gui\qt\installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "electrum\lib\base_wizard.py", line 168, in on_restore_from_key
    self.on_keystore(k)
  File "electrum\lib\base_wizard.py", line 308, in on_keystore
    self.run('create_wallet')
  File "electrum\lib\base_wizard.py", line 61, in run
    f(*args)
  File "electrum\lib\base_wizard.py", line 336, in create_wallet
    self.on_password(None, False)
  File "electrum\lib\base_wizard.py", line 347, in on_password
    self.wallet = Standard_Wallet(self.storage)
  File "electrum\lib\wallet.py", line 1586, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "electrum\lib\wallet.py", line 1425, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "electrum\lib\wallet.py", line 102, in __init__
    self.load_keystore()
  File "electrum\lib\wallet.py", line 1547, in load_keystore
    xtype = deserialize_xpub(self.keystore.xpub)[0]
AttributeError: 'Old_KeyStore' object has no attribute 'xpub'

```

**Comment by ecdsa** [comment]
I am working on that

**Comment by SomberNight** [comment]
Note that, while conceptually possibly distinct, this is the same trace as in #2873

**Comment by ecdsa** [comment]
use that as a temporary workaround
```
-        xtype = deserialize_xpub(self.keystore.xpub)[0]
+        try:
+            xtype = deserialize_xpub(self.keystore.xpub)[0]
+        except:
+            xtype = 'standard'

```

**Comment by shsmith** [comment]
I applied your patch in the two places where 'xtype = deserialize_xpub(self.keystore.xpub)[0]' exists. 
That allows the wallet to open. 
Thanks!
