### ISSUE TITLE
Issue with imported private keys with master (NotImplementedError: standard)

### ISSUE THREAD

**Issue by cynecx** [spesmilo/electrum#2915]
Traceback (most recent call last):
    File "/Users/xx/dev/electrum/lib/util.py", line 135, in run_jobs
        job.run()
    File "/Users/xx/dev/electrum/lib/synchronizer.py", line 189, in run
        self.wallet.synchronize()
    File "/Users/xx/dev/electrum/lib/wallet.py", line 1516, in synchronize
        self.receiving_addresses = [self.pubkeys_to_address(i) for i in pubkeys]
    File "/Users/xx/dev/electrum/lib/wallet.py", line 1516, in <listcomp>
        self.receiving_addresses = [self.pubkeys_to_address(i) for i in pubkeys]
    File "/Users/xx/dev/electrum/lib/wallet.py", line 1650, in pubkeys_to_address
        raise NotImplementedError(self.txin_type)
    NotImplementedError: standard

I am currently using a build from master which doesn't work with imported private keys which results in the above error.

**Comment by cynecx** [comment]
I fixed this by temporarily expanding this condition:

`
def pubkeys_to_address(self, pubkey):
        if self.txin_type == 'p2pkh' or self.txin_type == 'standard':
...
`

**Comment by cynecx** [comment]
A better temporary fix:

```
class Standard_Wallet(Simple_Deterministic_Wallet):
    wallet_type = 'standard'

+    def __init__(self, storage):
+        Simple_Deterministic_Wallet.__init__(self, storage)
+        if self.txin_type == 'standard':
+            self.txin_type = 'p2pkh'
```
