### ISSUE TITLE
2FA wallets can't be created

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2921]
On git master e99c2e8dfdad64ee8af7e798ff75195e0aba714c.

2FA wallets can't be created currently. After the wizard presents you with a seed, and you retype it to confirm, the GUI hangs.

```
[Plugins] loaded trustedcoin
language english
wordlist has 2048 words
make_seed 101 adding 132 bits
12 words
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 436, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 183, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 274, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 381, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 386, in create_seed
    wizard.show_seed_dialog(run_next=f, seed_text=seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 385, in <lambda>
    f = lambda x: wizard.request_passphrase(seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 393, in request_passphrase
    self.run('confirm_seed', seed, '')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 397, in confirm_seed
    self.confirm_seed_dialog(run_next=f, test=lambda x: x==seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 396, in <lambda>
    f = lambda x: self.confirm_passphrase(seed, passphrase)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 409, in confirm_passphrase
    f('')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 400, in <lambda>
    f = lambda x: self.run('create_keystore', seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 405, in create_keystore
    xprv1, xpub1, xprv2, xpub2 = self.xkeys_from_seed(seed, passphrase)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 397, in xkeys_from_seed
    xprv1, xpub1 = keystore.xkeys_from_seed(seed, passphrase, "m/0'/")
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 979, in xkeys_from_seed
    xprv, xpub = bip32_root(Mnemonic.mnemonic_to_seed(seed, passphrase), 0)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 910, in bip32_root
    xprv = serialize_xprv(xtype, master_c, master_k)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 845, in serialize_xprv
    xprv = xprv_header(xtype) + bytes([depth]) + fingerprint + child_number + c + bytes([0]) + k
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 837, in xprv_header
    return bfh("%08x" % XPRV_HEADERS[xtype])
KeyError: 0
```

**Comment by SomberNight** [comment]
Note: restoring 2FA wallets does not work either, it fails with a similar trace.
