### ISSUE TITLE
Making Multi-signature wallet results in error.

### ISSUE THREAD

**Issue by wakiyamap** [spesmilo/electrum#2932]
On git master https://github.com/spesmilo/electrum/commit/dcd50c3467d9de778de9d0e4db3836ec84c6d1cc .

Making Multi-signature wallet results in error.
"kind of wallet" select "Multi-signature wallet"
"Choose Seed type" select "Standard"

Traceback (most recent call last):
  File "/home/wakiyamap/electrum/lib/util.py", line 135, in run_jobs
    job.run()
  File "/home/wakiyamap/electrum/lib/synchronizer.py", line 189, in run
    self.wallet.synchronize()
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1511, in synchronize
    self.synchronize_sequence(False)
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1501, in synchronize_sequence
    self.create_new_address(for_change)
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1490, in create_new_address
    address = self.pubkeys_to_address(x)
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1677, in pubkeys_to_address
    raise NotImplementedError(self.txin_type)
NotImplementedError: p2pkh
Traceback (most recent call last):
  File "/home/wakiyamap/electrum/lib/util.py", line 135, in run_jobs
    job.run()
  File "/home/wakiyamap/electrum/lib/synchronizer.py", line 189, in run
    self.wallet.synchronize()
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1511, in synchronize
    self.synchronize_sequence(False)
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1501, in synchronize_sequence
    self.create_new_address(for_change)
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1490, in create_new_address
    address = self.pubkeys_to_address(x)
  File "/home/wakiyamap/electrum/lib/wallet.py", line 1677, in pubkeys_to_address
    raise NotImplementedError(self.txin_type)
NotImplementedError: p2pkh
.......

**Comment by benma** [comment]
I also had this, but the error suddenlyafter I checked out an older version and ran it (gone for good, even when going back to master).

**Comment by wakiyamap** [comment]
ummm.....
I cloned master repository too.
But error don't disappeared......

I checked out 283 branch and go back master.
Error don't disappeared.
![image](https://user-images.githubusercontent.com/7189933/30854431-89f76730-a2ec-11e7-8bf6-517153fd748d.png)

**Comment by wakiyamap** [comment]
Thanks @benma . This typo? fix, but I saw same thing....
> @wakiyamap what happens when fix this typo? 952049f#commitcomment-24570227

When making new Multi-signature wallet alway appear on my environment(ubuntu16.04x64 and x86)

**Comment by wakiyamap** [comment]
thanks !! everyone !!
