### ISSUE TITLE
NotImplementedError: p2phk 

### ISSUE THREAD

**Issue by mryellow** [spesmilo/electrum#2938]
```
Traceback (most recent call last):
  File "/home/yellow/src/electrum/lib/util.py", line 135, in run_jobs
    job.run()
  File "/home/yellow/src/electrum/lib/synchronizer.py", line 189, in run
    self.wallet.synchronize()
  File "/home/yellow/src/electrum/lib/wallet.py", line 1511, in synchronize
    self.synchronize_sequence(False)
  File "/home/yellow/src/electrum/lib/wallet.py", line 1501, in synchronize_sequence
    self.create_new_address(for_change)
  File "/home/yellow/src/electrum/lib/wallet.py", line 1490, in create_new_address
    address = self.pubkeys_to_address(x)
  File "/home/yellow/src/electrum/lib/wallet.py", line 1650, in pubkeys_to_address
    raise NotImplementedError(self.txin_type)
NotImplementedError: p2phk
```

Seems to be a typo where `p2phk` is being passed instead of `p2pkh`.

**Comment by mryellow** [comment]
I'm looking at this code in `keystore.py` which doesn't seem to exist on the repo itself.

```
class Old_KeyStore(Deterministic_KeyStore):

....

def txin_type(self):
        return 'p2phk'
```
