### ISSUE TITLE
Restoring 2FA wallet from seed only (lost QR code) not working

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2939]
On git master dcd50c3467d9de778de9d0e4db3836ec84c6d1cc.

Try to restore 2FA wallet from seed only, choose option "lost QR code".

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 446, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 193, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 282, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 381, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 442, in restore_wallet
    wizard.restore_seed_dialog(run_next=f, test=self.is_valid_seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 441, in <lambda>
    f = lambda seed, is_bip39, is_ext: wizard.run('on_restore_seed', seed, is_ext)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 446, in on_restore_seed
    wizard.passphrase_dialog(run_next=f) if is_ext else f('')
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 445, in <lambda>
    f = lambda x: self.restore_choice(wizard, seed, x)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 459, in restore_choice
    wizard.choice_dialog(choices=choices, message=msg, title=title, run_next=f)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 458, in <lambda>
    f = lambda x: self.on_choice(wizard, seed, passphrase, x)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 466, in on_choice
    self.create_keystore(wizard, seed, passphrase)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in create_keystore
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in <lambda>
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in on_password
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in <lambda>
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 520, in create_remote_key
    self.check_otp(wizard, short_id, otp_secret, xpub3)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 530, in check_otp
    wizard.restore_seed_dialog(run_next=f, test=self.is_valid_seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 529, in <lambda>
    f = lambda seed, is_bip39, is_ext: wizard.run('on_reset_seed', short_id, seed, is_ext, xpub3)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 534, in on_reset_seed
    wizard.passphrase_dialog(run_next=f) if is_ext else f('')
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 533, in <lambda>
    f = lambda passphrase: wizard.run('on_reset_auth', short_id, seed, passphrase, xpub3)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 569, in on_reset_auth
    r = server.reset_auth(short_id, challenge, signatures)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 153, in reset_auth
    return self.send_request('post', 'cosigner/%s/otp_secret' % quote(id), payload)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 89, in send_request
    kwargs['data'] = json.dumps(data)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'H4xSzi/O+65boaVYuvHGEeGmh1KO3VrxUK7dqNmcBa+bV7kbwffhBAVgY25IfbpTeLqJFnof8XqOLDQPlrOuiCQ=' is not JSON serializable
Aborted
```

**Comment by SomberNight** [comment]
With #2940 applied, new trace is
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 446, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 193, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 282, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 381, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 442, in restore_wallet
    wizard.restore_seed_dialog(run_next=f, test=self.is_valid_seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 441, in <lambda>
    f = lambda seed, is_bip39, is_ext: wizard.run('on_restore_seed', seed, is_ext)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 446, in on_restore_seed
    wizard.passphrase_dialog(run_next=f) if is_ext else f('')
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 445, in <lambda>
    f = lambda x: self.restore_choice(wizard, seed, x)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 459, in restore_choice
    wizard.choice_dialog(choices=choices, message=msg, title=title, run_next=f)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 458, in <lambda>
    f = lambda x: self.on_choice(wizard, seed, passphrase, x)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 466, in on_choice
    self.create_keystore(wizard, seed, passphrase)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in create_keystore
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in <lambda>
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in on_password
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in <lambda>
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 520, in create_remote_key
    self.check_otp(wizard, short_id, otp_secret, xpub3)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 530, in check_otp
    wizard.restore_seed_dialog(run_next=f, test=self.is_valid_seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 529, in <lambda>
    f = lambda seed, is_bip39, is_ext: wizard.run('on_reset_seed', short_id, seed, is_ext, xpub3)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 534, in on_reset_seed
    wizard.passphrase_dialog(run_next=f) if is_ext else f('')
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 533, in <lambda>
    f = lambda passphrase: wizard.run('on_reset_auth', short_id, seed, passphrase, xpub3)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 569, in on_reset_auth
    r = server.reset_auth(short_id, challenge, signatures)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 153, in reset_auth
    return self.send_request('post', 'cosigner/%s/otp_secret' % quote(id), payload)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 103, in send_request
    raise TrustedCoinException(message, response.status_code)
electrum_plugins.trustedcoin.trustedcoin.TrustedCoinException: invalid signature (#1)
Aborted
```

**Comment by SomberNight** [comment]
On git master dcd50c3467d9de778de9d0e4db3836ec84c6d1cc, with #2940 and #2941 applied, the issue is resolved, the GUI presents the user with the QR code.

**Comment by ecdsa** [comment]
thanks. I simplified #2941
