### ISSUE TITLE
Address generation in p2sh-segwit wallets is broken

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2961]
On git master 031b911dce818c4c005663e770b4784234bc5590.

Try restoring a BIP39 seeded wallet with a `m/49'/0'/0'` derivation path. When the wallet would try to generate its p2sh-segwit receive addresses, Electrum will crash.

```
[profiler] load_transactions 0.0000
[profiler] build_reverse_history 0.0000
[profiler] check_history 0.0000
[profiler] on_update 0.0001
[ElectrumWindow/test_bip39_49_treat] Notifying GUI
[ElectrumWindow/test_bip39_49_treat] using default geometry
Traceback (most recent call last):
  File "/home/user/wspace/electrum/lib/util.py", line 139, in run_jobs
    job.run()
  File "/home/user/wspace/electrum/lib/synchronizer.py", line 189, in run
    self.wallet.synchronize()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1575, in synchronize
    self.synchronize_sequence(False)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1565, in synchronize_sequence
    self.create_new_address(for_change)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1554, in create_new_address
    address = self.pubkeys_to_address(x)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1708, in pubkeys_to_address
    return bitcoin.pubkey_to_address(self.txin_type, pubkey)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 342, in pubkey_to_address
    scriptSig = transaction.p2wpkh_nested_script(pubkey)
NameError: name 'transaction' is not defined
```

Naively adding `from . import transaction` at the top of `bitcoin.py` will not work, I believe due to making imports circular, it then fails with:
```
$ ./electrum -v
Traceback (most recent call last):
  File "./electrum", line 91, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/wspace/electrum/lib/__init__.py", line 3, in <module>
    from .wallet import Synchronizer, Wallet
  File "/home/user/wspace/electrum/lib/wallet.py", line 47, in <module>
    from .bitcoin import *
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 36, in <module>
    from . import transaction
  File "/home/user/wspace/electrum/lib/transaction.py", line 45, in <module>
    from .keystore import xpubkey_to_address, xpubkey_to_pubkey
  File "/home/user/wspace/electrum/lib/keystore.py", line 33, in <module>
    from .bitcoin import pw_encode, pw_decode, bip32_root, bip32_private_derivation, bip32_public_derivation, bip32_private_key, deserialize_xprv, deserialize_xpub
ImportError: cannot import name 'pw_encode'
```

**Comment by SomberNight** [comment]
This is still not fixed (on master 91ed74a95ff705265da5f64dadd3c59c71cdd2bb), which is why the tests in #2964 still fail. The methods and imports in `keystore.py`, `transaction.py`, and `bitcoin.py` depend on each other convoluted ways, hence I did not attempt to move stuff around.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/lib/util.py", line 139, in run_jobs
    job.run()
  File "/home/user/wspace/electrum/lib/synchronizer.py", line 189, in run
    self.wallet.synchronize()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1575, in synchronize
    self.synchronize_sequence(False)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1565, in synchronize_sequence
    self.create_new_address(for_change)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1554, in create_new_address
    address = self.pubkeys_to_address(x)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1708, in pubkeys_to_address
    return bitcoin.pubkey_to_address(self.txin_type, pubkey)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 350, in pubkey_to_address
    scriptSig = p2wpkh_nested_script(pubkey)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 336, in p2wpkh_nested_script
    pubkey = safe_parse_pubkey(pubkey)
NameError: name 'safe_parse_pubkey' is not defined
```
