### ISSUE TITLE
[91ed74a] make_unsigned_request

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2970]
```
Traceback (most recent call last):
  File "/home/user/electrum/lib/python3.5/site-packages/electrum_gui/qt/request_list.py", line 126, in <lambda>
    menu.addAction(_("Save as BIP70 file"), lambda: self.parent.export_payment_request(addr))
  File "/home/user/electrum/lib/python3.5/site-packages/electrum_gui/qt/main_window.py", line 914, in export_payment_request
    pr = paymentrequest.serialize_request(r).SerializeToString()
  File "/home/user/electrum/lib/python3.5/site-packages/electrum/paymentrequest.py", line 432, in serialize_request
    pr = make_unsigned_request(req)
  File "/home/user/electrum/lib/python3.5/site-packages/electrum/paymentrequest.py", line 323, in make_unsigned_request
    pr.signature = ''
TypeError: '' has type str, but expected one of: bytes
```

**Comment by SomberNight** [comment]
(Trace happens when right-clicking a payment request in the `Receive` tab, and choosing `Save as BIP70 file`.)

If you fix this, there will be another crash after the save file dialog comes up, when you click `Save`.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/request_list.py", line 126, in <lambda>
    menu.addAction(_("Save as BIP70 file"), lambda: self.parent.export_payment_request(addr))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 919, in export_payment_request
    f.write(str(pr))
TypeError: a bytes-like object is required, not 'str'
Aborted
```
