### ISSUE TITLE
[dd006b5] non-hexadecimal number found in fromhex()

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2972]
```
Traceback (most recent call last):
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum_gui/qt/main_window.py", line 1980, in do_encrypt
    encrypted = bitcoin.encrypt_message(message, pubkey_e.text())
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/bitcoin.py", line 627, in encrypt_message
    return EC_KEY.encrypt_message(message, bfh(pubkey))
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/util.py", line 314, in bfh
    return bfh_builder(x)
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/util.py", line 294, in <lambda>
    bfh_builder = lambda x: bytes.fromhex(x)
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

Also:
```
ValueError: non-hexadecimal number found in fromhex() arg at position 2
```
```
ValueError: non-hexadecimal number found in fromhex() arg at position 4
```

Reproducible. Trying to encrypt a message on 91ed74a, appears on 088b1e6 too.

**Comment by lzsaver** [comment]
```
Traceback (most recent call last):
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum_gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/wallet.py", line 1645, in decrypt_message
    addr = self.pubkeys_to_address(pubkey)
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/wallet.py", line 1708, in pubkeys_to_address
    return bitcoin.pubkey_to_address(self.txin_type, pubkey)
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/bitcoin.py", line 346, in pubkey_to_address
    return public_key_to_p2pkh(bfh(pubkey))
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/util.py", line 314, in bfh
    return bfh_builder(x)
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/util.py", line 294, in <lambda>
    bfh_builder = lambda x: bytes.fromhex(x)
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

The same thing for decryption. Is it known bug?

**Comment by SomberNight** [comment]
Please include wallet/keystore type. E.g. Is this with a p2sh-segwit address?
Encryption/decryption works with p2pkh addresses for me (though message signing does not...).

**Comment by lzsaver** [comment]
I checked these wallets so far:
- standard / bip32;
- standard segwit / bip32;
- standard / hardware trezor m/44;
- standard segwit / hardware trezor m/49.

**Comment by SomberNight** [comment]
So this happens even with a standard (p2pkh) Electrum seed? Can you give steps to reproduce -- doesn't happen for me...
Also, if you post steps, please again name the commit you are testing on.

(Note that as mentioned in https://github.com/spesmilo/electrum/issues/2973#issuecomment-334141782, encryption/decryption for `Imported_KeyStore` does not work for a different reason atm.)

**Comment by lzsaver** [comment]
Yes, it happens even if I remove ~/.electrum before I create a new wallet. Here's on dd006b5:

```
Traceback (most recent call last):
  File "/home/user/electrum-dd006b5/lib/python3.5/site-packages/electrum_gui/qt/main_window.py", line 1980, in do_encrypt
    encrypted = bitcoin.encrypt_message(message, pubkey_e.text())
  File "/home/user/electrum-dd006b5/lib/python3.5/site-packages/electrum/bitcoin.py", line 622, in encrypt_message
    return EC_KEY.encrypt_message(message, bfh(pubkey))
  File "/home/user/electrum-dd006b5/lib/python3.5/site-packages/electrum/util.py", line 314, in bfh
    return bfh_builder(x)
  File "/home/user/electrum-dd006b5/lib/python3.5/site-packages/electrum/util.py", line 294, in <lambda>
    bfh_builder = lambda x: bytes.fromhex(x)
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

I created the wallet this way:
File -> New/Restore -> Standard wallet -> Create a new seed -> Standard

**Comment by SomberNight** [comment]
I can't reproduce.
The trace suggests that the second input field contains non-hex characters. Can you check this?
![el_issue_2972_pic1](https://user-images.githubusercontent.com/29142493/31178497-96976fac-a919-11e7-8aa8-a05485fd9c58.png)
I can only reproduce if I manually add such characters to that field.

**Comment by lzsaver** [comment]
I was not careful. I had to double check the string with my pubkey.
I spent your time on this issue. I apologize. Thank you for you help.

I'm closing the issue.
