### ISSUE TITLE
Message signing is broken

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2973]
On git master 91ed74a95ff705265da5f64dadd3c59c71cdd2bb.

-----

`Standard_Wallet` with `BIP32_KeyStore`, standard electrum seed (so p2pkh addresses)

Trying to sign with different addresses results in different traces.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1642, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 91, in sign_message
    return sign_message_with_wif_privkey(sec, message)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 622, in sign_message_with_wif_privkey
    txin_type, privkey, compressed = deserialize_privkey(sec)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 504, in deserialize_privkey
    vch = DecodeBase58Check(key)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 471, in DecodeBase58Check
    vchRet = base_decode(psz, None, base=58)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 451, in base_decode
    result.append(long_value)
ValueError: byte must be in range(0, 256)
```

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1642, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 91, in sign_message
    return sign_message_with_wif_privkey(sec, message)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 622, in sign_message_with_wif_privkey
    txin_type, privkey, compressed = deserialize_privkey(sec)
TypeError: 'bool' object is not iterable
```

-----

`Standard_Wallet` with `Imported_KeyStore`, p2pkh addresses

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1642, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 90, in sign_message
    sec = self.get_private_key(sequence, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 152, in get_private_key
    sec = pw_decode(self.keypairs[pubkey], password)
KeyError: (False, 0)
```

**Comment by SomberNight** [comment]
Note that this is still not fixed.
On git master 0f4b5abc158d46ac25fc2a976154004a2c705f2d.

-----

`Standard_Wallet` with `BIP32_KeyStore`, standard electrum seed (so p2pkh addresses)

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1643, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 92, in sign_message
    key = regenerate_key(privkey)
NameError: name 'privkey' is not defined
```

-----

`Standard_Wallet` with `Imported_KeyStore`, p2pkh addresses

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1643, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 90, in sign_message
    sec = self.get_private_key(sequence, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 154, in get_private_key
    sec = pw_decode(self.keypairs[pubkey], password)
KeyError: (False, 0)
```

**Comment by lzsaver** [comment]
I'm getting the same thing on dd006b5.
