### ISSUE TITLE
[91ed74a] 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2974]
```
Plugin error
Traceback (most recent call last):
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum/plugins.py", line 198, in run_hook
    r = f(*args)
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum_plugins/labels/labels.py", line 54, in set_label
    "externalId": self.encode(wallet, item),
  File "/home/user/electrum-master/lib/python3.5/site-packages/electrum_plugins/labels/labels.py", line 25, in encode
    msg.encode('utf8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

Steps to reproduce:
go to the Addresses tab; try to add a label to the Receiving QTreeWidgetItem (not to the address).

See also #2968.

**Comment by SomberNight** [comment]
Note that the `LabelSync` plugin needs to be enabled for this, and that to edit that "label" you need to double-click on it (the right-click context menu is correctly disabled).
