### ISSUE TITLE
Imported_Wallet missing: msg signing, msg decryption

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2992]
On git master 34a786ee433960fc3b33af3e82ca80656a540f21
Given Imported_Wallet seems to become the norm for "a wallet with a bunch of imported privkeys" ( https://github.com/spesmilo/electrum/issues/2989#issuecomment-334385866 ), the following needs fixing:

message signing
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1957, in <lambda>
    b.clicked.connect(lambda: self.do_sign(address_e, message_e, signature_e))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1281, in request_password
    return func(self, *args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1907, in do_sign
    task = partial(self.wallet.sign_message, address, message, password)
AttributeError: 'Imported_Wallet' object has no attribute 'sign_message'
Aborted
```

message decryption
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2015, in <lambda>
    b.clicked.connect(lambda: self.do_decrypt(message_e, pubkey_e, encrypted_e))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1281, in request_password
    return func(self, *args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1973, in do_decrypt
    task = partial(self.wallet.decrypt_message, pubkey_e.text(), cyphertext, password)
AttributeError: 'Imported_Wallet' object has no attribute 'decrypt_message'
Aborted
```

**Comment by ecdsa** [comment]
added in e299df7b82f626f669098ccc0dbe041934d72d86
