### ISSUE TITLE
Unknown wallet type: 2fa

### ISSUE THREAD

**Issue by scgbckbone** [spesmilo/electrum#3008]
Do I get this error when using electrum from cmd line because I've chosen 2 factor auth?

    Traceback (most recent call last):
      File "/usr/local/bin/electrum", line 427, in <module>
        result = run_offline_command(config, config_options)
      File "/usr/local/bin/electrum", line 266, in run_offline_command
        wallet = Wallet(storage)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1783, in __new__
        WalletClass = Wallet.wallet_class(wallet_type)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1801, in wallet_class
        raise RuntimeError("Unknown wallet type: " + wallet_type)
    RuntimeError: Unknown wallet type: 2fa

**Comment by ecdsa** [comment]
indeed, there is no command line support for the 2fa plugin.
what is your use case?

**Comment by scgbckbone** [comment]
I was just curious. Then I checked the source code and got it. I only need to do basic stuff, so I think I'll be good with gui.

**Comment by ecdsa** [comment]
I think it would not be difficult to add, just never had time for it

**Comment by ecdsa** [comment]
added in 4836adff84df2e7cadcb76f200095523cc99f15a
