### ISSUE TITLE
Backing out of 2FA wallet creation: unhandled exceptions

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3009]
On git master 5480b7dff50eaac8a10af9fc7d17c8e0a6f410c9.

When creating a 2FA wallet, in the install wizard [QT GUI],

-----

- cancel, when presented with the ToS and the email input field

<details>
 <summary>trace 1</summary>

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 86, in func_wrapper
    out = func(*args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 393, in show_seed_dialog
    self.exec_layout(slayout)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 326, in exec_layout
    raise GoBack
electrum_gui.qt.installwizard.GoBack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 86, in func_wrapper
    out = func(*args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 386, in confirm_seed_dialog
    seed, is_bip39, is_ext = self.seed_input(title, message, test, None)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 350, in seed_input
    self.exec_layout(slayout, title, next_enabled=False)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 326, in exec_layout
    raise GoBack
electrum_gui.qt.installwizard.GoBack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 86, in func_wrapper
    out = func(*args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 406, in request_password
    return self.pw_layout(MSG_ENTER_PASSWORD, PW_NEW)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 399, in pw_layout
    self.exec_layout(playout.layout())
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 326, in exec_layout
    raise GoBack
electrum_gui.qt.installwizard.GoBack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 446, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 194, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 282, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 381, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 386, in create_seed
    wizard.show_seed_dialog(run_next=f, seed_text=seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 88, in func_wrapper
    wizard.go_back() if wizard.can_go_back() else wizard.close()
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 73, in go_back
    self.run(action, *args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 381, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 386, in create_seed
    wizard.show_seed_dialog(run_next=f, seed_text=seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 385, in <lambda>
    f = lambda x: wizard.request_passphrase(seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 396, in request_passphrase
    self.run('confirm_seed', seed, '')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 400, in confirm_seed
    self.confirm_seed_dialog(run_next=f, test=lambda x: x==seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 88, in func_wrapper
    wizard.go_back() if wizard.can_go_back() else wizard.close()
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 73, in go_back
    self.run(action, *args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 386, in create_seed
    wizard.show_seed_dialog(run_next=f, seed_text=seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 385, in <lambda>
    f = lambda x: wizard.request_passphrase(seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 396, in request_passphrase
    self.run('confirm_seed', seed, '')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 400, in confirm_seed
    self.confirm_seed_dialog(run_next=f, test=lambda x: x==seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 399, in <lambda>
    f = lambda x: self.confirm_passphrase(seed, passphrase)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 412, in confirm_passphrase
    f('')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 403, in <lambda>
    f = lambda x: self.run('create_keystore', seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in create_keystore
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 88, in func_wrapper
    wizard.go_back() if wizard.can_go_back() else wizard.close()
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 73, in go_back
    self.run(action, *args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 400, in confirm_seed
    self.confirm_seed_dialog(run_next=f, test=lambda x: x==seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 399, in <lambda>
    f = lambda x: self.confirm_passphrase(seed, passphrase)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 412, in confirm_passphrase
    f('')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 403, in <lambda>
    f = lambda x: self.run('create_keystore', seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in create_keystore
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in <lambda>
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in on_password
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in <lambda>
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 487, in create_remote_key
    email = self.accept_terms_of_use(wizard)
  File "/home/user/wspace/electrum/plugins/trustedcoin/qt.py", line 224, in accept_terms_of_use
    window.exec_layout(vbox, next_enabled=False)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 326, in exec_layout
    raise GoBack
electrum_gui.qt.installwizard.GoBack
Aborted
```
</details>

-----

- cancel, when presented with the QR code

<details>
 <summary>trace 2</summary>

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 446, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 194, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 282, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 372, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(DISCLAIMER), run_next = lambda x: wizard.run('choose_seed'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 381, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 386, in create_seed
    wizard.show_seed_dialog(run_next=f, seed_text=seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 385, in <lambda>
    f = lambda x: wizard.request_passphrase(seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 396, in request_passphrase
    self.run('confirm_seed', seed, '')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 400, in confirm_seed
    self.confirm_seed_dialog(run_next=f, test=lambda x: x==seed)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 399, in <lambda>
    f = lambda x: self.confirm_passphrase(seed, passphrase)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 412, in confirm_passphrase
    f('')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 403, in <lambda>
    f = lambda x: self.run('create_keystore', seed, x)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in create_keystore
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 416, in <lambda>
    wizard.request_password(run_next=lambda pw, encrypt: self.on_password(wizard, pw, encrypt, k1, k2))
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in on_password
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 435, in <lambda>
    wizard.confirm_dialog(title='', message=msg, run_next = lambda x: wizard.run('create_remote_key'))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 520, in create_remote_key
    self.check_otp(wizard, short_id, otp_secret, xpub3)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 523, in check_otp
    otp, reset = self.request_otp_dialog(wizard, short_id, otp_secret)
  File "/home/user/wspace/electrum/plugins/trustedcoin/qt.py", line 268, in request_otp_dialog
    raise_on_cancel=False)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 326, in exec_layout
    raise GoBack
electrum_gui.qt.installwizard.GoBack
Aborted
```
</details>

-----

I've also managed to crash Electrum doing something else, along these lines, can't remember exactly what.
EDIT: When trying to open a half-complete wallet that was "created" during one of the above crashes, Electrum offers to "finish" completing the wallet creation now. Choose to do that, and when presented with the ToS and the email input field, close the wizard.
If you close using the "x" button, you get the trace below; if you close via the "cancel" button, you will get almost verbatim the same trace but with exception type `electrum_gui.qt.installwizard.GoBack` raised at `installwizard.py#L326`.

<details>
 <summary>trace 3</summary>

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 194, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 282, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 58, in run
    f(self, *args)
  File "/home/user/wspace/electrum/plugins/trustedcoin/trustedcoin.py", line 487, in create_remote_key
    email = self.accept_terms_of_use(wizard)
  File "/home/user/wspace/electrum/plugins/trustedcoin/qt.py", line 224, in accept_terms_of_use
    window.exec_layout(vbox, next_enabled=False)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 324, in exec_layout
    raise UserCancelled
electrum.util.UserCancelled
Aborted
```
</details>

**Comment by SomberNight** [comment]
Closing; #3010 fixed these.
