### ISSUE TITLE
deserialize problem

### ISSUE THREAD

**Issue by targon** [spesmilo/electrum#3014]
I am on master (commit e0635f5d08497f9bd467ac855fc736435b1a9de8)

After opening my wallet the synchronisation doesn't complete, the last transaction is not picked up. Running in verbose mode, I see these messages about the missing transaction printed:

[Synchronizer] missing tx {'0d573c417b6c2c773aa0f27de36cdd5c68a1e20ad3e477ef5330fff04df62fb0': 489102}
[us.electrum.be] connected
[E-X.not.fyi] connected
[profiler] on_update 0.0017
[Synchronizer] cannot deserialize transaction, skipping 0d573c417b6c2c773aa0f27de36cdd5c68a1e20ad3e477ef5330fff04df62fb0

Entering deserialize('...') with the raw transaction on the console gives this:

Traceback (most recent call last):
  File "electrum/gui/qt/main_window.py", line 1726, in <lambda>
    return lambda *args: f(method, args, self.password_dialog)
  File "electrum/lib/commands.py", line 121, in _run
    result = f(*args)
  File "electrum/lib/commands.py", line 94, in func_wrapper
    return func(*args, **kwargs)
  File "electrum/lib/commands.py", line 253, in deserialize
    return tx.deserialize()
  File "electrum/lib/transaction.py", line 588, in deserialize
    d = deserialize(self.raw)
  File "electrum/lib/transaction.py", line 476, in deserialize
    parse_witness(vds, txin)
  File "electrum/lib/transaction.py", line 434, in parse_witness
    w = list(bh2u(vds.read_bytes(vds.read_compact_size())) for i in range(n))
  File "electrum/lib/transaction.py", line 434, in <genexpr>
    w = list(bh2u(vds.read_bytes(vds.read_compact_size())) for i in range(n))
  File "electrum/lib/transaction.py", line 120, in read_compact_size
    size = self.input[self.read_cursor]
IndexError: bytearray index out of range

**Comment by ecdsa** [comment]
thanks
