### ISSUE TITLE
Keepkey issuing signing (git HEAD)

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#3044]
Traceback (most recent call last):
  File "/Users/neil/src/electrum/gui/qt/util.py", line 587, in run
    result = task.task()
  File "/Users/neil/src/electrum/lib/wallet.py", line 1130, in sign_transaction
    k.sign_transaction(tx, password)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 70, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 246, in sign_transaction
    client = self.get_client(keystore)
  File "/Users/neil/src/electrum/plugins/trezor/plugin.py", line 147, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/Users/neil/src/electrum/lib/plugins.py", line 391, in client_for_keystore
    handler.update_status(False)
AttributeError: 'NoneType' object has no attribute 'update_status'

**Comment by kyuupichan** [comment]
Caused by 0.7.3 version of keepkey libs
