### ISSUE TITLE
payto command only works with static fees

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3058]
Not sure if this is known, but I've found that the `payto` command does not work with dynamic fees enabled. _(EDIT: see edit below)_

On git master 0a648e2b1cdb7852d80c0626c62984ef01c1c7e9.
```
$ ./electrum --testnet -w "/home/user/.electrum/testnet/wallets/test_std_asdsada" payto mn9KjoNQh5vFVDNn6waWNG1HW4GPD8cSBg 0.01
Traceback (most recent call last):
  File "./electrum", line 429, in <module>
    result = run_offline_command(config, config_options)
  File "./electrum", line 294, in run_offline_command
    result = func(*args, **kwargs)
  File "/home/user/wspace/electrum/lib/commands.py", line 94, in func_wrapper
    return func(*args, **kwargs)
  File "/home/user/wspace/electrum/lib/commands.py", line 442, in payto
    tx = self._mktx([(destination, amount)], tx_fee, change_addr, domain, nocheck, unsigned, rbf, password, locktime)
  File "/home/user/wspace/electrum/lib/commands.py", line 427, in _mktx
    tx = self.wallet.make_unsigned_transaction(coins, final_outputs, self.config, fee, change_addr)
  File "/home/user/wspace/electrum/lib/wallet.py", line 813, in make_unsigned_transaction
    raise BaseException('Dynamic fee estimates not available')
BaseException: Dynamic fee estimates not available
```

Note that dynamic fees are enabled by default.
https://github.com/spesmilo/electrum/blob/0a648e2b1cdb7852d80c0626c62984ef01c1c7e9/lib/simple_config.py#L236-L237

EDIT: it works when a fee is specified in the command with the `-f` option. Maybe this could be clarified somehow?

**Comment by ecdsa** [comment]
you need to run a daemon if you want fee estimates.
I guess the error message should say it explicitlyy, because it is not obvious

**Comment by SomberNight** [comment]
This issue is severely outdated. Probably does not apply anymore.

```
$ ./run_electrum -v --testnet payto tb1qcs8sn834hc65nv0lypxf4zzh8yrp0vqw293vdl 0.001
Password:
Daemon not running; try 'electrum daemon -d'
To run this command without a daemon, use --offline
```
