### ISSUE TITLE
Exchange rates can't be obtained from some FX providers

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3063]
On git master 0a648e2b1cdb7852d80c0626c62984ef01c1c7e9.

Getting fiat exchange rates from numerous providers is broken. Maybe APIs changed?

Log with `-v` option:
```
[FxThread] using exchange BitPay
[BitPay] getting fx quotes for USD
[BitPay] failed fx quotes: Expecting value: line 1 column 1 (char 0)
[FxThread] using exchange BitStamp
[BitStamp] getting fx quotes for USD
[BitStamp] failed fx quotes: Expecting value: line 1 column 1 (char 0)
[FxThread] using exchange BitcoinAverage
[BitcoinAverage] getting fx quotes for USD
[BitcoinAverage] received fx quotes
[FxThread] using exchange BlockchainInfo
[BlockchainInfo] getting fx quotes for USD
[BlockchainInfo] received fx quotes
[FxThread] using exchange Coinbase
[Coinbase] getting fx quotes for USD
[Coinbase] failed fx quotes: Expecting value: line 1 column 1 (char 0)
[FxThread] using exchange Kraken
[Kraken] getting fx quotes for USD
[Kraken] failed fx quotes: Expecting value: line 1 column 1 (char 0)
[FxThread] using exchange LocalBitcoins
[LocalBitcoins] getting fx quotes for USD
[LocalBitcoins] received fx quotes
[FxThread] using exchange WEX
[WEX] getting fx quotes for USD
[WEX] failed fx quotes: Expecting value: line 1 column 1 (char 0)
[FxThread] using exchange Winkdex
[Winkdex] getting fx quotes for USD
[Winkdex] failed fx quotes: Expecting value: line 1 column 1 (char 0)
```

(these above are only the USD providers)

**Comment by SomberNight** [comment]
I'm getting HTTP 403-s from the failing provider.

```
[FxThread] using exchange BitStamp
[BitStamp] getting fx quotes for USD
ExchangeBase.get_json() https://www.bitstamp.net/api/ticker/ <Response [403]>
Traceback (most recent call last):
  File "/home/user/wspace/electrum/lib/exchange_rate.py", line 60, in update_safe
    self.quotes = self.get_rates(ccy)
  File "/home/user/wspace/electrum/lib/exchange_rate.py", line 169, in get_rates
    json = self.get_json('www.bitstamp.net', '/api/ticker/')
  File "/home/user/wspace/electrum/lib/exchange_rate.py", line 46, in get_json
    return response.json()
  File "/home/user/wspace/electrum/packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[BitStamp] failed fx quotes: Expecting value: line 1 column 1 (char 0)
```
No idea why, as, if I try to open the given URL in a browser, it works, with HTTP 200.

**Comment by SomberNight** [comment]
Turns out I've had the proxy setting enabled (pointed at the local Tor proxy).
I guess the exit node must have been banned by these providers.
Apologies for missing this.

**Comment by ecdsa** [comment]
at some point I would like to have exchange rate data forwarded by electrum servers.
we need to convince them to sign their data, though
