### ISSUE TITLE
TREZOR plugin does not support bech32 address

### ISSUE THREAD

**Issue by nomnombtc** [spesmilo/electrum#3064]
Hello,

some days ago I wanted to order something on openbazaar and they already
use bech32 addresses. From my understanding this should work with the new segwit enabled
electrum, but apparently the TREZOR plugin does not support this yet.

```
Traceback (most recent call last):
  File "/mnt/hdd/backup_raid/electrum/gui/qt/util.py", line 587, in run
    result = task.task()
  File "/mnt/hdd/backup_raid/electrum/lib/wallet.py", line 1130, in sign_transaction
    k.sign_transaction(tx, password)
  File "/mnt/hdd/backup_raid/electrum/plugins/trezor/plugin.py", line 63, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/mnt/hdd/backup_raid/electrum/plugins/trezor/plugin.py", line 242, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/mnt/hdd/backup_raid/electrum/plugins/trezor/clientbase.py", line 222, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/trezorlib/client.py", line 846, in sign_tx
    res = self.call(proto.TxAck(tx=msg))
  File "/usr/lib64/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/mnt/hdd/backup_raid/electrum/plugins/trezor/clientbase.py", line 35, in callback_Failure
    raise RuntimeError(msg.message)
RuntimeError: Failed to compile output
```

**Comment by SomberNight** [comment]
Indeed that seems to be the case, see #2976

**Comment by nomnombtc** [comment]
Oh thanks, I did not see the existing issue. I searched for bech32, but nothing did show up :)
I guess I close this, because duplicate. Thanks for pointing me to the existing issue!
