### ISSUE TITLE
2FA wallet has no attr wallet_type

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3095]
On git master af8b7a7fb1ee86a7edf56c39700e20556e0dcf34.

With a 2FA wallet open, in the QT GUI, go into `Tools`/`Plugins`.

```
[ElectrumWindow/wallet_1] error: cannot display plugin trustedcoin
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2856, in plugins_dialog
    cb.setEnabled(plugins.is_available(name, self.wallet))
  File "/home/user/wspace/electrum/lib/plugins.py", line 143, in is_available
    return not requires or w.wallet_type in requires
AttributeError: 'Wallet_2fa' object has no attribute 'wallet_type'
```

**Comment by SomberNight** [comment]
Note: Is it OK that for 2FA wallets (with #3096) when the Trusted Coin plugin ("Two Factor Authentication") is listed in `Plugins`, the checkbox can be disabled?

**Comment by ecdsa** [comment]
probably not..
