### ISSUE TITLE
No module name dns and pip cannot find it

### ISSUE THREAD

**Issue by elcolie** [spesmilo/electrum#3097]
python 3.6.3
Debian Stretch

```bash
(electrum) sarit@sniper:~/electrum-2.9.3$ ls
app.fil  contrib   electrum.conf.sample  electrum-env   gui    icons.qrc   lib      MANIFEST.in  pubkeys     RELEASE-NOTES  setup.py          snap
AUTHORS  electrum  electrum.desktop      electrum.icns  icons  Info.plist  LICENCE  plugins      README.rst  scripts        setup-release.py  tox.ini
(electrum) sarit@sniper:~/electrum-2.9.3$ ./el
bash: ./el: No such file or directory
(electrum) sarit@sniper:~/electrum-2.9.3$ ./electrum 
Error: No module named dns. Try 'sudo pip install <module-name>'
(electrum) sarit@sniper:~/electrum-2.9.3$ pip install dns
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns
```

**Comment by Rotonen** [comment]
There is a `setup.py` there to define the dependencies for you. Simply develop the electrum egg locally into your virtualenv with `pip install -Ue .`.

**Comment by elcolie** [comment]
```bash
(electrum) sarit@sniper:~/electrum-2.9.3$ pip install -Ue .
Obtaining file:///home/sarit/electrum-2.9.3
Collecting pyaes (from Electrum==2.9.3)
  Using cached pyaes-1.6.1.tar.gz
Collecting ecdsa>=0.9 (from Electrum==2.9.3)
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting pbkdf2 (from Electrum==2.9.3)
  Using cached pbkdf2-1.3.tar.gz
Collecting requests (from Electrum==2.9.3)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting qrcode (from Electrum==2.9.3)
  Using cached qrcode-5.3-py2.py3-none-any.whl
Collecting protobuf (from Electrum==2.9.3)
  Using cached protobuf-3.4.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting dnspython (from Electrum==2.9.3)
  Using cached dnspython-1.15.0-py2.py3-none-any.whl
Collecting jsonrpclib (from Electrum==2.9.3)
  Using cached jsonrpclib-0.1.7.tar.gz
Collecting PySocks>=1.6.6 (from Electrum==2.9.3)
  Using cached PySocks-1.6.7-py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->Electrum==2.9.3)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->Electrum==2.9.3)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->Electrum==2.9.3)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->Electrum==2.9.3)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting six (from qrcode->Electrum==2.9.3)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf->Electrum==2.9.3)
  Using cached setuptools-36.6.0-py2.py3-none-any.whl
Installing collected packages: pyaes, ecdsa, pbkdf2, idna, chardet, certifi, urllib3, requests, six, qrcode, setuptools, protobuf, dnspython, jsonrpclib, PySocks, Electrum
  Running setup.py install for pyaes ... done
  Running setup.py install for pbkdf2 ... done
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  Running setup.py install for jsonrpclib ... done
  Running setup.py develop for Electrum
Successfully installed Electrum PySocks-1.6.7 certifi-2017.7.27.1 chardet-3.0.4 dnspython-1.15.0 ecdsa-0.13 idna-2.6 jsonrpclib-0.1.7 pbkdf2-1.3 protobuf-3.4.0 pyaes-1.6.1 qrcode-5.3 requests-2.18.4 setuptools-36.6.0 six-1.11.0 urllib3-1.22
(electrum) sarit@sniper:~/electrum-2.9.3$ ls
app.fil  electrum              Electrum.egg-info  gui        Info.plist  MANIFEST.in  README.rst     setup.py          tox.ini
AUTHORS  electrum.conf.sample  electrum-env       icons      lib         plugins      RELEASE-NOTES  setup-release.py
contrib  electrum.desktop      electrum.icns      icons.qrc  LICENCE     pubkeys      scripts        snap
(electrum) sarit@sniper:~/electrum-2.9.3$ ./electrum 
Error: No module named dns. Try 'sudo pip install <module-name>'
(electrum) sarit@sniper:~/electrum-2.9.3$ pip install dns
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns

```

**Comment by ecdsa** [comment]
the package name is dnspython
it is in your log

**Comment by Rotonen** [comment]
After developing th egg, run `electrum`, not `./electrum`. The script will be in your `$PATH` now.

**Comment by elcolie** [comment]
```bash
ModuleNotFoundError: No module named 'xmlrpclib'
```
Looks like `Electrum` is running on python2 not 3
https://stackoverflow.com/questions/43750223/no-module-name-xmlrpclib-when-using-electrum-from-command-line

```bash
(electrum) sarit@sniper:~/electrum-2.9.3$ pip install -Ue .
Obtaining file:///home/sarit/electrum-2.9.3
Requirement already up-to-date: pyaes in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: ecdsa>=0.9 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: pbkdf2 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: requests in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: qrcode in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: protobuf in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: dnspython in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: jsonrpclib in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: PySocks>=1.6.6 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from Electrum==2.9.3)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from requests->Electrum==2.9.3)
Requirement already up-to-date: certifi>=2017.4.17 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from requests->Electrum==2.9.3)
Requirement already up-to-date: idna<2.7,>=2.5 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from requests->Electrum==2.9.3)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from requests->Electrum==2.9.3)
Requirement already up-to-date: six in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from qrcode->Electrum==2.9.3)
Requirement already up-to-date: setuptools in /home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages (from protobuf->Electrum==2.9.3)
Installing collected packages: Electrum
  Found existing installation: Electrum 2.9.3
    Uninstalling Electrum-2.9.3:
      Successfully uninstalled Electrum-2.9.3
  Running setup.py develop for Electrum
Successfully installed Electrum
(electrum) sarit@sniper:~/electrum-2.9.3$ electrum 
Traceback (most recent call last):
  File "/home/sarit/electrum-2.9.3/electrum", line 71, in check_imports
    import jsonrpclib
  File "/home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages/jsonrpclib/__init__.py", line 5, in <module>
    from jsonrpclib.jsonrpc import Server, MultiCall, Fault
  File "/home/sarit/.pyenv/versions/3.6.3/envs/electrum/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 50, in <module>
    from xmlrpclib import Transport as XMLTransport
ModuleNotFoundError: No module named 'xmlrpclib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sarit/.pyenv/versions/electrum/bin/electrum", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/sarit/electrum-2.9.3/electrum", line 90, in <module>
    check_imports()
  File "/home/sarit/electrum-2.9.3/electrum", line 73, in check_imports
    sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%e.message)
AttributeError: 'ModuleNotFoundError' object has no attribute 'message'
```
