### ISSUE TITLE
OSX : raise BaseException('wallet format requires update')

### ISSUE THREAD

**Issue by edwinwebb** [spesmilo/electrum#3162]
After setting up a wallet in 2.8.3 (probably) following a standard guide (link unknown) on the latest OSX a few months ago re-opening the app has generated error when trying to open the default wallet. I got an `wallet format requires update` error.

Hope someone can help and thanks in advance. 

```
31/10/2017 17:00:52.290 Electrum[723]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.1 instead of 10.11.1. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
31/10/2017 17:00:52.290 Electrum[723]: 0   CarbonCore                          0x00007fff8bce879f ___Gestalt_SystemVersion_block_invoke + 113
31/10/2017 17:00:52.290 Electrum[723]: 1   libdispatch.dylib                   0x00007fff916103c3 _dispatch_client_callout + 8
31/10/2017 17:00:52.290 Electrum[723]: 2   libdispatch.dylib                   0x00007fff916102bb dispatch_once_f + 67
31/10/2017 17:00:52.290 Electrum[723]: 3   CarbonCore                          0x00007fff8bc7509c _Gestalt_SystemVersion + 987
31/10/2017 17:00:52.290 Electrum[723]: 4   CarbonCore                          0x00007fff8bc748b0 Gestalt + 139
31/10/2017 17:00:52.290 Electrum[723]: 5   QtCore                              0x0000000106e53ae4 _ZN19QProcessEnvironment17systemEnvironmentEv + 31524
31/10/2017 17:00:52.290 Electrum[723]: 6   QtCore                              0x0000000106e3994a _ZN9QSettingsC1ERK7QStringS2_P7QObject + 34
31/10/2017 17:00:53.048 usernoted[319]: SecTaskLoadEntitlements failed error=22
31/10/2017 17:00:53.084 appleeventsd[51]: SecTaskLoadEntitlements failed error=22
31/10/2017 17:00:57.818 Electrum[723]: Traceback (most recent call last):
31/10/2017 17:00:57.818 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/__boot__.py", line 77, in <module>
31/10/2017 17:00:57.818 Electrum[723]:     _run()
31/10/2017 17:00:57.818 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/__boot__.py", line 62, in _run
31/10/2017 17:00:57.818 Electrum[723]:     exec(compile(source, path, 'exec'), globals(), globals())
31/10/2017 17:00:57.818 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/electrum.py", line 379, in <module>
31/10/2017 17:00:57.819 Electrum[723]:     d.init_gui(config, plugins)
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/daemon.py", line 283, in init_gui
31/10/2017 17:00:57.819 Electrum[723]:     self.gui.main()
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 200, in main
31/10/2017 17:00:57.819 Electrum[723]:     if not self.start_new_window(path, self.config.get('url')):
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 161, in start_new_window
31/10/2017 17:00:57.819 Electrum[723]:     wallet = wizard.run_and_get_wallet()
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 262, in run_and_get_wallet
31/10/2017 17:00:57.819 Electrum[723]:     self.wallet = Wallet(self.storage)
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1757, in __new__
31/10/2017 17:00:57.819 Electrum[723]:     wallet = WalletClass(storage)
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1661, in __init__
31/10/2017 17:00:57.819 Electrum[723]:     Deterministic_Wallet.__init__(self, storage)
31/10/2017 17:00:57.819 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1409, in __init__
31/10/2017 17:00:57.820 Electrum[723]:     Abstract_Wallet.__init__(self, storage)
31/10/2017 17:00:57.820 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 104, in __init__
31/10/2017 17:00:57.820 Electrum[723]:     self.load_keystore()
31/10/2017 17:00:57.820 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1680, in load_keystore
31/10/2017 17:00:57.820 Electrum[723]:     self.keystores[name] = load_keystore(self.storage, name)
31/10/2017 17:00:57.820 Electrum[723]:   File "/Users/edwin/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/keystore.py", line 610, in load_keystore
31/10/2017 17:00:57.820 Electrum[723]:     raise BaseException('wallet format requires update')
31/10/2017 17:00:57.820 Electrum[723]: BaseException: wallet format requires update
31/10/2017 17:00:57.887 Electrum[723]: Electrum Error
31/10/2017 17:00:57.887 Electrum[723]: 2017-10-31 17:00:57.886 Electrum[723:17353] Electrum Error
```

**Comment by SomberNight** [comment]
So you generated this wallet originally with the same version of Electrum you're using now?
In any case, the easiest way to regain access to your coins would be to restore from seed.

**Comment by edwinwebb** [comment]
I fear my google-fu is too weak to find a trustworthy guide. Can anyone help?

**Comment by ecdsa** [comment]
do you have the seed of this wallet?

**Comment by edwinwebb** [comment]
Yes. I have the seed.

**Comment by ecdsa** [comment]
so, as written above, restore your wallet from seed

**Comment by edwinwebb** [comment]
Still trying here...

Removed ~/.electrum, and dmg in /application/, installed 3.0.0, updated wallet to new format, entered password.

255 error thrown.

```02/11/2017 16:37:28.852 Electrum[7214]: assertion failed: 15B42: libxpc.dylib + 79134 [3E09C275-A33B-357A-B0AB-A2DDF88EC9D5]: 0x87
02/11/2017 16:37:46.589 com.apple.xpc.launchd[1]: (Electrum.809632[7213]) Service exited with abnormal code: 255
```
Creating a new wallet seems fine. 

I'm sorry. I've been googling around and just can't find any options to restore from seed.

Whenever I open Electrum I get the Install Wizard screen with just the option to select a wallet and the prompt for a password. No other options are presented.

Hoping someone can help here.

**Comment by SomberNight** [comment]
Try to select a wallet that does not exist by changing the text input field, and the wizard will proceed to create it.

**Comment by edwinwebb** [comment]
Restored. Thank you!

**Comment by calhroub** [comment]
My issue #4355 is Electrum won't open at all, even after update to latest version 3.1.3...
