### ISSUE TITLE
[Android] Cannot load SDL libraries

### ISSUE THREAD

**Issue by dllud** [spesmilo/electrum#3184]
I get a FC with [Electrum 3.0.0](https://download.electrum.org/3.0/Electrum-3.0.0.0-release.apk) on Android 4.2 as soon as I open the app. Here's the logcat output:

```
D/dalvikvm(29380): Trying to load lib /data/app-lib/org.electrum.electrum-1/libSDL2.so 0x42005488
E/dalvikvm(29380): dlopen("/data/app-lib/org.electrum.electrum-1/libSDL2.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1673): could not load library "libcrystax.so" needed by "libSDL2.so"; caused by load_library(linker.cpp:771): library "libcrystax.so" not found
D/dalvikvm(29380): Trying to load lib /data/app-lib/org.electrum.electrum-1/libSDL2_image.so 0x42005488
E/dalvikvm(29380): dlopen("/data/app-lib/org.electrum.electrum-1/libSDL2_image.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1673): could not load library "libSDL2.so" needed by "libSDL2_image.so"; caused by find_library(linker.cpp:927): "libSDL2.so" failed to load previously
D/dalvikvm(29380): Trying to load lib /data/app-lib/org.electrum.electrum-1/libSDL2_mixer.so 0x42005488
E/dalvikvm(29380): dlopen("/data/app-lib/org.electrum.electrum-1/libSDL2_mixer.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1673): could not load library "libSDL2.so" needed by "libSDL2_mixer.so"; caused by find_library(linker.cpp:927): "libSDL2.so" failed to load previously
D/dalvikvm(29380): Trying to load lib /data/app-lib/org.electrum.electrum-1/libSDL2_ttf.so 0x42005488
E/dalvikvm(29380): dlopen("/data/app-lib/org.electrum.electrum-1/libSDL2_ttf.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1673): could not load library "libSDL2.so" needed by "libSDL2_ttf.so"; caused by find_library(linker.cpp:927): "libSDL2.so" failed to load previously
D/dalvikvm(29380): Trying to load lib /data/app-lib/org.electrum.electrum-1/libpython3.5m.so 0x42005488
E/dalvikvm(29380): dlopen("/data/app-lib/org.electrum.electrum-1/libpython3.5m.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1673): could not load library "libcrystax.so" needed by "libpython3.5m.so"; caused by load_library(linker.cpp:771): library "libcrystax.so" not found
W/System.err(29380): Could not load any libpythonXXX.so
W/dalvikvm(29380): No implementation found for native Lorg/libsdl/app/SDLActivity;.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
D/AndroidRuntime(29380): Shutting down VM
W/dalvikvm(29380): threadid=1: thread exiting with uncaught exception (group=0x41d99930)
E/AndroidRuntime(29380): FATAL EXCEPTION: main
E/AndroidRuntime(29380): java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
E/AndroidRuntime(29380): 	at org.libsdl.app.SDLActivity.nativeSetEnv(Native Method)
E/AndroidRuntime(29380): 	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:167)
E/AndroidRuntime(29380): 	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:114)
E/AndroidRuntime(29380): 	at android.os.AsyncTask.finish(AsyncTask.java:631)
E/AndroidRuntime(29380): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(29380): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
E/AndroidRuntime(29380): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29380): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(29380): 	at android.app.ActivityThread.main(ActivityThread.java:5227)
E/AndroidRuntime(29380): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29380): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(29380): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(29380): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime(29380): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2836):   Force finishing activity org.electrum.electrum/org.kivy.android.PythonActivity
W/ActivityManager( 2836): Activity pause timeout for ActivityRecord{420feea8 u0 org.electrum.electrum/org.kivy.android.PythonActivity}
I/Process (29380): Sending signal. PID: 29380 SIG: 9
I/ActivityManager( 2836): Process org.electrum.electrum (pid 29380) has died.
W/InputDispatcher( 2836): channel '4284eb68 org.electrum.electrum/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 2836): channel '4284eb68 org.electrum.electrum/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher( 2836): channel '4285b348 org.electrum.electrum/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 2836): channel '4285b348 org.electrum.electrum/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher( 2836): Attempted to unregister already unregistered input channel '4285b348 org.electrum.electrum/org.kivy.android.PythonActivity (server)'
I/WindowState( 2836): WIN DEATH: Window{4285b348 u0 org.electrum.electrum/org.kivy.android.PythonActivity}
W/InputDispatcher( 2836): Attempted to unregister already unregistered input channel '4284eb68 org.electrum.electrum/org.kivy.android.PythonActivity (server)'
I/WindowState( 2836): WIN DEATH: Window{4284eb68 u0 org.electrum.electrum/org.kivy.android.PythonActivity}
W/InputMethodManagerService( 2836): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4260a228 attribute=null, token = android.os.BinderProxy@422c34f0
```

**Comment by ecdsa** [comment]
did you save your seed?
if yes, please uninstall and reinstall the app, and report if that fixed it.

**Comment by dllud** [comment]
Uninstalling and installing from scratch does not fix the issue.

**Comment by rdymac** [comment]
@dllud were you able to fix this? There was a suggestion on Kivy github that seemed to have fixed this issue: https://github.com/kivy/python-for-android/issues/1188#issuecomment-406166073

**Comment by dllud** [comment]
I was not able to fix it. Meanwhile I've upgraded to Android 6.0 and I no longer face this issue. I have no Android 4.2 phone at hand to test it again.
Should this issue be closed?
