### ISSUE TITLE
linux / electrum 3.0 segfault: send when clicking QR code

### ISSUE THREAD

**Issue by hohokus** [spesmilo/electrum#3224]
debian stretch 9.2
electrum 3.0
send > click QR code causes immediate crash with "segmentation fault".

video device is set to default.  this is a VM, there is no actual video input device.

upgraded from existing 2.9.3 install using "sudo pip3 install https://download.electrum.org/3.0/Electrum-3.0.tar.gz"

dmesg says this when it crashes:
[709556.439475] electrum[27881]: segfault at 968 ip 00007fb3d45536ec sp 00007ffe62a2d790 error 4 in libX11.so.6.3.0[7fb3d4522000+13a000]

**Comment by minecraft2048** [comment]
Confirmed,  Arch Linux, electrum 3.0.1, send > click QR code crashes with segfault

[Nov 9 01:09] electrum[20285]: segfault at 968 ip 00007f1097cf1bac sp 00007ffe1fbf6190 error 4 in libX11.so.6.3.0[7f1097cc1000+139000]

**Comment by minecraft2048** [comment]
Following https://github.com/spesmilo/electrum/issues/3239 instructions for gdb I get this stack trace:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffeb2debac in XMapRaised () from /usr/lib/libX11.so.6
(gdb) bt
#0  0x00007fffeb2debac in XMapRaised () at /usr/lib/libX11.so.6
#1  0x00007fffd79128b6 in  () at /usr/lib/libzbar.so.0
#2  0x00007fffd78f979a in zbar_processor_set_visible () at /usr/lib/libzbar.so.0
#3  0x00007ffff3bf11c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#4  0x00007ffff3bf0c2a in ffi_call () at /usr/lib/libffi.so.6
#5  0x00007ffff3e6c33e in _ctypes_callproc () at /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#6  0x00007ffff3e6cd85 in  () at /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#7  0x00007ffff7407d85 in _PyObject_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#8  0x00007ffff73c91be in  () at /usr/lib/libpython3.6m.so.1.0
#9  0x00007ffff73aeb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#10 0x00007ffff73ac2b4 in  () at /usr/lib/libpython3.6m.so.1.0
#11 0x00007ffff73c8c4f in  () at /usr/lib/libpython3.6m.so.1.0
#12 0x00007ffff73c914e in  () at /usr/lib/libpython3.6m.so.1.0
#13 0x00007ffff73aeb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#14 0x00007ffff73c8a1b in  () at /usr/lib/libpython3.6m.so.1.0
#15 0x00007ffff73c914e in  () at /usr/lib/libpython3.6m.so.1.0
#16 0x00007ffff73aeb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#17 0x00007ffff73ac496 in  () at /usr/lib/libpython3.6m.so.1.0
#18 0x00007ffff73c85cc in _PyFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#19 0x00007ffff7407f5f in _PyObject_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#20 0x00007ffff7408cd3 in _PyObject_Call_Prepend () at /usr/lib/libpython3.6m.so.1.0
#21 0x00007ffff7408dbb in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#22 0x00007fffe76e7941 in  () at /usr/lib/python3.6/site-packages/PyQt5/QtCore.so
#23 0x00007fffe76e7e31 in  () at /usr/lib/python3.6/site-packages/PyQt5/QtCore.so
#24 0x00007fffe76e80c3 in  () at /usr/lib/python3.6/site-packages/PyQt5/QtCore.so
#25 0x00007fffe76e8a58 in  () at /usr/lib/python3.6/site-packages/PyQt5/QtCore.so
#26 0x00007fffeda2dce2 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#27 0x00007fffe6695ff3 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007fffe669620c in  () at /usr/lib/libQt5Widgets.so.5
#29 0x00007fffe669764c in  () at /usr/lib/libQt5Widgets.so.5
#30 0x00007fffe6697845 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#31 0x00007fffe677b3fb in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#32 0x00007fffe70667b4 in  () at /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#33 0x00007fffe65e0a08 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#34 0x00007fffe677b495 in QToolButton::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#35 0x00007fffe7067364 in  () at /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#36 0x00007fffe65a0f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#37 0x00007fffe65a8f81 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#38 0x00007fffe6e5b50f in  () at /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#39 0x00007fffed9fe060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#40 0x00007fffe65a7f0a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#41 0x00007fffe65fbd81 in  () at /usr/lib/libQt5Widgets.so.5
#42 0x00007fffe65fe4c1 in  () at /usr/lib/libQt5Widgets.so.5
#43 0x00007fffe65a0f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#44 0x00007fffe65a8a06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#45 0x00007fffe6e5b50f in  () at /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#46 0x00007fffed9fe060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#47 0x00007fffedf5d3d4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#48 0x00007fffedf5ef36 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#49 0x00007fffedf3648c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#50 0x00007fffa4c2f4b1 in  () at /usr/lib/libQt5XcbQpa.so.5
---Type <return> to continue, or q <return> to quit---
#51 0x00007fffeb88a270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#52 0x00007fffeb88bf69 in  () at /usr/lib/libglib-2.0.so.0
#53 0x00007fffeb88bfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#54 0x00007fffeda58cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#55 0x00007fffed9fc48b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#56 0x00007fffeda054d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#57 0x00007fffe6e5a05d in  () at /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#58 0x00007ffff7419af0 in _PyCFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#59 0x00007ffff73c908b in  () at /usr/lib/libpython3.6m.so.1.0
#60 0x00007ffff73aeb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#61 0x00007ffff73ac682 in  () at /usr/lib/libpython3.6m.so.1.0
#62 0x00007ffff73c8c4f in  () at /usr/lib/libpython3.6m.so.1.0
#63 0x00007ffff73c914e in  () at /usr/lib/libpython3.6m.so.1.0
#64 0x00007ffff73aeb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#65 0x00007ffff73c8a1b in  () at /usr/lib/libpython3.6m.so.1.0
#66 0x00007ffff73c914e in  () at /usr/lib/libpython3.6m.so.1.0
#67 0x00007ffff73aeb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#68 0x00007ffff73ad1d8 in PyEval_EvalCodeEx () at /usr/lib/libpython3.6m.so.1.0
#69 0x00007ffff73ae06c in PyEval_EvalCode () at /usr/lib/libpython3.6m.so.1.0
#70 0x00007ffff748f2d4 in  () at /usr/lib/libpython3.6m.so.1.0
#71 0x00007ffff7491cc1 in PyRun_FileExFlags () at /usr/lib/libpython3.6m.so.1.0
#72 0x00007ffff7491ec4 in PyRun_SimpleFileExFlags () at /usr/lib/libpython3.6m.so.1.0
#73 0x00007ffff748e160 in Py_Main () at /usr/lib/libpython3.6m.so.1.0
#74 0x0000555555554c39 in main ()
(gdb) 
```

**Comment by Raulo** [comment]
No bug in Ubuntu 16.04. QR reading works fine.

**Comment by SuBPaR42** [comment]
Manjaro 17.0.6 and Git HEAD - same core dump when clicking QR code (on send tab).

**Comment by edescourtis** [comment]
Same issue here

**Comment by SomberNight** [comment]
Should be fixed by https://github.com/spesmilo/electrum/pull/3546
