### ISSUE TITLE
Electrum crashes on bad localization message

### ISSUE THREAD

**Issue by pokazef** [spesmilo/electrum#3237]
When a localization message omits a substitution variable, Electrum crashes.

For example, in the FR locale, "Connected to %d nodes" was translated to "Connecté aux noeuds".
In this case, upon opening the network dialog, Electrum 3.0.1 terminates with this trace:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/main_window.py", line 85, in onPress
        self.func()
      File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/main_window.py", line 1761, in <lambda>  
        self.status_button = StatusBarButton(QIcon(":icons/status_disconnected.png"), _("Network"), lambda: self.gui_object.show_network_dialog(self))
      File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/__init__.py", line 169, in show_network_dialog
        self.network_updated_signal_obj)
      File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/network_dialog.py", line 47, in __init__ 
        self.nlayout = NetworkChoiceLayout(network, config)
      File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/network_dialog.py", line 322, in __init__
        self.update()
      File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/network_dialog.py", line 358, in update  
        status = _("Connected to %d nodes.")%n if n else _("Not connected")
    TypeError: not all arguments converted during string formatting

Obviously, the right fix here is to correct the localized message, but could there be a way to make this kind of error non fatal?

**Comment by SomberNight** [comment]
I am wondering if this could be fixed in a generic way by somehow modifying the method "doing the translation"

https://github.com/spesmilo/electrum/blob/d599f11cceb0b74d092befff019097d0f0d3f2ac/lib/i18n.py#L35-L37

such that it would (for example) compare if `x` and `language.gettext(x)` are "compatible" format strings and if they aren't, return `x`.

**Comment by maxit77** [comment]
Thanks. I solved momentarily the problem by switching to english language.

**Comment by ecdsa** [comment]
closing this. I will fix other occurences as they are found. 
(I don't think we can fix it in a generic way, at least not easily)

**Comment by pokazef** [comment]
> maybe we should replace all occurences of % with string.format()

Right, Python seems to simply ignore missing replacement fields with the new string formatting API. That should work, thanks :)
