### ISSUE TITLE
On Tails 3.2, Electrum 3.0.1 segmentation fault opening QRcode scanner, OK on Linux Ubuntu 16.04.

### ISSUE THREAD

**Issue by JazzTp** [spesmilo/electrum#3239]
On Tails 3.2, Electrum 3.0.1 segmentation fault opening QRcode scanner, while it opens fine on Linux Ubuntu 16.04.

Related issue: #2527

**Comment by ysangkok** [comment]
A stack trace would be useful. If the Python interpreter is crashing, start GDB using `gdb $(which python3)` and write `run <path of the electrum script>`. Electrum should start, you can reproduce the crash and after the crash you can write `bt` to get a stack trace.

**Comment by JazzTp** [comment]
```bash: gdb: command not found```

((( I use to boot from DVD, no idea how to install stuff on Tails. Actually I chose to switch to Ubuntu Linux for the watching only part to avoid the webcam problem. I have the cold storage running on an Older Tails 2.12 where there's no webcam problem, and BTW I haven't tested so far if Electrum 3.0.1 based on python 3 can run on it [using the wallet very seldom admittedly]. )))

**Comment by yairEO** [comment]
On Puppy Linux I get this also

**Comment by JazzTp** [comment]
Same thing with Electrum 3.0.2 on Tails 3.3 (released 2017-11-14).

**Comment by jeffersoncarpenter** [comment]
Is this the same issue as #3224?

**Comment by JazzTp** [comment]
If "clicking QR code" means opening the QR code scanner, apparently it
would be the same issue.

I got there by "tools | load transaction | from QR code".

**Comment by potato20** [comment]
I'm getting this too. I'm using pyenv with python 3.6.3. Here's the backtrace in gdb

```
#0  0x00007fffbc4620dc in XUnmapWindow () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007fffeabdebc4 in ?? () from /usr/lib/x86_64-linux-gnu/libzbar.so.0
#2  0x00007fffeabbcac6 in zbar_processor_set_visible () from /usr/lib/x86_64-linux-gnu/libzbar.so.0
#3  0x00007ffff4234e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#4  0x00007ffff42348ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#5  0x00007ffff4448bff in _call_function_pointer (argcount=1, resmem=0x7fffffffa9a0, restype=<optimized out>, atypes=<optimized out>,  avalues=0x7fffffffa980, pProc=0x7fffeabbca29 <zbar_processor_set_visible>, flags=4353) at /tmp/python-build.20171208165912.16048/Python-3.6.3/Modules/_ctypes/callproc.c:809
#6  _ctypes_callproc (pProc=pProc@entry=0x7fffeabbca29 <zbar_processor_set_visible>, argtuple=argtuple@entry=0x7fffeb791898, flags=4353,  argtypes=argtypes@entry=0x0, restype=0xaf1918, checker=0x0) at /tmp/python-build.20171208165912.16048/Python-3.6.3/Modules/_ctypes/callproc.c:1147
#7  0x00007ffff443fbe9 in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=<optimized out>) at /tmp/python-build.20171208165912.16048/Python-3.6.3/Modules/_ctypes/_ctypes.c:3935
#8  0x0000000000453192 in _PyObject_FastCallDict (func=0x7fffeb5b0110, args=0x7fffeb7a1fd0, nargs=1, kwargs=0x0) at Objects/abstract.c:2331
#9  0x0000000000540268 in call_function (pp_stack=pp_stack@entry=0x7fffffffac90, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4848
#10 0x000000000054251d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#11 0x0000000000540105 in PyEval_EvalFrameEx (throwflag=0, f=0x7fffeb7a1e10) at Python/ceval.c:753
#12 _PyEval_EvalCodeWithName (_co=0x7fffeb799540, globals=globals@entry=0x7fffeb7bb120, locals=locals@entry=0x0, args=<optimized out>, argcount=1,  kwnames=kwnames@entry=0x0, kwargs=0x1921078, kwcount=0, kwstep=1, defs=0x7fffeb784ce0, defcount=4, kwdefs=0x0, closure=0x0, name=0x7ffff00b05b0,  qualname=0x7ffff00b05b0) at Python/ceval.c:4153
#13 0x00000000005403b7 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7fffeb79fd90) at Python/ceval.c:4965
#14 call_function (pp_stack=pp_stack@entry=0x7fffffffaef0, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#15 0x000000000054251d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#16 0x000000000053f761 in PyEval_EvalFrameEx (throwflag=0, f=0x1920ec8) at Python/ceval.c:753
#17 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=globals@entry=0x7ffff007f6c0) at Python/ceval.c:4906
#18 0x0000000000540611 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7ffff0099158) at Python/ceval.c:4941
#19 call_function (pp_stack=pp_stack@entry=0x7fffffffb0a0, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#20 0x000000000054251d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#21 0x0000000000540105 in PyEval_EvalFrameEx (throwflag=0, f=0x7fffeb5a6d68) at Python/ceval.c:753
#22 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffeb7cbae0, globals=globals@entry=0x7fffeb7c91f8, locals=locals@entry=0x0,  args=args@entry=0x7fffffffb300, argcount=argcount@entry=1, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0,  kwdefs=0x0, closure=0x7fffeb7c8c50, name=0x7ffff003b130, qualname=0x7fffeb7c9a50) at Python/ceval.c:4153
#23 0x00000000005490d6 in _PyFunction_FastCallDict (func=func@entry=0x7fffeb7cc730, args=args@entry=0x7fffffffb300, nargs=nargs@entry=1, 
#24 0x00000000004532d0 in _PyObject_FastCallDict (func=0x7fffeb7cc730, args=0x7fffffffb300, nargs=1, kwargs=0x0) at Objects/abstract.c:2310
#25 0x00000000004533ca in _PyObject_Call_Prepend (func=0x7fffeb7cc730, obj=<optimized out>, args=0x7ffff7f76048, kwargs=0x0) at Objects/abstract.c:2373
#26 0x0000000000452fac in PyObject_Call (func=0x7ffff4ea4588, args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2261
#27 0x00007fffb6a53ea5 in PyQtSlot::call(_object*, _object*) const () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtCore.so
#28 0x00007fffb6a543b0 in PyQtSlot::invoke(void**, _object*, void*, bool) const () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtCore.so
#29 0x00007fffb6a5462b in PyQtSlotProxy::unislot(void**) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtCore.so
#30 0x00007fffb6a55407 in PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtCore.so
#31 0x00007fffd13b2f8c in QMetaObject::activate(QObject*, int, int, void**) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#32 0x00007fffb5b8e7a2 in QAbstractButton::clicked(bool) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#33 0x00007fffb5b8e9b4 in ?? () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#34 0x00007fffb5b8fcb2 in ?? () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#35 0x00007fffb5b8fe5c in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#36 0x00007fffb5c5ffaa in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#37 0x00007fffb644f223 in sipQToolButton::mouseReleaseEvent(QMouseEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#38 0x00007fffb5ad7d98 in QWidget::event(QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#39 0x00007fffb5c60079 in QToolButton::event(QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#40 0x00007fffb644f8e3 in sipQToolButton::event(QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#41 0x00007fffb5a9b5bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#42 0x00007fffb5aa3638 in QApplication::notify(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#43 0x00007fffb64e724e in sipQApplication::notify(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#44 0x00007fffd1387a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#45 0x00007fffb5aa1ead in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#46 0x00007fffb5af144e in ?? () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#47 0x00007fffb5af3d3b in ?? () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#48 0x00007fffb5a9b5bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#49 0x00007fffb5aa28c1 in QApplication::notify(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#50 0x00007fffb64e724e in sipQApplication::notify(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#51 0x00007fffd1387a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#52 0x00007fffd1947133 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#53 0x00007fffd1948bb5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#54 0x00007fffd19247bb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#55 0x00007fffb549de60 in ?? () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#56 0x00007fffd02b2197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007fffd02b23f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#58 0x00007fffd02b249c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007fffd13db36f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#60 0x00007fffd138605a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#61 0x00007fffd138e964 in QCoreApplication::exec() () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#62 0x00007fffb6372be0 in meth_QApplication_exec_ () from /home/boatymcboatface/.pyenv/versions/3.6.3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#63 0x00000000004aee79 in _PyCFunction_FastCallDict (kwargs=0x0, nargs=<optimized out>, args=0xfc7718, func_obj=0x7ffff01845e8) at Objects/methodobject.c:234
#64 _PyCFunction_FastCallKeywords (func=func@entry=0x7ffff01845e8, stack=stack@entry=0xfc7718, nargs=<optimized out>, kwnames=kwnames@entry=0x0) at Objects/methodobject.c:294
#65 0x000000000054049e in call_function (pp_stack=pp_stack@entry=0x7fffffffc510, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4824
#66 0x000000000054251d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#67 0x0000000000540105 in PyEval_EvalFrameEx (throwflag=0, f=0xfc7578) at Python/ceval.c:753
#68 _PyEval_EvalCodeWithName (_co=0x7ffff0209030, globals=globals@entry=0x7ffff01fb1f8, locals=locals@entry=0x0, args=<optimized out>, argcount=1,  kwnames=kwnames@entry=0x0, kwargs=0xebfd50, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7ffff7e79030,  qualname=0x7ffff01fbe40) at Python/ceval.c:4153
#69 0x00000000005403b7 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7ffff3091510) at Python/ceval.c:4965
#70 call_function (pp_stack=pp_stack@entry=0x7fffffffc770, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#71 0x000000000054251d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#72 0x000000000053f761 in PyEval_EvalFrameEx (throwflag=0, f=0xebfba8) at Python/ceval.c:753
#73 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=3, globals=globals@entry=0x7ffff0d67a68) at Python/ceval.c:4906
#74 0x0000000000540611 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7ffff0cf2620) at Python/ceval.c:4941
#75 call_function (pp_stack=pp_stack@entry=0x7fffffffc920, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#76 0x000000000054251d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#77 0x0000000000540105 in PyEval_EvalFrameEx (throwflag=0, f=0x954068) at Python/ceval.c:753
#78 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff6dcbe40, globals=globals@entry=0x7ffff7f48198, locals=locals@entry=0x7ffff6dcbe40,  args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0,  closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4153
#79 0x0000000000540f93 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0,  locals=locals@entry=0x7ffff6dcbe40, globals=globals@entry=0x7ffff7f48198, _co=_co@entry=0x7ffff6dcbe40) at Python/ceval.c:4174
#80 PyEval_EvalCode (co=co@entry=0x7ffff6dcbe40, globals=globals@entry=0x7ffff7f2e3a8, locals=locals@entry=0x7ffff7f2e3a8) at Python/ceval.c:730
#81 0x000000000042762f in run_mod (arena=0x7ffff7f48198, flags=0x7fffffffcc00, locals=0x7ffff7f2e3a8, globals=0x7ffff7f2e3a8,  filename=0x7ffff6dc01b0, mod=0x9c0120) at Python/pythonrun.c:980
#82 PyRun_FileExFlags (fp=0x98e490, filename_str=<optimized out>, start=<optimized out>, globals=0x7ffff7f2e3a8, locals=0x7ffff7f2e3a8, closeit=1,  flags=0x7fffffffcc00) at Python/pythonrun.c:933
#83 0x000000000042785c in PyRun_SimpleFileExFlags (fp=0x98e490, filename=<optimized out>, closeit=1, flags=0x7fffffffcc00) at Python/pythonrun.c:396
#84 0x000000000043bc25 in run_file (p_cf=0x7fffffffcc00, filename=0x8fd220 L"/home/boatymcboatface/.pyenv/versions/3.6.3/bin/electrum", fp=0x98e490) at Modules/main.c:338
#85 Py_Main (argc=argc@entry=2, argv=argv@entry=0x8fb010) at Modules/main.c:809
#86 0x000000000041dd72 in main (argc=2, argv=<optimized out>) at ./Programs/python.c:69
```
