### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by steve-vincent** [spesmilo/electrum#3261]
I've installed(upgrade to) Electrum 3.0.1 on Linux Mint

Getting this upon launch (with 'python3 electrum'):

Traceback (most recent call last):
  File "electrum", line 80, in <module>
    check_imports()
  File "electrum", line 72, in check_imports
    from google.protobuf import reflection
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

**Comment by ecdsa** [comment]
this is a python2 syntax.
you should check why Linux Mint installed python2 libraries in your python3 path
