### ISSUE TITLE
ImportError: No module named 'xmlrpclib' on Windows PYTHON 3.5

### ISSUE THREAD

**Issue by miranos** [spesmilo/electrum#3301]
Hi,

I compiled Electrum 3.0.1 and everything was fine, but when i try to launch the generate EXE file, i receive this error message:

```
Traceback (most recent call last):
  File "electrum", line 70, in check_imports
  File "c:\python35\lib\site-packages\Py
Installer\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\jsonrpclib\__init__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\Py
Installer\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\jsonrpclib\jsonrpc.py", line 50, in <module>
ImportError: No module named 'xmlrpclib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electrum", line 86, in <module>
  File "electrum", line 72, in check_imports
AttributeError: 'ImportError' object has no attribute 'message'
[4352] Failed to execute script electrum
```

**I am using:**
Python 3.5.0
PyQT4
Pywin32 211
Pyinstaller 3.3

Please help to solve this issue.

**Comment by miranos** [comment]
**Just for note:**

I tried too with other version:
Python 3.4.4

I receive same error.

**Comment by ecdsa** [comment]
do not use jsonrpclib, but the library listed in setup.py (pelix)
