### ISSUE TITLE
Failed to compile Electrum under Windows

### ISSUE THREAD

**Issue by miranos** [spesmilo/electrum#3303]
Hi,

I spend all this day to find a way to compile it, but everytime i get errors.

Here my last one:

```
Traceback (most recent call last):
  File "electrum", line 371, in <module>
  File "site-packages\electrum-3.0-py3.4.egg\electrum\daemon.py", line 291, in i
nit_gui
  File "site-packages\electrum-3.0-py3.4.egg\electrum_gui\qt\__init__.py", line
223, in main
  File "site-packages\electrum-3.0-py3.4.egg\electrum_gui\qt\__init__.py", line
174, in start_new_window
  File "site-packages\electrum-3.0-py3.4.egg\electrum\daemon.py", line 228, in l
oad_wallet
  File "site-packages\electrum-3.0-py3.4.egg\electrum\wallet.py", line 1787, in
__new__
  File "site-packages\electrum-3.0-py3.4.egg\electrum\wallet.py", line 1344, in
__init__
  File "site-packages\electrum-3.0-py3.4.egg\electrum\wallet.py", line 124, in _
_init__
  File "site-packages\electrum-3.0-py3.4.egg\electrum\util.py", line 209, in <la
mbda>
  File "site-packages\electrum-3.0-py3.4.egg\electrum\util.py", line 205, in do_
profile
  File "site-packages\electrum-3.0-py3.4.egg\electrum\wallet.py", line 197, in c
heck_history
  File "site-packages\electrum-3.0-py3.4.egg\electrum\wallet.py", line 197, in <
lambda>
  File "site-packages\electrum-3.0-py3.4.egg\electrum\wallet.py", line 257, in i
s_mine
TypeError: unhashable type: 'list'
Failed to execute script electrum
```

**I am using:** 
Python 3.4
Electrum: 3.0.0
Pyinstaller: 3.2.1

Please help.

**Comment by ecdsa** [comment]
we dont compile it under windows, but under  linux+wine
see in contribs

**Comment by SomberNight** [comment]
Are you trying to build binaries, or just run Electrum from source?
To build the binaries, as above, see `contrib/build-wine/` (in the repository).

**Comment by bauerj** [comment]
If you are on Windows, you should update to a more recent version of Python, e.g. 3.6.

**Comment by miranos** [comment]
I am trying to build a binary, i followed all the steps from contrib/build-wine/ but all time i get this errors.

Version 3.6 will work ?

What version of pyinstaller will i use too ?

**Comment by SomberNight** [comment]
The content of the bash scripts in `contrib/build-wine/` should answer that question.

Note that the contents of that folder are under "rapid development" :P
Specifically, if you are looking at master, there is a step missing between step2 and step3:
```
./prepare-pyinstaller.sh
```

**Comment by miranos** [comment]
I already seen that.
Installed all the dependencies but still get that error.

I used previous version under Python 2.7 and worked well.

**Comment by SomberNight** [comment]
Ok, well, I don't understand the problem. Could you please describe what you are doing?
E.g. what did you do to get the trace in the OP?

**Comment by miranos** [comment]
So, the file is generated and built well.

But when i launch it, i get that error.

**Comment by miranos** [comment]
I used tha latest version and here the new error message when compiling:

**11175 INFO: Warnings written to c:\electrum\contrib\build-wine\build\determinist
ic\warndeterministic.txt
11286 INFO: Graph cross-reference written to c:\electrum\contrib\build-wine\buil
d\deterministic\xref-deterministic.html
11304 INFO: Appending 'datas' from .spec
Unable to find "C:\electrum\lib\locale" when adding binary and data files.**
