### ISSUE TITLE
Ledger with PIN not unlocked - not handled properly

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3304]
On git master ff0cd16aec48aa052d2381742e98c7e574c02fff.

Using a Ledger Nano S, with Bitcoin app 1.1.10, secure element 1.3.1, MCU 1.1.
btchip-python 0.1.23

Connect the Ledger to the computer, unlock with the PIN, enter the Bitcoin app, and let it time out, so that the "vires in numeris" text appears on the screen of the Ledger.
Now start Electrum:

```
$ ./electrum -v --testnet --offline
[SimpleConfig] electrum directory /home/user/.electrum/testnet
[get_server] [Errno 111] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0034
[WalletStorage] wallet path /home/user/.electrum/testnet/wallets/test_ledger_testing1_std
[Plugins] loaded ledger
[profiler] load_transactions 0.0000
[profiler] build_reverse_history 0.0000
[profiler] save_transactions 0.0001
[profiler] check_history 0.0001
[profiler] on_update 0.0001
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
=> b'e0c4000000'
<= b'1b3001010a010003'9000
=> b'f026000000'
<= b''6d00
[DeviceMgr] Registering <electrum_plugins.ledger.ledger.Ledger_Client object at 0x7f5ff8913cf8>
=> b'e0c4000000'
<= b'1b3001010a010003'9000
=> b'e024000000'
<= b'01'9000
=> b'e02280000130'
<= b''6d00
=> b'e040000009028000002c80000001'
<= b''6982
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 579, in run
    result = task.task()
  File "/home/user/wspace/electrum/plugins/ledger/ledger.py", line 497, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/home/user/wspace/electrum/lib/plugins.py", line 404, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/home/user/wspace/electrum/lib/plugins.py", line 434, in force_pair_xpub
    client_xpub = client.get_xpub(derivation, xtype)
  File "/home/user/wspace/electrum/plugins/ledger/ledger.py", line 70, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "/home/user/.local/lib/python3.5/site-packages/btchip/btchip.py", line 124, in getWalletPublicKey
    response = self.dongle.exchange(bytearray(apdu))
  File "/home/user/.local/lib/python3.5/site-packages/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
btchip.btchipException.BTChipException: Exception : Invalid status 6982
[profiler] on_update 0.0001
```

![ledger_locked_pin_6982](https://user-images.githubusercontent.com/29142493/32795148-272b5530-c96b-11e7-9476-1a9e49712a40.png)

https://github.com/LedgerHQ/blue-app-btc/blob/7266eed8821d474c06e936fe37cc952876ff5582/include/btchip_apdu_constants.h#L88

The `0x6982` error code is for `BTCHIP_SW_SECURITY_STATUS_NOT_SATISFIED`.

**Comment by ecdsa** [comment]
looks related to #2595 ?

**Comment by adrelanos** [comment]
Would be cool if this could get a better error message. "Ledger has time out. Please re-enter pin on device." or so.
