### ISSUE TITLE
Electrum 3.0.2 crashes on attempt to "Verify GA instant"

### ISSUE THREAD

**Issue by MikalaiR** [spesmilo/electrum#3305]
OS: Win 10.
This issue reproduces also in 3.0.1 and 3.0. Older versions i couldn't check.

**Comment by SomberNight** [comment]
I've tested with a tx that is "not covered by GreenAddress instant confirmation", and encountered no problems, on master.

Is your tx "covered" by GA instant confirmation?

Any chance you have access to a linux machine -- it would be easy to extract logs there (start Electrum with the `-v` flag)?

**Comment by MikalaiR** [comment]
No, tx isn't covered by GreenAddress instant.
I've used Visual Studio for debugging and got a strange traceback
```Traceback (most recent call last):
  File "C:\Program Files (x86)\Electrum\electrum_plugins\greenaddress_instant\qt.py", line 45, in <lambda>
    d.verify_button.clicked.connect(lambda: self.do_verify(d))
  File "C:\Program Files (x86)\Electrum\electrum_plugins\greenaddress_instant\qt.py", line 75, in do_verify
    password = window.password_dialog(msg, parent=d)
AttributeError: 'builtin_function_or_method' object has no attribute 'password_dialog'
Unhandled exception at 0x752F543B (ucrtbase.dll) in electrum-3.0.2.exe: Fatal program exit requested.```

**Comment by SomberNight** [comment]
Thanks.
