### ISSUE TITLE
Getting private key in testnet mode causes crash

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#3306]
On OSX, right click on an address and choose "Private key." Electrum 3.0.2 crashes with the following trace:

```
/Applications/Electrum.app/Contents/MacOS/Electrum --testnet
Traceback (most recent call last):
  File "Electrum-3.0.2-py3.6.egg/electrum_gui/qt/address_list.py", line 144, in <lambda>
  File "Electrum-3.0.2-py3.6.egg/electrum_gui/qt/main_window.py", line 1277, in request_password
  File "Electrum-3.0.2-py3.6.egg/electrum_gui/qt/main_window.py", line 1899, in show_private_key
  File "Electrum-3.0.2-py3.6.egg/electrum/wallet.py", line 269, in export_private_key
  File "Electrum-3.0.2-py3.6.egg/electrum/keystore.py", line 323, in get_private_key
  File "Electrum-3.0.2-py3.6.egg/electrum/bitcoin.py", line 932, in deserialize_xprv
  File "Electrum-3.0.2-py3.6.egg/electrum/bitcoin.py", line 921, in deserialize_xkey
BaseException: ('Invalid xpub format', '0x4358394')
Abort trap: 6
```

**Comment by AbdussamadA** [comment]
not seeing this on linux

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/issues/3169#issuecomment-341217798

"tpub" and "tprv" prefixes are now deprecated in the project. Restore the wallet from seed.

**Comment by rapodaca** [comment]
@SomberNight that solves the problem, thanks.
