### ISSUE TITLE
Testnet does not work with 3.0.x Windows binaries

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3321]
As in title, 3.0.x Windows binaries don't work with the `--testnet` option.

![electrum3_testnet_win_binaries](https://user-images.githubusercontent.com/29142493/32959467-ff7da6c4-cbc1-11e7-82cc-869e7d15c1f9.png)

Verbose log with custom built binary: (so that the `-v` option works)
```
C:\Users\User\Desktop>"electrum-3.0.2-4-gc48efc5f.exe" -v --testnet
[SimpleConfig] electrum directory C:\Users\User\AppData\Roaming\Electrum\testnet
[get_server] unexpected EOF while parsing (<unknown>, line 0)
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0153
[Network] blockchains dict_keys([0])
Traceback (most recent call last):
  File "electrum", line 371, in <module>
  File "site-packages\electrum-3.0.2-py3.5.egg\electrum\daemon.py", line 112, in __init__
  File "site-packages\electrum-3.0.2-py3.5.egg\electrum\network.py", line 221, in __init__
  File "site-packages\electrum-3.0.2-py3.5.egg\electrum\network.py", line 140, in deserialize_server
ValueError: not enough values to unpack (expected 3, got 1)
[3996] Failed to execute script electrum
[Plugins] stopped
```

**Comment by NicolasDorier** [comment]
Any ETA for 3.0.3 fixing this issue?

**Comment by ecdsa** [comment]
3.0.3 is out
