### ISSUE TITLE
Electrum 3.0.2-1 won't start with python-protobuf 3.4.1 / Linux 

### ISSUE THREAD

**Issue by biolypl** [spesmilo/electrum#3389]
I got errors below when trying to run Electrum:
```
Traceback (most recent call last):
  File "/usr/bin/electrum", line 80, in <module>
    check_imports()
  File "/usr/bin/electrum", line 73, in check_imports
    from google.protobuf import descriptor_pb2
  File "/usr/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 409, in <module>
    options=None),
  File "/usr/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"
```
Downgrade to 3.4.0 solves this issue but I don't think its long-term solution

**Comment by ecdsa** [comment]
the problem is not with electrum
