### ISSUE TITLE
Wizard crashes when starting from new seed

### ISSUE THREAD

**Issue by geoffrey-vl** [spesmilo/electrum#3405]
Error in Version 3.0.2 (it was not broken in 3.0.1)

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 373, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.5/dist-packages/electrum/daemon.py", line 284, in init_gui
    self.gui.main()
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/__init__.py", line 248, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/__init__.py", line 199, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 272, in run_and_get_wallet
    self.run(action)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 87, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 105, in on_wallet_type
    self.run(action)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 137, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 391, in choose_seed_type
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 393, in create_segwit_seed
    def create_segwit_seed(self): self.create_seed('segwit')
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 402, in create_seed
    self.show_seed_dialog(run_next=f, seed_text=seed)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 81, in func_wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 382, in show_seed_dialog
    slayout = SeedLayout(seed=seed_text, title=title, msg=True, options=['ext'])
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/seed_dialog.py", line 132, in __init__
    self.seed_warning.setText(seed_warning_msg(seed))
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/seed_dialog.py", line 48, in seed_warning_msg
    ]) % len(seed.split())
TypeError: not all arguments converted during string formatting

**Comment by SomberNight** [comment]
What is your system locale / language?

**Comment by geoffrey-vl** [comment]
LANG=nl_BE.UTF-8
LANGUAGE=nl_BE:nl
LC_CTYPE="nl_BE.UTF-8"
LC_NUMERIC="nl_BE.UTF-8"
LC_TIME="nl_BE.UTF-8"
LC_COLLATE="nl_BE.UTF-8"
LC_MONETARY="nl_BE.UTF-8"
LC_MESSAGES="nl_BE.UTF-8"
LC_PAPER="nl_BE.UTF-8"
LC_NAME="nl_BE.UTF-8"
LC_ADDRESS="nl_BE.UTF-8"
LC_TELEPHONE="nl_BE.UTF-8"
LC_MEASUREMENT="nl_BE.UTF-8"
LC_IDENTIFICATION="nl_BE.UTF-8"
LC_ALL=

**Comment by SomberNight** [comment]
I think this is the same underlying problem as in https://github.com/spesmilo/electrum/issues/3237

In the `nl_NL` locale file (which I'm guessing gets used in your case), I have:
```
#: gui/qt/seed_dialog.py:37
#, python-format
msgid "Please save these %d words on paper (order is important). "
msgstr "Gelieve deze woorden op papier te bewaren (volgorde is belangrijk)."
```
Note the missing `%d`.

https://github.com/spesmilo/electrum/blob/8b66d7c8ae0e0df84c7f02dc624def69dbbd78aa/gui/qt/seed_dialog.py#L35-L48

**Comment by geoffrey-vl** [comment]
Exactly!

**Comment by ecdsa** [comment]
@SomberNight thanks for finding that

**Comment by danger89** [comment]
Yep same problem. It just crashed.

Is this not yet solved, no commit or pull request created!?

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 373, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.5/dist-packages/electrum/daemon.py", line 284, in init_gui
    self.gui.main()
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/__init__.py", line 248, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/__init__.py", line 199, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 272, in run_and_get_wallet
    self.run(action)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 87, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 105, in on_wallet_type
    self.run(action)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 113, in choose_multisig
    self.multisig_dialog(run_next=on_multisig)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 112, in on_multisig
    self.run('choose_keystore')
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 137, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 83, in func_wrapper
    wizard.go_back() if wizard.can_go_back() else wizard.close()
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 72, in go_back
    self.run(action, *args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 113, in choose_multisig
    self.multisig_dialog(run_next=on_multisig)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 83, in func_wrapper
    wizard.go_back() if wizard.can_go_back() else wizard.close()
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 72, in go_back
    self.run(action, *args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 87, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 105, in on_wallet_type
    self.run(action)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 113, in choose_multisig
    self.multisig_dialog(run_next=on_multisig)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 112, in on_multisig
    self.run('choose_keystore')
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 137, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 391, in choose_seed_type
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 60, in run
    f(*args)
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 394, in create_standard_seed
    def create_standard_seed(self): self.create_seed('standard')
  File "/usr/local/lib/python3.5/dist-packages/electrum/base_wizard.py", line 402, in create_seed
    self.show_seed_dialog(run_next=f, seed_text=seed)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 81, in func_wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/installwizard.py", line 382, in show_seed_dialog
    slayout = SeedLayout(seed=seed_text, title=title, msg=True, options=['ext'])
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/seed_dialog.py", line 132, in __init__
    self.seed_warning.setText(seed_warning_msg(seed))
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/seed_dialog.py", line 48, in seed_warning_msg
    ]) % len(seed.split())
TypeError: not all arguments converted during string formatting
```

**Comment by SomberNight** [comment]
@danger89 This is non-trivial to solve properly. If you think otherwise, please create a PR.

The immediate cause is a badly "formatted" translation string. That string is outside this repository, so it has nothing to do with commits or PRs. It might already be fixed on crowdin, but the new string will only be present in a new release.

**Comment by danger89** [comment]
@SomberNight OK I see. I will fix in on crowdin (if this is the correct place):
https://crowdin.com/translate/electrum/68/en-nl#q=lease+save+these

**Comment by danger89** [comment]
Currently waiting to get this approved..
