### ISSUE TITLE
Application closes by accepting blank Terms of Service of a incompletely created wallet

### ISSUE THREAD

**Issue by ghjansen** [spesmilo/electrum#3438]
**Symptoms**: I created an encrypted wallet with 2FA using an offline computer. By resuming the process in a online computer, there is no content in the `Terms of Service` screen, also by informing my email address and clicking the `Accept` button, the application just closes.

**Environment**: macOS Sierra Version 10.12.6 and Electrum 3.0.2

**Logs**: 
```
$ ./Electrum.app/Contents/MacOS/Electrum 
Exception in thread Thread-19:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "/var/folders/2x/zhzhffjn62d2j0zyxh3qrmfh0000gn/T/_MEIh20MRj/electrum_plugins/trustedcoin/qt.py", line 208, in request_TOS
    tos = server.get_terms_of_service()
  File "/var/folders/2x/zhzhffjn62d2j0zyxh3qrmfh0000gn/T/_MEIh20MRj/electrum_plugins/trustedcoin/trustedcoin.py", line 113, in get_terms_of_service
    return self.send_request('get', 'tos', payload)
  File "/var/folders/2x/zhzhffjn62d2j0zyxh3qrmfh0000gn/T/_MEIh20MRj/electrum_plugins/trustedcoin/trustedcoin.py", line 92, in send_request
    response = requests.request(method, url, **kwargs)
  File "requests-2.18.4-py3.6.egg/requests/api.py", line 58, in request
  File "requests-2.18.4-py3.6.egg/requests/sessions.py", line 499, in request
  File "requests-2.18.4-py3.6.egg/requests/sessions.py", line 672, in merge_environment_settings
  File "requests-2.18.4-py3.6.egg/requests/utils.py", line 692, in get_environ_proxies
  File "requests-2.18.4-py3.6.egg/requests/utils.py", line 676, in should_bypass_proxies
  File "urllib/request.py", line 2612, in proxy_bypass
  File "urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
  File "urllib/request.py", line 2575, in _proxy_bypass_macosx_sysconf
ValueError: negative shift count

Traceback (most recent call last):
  File "electrum", line 373, in <module>
  File "Electrum-3.0.2-py3.6.egg/electrum/daemon.py", line 284, in init_gui
  File "Electrum-3.0.2-py3.6.egg/electrum_gui/qt/__init__.py", line 248, in main
  File "Electrum-3.0.2-py3.6.egg/electrum_gui/qt/__init__.py", line 199, in start_new_window
  File "Electrum-3.0.2-py3.6.egg/electrum_gui/qt/installwizard.py", line 272, in run_and_get_wallet
  File "Electrum-3.0.2-py3.6.egg/electrum/base_wizard.py", line 57, in run
  File "/var/folders/2x/zhzhffjn62d2j0zyxh3qrmfh0000gn/T/_MEIh20MRj/electrum_plugins/trustedcoin/trustedcoin.py", line 498, in create_remote_key
    r = server.create(xpub1, xpub2, email)
  File "/var/folders/2x/zhzhffjn62d2j0zyxh3qrmfh0000gn/T/_MEIh20MRj/electrum_plugins/trustedcoin/trustedcoin.py", line 129, in create
    return self.send_request('post', 'cosigner', payload)
  File "/var/folders/2x/zhzhffjn62d2j0zyxh3qrmfh0000gn/T/_MEIh20MRj/electrum_plugins/trustedcoin/trustedcoin.py", line 92, in send_request
    response = requests.request(method, url, **kwargs)
  File "requests-2.18.4-py3.6.egg/requests/api.py", line 58, in request
  File "requests-2.18.4-py3.6.egg/requests/sessions.py", line 499, in request
  File "requests-2.18.4-py3.6.egg/requests/sessions.py", line 672, in merge_environment_settings
  File "requests-2.18.4-py3.6.egg/requests/utils.py", line 692, in get_environ_proxies
  File "requests-2.18.4-py3.6.egg/requests/utils.py", line 676, in should_bypass_proxies
  File "urllib/request.py", line 2612, in proxy_bypass
  File "urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
  File "urllib/request.py", line 2575, in _proxy_bypass_macosx_sysconf
ValueError: negative shift count
[2392] Failed to execute script electrum
```

**UCS screen shots**:
![screen shot 2017-12-03 at 21 51 32](https://user-images.githubusercontent.com/1459428/33531794-59c6af2c-d879-11e7-95f1-6d572b635c04.png)
![screen shot 2017-12-03 at 21 51 47](https://user-images.githubusercontent.com/1459428/33531796-60a8df4a-d879-11e7-9945-cc8af98cdcea.png)
![screen shot 2017-12-03 at 21 52 24](https://user-images.githubusercontent.com/1459428/33531798-64c3a466-d879-11e7-8117-9e9a76782848.png)
![screen shot 2017-12-03 at 21 53 22](https://user-images.githubusercontent.com/1459428/33531799-67b8c8ae-d879-11e7-92b1-4227c7cd0f14.png)

Please, what should i do to finish creating my wallet?
Thanks in advance!

**Comment by SomberNight** [comment]
Can you check if turning off the (system?) proxy resolves the problem for you? If so, I'll close this, we can't fix it.

**Comment by ghjansen** [comment]
Thank you very much @SomberNight . Indeed, following the steps described [here](https://stackoverflow.com/questions/21677553/pip-installed-but-throwing-error-while-installing-any-package/21677856#comment32768797_21677553) (removing the bypass proxy settings) i managed to complete the creation of my wallet, so i'm closing the issue.

Congratulations for Electrum! Seems pretty sharped so far, great work guys! :)
