### ISSUE TITLE
Exceptions raised during interpreter shutdown

### ISSUE THREAD

**Issue by psyvisions** [spesmilo/electrum#344]
I get the following error on the console when trying to send a transaction, right after inputing the passphrase, and the transaction doesn't go trough. Using a newly compiled Electrum taken yesterday from github.
Ubuntu 13.10 64bit
Compiled from the master branch.
```
Exception in thread Thread-13 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
  File "/home/user/electrum/lib/wallet.py", line 1525, in run
  File "/home/user/electrum/lib/wallet.py", line 1581, in run_interface
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
  File "/home/user/electrum/lib/network.py", line 285, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-12 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
  File "/home/user/electrum/lib/verifier.py", line 114, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

**Comment by ecdsa** [comment]
this was caused by daemon threads.
They have been replaced: 72688a5cfa25066d1fd6eee646b874725359ff04
