### ISSUE TITLE
commandline - verifymessage is broken

### ISSUE THREAD

**Issue by smrt28** [spesmilo/electrum#3446]
I followed the examples at:
http://docs.electrum.org/en/latest/cmdline.html?highlight=verify#

electrum verifymessage 145dNVmUtucGZQHeqBFaWCDMFVxHAtwboY $sig -

```
assert bytes failed [<class 'bytes'>, <class 'str'>]
Traceback (most recent call last):
  File "./electrum", line 423, in <module>
    result = run_offline_command(config, config_options)
  File "./electrum", line 288, in run_offline_command
    result = func(*args, **kwargs)
  File "/home/smrt/src/Electrum-3.0.2/lib/commands.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "/home/smrt/src/Electrum-3.0.2/lib/commands.py", line 407, in verifymessage
    return bitcoin.verify_message(address, sig, message)
  File "/home/smrt/src/Electrum-3.0.2/lib/bitcoin.py", line 624, in verify_message
    assert_bytes(sig, message)
  File "/home/smrt/src/Electrum-3.0.2/lib/util.py", line 253, in assert_bytes
    assert isinstance(x, (bytes, bytearray))
AssertionError
```

Python is not my language, but my suggestion would be to add message.encode() to verify_message() function. Not sure if it could break something...

```
def verify_message(address, sig, message):
    message = message.encode()
    assert_bytes(sig, message)
```

**Comment by SomberNight** [comment]
fixed in 65c15c5a03ecd9dbe706141bcfd55c4ab72182f2
