### ISSUE TITLE
keepkey p2sh-segwit wallet can't spend

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3462]
On git master 4e60cedea9c295b2c2fa62b94d20eba3c515e5d9.

Keepkey standard wallet with `p2wpkh-p2sh` script type (BIP49 derivation path) fails to sign unsigned transactions.

Typical 1-in 2-out tx.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 579, in run
    result = task.task()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1152, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/user/wspace/electrum/plugins/keepkey/plugin.py", line 59, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/user/wspace/electrum/plugins/keepkey/plugin.py", line 224, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/home/user/wspace/electrum/plugins/keepkey/clientbase.py", line 218, in wrapped
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/keepkeylib/client.py", line 871, in sign_tx
    res = self.call(proto.TxAck(tx=msg))
  File "/home/user/.local/lib/python3.5/site-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/keepkeylib/client.py", line 189, in call
    msg = handler(resp)
  File "/home/user/wspace/electrum/plugins/keepkey/clientbase.py", line 35, in callback_Failure
    raise RuntimeError(msg.message)
RuntimeError: Failed to compile output
```

```
$ pip3 show keepkey
Name: keepkey
Version: 4.0.0
```

**Comment by SomberNight** [comment]
Tested again on 3851e78454f559ec4368a4b04dd61c2b9a1f9dc1 with python-keepkey 4.0.2.
Issue still persists.

**Comment by bsbits** [comment]
can you try to just sign the transaction and broadcast it using a different tool like blockchain info pushtx ?

**Comment by SomberNight** [comment]
> can you try to just sign the transaction

Sign how? Using a different tool?
The problem occurs when I try to sign it using Electrum.

**Comment by bitsolemn** [comment]
I too have coins trapped on BIP49 keepkey. Are these lost?

**Comment by SomberNight** [comment]
@bitsolemn No, not trapped. You can:
- use Electrum in combination with a different hw device (Trezor, Ledger, Digital Bitbox all support `p2wpkh-p2sh`) initialised from the same seed words
- use Electrum to create a software wallet from the same seed words (enable the BIP39 option when restoring from seed)

**Comment by bitsolemn** [comment]
Ah right. The stress clouded my thinking. Thanks~
