### ISSUE TITLE
can't build apk by using buildozer, zxing dose not exist

### ISSUE THREAD

**Issue by boluo9** [spesmilo/electrum#3723]
```
-pre-compile:

-compile:
    [javac] Compiling 27 source files to /root/electrum/.buildozer/android/platform/build/dists/Electrum/bin/classes
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:10: error: package me.dm7.barcodescanner.zxing does not exist
    [javac] import me.dm7.barcodescanner.zxing.ZXingScannerView;
    [javac]                                   ^
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:12: error: package com.google.zxing does not exist
    [javac] import com.google.zxing.Result;
    [javac]                        ^
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:13: error: package com.google.zxing does not exist
    [javac] import com.google.zxing.BarcodeFormat;
    [javac]                        ^
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:15: error: package ZXingScannerView does not exist
    [javac] public class SimpleScannerActivity extends Activity implements ZXingScannerView.ResultHandler {
    [javac]                                                                                ^
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:16: error: cannot find symbol
    [javac]     private ZXingScannerView mScannerView;
    [javac]             ^
    [javac]   symbol:   class ZXingScannerView
    [javac]   location: class SimpleScannerActivity
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:41: error: cannot find symbol
    [javac]     public void handleResult(Result rawResult) {
    [javac]                              ^
    [javac]   symbol:   class Result
    [javac]   location: class SimpleScannerActivity
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:22: error: cannot find symbol
    [javac]         mScannerView = new ZXingScannerView(this);   // Programmatically initialize the scanner view
    [javac]                            ^
    [javac]   symbol:   class ZXingScannerView
    [javac]   location: class SimpleScannerActivity
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:23: error: cannot find symbol
    [javac]         mScannerView.setFormats(Arrays.asList(BarcodeFormat.QR_CODE));
    [javac]                                               ^
    [javac]   symbol:   variable BarcodeFormat
    [javac]   location: class SimpleScannerActivity
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:40: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 9 errors

BUILD FAILED
/root/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:720: The following error occurred while executing this line:
/root/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 2 seconds


  STDERR:


[INFO]:    STDOUT (last 20 lines of 105):
	    [javac]                            ^	
    [javac]   symbol:   class ZXingScannerView	
    [javac]   location: class SimpleScannerActivity	
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:23: error: cannot find symbol	
    [javac]         mScannerView.setFormats(Arrays.asList(BarcodeFormat.QR_CODE));	
    [javac]                                               ^	
    [javac]   symbol:   variable BarcodeFormat	
    [javac]   location: class SimpleScannerActivity	
    [javac] /root/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:40: error: method does not override or implement a method from a supertype	
    [javac]     @Override	
    [javac]     ^	
    [javac] Note: Some input files use or override a deprecated API.	
    [javac] Note: Recompile with -Xlint:deprecation for details.	
    [javac] 9 errors	
```

**Comment by bauerj** [comment]
Please use a gradle-based build instead of ant. To do that, you can use the Android SDK manager in `/root/.buildozer/android/platform/android-sdk-20` to update the Android build tools to a more recent version (27 should be fine).

**Comment by SomberNight** [comment]
You need to manually merge the branches mentioned here https://github.com/spesmilo/electrum/pull/3624 against p4a (the `stable` branch!) and buildozer.
Also, you need to manually merge https://github.com/kivy/python-for-android/pull/1217

(Note: we should update the Android build instructions)

**Comment by ecdsa** [comment]
yes lets update build instructions and close this

**Comment by vivekteega** [comment]
I'm facing this issue even after merging the branches which @SomberNight suggested. 

@bauerj how to choose a gradle based build instead of ANT? I am not able to see version 27 on the SDK manager inside `~/.buildozer/android/platform/android-sdk-20/tools`

![screenshot from 2018-05-06 16-18-20](https://user-images.githubusercontent.com/21047998/39672522-35bb0058-5149-11e8-95e1-849e33e638c3.png)

**Comment by SomberNight** [comment]
@vivekteega The build instructions have been updated since, see https://github.com/spesmilo/electrum/blob/master/gui/kivy/Readme.md

**Comment by vivekteega** [comment]
@SomberNight I just followed the those instructions and built everything from scratch. I get the following error 

```
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /home/vivek/Documents/electrum/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a/six
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/opt/python-for-android/pythonforandroid/build.py", line 574, in build_recipes
    recipe.build_arch(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 775, in build_arch
    self.install_python_package(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 789, in install_python_package
    hostpython = sh.Command(self.hostpython_location)
  File "/home/vivek/.local/lib/python3.5/site-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: python3.6

```
I do not have Python 3.6 as I am on Ubuntu 16.04. There is some bug which makes life difficult if you run python 3.6 on the 16.04, ie. gnome applications do not work. Is it necessary to use python 3.6?

buildozer.spec file located over here https://github.com/spesmilo/electrum/blob/master/gui/kivy/tools/buildozer.spec#L34 specifically mentions to use python 3.6. Should I just remove that part of code? 

I'm uploading a screenshot of the error mentioned above. 
![screenshot from 2018-05-06 17-19-14](https://user-images.githubusercontent.com/21047998/39672979-aa69f47e-5151-11e8-8497-84b7aebfb234.png)

**Comment by vivekteega** [comment]
@SomberNight It has been more than a week now that I have been trying to compile an apk for the wallet. I'd be greateful if you could help get me in solving this error ? 

I installed Ubuntu 18.04 which has python 3 as default. I got the following error
```
[INFO]:    STDOUT (last 20 lines of 69):
	     [echo] Handling Resources...	
     [aapt] Found modified input file	
     [aapt] Generating resource IDs...	
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')	
     [echo] ----------	
     [echo] Handling BuildConfig class...	
[buildconfig] Generating BuildConfig class.	
	
-pre-compile:	
	
-compile:	
    [javac] Compiling 27 source files to /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/bin/classes	
    [javac] error: Source option 5 is no longer supported. Use 6 or later.	
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.	
	
BUILD FAILED	
/home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:716: The following error occurred while executing this line:	
/home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.	
	
Total time: 0 seconds
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum && /home/vivek/.buildozer/android/platform/apache-ant-1.9.4/bin/ant debug

[WARNING]: ERROR: /home/vivek/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
b'Could not find hostpython, will not compile to .pyo (this is normal with python3)\nNo compiled python is present to zip, skipping.\nthis should only be the case if you are using the CrystaX python\n'# 
```
So I changed     
```
<property name="java.target" value="1.5" />
<property name="java.source" value="1.5" />
```
to 
```
<property name="java.target" value="8" />
<property name="java.source" value="8" />
```
in the file /home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml
Now I get the same error the OP mentioned in this post. 
```
-pre-compile:

-compile:
    [javac] Compiling 27 source files to /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/bin/classes
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:10: error: package me.dm7.barcodescanner.zxing does not exist
    [javac] import me.dm7.barcodescanner.zxing.ZXingScannerView;
    [javac]                                   ^
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:12: error: package com.google.zxing does not exist
    [javac] import com.google.zxing.Result;
    [javac]                        ^
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:13: error: package com.google.zxing does not exist
    [javac] import com.google.zxing.BarcodeFormat;
    [javac]                        ^
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:15: error: package ZXingScannerView does not exist
    [javac] public class SimpleScannerActivity extends Activity implements ZXingScannerView.ResultHandler {
    [javac]                                                                                ^
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:16: error: cannot find symbol
    [javac]     private ZXingScannerView mScannerView;
    [javac]             ^
    [javac]   symbol:   class ZXingScannerView
    [javac]   location: class SimpleScannerActivity
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:41: error: cannot find symbol
    [javac]     public void handleResult(Result rawResult) {
    [javac]                              ^
    [javac]   symbol:   class Result
    [javac]   location: class SimpleScannerActivity
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:22: error: cannot find symbol
    [javac]         mScannerView = new ZXingScannerView(this);   // Programmatically initialize the scanner view
    [javac]                            ^
    [javac]   symbol:   class ZXingScannerView
    [javac]   location: class SimpleScannerActivity
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:23: error: cannot find symbol
    [javac]         mScannerView.setFormats(Arrays.asList(BarcodeFormat.QR_CODE));
    [javac]                                               ^
    [javac]   symbol:   variable BarcodeFormat
    [javac]   location: class SimpleScannerActivity
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:40: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 9 errors

BUILD FAILED
/home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 2 seconds


  STDERR:


[INFO]:    STDOUT (last 20 lines of 105):
	    [javac]                            ^	
    [javac]   symbol:   class ZXingScannerView	
    [javac]   location: class SimpleScannerActivity	
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:23: error: cannot find symbol	
    [javac]         mScannerView.setFormats(Arrays.asList(BarcodeFormat.QR_CODE));	
    [javac]                                               ^	
    [javac]   symbol:   variable BarcodeFormat	
    [javac]   location: class SimpleScannerActivity	
    [javac] /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum/tmp-src/org/electrum/qr/SimpleScannerActivity.java:40: error: method does not override or implement a method from a supertype	
    [javac]     @Override	
    [javac]     ^	
    [javac] Note: Some input files use or override a deprecated API.	
    [javac] Note: Recompile with -Xlint:deprecation for details.	
    [javac] 9 errors	
	
BUILD FAILED	
/home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:716: The following error occurred while executing this line:	
/home/vivek/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.	
	
Total time: 2 seconds
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/vivek/Documents/electrum/.buildozer/android/platform/build/dists/Electrum && /home/vivek/.buildozer/android/platform/apache-ant-1.9.4/bin/ant debug

[WARNING]: ERROR: /home/vivek/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
b'Could not find hostpython, will not compile to .pyo (this is normal with python3)\nNo compiled python is present to zip, skipping.\nthis should only be the case if you are using the CrystaX python\n'# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name Electrum --name Electrum --version 1.9.8 --package org.electrum.electrum --android_api 19 --minsdk 9 --private /home/vivek/Documents/electrum/.buildozer/android/app --permission INTERNET --permission WRITE_EXTERNAL_STORAGE --permission READ_EXTERNAL_STORAGE --permission CAMERA --add-activity org.electrum.qr.SimpleScannerActivity --presplash /home/vivek/Documents/electrum/./icons/electrum_presplash.png --icon /home/vivek/Documents/electrum/./icons/electrum_launcher.png --orientation portrait --window --intent-filters /home/vivek/Documents/electrum/gui/kivy/tools/bitcoin_intent.xml --activity-launch-mode singleTask --copy-libs --depend me.dm7.barcodescanner:zxing:1.9.8 --arch armeabi-v7a --color=always --storage-dir=/home/vivek/Documents/electrum/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
make[1]: Entering directory '/home/vivek/Documents/electrum/gui/kivy'
# Cleaning up
# rename main.py to electrum
# remove buildozer.spec
make[1]: Leaving directory '/home/vivek/Documents/electrum/gui/kivy'
~/Documents/electrum

```

**Comment by SomberNight** [comment]
I have updated the Kivy readme now in https://github.com/spesmilo/electrum/commit/7c6364c2c7502cf25df88152cc4464c5ce6819eb
Please take a look.

In any case, based on your latest trace, you are using ant instead of gradle.
I'm guessing you don't have the latest `Android SDK Build-tools`. See https://github.com/spesmilo/electrum/blob/7c6364c2c7502cf25df88152cc4464c5ce6819eb/gui/kivy/Readme.md#8-update-the-android-sdk-build-tools

**Comment by vivekteega** [comment]
@SomberNight it worked!! Thanks a ton dude! :smile: 

There are a few errors I ran into before it worked though. You may want to add them to the installation readme 

1. The problem was SDK build tools as you pointed out. But [the instructions to update SDK tools mentioned in the readme ](https://github.com/spesmilo/electrum/blob/7c6364c2c7502cf25df88152cc4464c5ce6819eb/gui/kivy/Readme.md#8-update-the-android-sdk-build-tools) weren't working for me, not sure why. On the terminal it showed that the build-tools are updated to version 27, but it didn't reflect in the local .buildozer folder. Maybe it is storing somewhere else. 
I have a copy of the latest build tools which my Android Studio's SDK manager downloaded, which I copied to .buildozer's sdk folder. The compile worked then
`cp -a /android-studio-sdk-location/Sdk/build-tools/27.0.3/. ~/.buildozer/android/platform/android-sdk-20/build-tools/`
Ps - I copied other matching folders too.

2. Kivy doesn't work on Ubuntu 17.10 when installed use the apt repository mentioned in the [official docs](https://kivy.org/docs/installation/installation-linux.html). The following worked for me 

```
sudo apt-get remove --purge python3-kivy
pip3 uninstall kivy
sudo apt autoremove
pip3 install kivy==1.9.1
```
