### ISSUE TITLE
Generated .app doesn't execute on macOS

### ISSUE THREAD

**Issue by nitinsurana** [spesmilo/electrum#3746]
Hi

I used the following steps to build
```
./contrib/make_packages
./contrib/make_locale (ignored errors)
./contrib/make_osx
```

The `.app` generated within `dist` directory, doesn't execute. Running ./dist/Electrum on terminal, gives the following error
```
Traceback (most recent call last):
  File "electrum", line 95, in <module>
    from electrum.util import set_verbosity, InvalidPassword, check_www_dir
ImportError: cannot import name 'check_www_dir'
[71267] Failed to execute script electrum
```

`osx.spec` (used by make_osx script) contains `lib/util.py` which contains the function `check_www_dir`, still the above error. I'm out of luck now, any pointers would be really useful. Thanks

**Comment by nitinsurana** [comment]
So far, I have been able to run it using `python3 electrum`  after executing the following set of commands
```
brew install pyqt5 --with-python3
pyrcc5 icons.qrc -o gui/qt/icons_rc.py
```
Still building `Electrum.app` using `./contrib/make_osx`  doesn't execute and gives the same `check_www_dir` error.

**Comment by SomberNight** [comment]
What commit are you trying to build? Master no longer has that function (`check_www_dir`) since https://github.com/spesmilo/electrum/commit/4a40b3a0b2522e6adad58631eba4f57341907d44

**Comment by nitinsurana** [comment]
Playing with the latest master
`python electrum` doesn't work any longer and gives
```
Error: Could not import PyQt5 on Linux system, you may try 'sudo apt-get install python3-pyqt5'
```
The error remains same even after `sudo pip3 install pyqt5` and `brew install pyqt5`

**Comment by ch4ot1c** [comment]
One of our developers took on this challenge and succeeded. Our fork of the official Electrum client has the adjustments to make this work; 'Building Releases' is the section of interest in the Readme: https://github.com/BTCP-community/electrum-zcl/tree/master. Also see https://github.com/spesmilo/electrum/issues/1063 for assorted related solutions.

**Comment by nitinsurana** [comment]
Cloned this repo again and tried the setups mentioned. There are a couple of ignorable errors in the terminal and the finally generated `.app` file doesn't execute

<img width="439" alt="screen shot 2018-01-27 at 16 58 14" src="https://user-images.githubusercontent.com/7137160/35477894-4acadb6c-0383-11e8-9313-33bf78121377.png">

Following are the errors in console
```
WARNING: ImportError in sip recipe ignored: No module named docutils-0
WARNING: ImportError in sip recipe ignored: No module named future-0
WARNING: ImportError in sip recipe ignored: No module named altgraph-0
WARNING: ImportError in sip recipe ignored: No module named macholib-1
WARNING: ImportError in sip recipe ignored: No module named sip-4
WARNING: ImportError in sip recipe ignored: No module named wheel-0
WARNING: ImportError in sip recipe ignored: No module named pefile-2017
WARNING: ImportError in sip recipe ignored: No module named requests-2
WARNING: ImportError in sip recipe ignored: No module named setuptools-36
WARNING: ImportError in sip recipe ignored: No module named six-1
WARNING: ImportError in sip recipe ignored: No module named PyInstaller-3
WARNING: ImportError in sip recipe ignored: No module named Electrum-3
WARNING: ImportError in sip recipe ignored: No module named mnemonic-0
WARNING: ImportError in sip recipe ignored: No module named trezor-0
WARNING: ImportError in sip recipe ignored: No module named PyQt5-5
WARNING: ImportError in sip recipe ignored: No module named Kivy-1
WARNING: ImportError in sip recipe ignored: No module named pip-9
WARNING: ImportError in sip recipe ignored: No module named Cython-0
WARNING: ImportError in sip recipe ignored: No module named modulegraph-0
WARNING: ImportError in sip recipe ignored: No module named hidapi-0
WARNING: ImportError in sip recipe ignored: No module named Pygments-2
WARNING: ImportError in sip recipe ignored: No module named urllib3-1
WARNING: ImportError in sip recipe ignored: No module named certifi-2018
WARNING: ImportError in sip recipe ignored: No module named btchip_python-0
WARNING: ImportError in sip recipe ignored: No module named py2app-0
WARNING: ImportError in sip recipe ignored: No module named protobuf-3
WARNING: ImportError in sip recipe ignored: No module named keepkey-4
WARNING: ImportError in sip recipe ignored: No module named Kivy_Garden-0
```
```
 Traceback (most recent call last):
   File "setup-release.py", line 66, in <module>
     **extra_options
   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
     dist.run_commands()
   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
     self.run_command(cmd)
   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
     cmd_obj.run()
   File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 825, in run
     self._run()
   File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 1040, in _run
     self.run_normal()
   File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 1253, in run_normal
     o = __import__(m1, fromlist=[m2])
   File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/port_v2/ascii_upper.py", line 27, in <module>
     _ascii_trans_table = string.maketrans(string.ascii_lowercase,
 AttributeError: module 'string' has no attribute 'maketrans'
Creating python Electrum.app and .dmg
```
Also, I have copied the files `setup-release.py`, `setup-mac.sh` and `install-mac.sh` from [here](https://github.com/BTCP-community/electrum-zcl/tree/master) required to follow the build steps.

**Comment by SomberNight** [comment]
Can you retest with the new instructions? See e.g. https://github.com/spesmilo/electrum/pull/3814

**Comment by nitinsurana** [comment]
@SomberNight Thanks for the updated instructions.

I cloned the `master` and executed the `make_osx` script by being in both `electrum` folder and `build-osx` folder, but the build fails with the following error

```
14614 INFO: Analyzing /Users/coding_idiot/Downloads/electrum/electrum
14828 INFO: Analyzing /Users/coding_idiot/Downloads/electrum/gui/qt/main_window.py
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 57, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 415, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/analysis.py", line 219, in run_script
    return super(PyiModuleGraph, self).run_script(pathname, caller=caller)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1347, in run_script
    co_ast = compile(contents, pathname, 'exec', ast.PyCF_ONLY_AST, True)
  File "/Users/coding_idiot/Downloads/electrum/gui/qt/main_window.py", line 2386
    nonlocal done
                ^
SyntaxError: invalid syntax
🗯 ERROR: Could not build binary
```

**Comment by SomberNight** [comment]
Looks like you have pyinstaller for python2 instead of python3.

https://github.com/spesmilo/electrum/blob/afa0168e1427fa0849ef219d596e1e91477b4e28/contrib/build-osx/make_osx#L34-L37

@bauerj ^ should the above be changed to handle this case? I'm not sure.

**Comment by nitinsurana** [comment]
```
💬 INFO: Building binary
217 INFO: PyInstaller: 3.3.1
218 INFO: Python: 2.7.14
226 INFO: Platform: Darwin-17.4.0-x86_64-i386-64bit
233 INFO: UPX is not available.
453 INFO: Extending PYTHONPATH with paths
```

Looks like python 2 is being used instead of python 3. The `make_osx` script contains many `pip` commands instead of `pip3` commands - maybe that's what the issue is.

**Comment by nitinsurana** [comment]
I deleted `\usr\local\bin\pyinstaller` forcing re-install and set `alias python=python3` before executing`./contrib/build-osx/make_osx`. And finally, it works. The built `.app` is of expected size and executes perfectly fine.

**Comment by bauerj** [comment]
>  The make_osx script contains many pip commands instead of pip3 commands

I'm confused, the script doesn't have a single call to pip directly.

>  And build-osx readme should be updated with the instructions to make sure that pyinstaller for python3 is being used

I guess we could just change the order of the folders in `$PATH` so that the pyinstaller binary the script installs has precedence over your system installation.

**Comment by bauerj** [comment]
Should be fixed now.

**Comment by SomberNight** [comment]
(see https://github.com/spesmilo/electrum/commit/240ecee6ced32623a277f475ce7aeaab77713824)
