### ISSUE TITLE
jsonrpclib.jsonrpc.ProtocolError

### ISSUE THREAD

**Issue by GuestInCorle** [spesmilo/electrum#3759]
Error has occured when I tried to run "electrum commands". Electrum's version is 3.0.5.
```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 419, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32601, 'Method run_cmdline not supported.')
```

**Comment by SomberNight** [comment]
This is due to https://github.com/spesmilo/electrum/commit/1020449684a4a12eea85e7f51670a8eb35316873 and should only happen when the GUI is running. Stop the GUI and try again.

**Comment by SomberNight** [comment]
Note: keeping open as maybe we could make the error message more intuitive (include hint about GUI running)

**Comment by ecdsa** [comment]
closing, as this is no longer returning an error
