### ISSUE TITLE
Electrum crashes when I try to sign a message without having privkey

### ISSUE THREAD

**Issue by chrotz** [spesmilo/electrum#3776]
Iam using version 3.0.5

Whenever I try to sign a message and want to sign it with a adress which I dont have imported in my client and dont have the private key to it, the application stops working and crashes.

using windows10 with latest updates

**Comment by SomberNight** [comment]
Trace using 3.0.5:
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2012, in <lambda>
    b.clicked.connect(lambda: self.do_sign(address_e, message_e, signature_e))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1289, in request_password
    return func(self, *args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1958, in do_sign
    txin_type = self.wallet.get_txin_type(address)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1547, in get_txin_type
    return self.addresses[address].get('type', 'address')
KeyError: 'tb1q63yw5n7hwkalupn5jvu3e53zu4jjp38nk9v8dl'
Aborted
```

This is fixed on master since https://github.com/spesmilo/electrum/commit/99a08f35b20c88ee9979fe5c38ad0c4c8f728c04
