### ISSUE TITLE
Preferences not opening in ubuntu 17.10

### ISSUE THREAD

**Issue by sdlarkin** [spesmilo/electrum#3789]
when I click on the preferences icon or go to tools -> preferences nothing happens therefore I can not open my preferences dialog. all other icons and menu items seem to be functioning normally. if I start electrum from the command line an attempt to open preferences I get:

```
(process:7880): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
No systemtrayicon available
Traceback (most recent call last):
  File "/snap/electrum/2/gui/qt/main_window.py", line 2773, in settings_dialog
    system_cameras = qrscanner._find_system_cameras()
  File "/snap/electrum/2/lib/qrscanner.py", line 70, in _find_system_cameras
    name = open(os.path.join(device_root, device, 'name')).read()
IOError: [Errno 13] Permission denied: '/sys/class/video4linux/video0/name'

```

I am confused as to what locale it is looking for because can run these two commands:
```
locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

sudo apt-get install libcanberra-gtk3-module
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcanberra-gtk3-module is already the newest version (0.30-3ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.13.0-16 linux-headers-4.13.0-16-generic linux-image-4.13.0-16-generic
  linux-image-extra-4.13.0-16-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

```

**Comment by bauerj** [comment]
Hey, what version of Electrum do you use?

**Comment by SomberNight** [comment]
Looks like dupe of https://github.com/spesmilo/electrum/issues/2603
Please confirm that you are using an outdated version and then close this.

**Comment by sdlarkin** [comment]
I think you are correct. However I am using the version(2.6.4-tpaw0) in the
Ubuntu software center. I don't know who maintains that but it should
probably be updated if it is out of date.

**Comment by SomberNight** [comment]
@sdlarkin That version is very much out of date and also has at least one known security vulnerability. Please update to 3.0.5 (or possibly 2.9.4).
