### ISSUE TITLE
Android build issues: No such file or directory: './contrib/versions.py'

### ISSUE THREAD

**Issue by Neustart** [spesmilo/electrum#3829]
Hi, I faced an error. What it can be ? 
```
# Package the application
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.35.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/targets/android.py", line 648, in build_package
    version = self.buildozer.get_version()
  File "/usr/local/lib/python3.5/site-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/__init__.py", line 710, in get_version
    with open(fn) as fd:
FileNotFoundError: [Errno 2] No such file or directory: './contrib/versions.py'
Makefile:20: recipe for target 'apk' failed
make: [apk] Error 1 (ignored)
make[1]: Entering directory '/home/kirill/Projects/SI-Crypto/Electrum/gui/kivy'

```

**Comment by Neustart** [comment]
**Solution 1:** 
comment/uncomment line as in example below:
`buildozer.spec`
```
# (str) Application versioning (method 1)
#version.regex = version_apk = '(.*)'
#version.filename = %(source.dir)s/contrib/versions.py

# (str) Application versioning (method 2)
version = 1.9.8
```
**Solution 2:**
Create versions.py file and add next lines:
`version = 1.9.8`
