### ISSUE TITLE
blockchain.py::read_header() local variable 'h' referenced before assignment

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3872]
On git master 81bd8d8d679a0a6ece4b35da818cf8ce958016dd.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/lib/util.py", line 731, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/user/wspace/electrum/lib/network.py", line 978, in run
    self.wait_on_sockets()
  File "/home/user/wspace/electrum/lib/network.py", line 960, in wait_on_sockets
    self.process_responses(interface)
  File "/home/user/wspace/electrum/lib/network.py", line 623, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/user/wspace/electrum/lib/network.py", line 569, in process_response
    self.on_get_header(interface, response)
  File "/home/user/wspace/electrum/lib/network.py", line 819, in on_get_header
    chain = blockchain.check_header(header)
  File "/home/user/wspace/electrum/lib/blockchain.py", line 85, in check_header
    if b.check_header(header):
  File "/home/user/wspace/electrum/lib/blockchain.py", line 131, in check_header
    return header_hash == self.get_hash(height)
  File "/home/user/wspace/electrum/lib/blockchain.py", line 271, in get_hash
    return hash_header(self.read_header(height))
  File "/home/user/wspace/electrum/lib/blockchain.py", line 256, in read_header
    if h == bytes([0])*80:
UnboundLocalError: local variable 'h' referenced before assignment
```

This was encountered by an electrum daemon running on mainnet for several hours, so don't have a way to reproduce.

**Comment by SomberNight** [comment]
Oops. This was me. I had this daemon running for some time, totally forgot about it, and WHILE it was running I deleted its electrum datadir. :P
