### ISSUE TITLE
Electrum not recognizing Trezor (Linux)

### ISSUE THREAD

**Issue by colourful-land** [spesmilo/electrum#3928]
On Ubuntu 16.04 Installed using

    $ sudo pip3 install https://download.electrum.org/3.0.6/Electrum-3.0.6.tar.gz
    $ sudo pip3 install trezor

Showing that the trezor installed is above the required version of 0.7.16.

    $ pip3 show trezor 
    ---
    Metadata-Version: 1.1
    Name: trezor
    Version: 0.9.0

Electrum prompted "No hardware device detected", and asked me to check the udev rule permission. Trezor is working for the web (Chroimum) so I don't think that it's udev rule related. 

Traceback:
````
$ electrum 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins.py", line 151, in get_hardware_support
    p = self.get_plugin(name)
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins.py", line 179, in get_plugin
    self.load_plugin(name)
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins.py", line 104, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/usr/local/lib/python3.5/dist-packages/electrum_plugins/trezor/trezor.py", line 22, in __init__
    self.types = trezorlib.client.types
AttributeError: module 'trezorlib.client' has no attribute 'types'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins.py", line 151, in get_hardware_support
    p = self.get_plugin(name)
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins.py", line 179, in get_plugin
    self.load_plugin(name)
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins.py", line 104, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/usr/local/lib/python3.5/dist-packages/electrum_plugins/trezor/trezor.py", line 22, in __init__
    self.types = trezorlib.client.types
AttributeError: module 'trezorlib.client' has no attribute 'types'
````

**Comment by SomberNight** [comment]
Electrum 3.0.6 needs python-trezor 0.7.16.
Electrum 3.1.0 (unreleased, master) needs python-trezor 0.9.0.
It's not ideal but there were breaking changes in the newest python-trezor.

```
sudo pip3 uninstall trezor
sudo pip3 install trezor==0.7.16
```

**Comment by colourful-land** [comment]
Ah, it worked. I could have saved 1 hour attempting to get python-trezor installed with its rigid dependency on the latest version of hidapi...
