### ISSUE TITLE
crash: wallet.get_full_history - NoneType to Decimal

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3939]
On git master d77e522721b98c8d455f866bc40b778c6a0fb74e.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 217, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 179, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 201, in __init__
    self.load_wallet(wallet)
  File "/home/user/wspace/electrum/lib/util.py", line 275, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/home/user/wspace/electrum/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 344, in load_wallet
    self.history_list.update()
  File "/home/user/wspace/electrum/gui/qt/util.py", line 484, in update
    self.on_update()
  File "/home/user/wspace/electrum/lib/util.py", line 275, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/home/user/wspace/electrum/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/gui/qt/history_list.py", line 202, in on_update
    r = self.wallet.get_full_history(domain=self.get_domain(), from_timestamp=self.start_timestamp, to_timestamp=self.end_timestamp, fx=fx)
  File "/home/user/wspace/electrum/lib/util.py", line 275, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/home/user/wspace/electrum/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1044, in get_full_history
    summary['start_fiat_balance'] = Fiat(fx.historical_value(init_balance, start_date), fx.ccy)
  File "/home/user/wspace/electrum/lib/exchange_rate.py", line 539, in historical_value
    return Decimal(satoshis) / COIN * Decimal(rate)
TypeError: conversion from NoneType to Decimal is not supported
```

**Comment by goodProjects** [comment]
As a temporary fix, i've added Decimal number instead of Satoshi variable

```
  def historical_value(self, satoshis, d_t):
        rate = self.history_rate(d_t)
        return Decimal(0.1) / COIN * Decimal(rate)
```
And its working now
