### ISSUE TITLE
crash: wallet.get_full_history - self.transactions[txid] KeyError

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3940]
On git master d77e522721b98c8d455f866bc40b778c6a0fb74e.
(with minor modifications so that https://github.com/spesmilo/electrum/issues/3938 and https://github.com/spesmilo/electrum/issues/3939 won't get triggered)

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 616, in timer_actions
    self.update_wallet()
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 736, in update_wallet
    self.update_tabs()
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 739, in update_tabs
    self.history_list.update()
  File "/home/user/wspace/electrum/gui/qt/util.py", line 484, in update
    self.on_update()
  File "/home/user/wspace/electrum/lib/util.py", line 275, in 
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/home/user/wspace/electrum/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/gui/qt/history_list.py", line 202, in on_update
    r = self.wallet.get_full_history(domain=self.get_domain(), from_timestamp=self.start_timestamp, to_timestamp=self.end_timestamp, fx=fx)
  File "/home/user/wspace/electrum/lib/util.py", line 275, in 
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/home/user/wspace/electrum/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1019, in get_full_history
    ap, lp = self.capital_gain(tx_hash, fx.timestamp_rate, fx.ccy)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1709, in capital_gain
    acquisition_price = out_value/Decimal(COIN) * self.average_price(tx, price_func, ccy)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1715, in average_price
    total_price = sum(self.coin_price(txin, price_func, ccy, self.txin_value(txin)) for txin in tx.inputs())
  File "/home/user/wspace/electrum/lib/wallet.py", line 1715, in 
    total_price = sum(self.coin_price(txin, price_func, ccy, self.txin_value(txin)) for txin in tx.inputs())
  File "/home/user/wspace/electrum/lib/wallet.py", line 1721, in coin_price
    tx = self.transactions[txid]
KeyError: '3a20f720b0b5f6d042d757a7c1d0c474d71c976efca23566328a8825f11f2032'
```

**Comment by ecdsa** [comment]
fixed in 51f04d4e7bdb1021c5535c47b676c3d2d084eebf
