### ISSUE TITLE
Trezor not found

### ISSUE THREAD

**Issue by Kixunil** [spesmilo/electrum#3953]
When I run electrum from command line and attempt to setup hardware wallet, I get this output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/electrum/plugins.py", line 151, in get_hardware_support
    p = self.get_plugin(name)
  File "/usr/local/lib/python3.4/dist-packages/electrum/plugins.py", line 179, in get_plugin
    self.load_plugin(name)
  File "/usr/local/lib/python3.4/dist-packages/electrum/plugins.py", line 104, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/usr/local/lib/python3.4/dist-packages/electrum_plugins/trezor/trezor.py", line 22, in __init__
    self.types = trezorlib.client.types
AttributeError: 'module' object has no attribute 'types'
```

Of course, GUI isn't showing any wallet, making it impossible to use.

**Comment by ecdsa** [comment]
update you python-trezor library

**Comment by SomberNight** [comment]
read https://github.com/spesmilo/electrum/issues/3928#issuecomment-366846324

**Comment by SomberNight** [comment]
Closing; please comment/reopen if using python-trezor 0.7.16 with electrum 3.0.6 still results in this.

**Comment by Kixunil** [comment]
The suggestion at #3928 helped. Thank you!
