### ISSUE TITLE
Hanging "Please wait" window

### ISSUE THREAD

**Issue by danielcft** [spesmilo/electrum#3956]
If I attempt to make a transaction and type a wrong password I get a hanging "Please wait" window.
It is not possible to close the window.
![screenshot from 2018-02-21 21-34-18](https://user-images.githubusercontent.com/3066697/36503891-0289847c-174f-11e8-8d2e-7e855fe9ea99.png)

```
appmenu-qt: registerWindow 206 "&File"
appmenu-qt: registerWindow 206 "&Wallet"
appmenu-qt: registerWindow 206 "&View"
appmenu-qt: registerWindow 206 "&Tools"
appmenu-qt: registerWindow 206 "&Help"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/bitcoin.py", line 167, in aes_decrypt_with_iv
    return strip_PKCS7_padding(data)
  File "/usr/local/lib/python3.5/dist-packages/electrum/bitcoin.py", line 138, in strip_PKCS7_padding
    raise InvalidPadding("invalid padding byte (large)")
electrum.bitcoin.InvalidPadding: invalid padding byte (large)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/bitcoin.py", line 196, in pw_decode
    d = to_string(DecodeAES(secret, s), "utf8")
  File "/usr/local/lib/python3.5/dist-packages/electrum/bitcoin.py", line 182, in DecodeAES
    s = aes_decrypt_with_iv(secret, iv, e)
  File "/usr/local/lib/python3.5/dist-packages/electrum/bitcoin.py", line 169, in aes_decrypt_with_iv
    raise InvalidPassword()
electrum.util.InvalidPassword: Incorrect password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum_gui/qt/util.py", line 587, in run
    result = task.task()
  File "/usr/local/lib/python3.5/dist-packages/electrum/wallet.py", line 1153, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python3.5/dist-packages/electrum/keystore.py", line 99, in sign_transaction
    self.check_password(password)
  File "/usr/local/lib/python3.5/dist-packages/electrum/keystore.py", line 291, in check_password
    xprv = pw_decode(self.xprv, password)
  File "/usr/local/lib/python3.5/dist-packages/electrum/bitcoin.py", line 198, in pw_decode
    raise InvalidPassword()
electrum.util.InvalidPassword: Incorrect password
```

Observed on Electrum 3.0.5 / Linux

**Comment by SomberNight** [comment]
Hmm. Well I can't reproduce that on Debian 9.3.
I get the exact same trace (on 3.0.5) but the popup closes as expected for me.
What distro are you using?

Your pic looks a bit weird. Have you used some image manipulation program to obfuscate some detail or is that how it actually looks?

Maybe it's a QT quirk...
Can you run in a python3 interpreter:
```
from PyQt5.QtCore import QT_VERSION_STR
from PyQt5.Qt import PYQT_VERSION_STR
from sip import SIP_VERSION_STR

print("Qt version:", QT_VERSION_STR)
print("SIP version:", SIP_VERSION_STR)
print("PyQt version:", PYQT_VERSION_STR)
```
For me it prints
```
Qt version: 5.9.1
SIP version: 4.19.7
PyQt version: 5.9
```

**Comment by ecdsa** [comment]
I cannot reproduce it either, but I do not like the fact that no reference is held to the WaitingDialog.
maybe some signals get lost because of that.

could you try this patch?

```
iff --git a/gui/qt/main_window.py b/gui/qt/main_window.py
index 6b4a1f9b..da99d776 100644
--- a/gui/qt/main_window.py
+++ b/gui/qt/main_window.py
@@ -1559,8 +1559,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
             # call hook to see if plugin needs gui interaction
             run_hook('sign_tx', self, tx)
             task = partial(self.wallet.sign_transaction, tx, password)
-        WaitingDialog(self, _('Signing transaction...'), task,
-                      on_signed, on_failed)
+        self.signing_dialog = WaitingDialog(self, _('Signing transaction...'), task, on_signed, on_failed)
 
     def broadcast_transaction(self, tx, tx_desc):
 

```

**Comment by danielcft** [comment]
@SomberNight Yes, it's weird. The image was not manipulated in any way.
I'm running on Ubuntu 16.04.3 LTS.

Qt, SIP and PyQT versions:
```
Qt version: 5.5.1
SIP version: 4.17
PyQt version: 5.5.1

```

**Comment by danielcft** [comment]
@ecdsa I applied the patch but it did not fix the bug. I'm running on Ubuntu 16.04.3 LTS.

**Comment by SomberNight** [comment]
Ok, I can reproduce.

**Comment by SomberNight** [comment]
It seems we are trying to close the dialog too soon... ? It's not even fully painted when we are closing it.
After we "close it" it gets into a weird state for some reason.

I maintain a reference to it to test some things:
```
>> window.wd.close()
True
```
The window does not disappear. The docs say:
`Closes this widget. Returns true if the widget was closed; otherwise returns false.`
So apparently the widget "was closed"...

```
>> window.wd.isVisible()
False
```
But I can see it :P

```
>> window.wd.destroy()
```
^ That closes (and deletes) it properly.

-----

If we wait for it to get painted that seems to resolve the issue... this is a bit ugly, but it works:
```patch
diff --git a/gui/qt/util.py b/gui/qt/util.py
index 7f0cb238..77a9a8c2 100644
--- a/gui/qt/util.py
+++ b/gui/qt/util.py
@@ -225,17 +225,31 @@ class WaitingDialog(WindowModalDialog):
         WindowModalDialog.__init__(self, parent, _("Please wait"))
         vbox = QVBoxLayout(self)
         vbox.addWidget(QLabel(message))
+        import threading
+        self.has_been_painted = threading.Event()
+        self.has_finished = threading.Event()
         self.accepted.connect(self.on_accepted)
         self.show()
         self.thread = TaskThread(self)
-        self.thread.add(task, on_success, self.accept, on_error)
+        self.thread.add(task, on_success, self._close, on_error)
 
     def wait(self):
         self.thread.wait()
 
+    def _close(self):
+        self.has_finished.set()
+        if self.has_been_painted.is_set():
+            self.accept()
+
     def on_accepted(self):
         self.thread.stop()
 
+    def paintEvent(self, event):
+        super().paintEvent(event)
+        self.has_been_painted.set()
+        if self.has_finished.is_set():
+            self.accept()
+
 
 def line_dialog(parent, title, label, ok_label, default=None):
     dialog = WindowModalDialog(parent, title)
```

**Comment by ecdsa** [comment]
how did you reproduce the issue?

**Comment by SomberNight** [comment]
@ecdsa In a VirtualBox running a Ubuntu 16.04 guest, with the same QT versions as OP said. It happens for me with about a 30% chance.

**Comment by SomberNight** [comment]
It does't actually depend on the QT version..
I've updated pyqt5, and it still happens.
```
Qt version: 5.10.0
SIP version: 4.19.7
PyQt version: 5.10
```

BUT it does not happen with KDE...

-----

Ok, so it happens on Ubuntu 16.04 with Unity; irrespective of QT version.

**Comment by ecdsa** [comment]
@SomberNight I am not sure if we really want to add that kind of fix to electru code, because it seems to be a  Qt bug. perhaps we should consider this as "out of scope" ?

**Comment by SomberNight** [comment]
@danielcft Can you confirm you too used Unity, when experiencing this?

@ecdsa I am not fully certain it is a Qt bug.. How about monkey-patching it for this specific case as below:
```patch
diff --git a/gui/qt/main_window.py b/gui/qt/main_window.py
index ddaafc4b..d1661127 100644
--- a/gui/qt/main_window.py
+++ b/gui/qt/main_window.py
@@ -1554,6 +1554,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
         def on_signed(result):
             callback(True)
         def on_failed(exc_info):
+            wd.destroy()  # sometimes it won't close... see #3956
             self.on_error(exc_info)
             callback(False)
 
@@ -1564,8 +1565,8 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
             # call hook to see if plugin needs gui interaction
             run_hook('sign_tx', self, tx)
             task = partial(self.wallet.sign_transaction, tx, password)
-        WaitingDialog(self, _('Signing transaction...'), task,
-                      on_signed, on_failed)
+        wd = WaitingDialog(self, _('Signing transaction...'), task,
+                           on_signed, on_failed)
 
     def broadcast_transaction(self, tx, tx_desc):
```

**Comment by SomberNight** [comment]
Oh wait, actually; let's do this:

```patch
diff --git a/gui/qt/util.py b/gui/qt/util.py
index 369c05e8..9f975e00 100644
--- a/gui/qt/util.py
+++ b/gui/qt/util.py
@@ -225,6 +225,7 @@ class WaitingDialog(WindowModalDialog):
         if isinstance(parent, MessageBoxMixin):
             parent = parent.top_level_window()
         WindowModalDialog.__init__(self, parent, _("Please wait"))
+        self.setAttribute(Qt.WA_DeleteOnClose)  # see #3956
         vbox = QVBoxLayout(self)
         vbox.addWidget(QLabel(message))
         self.accepted.connect(self.on_accepted)
```

**Comment by SomberNight** [comment]
Ok, well this doesn't quite work...
There is a race condition, and occasionally this deletion happens too soon :(
```
QThread: Destroyed while thread is still running
Segmentation fault (core dumped)
```

**Comment by donob4n** [comment]
Hi,

I'm experimenting heavily this problem, all "WaitingDialog" that appear remain visible forever...  

I am running master github version on Fedora-32/Qubes OS and ended here while looking at code:     `self.thread.finished.connect(self.deleteLater)  # see #3956` gui/qt/util.py

Before digging more deep into the problem I am wondering if this solution is pretty overhead especially for very fast tasks like opening the "Confirm Transaction" dialog. For this kind of situations Qt provides two built in solutions:
- QProgressBar which is directly not shown if the load time is not greater than a minimum delay.
- Change cursor to BusyCursor while doing some task so the user knows some action is being processed without the need of opening a new window. This can be easily done with: 
```
@contextmanager
def busy_cursor():
    try:
        QtWidgets.QApplication.setOverrideCursor(QtCore.Qt.BusyCursor)
        yield
    finally:
        QtWidgets.QApplication.restoreOverrideCursor()
```

If you like the idea I can do a pull request.

**Comment by SomberNight** [comment]
Is it `WaitingDialog` or `BlockingWaitingDialog` that are problematic for you?

> especially for very fast tasks like opening the "Confirm Transaction" dialog

Note that e.g. for large wallets that action might take several seconds.
In other cases, E.g. in PreviewTxDialog, sometimes we might make a network request, but usually not.

> Qt provides two built in solutions
> Change cursor to BusyCursor while doing some task so the user knows some action is being processed without the need of opening a new window. 

If for whatever reason the program hangs, I would prefer if there was a clear message about what it was doing before it hanged.
Changing the cursor does not provide this.

> QProgressBar which is directly not shown if the load time is not greater than a minimum delay.

That sounds good.

**Comment by donob4n** [comment]
> Is it `WaitingDialog` or `BlockingWaitingDialog` that is problematic for you?

I am not sure.  If I prepare a transaction, click on "Pay...", then cancel and click again "Pay...", I have a new phantom "Please wait" window per each time I clicked on "Pay...".

**Comment by donob4n** [comment]
It is a `BlockingWaitingDialog` inside `ConfirmTxDialog` init.

**Comment by donob4n** [comment]
I think that the problem is calling `self.accept()` inside `__init__()` , I had similar problem on another project and solved moving the accept() to the class that constructed the dialog.

The problem with the 'QProgressBar' solution is that is not really multi thread so the "heavy" task needs to be aware of the 'QProgressBar' for calling setValue() (it updates the progress % if used and also redraws the GUI) so maybe it needs a little rewrite. (Not many, I only see BlockWaitingDialog in two or three places).

**Comment by donob4n** [comment]
Well, after doing some tests I discovered that the `self.accept()` closes the dialog if I add a `time.sleep(5)` inside the task function.

Probably my computer performs the task so quickly that the `accept()` is called before the dialog has been created. I am thinking on some solution but I don't find something simple without too much rewrite. QProgressDialog are nice but you need to call frequently their setValue() method or at least release the main loop thread using a QThread or similar.

What do you think if I rewrite the `BlockingWaitingDialog` as a static method that creates a new Dialog (maybe a QProgressDialog), then does the task and finally accepts/close/deletes it?

Maybe if we are lucky enough we get that builtin effect on QProgressDialog that hides the dialog until the task elapses more than X delay (default is 4 seconds).

**Comment by SomberNight** [comment]
> What do you think if I rewrite the BlockingWaitingDialog as a static method that creates a new Dialog (maybe a QProgressDialog), then does the task and finally accepts/close/deletes it?
> Maybe if we are lucky enough we get that builtin effect on QProgressDialog that hides the dialog until the task elapses more than X delay (default is 4 seconds).

Sounds good.

Note that `BlockingWaitingDialog` is atm assumed to be created on the main GUI thread and runs the task there (although looking at the code it does not seem to be utilising this much; in current usages the tasks are hardly touching GUI elements). Not sure how this would work with `QProgressDialog`.

> Well, after doing some tests I discovered that the self.accept() closes the dialog if I add a time.sleep(5) inside the task function.
> Probably my computer performs the task so quickly that the accept() is called before the dialog has been created.

Have you tried calling `QCoreApplication.processEvents()` a bunch of times right before `self.accept()`?
But anyway that would be quite hacky; using `QProgressDialog` sounds nicer.

**Comment by donob4n** [comment]
Adding a few `QCoreApplication.processEvents()` does not help and I also discovered that there is no real need for calling it. Using this "wait" works:
```
i = 0
while i < 1000000:
      #QTcorreApplication.processEvents()
      i = i + 1
self.accept()
```
Uncommenting `processEvents()` it "waits" a lot more but is really no need for calling it. This in some way "good" because that I was afraid that calling `time.sleep()` was in some way releasing the GUI thread so it can draw the window.

Maybe all the problem will be solved if there is some function that waits until a window is drawn/shown...

**Comment by SomberNight** [comment]
reopening re `BlockingWaitingDialog` issues.
As last few comments already pointed out, on some systems `BlockingWaitingDialog` will sometimes not get drawn properly or not get closed properly.

**Comment by bitromortac** [comment]
I see this often in QubesOS as well.

**Comment by SomberNight** [comment]
> As last few comments already pointed out, on some systems `BlockingWaitingDialog` will sometimes not get drawn properly or not get closed properly.

"not get closed properly" part maybe solved by https://github.com/spesmilo/electrum/commit/57ec9612cb3395bfc1237c56efb3c3fdb144145f
