### ISSUE TITLE
crash: wallet.get_full_history - datetime.fromtimestamp

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3960]
On git master https://github.com/spesmilo/electrum/commit/c1d2aabd54a3ab30603a97eae865aed35e925342.

On Windows 10, with python 3.6.4

```
Traceback (most recent call last):
  File "...\electrum\gui\qt\__init__.py", line 217, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "...\electrum\gui\qt\__init__.py", line 179, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "...\electrum\gui\qt\main_window.py", line 198, in __init__
    self.load_wallet(wallet)
  File "...\electrum\lib\util.py", line 278, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "...\electrum\lib\util.py", line 274, in do_profile
    o = func(*args, **kw_args)
  File "...\electrum\gui\qt\main_window.py", line 341, in load_wallet
    self.history_list.update()
  File "...\electrum\gui\qt\util.py", line 490, in update
    self.on_update()
  File "...\electrum\lib\util.py", line 278, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "...\electrum\lib\util.py", line 274, in do_profile
    o = func(*args, **kw_args)
  File "...\electrum\gui\qt\history_list.py", line 205, in on_update
    r = self.wallet.get_full_history(domain=self.get_domain(), from_timestamp=self.start_timestamp, to_timestamp=self.end_timestamp, fx=fx)
  File "...\electrum\lib\util.py", line 278, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "...\electrum\lib\util.py", line 274, in do_profile
    o = func(*args, **kw_args)
  File "...\electrum\lib\wallet.py", line 1003, in get_full_history
    item['date'] = timestamp_to_datetime(timestamp) if timestamp is not None else None
  File "...\electrum\lib\util.py", line 423, in timestamp_to_datetime
    return datetime.fromtimestamp(timestamp)
OSError: [Errno 22] Invalid argument
```

I've printed the value of timestamp and it is `False`.

```
>>> from datetime import datetime
>>> datetime.fromtimestamp(False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

(EDIT: I've just realised that I have very minor changes, so some line numbers might be a bit off --- but they are unrelated otherwise)

**Comment by SomberNight** [comment]
maybe `get_tx_height` could return `None` instead of `False`
https://github.com/spesmilo/electrum/blob/5e7c1330d4d3d0bad0745cd897c05f9ffafd70ee/lib/wallet.py#L464-L469

**Comment by ecdsa** [comment]
right it should be None
