### ISSUE TITLE
Crash on plot

### ISSUE THREAD

**Issue by xsmile** [spesmilo/electrum#3961]
Version: 3.0.6
Transaction count: 1 (incoming)

Electrum crashes if a plot is requested with Wallet -> History -> Plot.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/electrum_gui/qt/main_window.py", line 2321, in plot_history_dialog
    plt = plot_history(self.wallet, history)
  File "/usr/lib/python3.6/site-packages/electrum/plot.py", line 49, in plot_history
    dates, values = zip(*sorted(hist_out.items()))
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by SomberNight** [comment]
I believe this was fixed by https://github.com/spesmilo/electrum/pull/3488 (but the fix is not yet in a release)
However, I've found a related still not fixed bug; so thank you.
