### ISSUE TITLE
Daemon with Coldstorage not working

### ISSUE THREAD

**Issue by marcelomorgado** [spesmilo/electrum#4080]
Hi, I'm trying to interact with my coldstorage wallet using electrum daemon but it's not working:
1) electrum daemon start (OK)
2) electrum load_wallet -w /path/to/my/coldstorage/wallet/watch_only
Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.4/dist-packages/electrum/bitcoin.py", line 412, in address_to_script | BaseException: unknown address type
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.4/dist-packages/electrum/daemon.py", line 174, in run_daemon
    wallet = self.load_wallet(path, config.get('password'))
  File "/usr/local/lib/python3.4/dist-packages/electrum/daemon.py", line 240, in load_wallet
    wallet.start_threads(self.network)
  File "/usr/local/lib/python3.4/dist-packages/electrum/wallet.py", line 973, in start_threads
    self.synchronizer = Synchronizer(self, network)
  File "/usr/local/lib/python3.4/dist-packages/electrum/synchronizer.py", line 53, in __init__
    self.initialize()
  File "/usr/local/lib/python3.4/dist-packages/electrum/synchronizer.py", line 179, in initialize
    self.subscribe_to_addresses(set(self.wallet.get_addresses()))
  File "/usr/local/lib/python3.4/dist-packages/electrum/synchronizer.py", line 76, in subscribe_to_addresses
    self.network.subscribe_to_addresses(addresses, self.on_address_status)
  File "/usr/local/lib/python3.4/dist-packages/electrum/network.py", line 631, in subscribe_to_addresses
    hashes = [self.addr_to_scripthash(addr) for addr in addresses]
  File "/usr/local/lib/python3.4/dist-packages/electrum/network.py", line 631, in <listcomp>
    hashes = [self.addr_to_scripthash(addr) for addr in addresses]
  File "/usr/local/lib/python3.4/dist-packages/electrum/network.py", line 616, in addr_to_scripthash
    h = bitcoin.address_to_scripthash(addr)
  File "/usr/local/lib/python3.4/dist-packages/electrum/bitcoin.py", line 416, in address_to_scripthash
    script = address_to_script(addr)
  File "/usr/local/lib/python3.4/dist-packages/electrum/bitcoin.py", line 412, in address_to_script
    raise BaseException('unknown address type')
BaseException: unknown address type
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 411, in <module>
    result = server.daemon(config_options)
  File "/usr/local/lib/python3.4/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.4/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.4/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.4/dist-packages/electrum/bitcoin.py", line 412, in address_to_script | BaseException: unknown address type\n')

**Comment by SomberNight** [comment]
What version of Electrum?
What kind of addresses do you have in that wallet? Please paste one here; at least the first few chars.
Is it perhaps a testnet/mainnet mixup?

**Comment by marcelomorgado** [comment]
You are right!
Now it's working. Thank you.
