### ISSUE TITLE
Android app crashes when importing p2sh privkey

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4197]
On git master d69318ff148f99c2b77ba8acd17a7988797191cd.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/lib/daemon.py", line 311, in init_gui
    self.gui.main()
  File "/home/user/wspace/electrum/gui/kivy/__init__.py", line 62, in main
    w.run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 342, in idle
    self.dispatch_input()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
  File "/usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7681)
  File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
  File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:12356)
  File "/usr/lib/python3/dist-packages/kivy/lang/builder.py", line 64, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "<string>", line 23, in <module>
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
  File "/home/user/wspace/electrum/gui/kivy/uix/dialogs/installwizard.py", line 478, in on_release
    self.run_next(*params)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 168, in on_import
    w.import_private_key(x, None)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1971, in import_private_key
    raise BitcoinException('Redeem script required for script type {}'.format(txin_type))
electrum.util.BitcoinException: Redeem script required for script type p2sh
```

**Comment by SomberNight** [comment]
closing for https://github.com/spesmilo/electrum/issues/4512
