### ISSUE TITLE
List Index out of Range: Trezor & Electrum TX import

### ISSUE THREAD

**Issue by vzelenko** [spesmilo/electrum#4229]
# Unable to import unsigned transaction

## Problem

I have setup an Electrum 3.1.2 on Windows as Read-only wallet, and on Ubuntu 16.04 64bit as an Offline wallet.

Both wallets use Trezor as hardware key storage, 3-of-2 setup, with online wallet seeded with xPub keys in the same sequence as the Cold wallet was seeded.

The readonly wallet receives some BTC, then creates an UNSIGNED transaction that is saved in a file 'transaction.txt'.  This file then transported to Cold wallet, loaded and attempt to sign is made.

The issue does not happen when Cold wallet is running on Mac OS (my dev box).  It only happens when it is on Windows 7 && Ubuntu 16.04.

## Error Details

It happens when electrum is run either with python 3.5 (ubuntu's default) or 3.6.4.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/electrum_gui/qt/util.py", line 639, in run
    result = task.task()
  File "/usr/local/lib/python3.6/site-packages/electrum/wallet.py", line 1465, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python3.6/site-packages/electrum_plugins/trezor/trezor.py", line 76, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/local/lib/python3.6/site-packages/electrum_plugins/trezor/trezor.py", line 271, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/usr/local/lib/python3.6/site-packages/electrum_plugins/trezor/clientbase.py", line 234, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezor-0.9.1-py3.6.egg/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezor-0.9.1-py3.6.egg/trezorlib/client.py", line 995, in sign_tx
    msg._extend_bin_outputs([current_tx.bin_outputs[res.details.request_index], ])
IndexError: list index out of range
```

PLEASE HELP

**Comment by SomberNight** [comment]
Offline signing with Trezor does not work for legacy inputs. It works with segwit inputs (though segwit multisig for hardware wallets is disabled atm due to there not being a standard of what derivation to use for keys).

See https://github.com/spesmilo/electrum/issues/3302
