### ISSUE TITLE
I can not send bitcoins from my wallet

### ISSUE THREAD

**Issue by zemelax** [spesmilo/electrum#4310]
Electrum-3.1.3
Linux Ubuntu 16.04

Everything was fine, I did not go into my wallet for a long time.
Today bitcoins were sent and I decided to withdraw them and could not.
when I click on the send button or the preview nothing happens (
I thought that the reason for updating the wallet, was updated and the problem remained. + I get an error message when entering the wallet, but I can not send it, writes
server is busy or an error in the wallet.

![2018-04-25 21-28-09](https://user-images.githubusercontent.com/32588633/39265650-7d897fa8-48d0-11e8-968f-9fb79ab61c55.png)
![2018-04-25 21-28-42](https://user-images.githubusercontent.com/32588633/39265651-7daa044e-48d0-11e8-8132-d44c7b1f40a9.png)

**Comment by SomberNight** [comment]
Please click `Show report contents` and copy-paste that here, or take a picture of that.

**Comment by zemelax** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 787, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Соединение разорвано другой стороной

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 787, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)

**Comment by zemelax** [comment]
I did not understand the question about 2fa)  No like I'm not a restrictive firewall)
Although I do not know, we now in Russia are struggling with a telegram and blocking the IP, maybe it's related somehow?

**Comment by bauerj** [comment]
What do you see on https://api.trustedcoin.com/?

**Comment by zemelax** [comment]
no changes

**Comment by SomberNight** [comment]
Can you try with a Tor proxy?
Start tor in the background, and configure Electrum to connect to the local SOCKS proxy the tor process sets up:
In Electrum, go into the network dialog (e.g. click the coloured orb in the bottom right), then `Proxy` tab. There should be a checkbox `Use Tor proxy at port ...`. Check that. (also try restarting Electrum after this, just to make sure)
