### ISSUE TITLE
Qt wizard does blocking hw wallet IO in main thread

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4341]
![wizard_blocking_io](https://user-images.githubusercontent.com/29142493/39664077-2b799f8a-507e-11e8-9c04-1d0c20dab5f4.PNG)

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 464, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 203, in start_new_window
    wallet = wizard.run_and_get_wallet(self.daemon.get_wallet)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 305, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 74, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 101, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 83, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 119, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 74, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 151, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 83, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 74, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 247, in choose_hw_device
    self.choice_dialog(title=title, message=msg, choices=choices, run_next= lambda *args: self.on_device(*args, purpose=purpose))
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 83, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 247, in 
    self.choice_dialog(title=title, message=msg, choices=choices, run_next= lambda *args: self.on_device(*args, purpose=purpose))
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 252, in on_device
    self.plugin.setup_device(device_info, self, purpose)
  File "/home/user/wspace/electrum/plugins/trezor/trezor.py", line 264, in setup_device
    client.get_xpub('m', 'standard')
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 174, in get_xpub
    node = self.get_public_node(address_n, creating).node
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 238, in wrapped
    return func(self, *args, **kwargs)
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 215, in get_public_node
    return super(TrezorClientBase, self).get_public_node(address_n)
  File "/home/user/.local/lib/python3.5/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/trezorlib/client.py", line 560, in get_public_node
    return self.call(proto.GetPublicKey(address_n=n, ecdsa_curve_name=ecdsa_curve_name, show_display=show_display, coin_name=coin_name))
  File "/home/user/.local/lib/python3.5/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 41, in callback_ButtonRequest
    raise Exception("unwind stack")
Exception: unwind stack
```
This is also the cause of https://github.com/spesmilo/electrum/issues/3377

**Comment by SomberNight** [comment]
somewhat fixed by https://github.com/spesmilo/electrum/commit/371f55a0f922cf57196ae3d8d7c2fabc7a9f0f08
