### ISSUE TITLE
Error every time I need to use password

### ISSUE THREAD

**Issue by awesom3p** [spesmilo/electrum#4364]
I get this error when I try to send any coins:

Traceback (most recent call last):
  File "site-packages\electrum-3.1.3-py3.5.egg\electrum\keystore.py", line 106, in sign_transaction
  File "site-packages\electrum-3.1.3-py3.5.egg\electrum\keystore.py", line 140, in check_password
  File "site-packages\electrum-3.1.3-py3.5.egg\electrum\keystore.py", line 160, in get_private_key
  File "site-packages\electrum-3.1.3-py3.5.egg\electrum\bitcoin.py", line 515, in deserialize_privkey
KeyError: 71

Can't change password as it says it failed, and cant get private keys as it gives the same error.

**Comment by SomberNight** [comment]
I have troubleshooted with this user for 2+ hours on irc.
He has a keystore-encrypted imported wallet with a single private key imported.
That key became corrupted somehow..
```
pubkey, wif_ciphertext = list(wallet.keystore.keypairs.items())[0]
wif_key = pw_decode(wif_ciphertext, password)
```
`wif_key` is a 51-long string that starts with a "7". It has a valid base58 checksum.

**Comment by dabura667** [comment]
Perhaps the private key isn’t 32 bytes.

Try encoding a 31 byte as a compressed WIF and uncompressed WIF. Do either have a 7 at the beginning?

If so try appending chr(0) to the left until it’s 32 bytes.
