### ISSUE TITLE
[Android] Electrum 3.1.3 refuses to open (Insta-crash)

### ISSUE THREAD

**Issue by HardCorePawn** [spesmilo/electrum#4378]
Device: Samsung Galaxy S5
OS: Latest LineageOS 14.1 (Android 7.1.2, 18 May 2018)
Electrum Version: 3.1.3.0 (from Google Play Store)

As soon as I attempt to start the app, it crashes... a "toast" message pops up that says "Could not extract private data" and then the following exception is found in logcat:
```
05-25 11:31:37.795   719  9898 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.electrum.electrum/org.kivy.android.PythonActivity (has extras)} from uid 10027 on display 0
05-25 11:31:37.843   719   751 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10027)
05-25 11:31:37.891   719 15313 I ActivityManager: Start proc 31160:org.electrum.electrum/u0a138 for activity org.electrum.electrum/org.kivy.android.PythonActivity
05-25 11:31:37.907   719   719 D ZenLog  : intercepted: 0|android|17039403|null|1000,alarmsOnly
05-25 11:31:37.908   719   719 V NotificationService: pkg=android canInterrupt=false intercept=true
05-25 11:31:37.965 31160 31160 I art     : Starting a blocking GC AddRemoveAppImageSpace
05-25 11:31:37.991 31160 31160 W ContextImpl: Failed to ensure /mnt/expand/bd862995-d5b8-4cfb-8d8d-05a20d21ffbc/user/0/org.electrum.electrum/cache: mkdir failed: EACCES (Permission denied)
05-25 11:31:37.995 31160 31160 W ContextImpl: Failed to ensure /mnt/expand/bd862995-d5b8-4cfb-8d8d-05a20d21ffbc/user_de/0/org.electrum.electrum/code_cache: mkdir failed: ENOENT (No such file or directory)
05-25 11:31:38.074 31160 31171 W art     : Suspending all threads took: 70.462ms
05-25 11:31:38.089 31160 31171 I art     : Background partial concurrent mark sweep GC freed 22809(956KB) AllocSpace objects, 0(0B) LOS objects, 42% free, 5MB/9MB, paused 71.114ms total 102.587ms
05-25 11:31:38.118 31160 31160 V PythonActivity: My oncreate running
05-25 11:31:38.118 31160 31160 V PythonActivity: About to do super onCreate
05-25 11:31:38.118 31160 31160 V SDL     : Device: klte
05-25 11:31:38.118 31160 31160 V SDL     : Model: SM-G900F
05-25 11:31:38.118 31160 31160 V SDL     : onCreate():null
05-25 11:31:38.118 31160 31160 V PythonActivity: Did super onCreate
05-25 11:31:38.118 31160 31160 V SDL     : getting identifier
05-25 11:31:38.118 31160 31160 V SDL     : kind is drawable and name presplash
05-25 11:31:38.118 31160 31160 V SDL     : result is 2130837506
05-25 11:31:38.129 31160 31160 V SDL     : asked to get string presplash_color
05-25 11:31:38.129 31160 31160 V SDL     : getting identifier
05-25 11:31:38.129 31160 31160 V SDL     : kind is string and name presplash_color
05-25 11:31:38.130 31160 31160 V SDL     : result is 2131099649
05-25 11:31:38.146 31160 31181 V PythonActivity: Ready to unpack
05-25 11:31:38.146 31160 31181 V PythonActivity: UNPACKING!!! private app
05-25 11:31:38.147 31160 31181 V SDL     : asked to get string private_version
05-25 11:31:38.147 31160 31181 V SDL     : getting identifier
05-25 11:31:38.147 31160 31181 V SDL     : kind is string and name private_version
05-25 11:31:38.147 31160 31181 V SDL     : result is 2131099650
05-25 11:31:38.147 31160 31181 V PythonActivity: Data version is 1523898138.9724207
05-25 11:31:38.148 31160 31160 V PythonActivity: onResume()
05-25 11:31:38.148 31160 31160 V SDL     : onResume()
05-25 11:31:38.153 31160 31181 V PythonActivity: Extracting private assets.
05-25 11:31:38.155   908   923 I art     : Background partial concurrent mark sweep GC freed 117083(5MB) AllocSpace objects, 43(2MB) LOS objects, 26% free, 43MB/59MB, paused 560us total 132.551ms
05-25 11:31:38.175 31160 31181 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-25 11:31:38.175 31160 31181 E AndroidRuntime: Process: org.electrum.electrum, PID: 31160
05-25 11:31:38.175 31160 31181 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
05-25 11:31:38.175 31160 31181 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at org.kivy.android.PythonActivity.recursiveDelete(PythonActivity.java:84)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at org.kivy.android.PythonActivity.unpackData(PythonActivity.java:245)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at org.kivy.android.PythonActivity$UnpackFilesTask.doInBackground(PythonActivity.java:119)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at org.kivy.android.PythonActivity$UnpackFilesTask.doInBackground(PythonActivity.java:114)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 11:31:38.175 31160 31181 E AndroidRuntime:        ... 4 more
05-25 11:31:38.181   719 15311 W ActivityManager:   Force finishing activity org.electrum.electrum/org.kivy.android.PythonActivity
05-25 11:31:38.190 31160 31160 V PythonActivity: onPause()
```

I even attempted to manually create the two "missing" directories (/mnt/expand/bd862995-d5b8-4cfb-8d8d-05a20d21ffbc/user/0/org.electrum.electrum/cache and /mnt/expand/bd862995-d5b8-4cfb-8d8d-05a20d21ffbc/user_de/0/org.electrum.electrum/code_cache) but the app still crashes with the NPE:

```
05-25 11:46:07.459   719 23395 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.electrum.electrum/org.kivy.android.PythonActivity (has extras)} from uid 10027 on display 0
05-25 11:46:07.473   719   751 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10027)
05-25 11:46:07.526   719  2024 I ActivityManager: Start proc 888:org.electrum.electrum/u0a138 for activity org.electrum.electrum/org.kivy.android.PythonActivity
05-25 11:46:07.544   719   719 D ZenLog  : intercepted: 0|android|17039403|null|1000,alarmsOnly
05-25 11:46:07.545   719   719 V NotificationService: pkg=android canInterrupt=false intercept=true
05-25 11:46:07.564   888   888 I art     : Starting a blocking GC AddRemoveAppImageSpace
05-25 11:46:07.590   888   888 V PythonActivity: My oncreate running
05-25 11:46:07.590   888   888 V PythonActivity: About to do super onCreate
05-25 11:46:07.590   888   888 V SDL     : Device: klte
05-25 11:46:07.590   888   888 V SDL     : Model: SM-G900F
05-25 11:46:07.590   888   888 V SDL     : onCreate():null
05-25 11:46:07.590   888   888 V PythonActivity: Did super onCreate
05-25 11:46:07.590   888   888 V SDL     : getting identifier
05-25 11:46:07.590   888   888 V SDL     : kind is drawable and name presplash
05-25 11:46:07.590   888   888 V SDL     : result is 2130837506
05-25 11:46:07.606   888   888 V SDL     : asked to get string presplash_color
05-25 11:46:07.606   888   888 V SDL     : getting identifier
05-25 11:46:07.606   888   888 V SDL     : kind is string and name presplash_color
05-25 11:46:07.607   888   888 V SDL     : result is 2131099649
05-25 11:46:07.617   888   936 V PythonActivity: Ready to unpack
05-25 11:46:07.617   888   936 V PythonActivity: UNPACKING!!! private app
05-25 11:46:07.617   888   936 V SDL     : asked to get string private_version
05-25 11:46:07.617   888   936 V SDL     : getting identifier
05-25 11:46:07.617   888   936 V SDL     : kind is string and name private_version
05-25 11:46:07.618   888   936 V SDL     : result is 2131099650
05-25 11:46:07.618   888   936 V PythonActivity: Data version is 1523898138.9724207
05-25 11:46:07.618   888   888 V PythonActivity: onResume()
05-25 11:46:07.618   888   888 V SDL     : onResume()
05-25 11:46:07.619   888   936 V PythonActivity: Extracting private assets.
05-25 11:46:07.621   888   936 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-25 11:46:07.621   888   936 E AndroidRuntime: Process: org.electrum.electrum, PID: 888
05-25 11:46:07.621   888   936 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-25 11:46:07.621   888   936 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
05-25 11:46:07.621   888   936 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
05-25 11:46:07.621   888   936 E AndroidRuntime:        at org.kivy.android.PythonActivity.recursiveDelete(PythonActivity.java:84)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at org.kivy.android.PythonActivity.unpackData(PythonActivity.java:245)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at org.kivy.android.PythonActivity$UnpackFilesTask.doInBackground(PythonActivity.java:119)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at org.kivy.android.PythonActivity$UnpackFilesTask.doInBackground(PythonActivity.java:114)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-25 11:46:07.621   888   936 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 11:46:07.621   888   936 E AndroidRuntime:        ... 4 more
05-25 11:46:07.624   719 15311 W ActivityManager:   Force finishing activity org.electrum.electrum/org.kivy.android.PythonActivity
05-25 11:46:07.652   888   888 V PythonActivity: onPause()
```

**Comment by SomberNight** [comment]
Is it "Could not extract private data" or "Could not extract public data"?

May be related:
https://github.com/kivy/python-for-android/issues/260
https://kivy.org/docs/faq.html#could-not-extract-public-data

**Comment by HardCorePawn** [comment]
Definitely "private data"

**Comment by ecdsa** [comment]
closing, too old
