### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: .... but only under normal user (not root)

### ISSUE THREAD

**Issue by geomule** [spesmilo/electrum#4385]
Hi,
I've downloaded the electrum version 3.0.6-1 that is on Debian Stretch backports. There is no way to get it fired up under a normal user. The errors are below. The version of python installed on my system is 3.5.3-1. I find it strange that it fires up is i run "sudo electrum -v" but it doesn't if I don't. It's clearly a question of permissions but can't work out if this is a electrum issue of not. Any pointers?

Thanks

(base) [dom mag 27, 05:58 ][user@system1:~]electrum -v
Traceback (most recent call last):
  File "/usr/bin/electrum", line 80, in <module>
    check_imports()
  File "/usr/bin/electrum", line 64, in check_imports
    import pbkdf2
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "<frozen importlib._bootstrap_external>", line 826, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/pbkdf2.py'

**Comment by AbdussamadA** [comment]
remove it using apt-get remove and then install the latest version using pip3 as per the instructions on electrum.org/#download.

**Comment by geomule** [comment]
Yes, I already tried that. It has exactly the same problem. The pip3 solution install the binary in /use/local/bin/ on Debian Stretch. I initially thought it was a permission problem. The binary is installed with the "staff" group. My user is member of that group. I logged out an in again to ensure permission would reload on login. It hasn't helped.

This seems to be a python permission problem maybe although I don't have similar problems with other python apps.
