### ISSUE TITLE
Can't send coins

### ISSUE THREAD

**Issue by petrtyurkin** [spesmilo/electrum#4434]
Traceback
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 326, in connect
  File "site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "ssl.py", line 385, in wrap_socket
  File "ssl.py", line 760, in __init__
  File "ssl.py", line 996, in do_handshake
  File "ssl.py", line 641, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 357, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 326, in connect
  File "site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "ssl.py", line 385, in wrap_socket
  File "ssl.py", line 760, in __init__
  File "ssl.py", line 996, in do_handshake
  File "ssl.py", line 641, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\electrum-3.1.3-py3.5.egg\electrum\util.py", line 794, in run_with_except_hook
  File "threading.py", line 862, in run
  File "E:\Soft\Trading\Electrum\electrum_plugins\trustedcoin\trustedcoin.py", line 343, in request_billing_info
    billing_info = server.get(wallet.get_user_id()[1])
  File "E:\Soft\Trading\Electrum\electrum_plugins\trustedcoin\trustedcoin.py", line 153, in get
    return self.send_request('get', 'cosigner/%s' % quote(id))
  File "E:\Soft\Trading\Electrum\electrum_plugins\trustedcoin\trustedcoin.py", line 103, in send_request
    response = requests.request(method, url, **kwargs)
  File "site-packages\requests\api.py", line 58, in request
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
 
Additional information
Electrum version: 3.1.3 
Operating system: Windows-7-6.1.7601-SP1 
Wallet type: 2fa 
Locale: ru_RU

**Comment by SomberNight** [comment]
I'm closing this but can reopen if it's not resolved.
