### ISSUE TITLE
JSONDecodeError for crash reporter on kivy 

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4456]
(ignore the first trace for the purposes of this issue)
```
06-22 17:33:21.536  6364  6477 I python  : INFO:kivy:[network event] updated
06-22 17:33:21.536  6364  6477 I python  : [INFO   ] [network event] interfaces
06-22 17:33:21.537  6364  6477 I python  : INFO:kivy:[network event] interfaces
06-22 17:33:21.798  6364  6397 I python  : [b]Traceback[/b]
06-22 17:33:21.798  6364  6397 I python  : 
06-22 17:33:21.798  6364  6397 I python  : [i]Traceback (most recent call last):
06-22 17:33:21.798  6364  6397 I python  :   File "./lib/util.py", line 856, in run_with_except_hook
06-22 17:33:21.798  6364  6397 I python  :     run_original(*args2, **kwargs2)
06-22 17:33:21.798  6364  6397 I python  :   File "./lib/interface.py", line 237, in run
06-22 17:33:21.798  6364  6397 I python  :     socket = self.get_socket()
06-22 17:33:21.798  6364  6397 I python  :   File "./lib/interface.py", line 152, in get_socket
06-22 17:33:21.798  6364  6397 I python  :     if s and self.check_host_name(s.getpeercert(), self.host):
06-22 17:33:21.798  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/stdlib.zip/ssl.py", line 897, in getpeercert
06-22 17:33:21.798  6364  6397 I python  :     self._check_connected()
06-22 17:33:21.798  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/stdlib.zip/ssl.py", line 861, in _check_connected
06-22 17:33:21.798  6364  6397 I python  :     self.getpeername()
06-22 17:33:21.798  6364  6397 I python  : OSError: [Errno 107] Transport endpoint is not connected
06-22 17:33:21.798  6364  6397 I python  : [/i]
06-22 17:33:21.798  6364  6397 I python  : 
06-22 17:33:21.798  6364  6397 I python  : 
06-22 17:33:21.798  6364  6397 I python  : [b]Additional information[/b]
06-22 17:33:21.798  6364  6397 I python  :  * Electrum version: 3.1.3
06-22 17:33:21.798  6364  6397 I python  :  * Operating system: Android 8.1.0 on google bullhead (OPM6.171019.030.B1)
06-22 17:33:21.798  6364  6397 I python  :  * Wallet type: standard
06-22 17:33:21.798  6364  6397 I python  :  * Locale: ?
06-22 17:33:21.799  6364  6397 I python  :         
06-22 17:33:31.464  6364  6477 I python  : [INFO   ] [network event] interfaces
06-22 17:33:31.464  6364  6477 I python  : INFO:kivy:[network event] interfaces
...
06-22 17:35:49.785  6364  6477 I python  : [INFO   ] [network event] updated
06-22 17:35:49.785  6364  6477 I python  : INFO:kivy:[network event] updated
06-22 17:35:49.787  6364  6477 I python  : [INFO   ] [network event] interfaces
06-22 17:35:49.787  6364  6477 I python  : INFO:kivy:[network event] interfaces
06-22 17:36:29.879  6364  6397 I python  : [INFO   ] [Base        ] Leaving application in progress...
06-22 17:36:29.880  6364  6397 I python  : INFO:kivy:[Base        ] Leaving application in progress...
06-22 17:36:29.890  6364  6397 I python  : Traceback (most recent call last):
06-22 17:36:29.890  6364  6397 I python  :   File "./lib/daemon.py", line 311, in init_gui
06-22 17:36:29.891  6364  6397 I python  :     self.gui.main()
06-22 17:36:29.891  6364  6397 I python  :   File "./gui/kivy/__init__.py", line 62, in main
06-22 17:36:29.891  6364  6397 I python  :     w.run()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/app.py", line 826, in run
06-22 17:36:29.891  6364  6397 I python  :     runTouchApp()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/base.py", line 502, in runTouchApp
06-22 17:36:29.891  6364  6397 I python  :     EventLoop.window.mainloop()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
06-22 17:36:29.891  6364  6397 I python  :     self._mainloop()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
06-22 17:36:29.891  6364  6397 I python  :     EventLoop.idle()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/base.py", line 340, in idle
06-22 17:36:29.891  6364  6397 I python  :     self.dispatch_input()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/base.py", line 325, in dispatch_input
06-22 17:36:29.891  6364  6397 I python  :     post_dispatch_input(*pop(0))
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/base.py", line 291, in post_dispatch_input
06-22 17:36:29.891  6364  6397 I python  :     wid.dispatch('on_touch_up', me)
06-22 17:36:29.891  6364  6397 I python  :   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
06-22 17:36:29.891  6364  6397 I python  :     self.dispatch('on_release')
06-22 17:36:29.891  6364  6397 I python  :   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
06-22 17:36:29.891  6364  6397 I python  :   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
06-22 17:36:29.891  6364  6397 I python  :   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
06-22 17:36:29.891  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 64, in custom_callback
06-22 17:36:29.891  6364  6397 I python  :     exec(__kvlang__.co_value, idmap)
06-22 17:36:29.891  6364  6397 I python  :   File "<string>", line 41, in <module>
06-22 17:36:29.891  6364  6397 I python  :   File "./gui/kivy/uix/dialogs/crash_reporter.py", line 118, in send_report
06-22 17:36:29.891  6364  6397 I python  :     response = BaseCrashReporter.send_report(self, "/crash.json").json()
06-22 17:36:29.891  6364  6397 I python  :   File "/data/data/org.electrum.electrum/files/app/packages/requests/models.py", line 892, in json
06-22 17:36:29.892  6364  6397 I python  :     return complexjson.loads(self.text, **kwargs)
06-22 17:36:29.892  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/stdlib.zip/json/__init__.py", line 354, in loads
06-22 17:36:29.892  6364  6397 I python  :     return _default_decoder.decode(s)
06-22 17:36:29.892  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/stdlib.zip/json/decoder.py", line 339, in decode
06-22 17:36:29.892  6364  6397 I python  :     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
06-22 17:36:29.892  6364  6397 I python  :   File "/data/user/0/org.electrum.electrum/files/app/crystax_python/stdlib.zip/json/decoder.py", line 357, in raw_decode
06-22 17:36:29.892  6364  6397 I python  :     raise JSONDecodeError("Expecting value", s, err.value) from None
06-22 17:36:29.892  6364  6397 I python  : json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
@bauerj

**Comment by SomberNight** [comment]
So I guess we should catch JSONDecodeError (or ValueError) at
https://github.com/spesmilo/electrum/blob/5220451b7302fe98c2234ceaa08dbbc5040c8c94/gui/kivy/uix/dialogs/crash_reporter.py#L117-L121
though not sure what the underlying cause was

**Comment by bauerj** [comment]
I'm not sure either, can you reproduce the issue?
