### ISSUE TITLE
electrum 3.2.0 linux distributables missing wordlists

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#4475]
Trying to install electrum  for Ubuntu 18:
sudo apt-get install python3-setuptools python3-pyqt5 python3-pip
sudo pip3 install https://download.electrum.org/3.2.0/Electrum-3.2.0.tar.gz
it immediately crashes without any warning message in the "I already have a seed" option screen:

![screenshot from 2018-06-30 09-48-54](https://user-images.githubusercontent.com/5799190/42127331-3ca29624-7c4b-11e8-83a1-cb3985e353d4.png)
![screenshot from 2018-06-30 09-49-13](https://user-images.githubusercontent.com/5799190/42127332-408ff038-7c4b-11e8-8b59-f5ccfff9d5a5.png)

**Comment by bauerj** [comment]
Hey,

the following would help us to debug this issue:

Open a console window and run `electrum -v`. Try to make the wizard crash again. If it crashes, can you post the console output here?

**Comment by charleshsu168** [comment]
upon further investigation, this error in terminal:

[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 313, in init_gui
    self.gui.main()
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/__init__.py", line 291, in main
    if not self.start_new_window(path, self.config.get('url'), app_is_starting=True):
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/__init__.py", line 221, in start_new_window
    wallet = wizard.run_and_get_wallet(self.daemon.get_wallet)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 305, in run_and_get_wallet
    self.run(action)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 79, in run
    f(*args)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 106, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 130, in on_wallet_type
    self.run(action)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 76, in run
    f(self, *args)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 424, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(self.disclaimer_msg), run_next = lambda x: wizard.run('choose_seed'))
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 424, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(self.disclaimer_msg), run_next = lambda x: wizard.run('choose_seed'))
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 76, in run
    f(self, *args)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 433, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 76, in run
    f(self, *args)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 491, in restore_wallet
    wizard.restore_seed_dialog(run_next=f, test=self.is_valid_seed)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 79, in func_wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 403, in restore_seed_dialog
    return self.seed_input(title, message, test, options)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 371, in seed_input
    slayout = SeedLayout(title=message, is_seed=is_seed, options=options, parent=self)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/seed_dialog.py", line 109, in __init__
    self.initialize_completer()
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/seed_dialog.py", line 147, in initialize_completer
    english_list = Mnemonic('en').wordlist
  File "/usr/local/lib/python3.6/dist-packages/electrum/mnemonic.py", line 126, in __init__
    self.wordlist = load_wordlist(filename)
  File "/usr/local/lib/python3.6/dist-packages/electrum/mnemonic.py", line 94, in load_wordlist
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/electrum/wordlist/english.txt'

**Comment by charleshsu168** [comment]
electrum -v
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
[SimpleConfig] electrum directory /home/chuck/.electrum
[get_server] [Errno 111] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0038
[Network] blockchains dict_keys([0])
[Network] starting network
[Network] connecting to 74.222.1.20:50002:s as new interface
[ozahtqwp25chjdjd.onion] cannot resolve hostname
[FxThread] using exchange BitcoinAverage
[74.222.1.20] failed to connect [Errno 111] Connection refused
[electrum.poorcoding.com] failed to connect [Errno 111] Connection refused
[207.154.223.80] failed to connect [Errno 111] Connection refused
[WalletStorage] wallet path /home/chuck/.electrum/wallets/default_wallet
[WalletStorage] wallet path /home/chuck/.electrum/wallets/default_wallet
[btc.smsys.me] connected
[WalletStorage] wallet path /home/chuck/.electrum/wallets/default_wallet
[orannis.com] connected
[Network] switching to orannis.com:50002:s
[Network] sending subscriptions to orannis.com:50002:s 0 0
[enode.duckdns.org] connected
[spv.48.org] failed to connect [Errno 111] Connection refused
[electrumx-core.1209k.com] failed to connect [Errno 101] Network is unreachable
[Network] no height for main interface
[Network] switching to btc.smsys.me:995:s
[Network] sending subscriptions to btc.smsys.me:995:s 0 0
[Network] fee_histogram [[1, 5477445], [0, 826073]]
[Network] fee_estimates[25] 1081
[Network] relayfee 100
[Network] fee_estimates[10] 1132
[Network] fee_estimates[5] 4990
[Network] fee_estimates[2] 5401
[Network] fee_histogram [[1, 5486686]]
[Network] fee_estimates[25] 1080
[Network] fee_estimates[5] 4990
[electrum.hsmiths.com] connected
[elec.luggs.co] connected
[Network] relayfee 1000
[Network] fee_estimates[2] 5401
[Network] fee_estimates[10] 1132
[aspinall.io] connected
[electrum.nute.net] SSL certificate signed by CA
[electrum.nute.net] connected
[electrum.festivaldelhumor.org] connected
[Plugins] loaded trustedcoin
[elx2018.mooo.com] failed to connect timed out
[electrum.meltingice.net] failed to connect [Errno 111] Connection refused
[electrumx.bot.nu] connected
[electrumx.nmdps.net] failed to connect [Errno 101] Network is unreachable
[bauerjda5hnedjam.onion] cannot resolve hostname
[electrum0.snel.it] connected
language en
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 313, in init_gui
    self.gui.main()
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/__init__.py", line 291, in main
    if not self.start_new_window(path, self.config.get('url'), app_is_starting=True):
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/__init__.py", line 221, in start_new_window
    wallet = wizard.run_and_get_wallet(self.daemon.get_wallet)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 305, in run_and_get_wallet
    self.run(action)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 79, in run
    f(*args)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 106, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 130, in on_wallet_type
    self.run(action)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 76, in run
    f(self, *args)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 424, in show_disclaimer
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(self.disclaimer_msg), run_next = lambda x: wizard.run('choose_seed'))
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 424, in <lambda>
    wizard.confirm_dialog(title='Disclaimer', message='\n\n'.join(self.disclaimer_msg), run_next = lambda x: wizard.run('choose_seed'))
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 76, in run
    f(self, *args)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 433, in choose_seed
    wizard.choice_dialog(title=title, message=message, choices=choices, run_next=wizard.run)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 76, in run
    f(self, *args)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/trustedcoin/trustedcoin.py", line 491, in restore_wallet
    wizard.restore_seed_dialog(run_next=f, test=self.is_valid_seed)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 79, in func_wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 403, in restore_seed_dialog
    return self.seed_input(title, message, test, options)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/installwizard.py", line 371, in seed_input
    slayout = SeedLayout(title=message, is_seed=is_seed, options=options, parent=self)
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/seed_dialog.py", line 109, in __init__
    self.initialize_completer()
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/seed_dialog.py", line 147, in initialize_completer
    english_list = Mnemonic('en').wordlist
  File "/usr/local/lib/python3.6/dist-packages/electrum/mnemonic.py", line 126, in __init__
    self.wordlist = load_wordlist(filename)
  File "/usr/local/lib/python3.6/dist-packages/electrum/mnemonic.py", line 94, in load_wordlist
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/electrum/wordlist/english.txt'
[Plugins] stopped
[Daemon] shutting down network
[Network] stopping network
[Network] stopped
[Daemon] stopped

**Comment by SomberNight** [comment]
related? https://github.com/spesmilo/electrum/commit/56a399e1da2117992ec4dc4d794bf860740ea243

**Comment by bauerj** [comment]
@charleshsu168 Thanks, this will be fixed in a bugfix release 3.2.1 shortly.
