### ISSUE TITLE
"scripts" assume that 'server' in config is set

### ISSUE THREAD

**Issue by aghamir** [spesmilo/electrum#4519]
I tried to use [scripts](https://github.com/spesmilo/electrum/tree/master/scripts) in your repo. However, I got this error:
```
Traceback (most recent call last):
  File "estimate_fee", line 3, in <module>
    peers = util.get_peers()
  File "/home/mohammad/Desktop/Applications/electrum/scripts/util.py", line 55, in get_peers
    interfaces = get_interfaces([server])
  File "/home/mohammad/Desktop/Applications/electrum/scripts/util.py", line 18, in get_interfaces
    connecting[server] = Connection(server, socket_queue, config.path)
  File "/usr/local/lib/python3.5/dist-packages/electrum/interface.py", line 53, in Connection
    host, port, protocol = server.rsplit(':', 2)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```
After debugging, I found this line returns `None`:
https://github.com/spesmilo/electrum/blob/c6ccdbef90de0a96b5354125d090fc4dea8443cd/scripts/util.py#L53
Is there something that I missed?
Thanks a lot

**Comment by bauerj** [comment]
Sure, why not.

**Comment by aghamir** [comment]
Hi @SomberNight ,
Thanks a lot. Your respond is very helpful for me.
I got another error while explore scripts:
```Traceback (most recent call last):
  File "estimate_fee", line 4, in <module>
    results = util.send_request(peers, 'blockchain.estimatefee', [2])
  File "/home/mohammad/Desktop/Applications/electrum/scripts/util.py", line 72, in send_request
    interfaces = get_interfaces(peers)
  File "/home/mohammad/Desktop/Applications/electrum/scripts/util.py", line 19, in get_interfaces
    connecting[server] = Connection(server, socket_queue, config.path)
  File "/usr/local/lib/python3.5/dist-packages/electrum/interface.py", line 53, in Connection
    host, port, protocol = server.rsplit(':', 2)
ValueError: not enough values to unpack (expected 3, got 1)
```
I think interface.py assume there is port and protocol in server name. However, server name is like this `ozahtqwp25chjdjd.onion`.

**Comment by SomberNight** [comment]
Which script are you trying to run? and what is `server` set to in config (because that should include port and protocol like in my example)

**Comment by aghamir** [comment]
I ran `estimate_fee`. I've set server like you said before:
`electrum setconfig server testnet.qtornado.com:50002:s`
