### ISSUE TITLE
Exception and freeze on wallet recovery

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#4572]
It is very often that Electrum gets stuck on wallet recovery, I tried 10 times and only 2 of them were successful.  It gets stuck when I use socks5 and also when it's a direct network connection. Obviously it is more noticeable on larger wallets, when Electrum needs to contact servers more times which makes exceptions statistically more probable. It might also depend on network quality, but it definitely should not behave like this. This is current master.

The exception is:

```
[Synchronizer] received tx 880b5ebedb5aab7b60577977464db145583517cdf4174b0f1604ae054760b049 height: 480467 bytes: 33194
Traceback (most recent call last):
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/util.py", line 863, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 1066, in run
    self.wait_on_sockets()
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 1048, in wait_on_sockets
    self.process_responses(interface)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 713, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 653, in process_response
    self.on_get_header(interface, response)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 1004, in on_get_header
    raise Exception(interface.mode)
Exception: default
```

**Comment by SomberNight** [comment]
I can't reproduce this. Please describe what you are doing.
Are you deleting the `blockchain_headers` file between attempts? Are you always trying to recover the same wallet? Is this bitcoin mainnet?

I have an idea what it could be, but again, I cannot reproduce..
To narrow it down, could you try disabling the verifier?
Put a `return` at the beginning of https://github.com/spesmilo/electrum/blob/b96b5af10191511efc1ef8cd93d655c028503a03/electrum/verifier.py#L41
See if the crash still happens then.

**Comment by SomberNight** [comment]
_This is my current idea:_
```patch
diff --git a/electrum/network.py b/electrum/network.py
index b836fbc7d..20192e6cc 100644
--- a/electrum/network.py
+++ b/electrum/network.py
@@ -875,13 +875,17 @@ class Network(util.DaemonThread):
         if not connect:
             self.connection_down(interface.server)
             return
-        # If not finished, get the next chunk
-        if index >= len(blockchain.checkpoints) and blockchain.height() < interface.tip:
-            self.request_chunk(interface, index+1)
+        if index >= len(blockchain.checkpoints):
+            # If not finished, get the next chunk
+            if blockchain.height() < interface.tip:
+                self.request_chunk(interface, index+1)
+            else:
+                interface.mode = 'default'
+                interface.print_error('catch up done', blockchain.height())
+                blockchain.catch_up = None
         else:
-            interface.mode = 'default'
-            interface.print_error('catch up done', blockchain.height())
-            blockchain.catch_up = None
+            # the verifier must have asked for this chunk
+            pass
         self.notify('updated')
 
     def on_get_header(self, interface, response):
```

**Comment by ser** [comment]
It's bitcoin mainnet, my wallet has thousands of addresses and transactions.

What I am doing is a wallet restoration from MPK to a clean ```~./electrum```

```
electrum restore xpubxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I got stuck now on this, but I have not commented what you asked yet, I will do it in next attempt, give me few minutes please.

```
[e.keff.org] received chunk 263
[e.keff.org] requesting chunk 264
Traceback (most recent call last):
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/util.py", line 863, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 1066, in run
    self.wait_on_sockets()
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 1048, in wait_on_sockets
    self.process_responses(interface)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 713, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 653, in process_response
    self.on_get_header(interface, response)
  File "/home/btc/.local/lib/python3.6/site-packages/electrum/network.py", line 1004, in on_get_header
    raise Exception(interface.mode)
Exception: default
```

**Comment by ser** [comment]
Thanks <3
