### ISSUE TITLE
cannot sign transaction

### ISSUE THREAD

**Issue by reablaz** [spesmilo/electrum#4599]
Getting problems with transaction creation.

Electrum version 3.2.2

payto command - OK
signtransaction command not working with tx hex from payto command. error:

with not loaded wallet:

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 472, in <module>
    result = run_offline_command(config, config_options, plugins)
  File "/usr/local/bin/electrum", line 323, in run_offline_command
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/electrum/commands.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/electrum/commands.py", line 245, in signtransaction
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python3.6/site-packages/electrum/wallet.py", line 1510, in sign_transaction
    if k.can_sign(tx):
  File "/usr/local/lib/python3.6/site-packages/electrum/keystore.py", line 79, in can_sign
    return bool(self.get_tx_derivations(tx))
  File "/usr/local/lib/python3.6/site-packages/electrum/keystore.py", line 61, in get_tx_derivations
    x_signatures = txin['signatures']
KeyError: 'signatures'

with loaded wallet:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.6/site-packages/electrum/daemon.py", line 287, in run_cmdline
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/electrum/commands.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/electrum/commands.py", line 245, in signtransaction
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python3.6/site-packages/electrum/wallet.py", line 1510, in sign_transaction
    if k.can_sign(tx):
  File "/usr/local/lib/python3.6/site-packages/electrum/keystore.py", line 79, in can_sign
    return bool(self.get_tx_derivations(tx))
  File "/usr/local/lib/python3.6/site-packages/electrum/keystore.py", line 61, in get_tx_derivations
    x_signatures = txin['signatures']
KeyError: 'signatures'
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 464, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.6/site-packages/electrum/keystore.py", line 61, in get_tx_derivations | KeyError: \'signatures\'\n')

**Comment by SomberNight** [comment]
I'm having trouble reproducing, can you give more detailed steps?
What kind of wallet is this; e.g. is it multisig?
When you are trying to sign a raw hex transaction with `signtransaction`, was the raw transaction generated by the same version of electrum? Using `payto --unsigned`?

**Comment by ecdsa** [comment]
closing, OP did not answer
