### ISSUE TITLE
make_packages throws error - Ubuntu

### ISSUE THREAD

**Issue by DanZlotnikov** [spesmilo/electrum#4628]
Ubuntu 16.04
Python 2.7.12

Sorry in advance for newbie question:

Following the guide for "Development Version", I installed Electrum on my Ubuntu 16.04 VMWare Virtual Machine.

When trying to create binaries - I got this error:

Installing collected packages: certifi, chardet, dnspython, ecdsa, idna, jsonrpclib-pelix, pip, setuptools, six, protobuf, pyaes, PySocks, QDarkStyle, qrcode, urllib3, requests, typing, wheel, colorama
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base

Any idea on how to solve this?

Thanks!

**Comment by SomberNight** [comment]
try updating pip and setuptools
```
python3 -m pip install pip --upgrade
python3 -m pip install setuptools --upgrade
```

**Comment by DanZlotnikov** [comment]
Worked like a charm. Huge thanks!
