### ISSUE TITLE
Failed to launch Electrum 3.2.2, ImportError: No module named 'typing'

### ISSUE THREAD

**Issue by federicoon** [spesmilo/electrum#4642]
Hello,
I just tried to update Electrum to version 3.2.2 on a Ubuntu cold wallet.
When I launched it, the wallet failed to open and the following error trace was shown on the console:

Traceback (most recent call last):
  File "electrum", line 70, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jack/Scaricati/Electrum-3.2.2/lib/__init__.py", line 3, in <module>
    from .wallet import Synchronizer, Wallet
  File "/home/jack/Scaricati/Electrum-3.2.2/lib/wallet.py", line 52, in <module>
    from .bitcoin import *
  File "/home/jack/Scaricati/Electrum-3.2.2/lib/bitcoin.py", line 33, in <module>
    from . import ecc
  File "/home/jack/Scaricati/Electrum-3.2.2/lib/ecc.py", line 29, in <module>
    from typing import Union
ImportError: No module named 'typing'

In case any library is missing, I need someway to install it offline, as the wallet is on a airgapped computer.
Any help would be highly appreciated.

**Comment by SomberNight** [comment]
This is already fixed in master via https://github.com/spesmilo/electrum/commit/281805a0a4bb7e01a8ec623be9ea23d7505bb9a0

The `typing` module that we recently started using only became part of python in version 3.5, but you only have python3.4.

You need to either
- install a newer version of python (btw newer versions of Ubuntu have newer python) 
- install the `typing` package separately (by e.g. `python3 -m pip install typing`)

Not sure how to do these offline without looking it up myself.

**Comment by federicoon** [comment]
Ok, never mind, I figured it out.
