### ISSUE TITLE
Small bug in get_utxos()

### ISSUE THREAD

**Issue by devwarrior777** [spesmilo/electrum#4651]
Small bug found on `master` today:

$  ~/electrum/bitcoin/electrum$ ./run_electrum **--testnet listunspent**

```
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
Invalid call parameters: <Fault -32602: Invalid parameters: get_utxos() got an unexpected keyword argument 'exclude_frozen'>
Traceback (most recent call last):
  File "./run_electrum", line 457, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32602, "Invalid parameters: get_utxos() got an unexpected keyword argument 'exclude_frozen'")
```

Hope this helps ;-)

**Comment by SomberNight** [comment]
Thanks.
