### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by joekendal** [spesmilo/electrum#4661]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/snap/electrum/2/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/snap/electrum/2/lib/network.py", line 794, in run
    self.wait_on_sockets()
  File "/snap/electrum/2/lib/network.py", line 788, in wait_on_sockets
    self.process_responses(interface)
  File "/snap/electrum/2/lib/network.py", line 578, in process_responses
    self.process_response(interface, response, callbacks)
  File "/snap/electrum/2/lib/network.py", line 530, in process_response
    callback(response)
  File "/snap/electrum/2/lib/synchronizer.py", line 127, in tx_response
    assert tx_hash == hash_encode(Hash(result.decode('hex')))
AssertionError

**Comment by SomberNight** [comment]
Hi. Please update.
I'm guessing you might have installed from the snap store, however the package there is not maintained by us.
