### ISSUE TITLE
Error while getting private keys from segwit addresses

### ISSUE THREAD

**Issue by partylana** [spesmilo/electrum#4739]
I was able to extract pkeys from non segwit address but got the below error while trying the same using segwit addresses.

```
~/Electrum-3.2.3 test$ electrum listaddresses -w ~/.electrum/wallets/default_wallet | electrum getprivatekeys -
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
WARNING: ALL your private keys are secret.
Exposing a single private key can compromise your entire wallet!
In particular, DO NOT use 'redeem private key' services proposed by third parties.
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 473, in <module>
    result = run_offline_command(config, config_options, plugins)
  File "/usr/local/bin/electrum", line 316, in run_offline_command
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/electrum/commands.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/electrum/commands.py", line 286, in getprivatekeys
    return [self.wallet.export_private_key(address, password)[0] for address in domain]
  File "/usr/local/lib/python3.7/site-packages/electrum/commands.py", line 286, in <listcomp>
    return [self.wallet.export_private_key(address, password)[0] for address in domain]
  File "/usr/local/lib/python3.7/site-packages/electrum/wallet.py", line 307, in export_private_key
    index = self.get_address_index(address)
  File "/usr/local/lib/python3.7/site-packages/electrum/wallet.py", line 1476, in get_address_index
    return self._addr_to_addr_index[address]
KeyError: 'bc1qex0pfjng8zhfylfudf365xjetphw360rau4c4r'
```
Thank you.

**Comment by partylana** [comment]
The same issue when its a BIP39 seed.

**Comment by SomberNight** [comment]
Can you try specifying the wallet to both invocations?
```
electrum listaddresses -w ~/.electrum/wallets/default_wallet | electrum getprivatekeys - -w ~/.electrum/wallets/default_wallet
```

**Comment by partylana** [comment]
Wow!! that worked. Thanks. Closing.
