### ISSUE TITLE
bytearray index out of range | Multisig with ledger

### ISSUE THREAD

**Issue by pakokrew** [spesmilo/electrum#4749]
Hi there,

I can't sign a transaction from a multisig wallet with a ledger.

I get `bytearray index out of range`

Electrum 3.2.3
Ledger 1.4.2 BTC 1.2.8

stacktrace 
```
Traceback (most recent call last):
  File "/var/folders/y.../electrum/plugins/ledger/ledger.py", line 478, in sign_transaction
    outputData = self.get_client().finalizeInputFull(txOutput)
  File "btchip/btchip.py", line 352, in finalizeInputFull
IndexError: bytearray index out of range
Traceback (most recent call last):
  File "/var/folders/y.../electrum/plugins/ledger/ledger.py", line 478, in sign_transaction
    outputData = self.get_client().finalizeInputFull(txOutput)
  File "btchip/btchip.py", line 352, in finalizeInputFull
IndexError: bytearray index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electrum/gui/qt/util.py", line 661, in run
  File "electrum/wallet.py", line 819, in sign_transaction
  File "/var/folders/y.../electrum/plugins/ledger/ledger.py", line 46, in catch_exception
    return func(self, *args, **kwargs)
  File "/var/folders/y.../electrum/plugins/ledger/ledger.py", line 248, in wrapper
    return func(self, *args, **kwargs)
  File "/var/folders/y.../electrum/plugins/ledger/ledger.py", line 511, in sign_transaction
    self.give_error(e, True)
  File "/var/folders/y.../electrum/plugins/ledger/ledger.py", line 241, in give_error
    raise Exception(message)
Exception: bytearray index out of range
```

**Comment by pakokrew** [comment]
Electrum 3.1.3 was working

**Comment by SomberNight** [comment]
well it works for me. so going to need more details.
- what kind of multisig is it? what is `m` and `n` in `m-of-n`?
- based on the code path, it looks like it's not segwit (the inputs), and there is no change in the transaction; please confirm
- how many outputs are there? how many inputs?
- what are the other cosigners? in what order are you signing?

**Comment by pakokrew** [comment]
Ok so:
I tried to do exactly the same thing on electrum 3.1.3 and 3.2.3, first works and not the second.

- The wallet is 3-of-4 , one key is my ledger and others are xpub
- I don't think it's segwit, at least I never asked for it (just created the wallet with electrum wizard) with the configuration mentioned above
- Only one output, tried with one and several inputs, same problem
- I was creating the tx, so first signer

**Comment by pakokrew** [comment]
In my electrum wallet file I have `"derivation": "m/45'/0"` under my ledger's x1

**Comment by SomberNight** [comment]
ok, so it is most likely not segwit.

well.. I don't see anything in the diff that could explain it...
https://github.com/spesmilo/electrum/compare/3.1.3...3.2.3 (looking at `ledger.py`)

was it *exactly* the same transaction that worked on 3.1.3 and not 3.2.3? can you reproduce the failure?

btw can you run from source and test some changes if needed?

**Comment by SomberNight** [comment]
If you can reproduce the failure on 3.2.3; does it only fail if there is no change? Please try to reproduce with only one output (not controlled by the wallet), and one output (not controlled by wallet) + one change output.

**Comment by pakokrew** [comment]
Ok I am sorry but I cannot reproduce anymore ... 

I tried all combination, one/multiple inputs, one/multiple output internal/external and it always work now ... Would like to say better like this but now cannot find the initial bug :/

**Comment by SomberNight** [comment]
Ok, no problem. Looking at the trace the device fw sent back data that btchip-python found malformed, so it really might not be an electrum bug at all.
In any case, it seems cleaner if we don't call that function at all during the signing; I made some simplifications in https://github.com/spesmilo/electrum/commit/788b5b04febf45da891b1a85990385d06c6f14bc

**Comment by pakokrew** [comment]
Great. I'll come back here if it happens again. Thanks for reactivity

**Comment by BravoIndia** [comment]
This happened to me and the issue was I still had the ledger bitcoin chrome app opened. Once I closed the ledger bitcoin chrome app it worked fine. 

Hope this helps someone who gets the "bytearray index out of range" error in the future and I believe this issue can now be closed.
