### ISSUE TITLE
Invalid format specifier: .01f

### ISSUE THREAD

**Issue by pooler** [spesmilo/electrum#4771]
70cca3b appears to break Electrum on Python 3.7. When starting the GUI I get:

```
Traceback (most recent call last):
  File "electrum/electrum/gui/qt/__init__.py", line 242, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "electrum/electrum/gui/qt/__init__.py", line 191, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "electrum/electrum/gui/qt/main_window.py", line 146, in __init__
    self.send_tab = self.create_send_tab()
  File "electrum/electrum/gui/qt/main_window.py", line 1153, in create_send_tab
    self.fee_slider = FeeSlider(self, self.config, fee_cb)
  File "electrum/electrum/gui/qt/fee_slider.py", line 19, in __init__
    self.update()
  File "electrum/electrum/gui/qt/fee_slider.py", line 49, in update
    tooltip = self.get_tooltip(pos, fee_rate)
  File "electrum/electrum/gui/qt/fee_slider.py", line 36, in get_tooltip
    target, estimate = self.config.get_fee_text(pos, self.dyn, mempool, fee_rate)
  File "electrum/electrum/simple_config.py", line 404, in get_fee_text
    rate_str = format_fee_satoshis(fee_rate/1000) + ' sat/byte'
  File "electrum/electrum/util.py", line 544, in format_fee_satoshis
    return format_satoshis(fee, num_zeros, 0, precision=FEERATE_PRECISION)
  File "electrum/electrum/util.py", line 524, in format_satoshis
    result = ("{:" + decimal_format + "f}").format(x / scale_factor)
  File "/usr/lib/python3.7/_pydecimal.py", line 3762, in __format__
    spec = _parse_format_specifier(specifier, _localeconv=_localeconv)
  File "/usr/lib/python3.7/_pydecimal.py", line 6192, in _parse_format_specifier
    raise ValueError("Invalid format specifier: " + format_spec)
```

As far as I can tell the issue is due to the extra zero right after the decimal point (see [this line](https://github.com/spesmilo/electrum/commit/70cca3bad9a40b5b5230e13c0d2fce7ae1312b53#diff-fca387ea434f3be37124dd66cbf029a6L514)), whose purpose I could not ascertain (but I may have missed something in the Python docs). This was not an issue before 70cca3b because `float` does not complain about the extra zero, while `Decimal` does.

**Comment by SomberNight** [comment]
Arghh; maybe that whole function should be rewritten...

However I cannot reproduce this ValueError on python 3.7.0.
```
>>> ("{:01f}").format(Decimal('1.7'))
'1.7'
```
Could you please give an exact invocation that raises?

**Comment by SomberNight** [comment]
this is really weird
```
> python3.7
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> ("{:01f}").format(Decimal('1.7'))
'1.7'
>>> ("{:.01f}").format(Decimal('1.7'))
'1.7'
```
```
$ python3
Python 3.7.0 (default, Sep 15 2018, 19:13:07) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> ("{:01f}").format(Decimal('1.7'))
'1.7'
>>> ("{:.01f}").format(Decimal('1.7'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/_pydecimal.py", line 3762, in __format__
    spec = _parse_format_specifier(specifier, _localeconv=_localeconv)
  File "/usr/lib/python3.7/_pydecimal.py", line 6192, in _parse_format_specifier
    raise ValueError("Invalid format specifier: " + format_spec)
ValueError: Invalid format specifier: .01f
```
