### ISSUE TITLE
Error after running mac os build

### ISSUE THREAD

**Issue by vinnyvoo** [spesmilo/electrum#4800]
Followed mac os build instructions. Got the following error while running the build.

```
vinnyvoos-Mac:~ vinnyvoo$ /Users/vinnyvoo/Documents/electrum/dist/Electrum ; exit;
Traceback (most recent call last):
  File "run_electrum", line 405, in <module>
  File "electrum/daemon.py", line 310, in init_gui
  File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/PyInstaller/loader/pyimod03_importers.py", line 441, in exec_module
    #
  File "electrum/gui/qt/__init__.py", line 36, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtGui'
[66193] Failed to execute script run_electrum
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.
 
[Process completed]
```
It says qt not installed? the build.sh doesn't take care of it?

Thanks.

**Comment by bauerj** [comment]
Can you post the full build log please?

**Comment by vinnyvoo** [comment]
Now theres an error while building on OSX.

```
[REDACTED long log]
Collecting protobuf==3.6.1 (from -r ./contrib/deterministic-build/requirements.txt (line 89))
  Using cached https://files.pythonhosted.org/packages/c7/27/133f225035b9539f2dcfebcdf9a69ff0152f56e0120160ec5c972ea7deb9/protobuf-3.6.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyaes==1.6.1 (from -r ./contrib/deterministic-build/requirements.txt (line 107))
  Using cached https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz
Collecting QDarkStyle==2.5.4 (from -r ./contrib/deterministic-build/requirements.txt (line 109))
  Using cached https://files.pythonhosted.org/packages/97/26/4ec7b5c654d69bce00004deb78dff72879d9dc5031b7b4f9f0736070083a/QDarkStyle-2.5.4-py2.py3-none-any.whl
Collecting qrcode==6.0 (from -r ./contrib/deterministic-build/requirements.txt (line 112))
  Using cached https://files.pythonhosted.org/packages/79/be/11999004f7e6e5db0fa410c2feacd67c07f472f4500fde0026101f31d0df/qrcode-6.0-py2.py3-none-any.whl
Collecting requests==2.20.0 (from -r ./contrib/deterministic-build/requirements.txt (line 115))
  Using cached https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl
Collecting setuptools==40.4.3 (from -r ./contrib/deterministic-build/requirements.txt (line 118))
  Using cached https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl
Collecting six==1.11.0 (from -r ./contrib/deterministic-build/requirements.txt (line 121))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting urllib3==1.24 (from -r ./contrib/deterministic-build/requirements.txt (line 124))
  Using cached https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl
Collecting wheel==0.32.2 (from -r ./contrib/deterministic-build/requirements.txt (line 127))
  Using cached https://files.pythonhosted.org/packages/5a/9b/6aebe9e2636d35d1a93772fa644c828303e1d5d124e8a88f156f42ac4b87/wheel-0.32.2-py2.py3-none-any.whl
Collecting yarl==1.2.6 (from -r ./contrib/deterministic-build/requirements.txt (line 130))
  Using cached https://files.pythonhosted.org/packages/43/b8/057c3e5b546ff4b24263164ecda13f6962d85c9dc477fcc0bcdcb3adb658/yarl-1.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/30/lccxygxs151_qy0s1vcc10hr0000gn/T/pip-install-g9wgdtwg/yarl/setup.py", line 26, in <module>
        extensions = cythonize(extensions)
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Build/Dependencies.py", line 947, in cythonize
        ctx = c_options.create_context()
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/Main.py", line 595, in create_context
        self.cplus, self.language_level, options=self)
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/Main.py", line 78, in __init__
        from . import Builtin, CythonScope
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
        from .UtilityCode import CythonUtilityCode
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
        from .TreeFragment import parse_from_strings, StringParseContext
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
        from .Visitor import VisitorTransform
      File "Cython/Compiler/Visitor.py", line 17, in init Cython.Compiler.Visitor
      File "/Users/vinnyvoo/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/ExprNodes.py", line 46, in <module>
        from .Pythran import (to_pythran, is_pythran_supported_type, is_pythran_supported_operation_type,
    ImportError: cannot import name 'pythran_is_numpy_func_supported'
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/30/lccxygxs151_qy0s1vcc10hr0000gn/T/pip-install-g9wgdtwg/yarl/
🗯 ERROR: Could not install requirements**
```

What might be the issue?

**Comment by vinnyvoo** [comment]
Resolved issue after reboot.

**Comment by inspiraluna** [comment]
i have this issue and its not resolved after reboot

**Comment by SomberNight** [comment]
Do you have get the same trace?
Is this when running `contrib/osx/make_osx`?

**Comment by inspiraluna** [comment]
yes, seems like its exactly the same. Its starts after **'yarl'**  and ends with **cannot import name 'pythran_is_numpy_func_supported'** but I get another warning in the end about pip would be not the correct verison. I checked it and installed current pip but it always fetches the old version from the text file. Actually I think thats not the reason for this problem.

Found such hints in other repos: 
- https://github.com/cython/cython/issues/2680'*
- https://github.com/facebook/prophet/issues/934

Using cached https://files.pythonhosted.org/packages/fb/84/6d82f6be218c50b547aa29d0315e430cf8a23c52064c92d0a8377d7b7357/yarl-1.3.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/nico/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jr/ssq8z_p97llf3j1t0vrv21hr0000gq/T/pip-install-_ee5_aik/yarl/setup.py'"'"'; __file__='"'"'/private/var/folders/jr/ssq8z_p97llf3j1t0vrv21hr0000gq/T/pip-install-_ee5_aik/yarl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/jr/ssq8z_p97llf3j1t0vrv21hr0000gq/T/pip-install-_ee5_aik/yarl/
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jr/ssq8z_p97llf3j1t0vrv21hr0000gq/T/pip-install-_ee5_aik/yarl/setup.py", line 25, in <module>
        extensions = cythonize(extensions)
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Build/Dependencies.py", line 958, in cythonize
        ctx = c_options.create_context()
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/Main.py", line 595, in create_context
        self.cplus, self.language_level, options=self)
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/Main.py", line 78, in __init__
        from . import Builtin, CythonScope
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
        from .UtilityCode import CythonUtilityCode
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
        from .TreeFragment import parse_from_strings, StringParseContext
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
        from .Visitor import VisitorTransform
      File "Cython/Compiler/Visitor.py", line 17, in init Cython.Compiler.Visitor
      File "/Users/nico/Library/Python/3.6/lib/python/site-packages/Cython/Compiler/ExprNodes.py", line 46, in <module>
        from .Pythran import (to_pythran, is_pythran_supported_type, is_pythran_supported_operation_type,
    ImportError: cannot import name 'pythran_is_numpy_func_supported'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
