### ISSUE TITLE
No module named 'PyQt5.QtGui' on Ubuntu 16.04

### ISSUE THREAD

**Issue by rsuhada** [spesmilo/electrum#4848]
electrum 3.2.2 gives

`ModuleNotFoundError: No module named 'PyQt5.QtGui'`

on  Ubuntu 16.04 xenial with Python 3.6.5.

All requirements are OK and there was no error during installation with pip:

> python3-setuptools is already the newest version (20.7.0-1).
> 
> python3-pyqt5 is already the newest version (5.5.1+dfsg-3ubuntu4).
> 
> python3-pip is already the newest version (8.1.1-2ubuntu0.4).
> 

Thank you!

**Comment by ysangkok** [comment]
You must have a custom Python installation installed since you're on Xenial, which ships with Python 3.5.

So the dependencies need to be installed for your custom Python instead.

Dpkg packages are not pip packages, `python3-pyqt5` is a dpkg package. You seem to be confused about this.

I'd recommend using a venv. That way, you can install the packages in there. See https://docs.python.org/3/library/venv.html

**Comment by repsorp** [comment]
Hi,

Electrum 3.3.0
Ubuntu 16.04
Python 3.6.7

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 92, in load_plugins
    self.load_plugin(name)
  File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 116, in load_plugin
    raise Exception(f"Error loading {name} plugin: {repr(e)}") from e
Exception: Error loading virtualkeyboard plugin: ModuleNotFoundError("No module named 'PyQt5.QtGui'",)
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 339, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 326, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/__init__.py", line 37, in <module>
    from PyQt5.QtGui import *
ModuleNotFoundError: No module named 'PyQt5.QtGui'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 339, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 326, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/__init__.py", line 37, in <module>
    from PyQt5.QtGui import *
ModuleNotFoundError: No module named 'PyQt5.QtGui'
