### ISSUE TITLE
Electrum | Can't Paytomany

### ISSUE THREAD

**Issue by arcaelas** [spesmilo/electrum#4859]
**JSON-RPC <- cURL**
`
{"method": "paytomany", "params": [{"password": "", "fee": "0.00004", "outputs": [["tb1qfl6n8lmk0sy7tua6cxtc5spx9m4jycx0rep6vu", "0.0004"] ] } ], "id": "curltext"}
`

**cURL RESPONSE**
<Fault -32603: Server error: File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 488, in _mktx | ValueError: too many values to unpack (expected 2)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 97, in func_wrapper
    return func(*args, **kwargs)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 518, in paytomany
    tx = self._mktx(outputs, tx_fee, change_addr, domain, nocheck, unsigned, rbf, password, locktime)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 488, in _mktx
    for address, amount in outputs:
ValueError: too many values to unpack (expected 2)

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum/issues/4837#issuecomment-440281990

**Comment by arcaelas** [comment]
> See [#4837 (comment)](https://github.com/spesmilo/electrum/issues/4837#issuecomment-440281990)

Ok, thanks...
