### ISSUE TITLE
Error while building apk : patching file jnius/jnius_jvm_android.pxi, Reversed (or previously applied) patch detected! 

### ISSUE THREAD

**Issue by vivekteega** [spesmilo/electrum#4862]
`sudo make_apk ` command fails when building apk. Can someone help me with this, I'm attaching the logs below 

```
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    Applying patch sdl2_jnienv_getter.patch
[INFO]:    -> running patch -t -d /home/vivek/Deskto...(and 200 more)
Exception in thread background thread for pid 19059:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /home/vivek/Desktop/electrum/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /opt/python-for-android/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
Reversed (or previously applied) patch detected!  Assuming -R.
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej


  STDERR:


[INFO]:    STDOUT:
	patching file jnius/jnius_jvm_android.pxi	
Reversed (or previously applied) patch detected!  Assuming -R.	
patching file setup.py	
Hunk #1 FAILED at 53.	
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
[INFO]:    STDERR:
	
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/opt/python-for-android/pythonforandroid/build.py", line 567, in build_recipes
    recipe.apply_patches(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 486, in apply_patches
    arch.arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 194, in apply_patch
    "-i", filename, _tail=10)
  File "/opt/python-for-android/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/vivek/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /home/vivek/Desktop/electrum/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /opt/python-for-android/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
Reversed (or previously applied) patch detected!  Assuming -R.
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
```

**Comment by SomberNight** [comment]
ack. can reproduce.

**Comment by SomberNight** [comment]
try with https://github.com/spesmilo/electrum/pull/4864

**Comment by SomberNight** [comment]
it's a substantial change to the toolchain, so you will need to be more specific than "not working"

**Comment by SomberNight** [comment]
well in any case https://github.com/spesmilo/electrum/pull/4864 is now merged, and that fixed it for me
btw I'm trying to streamline the android build by using docker, see https://github.com/spesmilo/electrum/pull/4873
