### ISSUE TITLE
Text gui gives TypeError: argument of type 'bool' is not iterable in util.py

### ISSUE THREAD

**Issue by Grimler91** [spesmilo/electrum#4886]
Hi, 

Running `electrum gui -g text` on python3.7 gives
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/electrum/util.py", line 882, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/lib/python3.7/site-packages/electrum/daemon.py", line 296, in run
    self.print_error("shutting down network")
  File "/usr/lib/python3.7/site-packages/electrum/util.py", line 180, in print_error
    if self.verbosity_filter in verbosity or verbosity == '*':
TypeError: argument of type 'bool' is not iterable
```

It seems that verbosity is sometimes set to a bool and sometimes a string and this causes the problem.

One possible fix is:
```diff
--- /usr/lib/python3.7/site-packages/electrum/util.py   2018-11-30 13:28:42.089832561 +0100
+++ util.py     2018-11-30 13:28:33.236499294 +0100
@@ -177,8 +177,9 @@
         return self.__class__.__name__
 
     def print_error(self, *msg):
-        if self.verbosity_filter in verbosity or verbosity == '*':
-            print_error("[%s]" % self.diagnostic_name(), *msg)
+        if verbosity:
+            if self.verbosity_filter in verbosity or verbosity == '*':
+                print_error("[%s]" % self.diagnostic_name(), *msg)
 
     def print_stderr(self, *msg):
         print_stderr("[%s]" % self.diagnostic_name(), *msg)
```

But this doesn't really fix the root of the problem (which I'm guessing is that that verbosity is sometimes a filter and sometimes a bool)

**Comment by SomberNight** [comment]
what commit is this on? or is it 3.2.3?
related https://github.com/spesmilo/electrum/commit/43664d5f113992062ffc33c2f63ebd485069e6aa

**Comment by Grimler91** [comment]
@SomberNight It's 3.2.3, sorry for not mentioning that. 
I'll try building master and see if it's any different

**Comment by Grimler91** [comment]
Yeah, no problem on the master branch, sorry for the noise!
