### ISSUE TITLE
digitalbitbox fails to initialize (create new seed): Invalid command

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4902]
My dbb had firmware 3.x which I have now upgraded to 5.0.0 to test https://github.com/spesmilo/electrum/pull/4895

I had erased the device, and then tried to generate a new seed.
It fails as below.

```
Traceback (most recent call last):
  File "...\electrum\electrum\base_wizard.py", line 296, in on_device
    self.plugin.setup_device(device_info, self, purpose)
  File "...\electrum\electrum\plugins\digitalbitbox\digitalbitbox.py", line 728, in setup_device
    client.get_xpub("m/44'/0'", 'standard')
  File "...\electrum\electrum\plugins\digitalbitbox\digitalbitbox.py", line 110, in get_xpub
    reply = self._get_xpub(bip32_path)
  File "...\electrum\electrum\plugins\digitalbitbox\digitalbitbox.py", line 104, in _get_xpub
    if self.check_device_dialog():
  File "...\electrum\electrum\plugins\digitalbitbox\digitalbitbox.py", line 215, in check_device_dialog
    self.seed_device_dialog() # Seed if not initialized
  File "...\electrum\electrum\plugins\digitalbitbox\digitalbitbox.py", line 254, in seed_device_dialog
    self.dbb_generate_wallet()
  File "...\electrum\electrum\plugins\digitalbitbox\digitalbitbox.py", line 311, in dbb_generate_wallet
    raise UserFacingException(reply['error']['message'])
electrum.util.UserFacingException: Invalid command.
```

@benma

**Comment by benma** [comment]
Thanks for testing. I opened a PR to fix it.

FYI, the mobile pairing is also is out of date / broken. I am working on a PR for that too.
