### ISSUE TITLE
lnbase test in lightning branch has local import errors. Maybe my pycharm ide is set up incorrectly?

### ISSUE THREAD

**Issue by renepickhardt** [spesmilo/electrum#4907]
I have been importing electrum to pycharm community edition. and I have successfully installed the dependencies from `requirements.txt` to the virtual environment and I have self recompiled and installed `libsecp256k1` because the python interpreter had a hard time finding it. 

However running the `test_lnbase` produces this error with the local import in line 23:
https://github.com/spesmilo/electrum/blob/316666c1168be5ba6b51e3a78b425d2191e15aff/electrum/tests/test_lnbase.py#L23

if I omit the `.` in front of the module name the IDE complains stating that there is an unresolved reference to `test_lnchan` but the tests passes without errors.  

I think I might have forgot to set something up within my IDE. Could anybody help out please?

```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_lnbase
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/rpickhardt/hacken/electrum/electrum/tests/test_lnbase.py", line 23, in <module>
    from .test_lnchan import create_test_channels
ImportError: attempted relative import with no known parent package
```

**Comment by ysangkok** [comment]
Could you please upload the contents of the .idea directory somewhere. PyCharm creates it in the project directory.
