### ISSUE TITLE
Docker apk build fails - Android NDK missing 

### ISSUE THREAD

**Issue by vivekteega** [spesmilo/electrum#4936]
Building android apk with the new buildozer command fails as it cannot find the NDK. Also, I don't understand why its downloading version **9c** even though version 14 is mentioned in buildozer.spec and Dockerfile. Could someone help me with this. I have attached the logs below :

```
vivek@pop-os:~/Dev/FLO/electrum$ sudo docker run -it --rm \
>     --name electrum-android-builder-cont \
>     -v $PWD:/home/vivek/wspace/electrum \
>     -v ~/.keystore:/home/vivek/.keystore \
>     --workdir /home/vivek/wspace/electrum \
>     electrum-android-builder-img \
>     ./contrib/make_apk
~/wspace/electrum/electrum/gui/kivy ~/wspace/electrum
make[1]: Entering directory '/home/vivek/wspace/electrum/electrum/gui/kivy'
# running pre build setup
# copy electrum to main.py
# Check configuration tokens
# Ensure build layout
# Create directory /home/vivek/.buildozer
# Create directory /home/vivek/.buildozer/cache
# Create directory /home/vivek/wspace/electrum/.buildozer
# Create directory /home/vivek/wspace/electrum/.buildozer/applibs
# Create directory /home/vivek/.buildozer/android/platform/android/platform
# Create directory /home/vivek/wspace/electrum/.buildozer/android/platform
# Create directory /home/vivek/wspace/electrum/.buildozer/android/app
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/vivek/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\''
# Cwd None
# Android ANT is missing, downloading
# Downloading http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
# Run 'tar xzf apache-ant-1.9.4-bin.tar.gz'
# Cwd /home/vivek/.buildozer/android/platform
# Apache ANT installation done.
# Android SDK is missing, downloading
# Downloading http://dl.google.com/android/android-sdk_r20-linux.tgz
# Unpacking Android SDK
# Run 'tar xzf android-sdk_r20-linux.tgz'
# Cwd /home/vivek/.buildozer/android/platform
# Rename /home/vivek/.buildozer/android/platform/android-sdk-linux to /home/vivek/.buildozer/android/platform/android-sdk-20
# Android SDK installation done.
# Android NDK is missing, downloading
# Downloading http://dl.google.com/android/repository/android-ndk-r9c-linux-x86_64.tar.bz2
Traceback (most recent call last):
  File "/home/vivek/.local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer', 'console_scripts', 'buildozer')()
  File "/opt/buildozer/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/opt/buildozer/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/opt/buildozer/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/opt/buildozer/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/opt/buildozer/buildozer/__init__.py", line 176, in prepare_for_build
    self.target.install_platform()
  File "/opt/buildozer/buildozer/targets/android.py", line 507, in install_platform
    self._install_android_ndk()
  File "/opt/buildozer/buildozer/targets/android.py", line 319, in _install_android_ndk
    cwd=self.buildozer.global_platform_dir)
  File "/opt/buildozer/buildozer/__init__.py", line 687, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib/python3.6/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
cp: cannot create regular file '.buildozer/android/platform/python-for-android/src/blacklist.txt': No such file or directory
make[1]: Leaving directory '/home/vivek/wspace/electrum/electrum/gui/kivy'
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/vivek/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\''
# Cwd None
# Apache ANT found at /home/vivek/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/vivek/.buildozer/android/platform/android-sdk-20
# Android NDK is missing, downloading
# Downloading http://dl.google.com/android/repository/android-ndk-r9c-linux-x86_64.tar.bz2
Traceback (most recent call last):
  File "/home/vivek/.local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer', 'console_scripts', 'buildozer')()
  File "/opt/buildozer/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/opt/buildozer/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/opt/buildozer/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/opt/buildozer/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/opt/buildozer/buildozer/__init__.py", line 176, in prepare_for_build
    self.target.install_platform()
  File "/opt/buildozer/buildozer/targets/android.py", line 507, in install_platform
    self._install_android_ndk()
  File "/opt/buildozer/buildozer/targets/android.py", line 319, in _install_android_ndk
    cwd=self.buildozer.global_platform_dir)
  File "/opt/buildozer/buildozer/__init__.py", line 687, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib/python3.6/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
Makefile:20: recipe for target 'apk' failed
make: [apk] Error 1 (ignored)
make[1]: Entering directory '/home/vivek/wspace/electrum/electrum/gui/kivy'
# Cleaning up
# rename main.py to electrum
# remove buildozer.spec
make[1]: Leaving directory '/home/vivek/wspace/electrum/electrum/gui/kivy'
~/wspace/electrum
```

**Comment by SomberNight** [comment]
Maybe delete the `.buildozer` folder inside the electrum directory, and try again.
Get an interactive shell and look around in the container, the sdk and ndk should already be downloaded:
```
$ sudo docker run -it --rm     -v $PWD:/home/user/wspace/electrum     --workdir /home/user/wspace/electrum     electrum-android-builder-img
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

user@79070830462e:~/wspace/electrum$ ls /opt/android/
android-ndk  android-ndk-r14b  android-sdk
user@79070830462e:~/wspace/electrum$ ls /opt/android/android-ndk
CHANGELOG.md  ndk-gdb    prebuilt         source.properties
build         ndk-stack  python-packages  sources
ndk-build     ndk-which  shader-tools     sysroot
ndk-depends   platforms  simpleperf       toolchains
user@79070830462e:~/wspace/electrum$ ls /opt/android/android-sdk
build-tools  extras  licenses  platforms  tools
```

**Comment by SomberNight** [comment]
Oh wait, I've just realised you've changed the command.
```
$ sudo docker run -it --rm \
	--name electrum-android-builder-cont \
	-v $PWD:/home/user/wspace/electrum \
	-v ~/.keystore:/home/user/.keystore \
	--workdir /home/user/wspace/electrum \
	electrum-android-builder-img \
	./contrib/make_apk
```
You've changed `/home/user` to `/home/vivek`. Those paths are inside the container.
https://github.com/spesmilo/electrum/blob/c59ac49feadeb6905aef17990b0f93414fd93574/electrum/gui/kivy/tools/Dockerfile#L66-L69

**Comment by vivekteega** [comment]
Yeap, it was my bad
Thanks so much :)
