### ISSUE TITLE
No module named 'PyQt5.QtGui' [Ubuntu 16.04]

### ISSUE THREAD

**Issue by repsorp** [spesmilo/electrum#4942]
_Originally posted by @rsuhada in https://github.com/spesmilo/electrum/issues/4848#issuecomment-437981969_

Hi,

Electrum 3.3.0
Ubuntu 16.04
Python 3.6.7

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 92, in load_plugins
self.load_plugin(name)
File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 116, in load_plugin
raise Exception(f"Error loading {name} plugin: {repr(e)}") from e
Exception: Error loading virtualkeyboard plugin: ModuleNotFoundError("No module named 'PyQt5.QtGui'",)

Traceback (most recent call last):
File "/usr/local/bin/electrum", line 339, in 
d.init_gui(config, plugins)
File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 326, in init_gui
gui = import('electrum.gui.' + gui_name, fromlist=['electrum'])
File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/init.py", line 37, in 
from PyQt5.QtGui import *
ModuleNotFoundError: No module named 'PyQt5.QtGui'

Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
from apport.fileutils import likely_packaged, get_recent_crashes
File "/usr/lib/python3/dist-packages/apport/init.py", line 5, in 
from apport.report import Report
File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in 
import apport.fileutils
File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in 
from apport.packaging_impl import impl as packaging
File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in 
import apt
File "/usr/lib/python3/dist-packages/apt/init.py", line 23, in 
import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
File "/usr/local/bin/electrum", line 339, in 
d.init_gui(config, plugins)
File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 326, in init_gui
gui = import('electrum.gui.' + gui_name, fromlist=['electrum'])
File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/init.py", line 37, in 
from PyQt5.QtGui import *
ModuleNotFoundError: No module named 'PyQt5.QtGui'
```

**Comment by SomberNight** [comment]
try `python3.6 -m pip install pyqt5`

**Comment by repsorp** [comment]
Perfect !

a small error message though:
[ecc] warning: libsecp256k1 library was found and loaded but there was an error when using it

**Comment by repsorp** [comment]
Don't know if it's correlated but update-manager is broken...

sudo apt-get update is ok though...

**Comment by repsorp** [comment]
could be...

update-manager and apt-get are broken
https://askubuntu.com/questions/915226/update-manager-and-apt-get-are-broken

"I was facing the same issue on 16.10, upgrade to 17.04 didn't help. I'm pretty sure the problem started because of python3 packages conflict, looking at the trace of the exception it seemed like it was using packages from /usr/lib/python3 (apt managed) and from /usr/local/lib/python3.5 (pip managed). I removed all my pip installed packages, I reinstalled update-manager/python3-aptdaemon/etc but that didn't work... After some additional attempts at removing and purging everything and then reinstalling, it seems that update-manager is working when using synaptic backend and not aptdaemon. So far so good. Unfortunately I can't really offer any steps to reproduce or solve this.."

**Comment by SomberNight** [comment]
Unfortunately it's non-trivial to install and manage another python in addition to the one provided by the Linux distribution (e.g. the one packaged by `apt` for `Ubuntu`).
As we require python 3.6 now, and that is still relatively new, this will be a problem for some users. :/

To overcome this, we could distribute "binaries" for Linux, see https://github.com/spesmilo/electrum/issues/4343  < for which help is welcome!
