### ISSUE TITLE
Docker android build fails with "non-system libraries in linker flags: -lpython3.7m"

### ISSUE THREAD

**Issue by homberger** [spesmilo/electrum#5028]
I am trying to build apk binary using the development instructions for docker on macOS 10.14.2 Mojave.
I followed the manual of the Kyvi Readme.

Following (initial?) error got reported:
```
INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/user/wspace/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running ndk-build V=1
           working: make: *** [/home/user/wspace/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/obj/local/armeabi-v7a/libmain.so] Error 1                                      Exception in thread background thread for pid 33408:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/user/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/user/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /opt/android/android-ndk-r14b/ndk-build V=1

  STDOUT:
Android NDK: WARNING:/home/user/wspace/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni/application/src/Android.mk:main: non-system libraries in linker flags: -lpython3.7m    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
```

Detailed logs with additional related(?) errors are attached.

[apk_build_failed_missing_python3.7m.txt](https://github.com/spesmilo/electrum/files/2791641/apk_build_failed_missing_python3.7m.txt)

Are any libs installed on the host system relevant for the docker build maybe? Looking at known problems with LD_LIBRARY_PATH and macOS...

**Comment by ecdsa** [comment]
can you try again with the current master? we pinned buildozer and py4a versions

**Comment by SomberNight** [comment]
There have been no issues with the Android build for some time now I believe. Closing this.
