### ISSUE TITLE
Electrum 3.3.4 - unable to broadcast a txn: Missing inputs / Transaction uses non-standard version.

### ISSUE THREAD

**Issue by RuhiPoddar** [spesmilo/electrum#5137]
I installed the 3.3.4 version from the official website today (18th feb) after receiving the message as per <a href="https://twitter.com/ElectrumWallet/status/1093561779031076864" target="_blank">this</a>. Previously version 3.2.3 was installed. Since the upgrade, the txns wont get broadcasted. Using electrum with python3.

 On testnet, I get the following error: 
```
Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction | electrum.network.TxBroadcastServerReturnedError: Missing inputs
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 800, in broadcast_transaction
    out = await self.interface.session.send_request('blockchain.transaction.broadcast', [str(tx)], timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/electrum/interface.py", line 107, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 526, in send_request
    raise result
aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\nMissing inputs\n[02000000031****1600]')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 306, in run_cmdline
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 98, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 338, in broadcast
    self.network.run_from_another_thread(self.network.broadcast_transaction(tx))
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 287, in run_from_another_thread
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 768, in make_reliable_wrapper
    raise success_fut.exception()
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction
    raise TxBroadcastServerReturnedError(self.sanitize_tx_broadcast_response(e.message)) from e
electrum.network.TxBroadcastServerReturnedError: Missing inputs
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 384, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction | electrum.network.TxBroadcastServerReturnedError: Missing inputs\n')
```
Same code, when running on mainnet gives:
```
'message': 'Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction | electrum.network.TxBroadcastServerReturnedError: Transaction uses non-standard version.\n'
```

**Comment by SomberNight** [comment]
Have you tried switching servers? I think that should fix the mainnet issue.

Re the testnet error, that might be different. Can you share the raw transaction for that?

**Comment by RuhiPoddar** [comment]
Thanks! Works on mainnet when server is switched. Servers with version 1.4.1 working. I restarted electrum to switch servers, is there a better way to do that using the CLI?

Testnet Txn: 
1. electrum --testnet payto mpM38Zv1DG6iMzAhuFiMHBzz5RXYib5eNX 0.001 -w /home/usr/Wallets/test_btc_wallet
```
{
    "complete": true,
    "final": false,
    "hex": "02000000031eb6026b0353b9ce95f11bf162fb802054b9aae7356aadb8263f49580417796d000000006b483045022100f0ca3263933eb35ce1c3114f2fceaabdb10767f5e6b65301de80a81e026c4c0502205f66cafa2b0a58fb28d6ce585ad84c41449b51398577c21e9f5dd5c99ec7796b012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdffffffb7ea65e7ecbd181357ef02e1b1cdd2aaf2ce044d914528c66d324d6b5b29b37a000000006b4830450221008e2d2a258c1f4fe3c812a705d7a8005954679869a90d64fc9ee72d6e48773206022076ad230675cf952d279c57239b9c7846b942b5b589c23e75a9dcb36ab340b47b012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdfffffff210208ef21099c5687aac9a902782c58afa7f03aa3b27cd68b7a3f6828383f2000000006a473044022040ee52fa57fa447d7e9629ea52afe2bb1ea12f4326cfe43c740de7c94b860edb022001ed7a952e3b97c152256b65367be9c217a37ff2730780277d02ae542cf59fe8012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdffffff02a0860100000000001976a91460d9027bf273cc405417ecf8eaa3ea4849180fdf88acafdd1000000000001976a91406c13fd5fb0f2c46e784fe2a41d129972ae1d9c988ac498d1600"
}
```
2. electrum --testnet -w /home/usr/Wallets/test_btc_wallet broadcast 02000000031eb6026b0353b9ce95f11bf162fb802054b9aae7356aadb8263f49580417796d000000006b483045022100f0ca3263933eb35ce1c3114f2fceaabdb10767f5e6b65301de80a81e026c4c0502205f66cafa2b0a58fb28d6ce585ad84c41449b51398577c21e9f5dd5c99ec7796b012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdffffffb7ea65e7ecbd181357ef02e1b1cdd2aaf2ce044d914528c66d324d6b5b29b37a000000006b4830450221008e2d2a258c1f4fe3c812a705d7a8005954679869a90d64fc9ee72d6e48773206022076ad230675cf952d279c57239b9c7846b942b5b589c23e75a9dcb36ab340b47b012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdfffffff210208ef21099c5687aac9a902782c58afa7f03aa3b27cd68b7a3f6828383f2000000006a473044022040ee52fa57fa447d7e9629ea52afe2bb1ea12f4326cfe43c740de7c94b860edb022001ed7a952e3b97c152256b65367be9c217a37ff2730780277d02ae542cf59fe8012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdffffff02a0860100000000001976a91460d9027bf273cc405417ecf8eaa3ea4849180fdf88acafdd1000000000001976a91406c13fd5fb0f2c46e784fe2a41d129972ae1d9c988ac498d1600
```
Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction | electrum.network.TxBroadcastServerReturnedError: Missing inputs
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 800, in broadcast_transaction
    out = await self.interface.session.send_request('blockchain.transaction.broadcast', [str(tx)], timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/electrum/interface.py", line 107, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 526, in send_request
    raise result
aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\nMissing inputs\n[02000000031eb6026b0353b9ce95f11bf162fb802054b9aae7356aadb8263f49580417796d000000006b483045022100f0ca3263933eb35ce1c3114f2fceaabdb10767f5e6b65301de80a81e026c4c0502205f66cafa2b0a58fb28d6ce585ad84c41449b51398577c21e9f5dd5c99ec7796b012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdffffffb7ea65e7ecbd181357ef02e1b1cdd2aaf2ce044d914528c66d324d6b5b29b37a000000006b4830450221008e2d2a258c1f4fe3c812a705d7a8005954679869a90d64fc9ee72d6e48773206022076ad230675cf952d279c57239b9c7846b942b5b589c23e75a9dcb36ab340b47b012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdfffffff210208ef21099c5687aac9a902782c58afa7f03aa3b27cd68b7a3f6828383f2000000006a473044022040ee52fa57fa447d7e9629ea52afe2bb1ea12f4326cfe43c740de7c94b860edb022001ed7a952e3b97c152256b65367be9c217a37ff2730780277d02ae542cf59fe8012103619d521729d7eaf8d1d781ad374c722d3820efc8134467263ba93cac36710128fdffffff02a0860100000000001976a91460d9027bf273cc405417ecf8eaa3ea4849180fdf88acafdd1000000000001976a91406c13fd5fb0f2c46e784fe2a41d129972ae1d9c988ac498d1600]')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 306, in run_cmdline
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 98, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 338, in broadcast
    self.network.run_from_another_thread(self.network.broadcast_transaction(tx))
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 287, in run_from_another_thread
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 768, in make_reliable_wrapper
    raise success_fut.exception()
  File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction
    raise TxBroadcastServerReturnedError(self.sanitize_tx_broadcast_response(e.message)) from e
electrum.network.TxBroadcastServerReturnedError: Missing inputs
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 384, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 806, in broadcast_transaction | electrum.network.TxBroadcastServerReturnedError: Missing inputs\n')
```

**Comment by SomberNight** [comment]
Re testnet; do you have "local" transactions in your wallet?

Probably easier to see using GUI. With CLI, you can use the "history" command, and check if any transactions have height == -2.

**Comment by RuhiPoddar** [comment]
yes, 2 txns with height = -2. How can I get rid of these?

**Comment by SomberNight** [comment]
I don't think there is a way from the CLI atm. Using the Qt GUI, you can right click>`Remove` them in the History tab. Do you exclusively use the CLI?

I don't think there is a way to directly create local transactions in the CLI either, so unless you created them in the GUI, I think these might have dropped out of mempool/reorged out of chain (does not seem unlikely on testnet).

**Comment by SomberNight** [comment]
Added a `removelocaltx` command in https://github.com/spesmilo/electrum/commit/40bf049c82f9c6850fa0124ed5524b5e42d36406

**Comment by RuhiPoddar** [comment]
Removed the local txns using the GUI. Its working. Thanks a lot. :)
