### ISSUE TITLE
With Trezor: "if you use password, please ensure the password is correct" when the correct password is "" (empty)

### ISSUE THREAD

**Issue by colourful-land** [spesmilo/electrum#5139]
Reproduce.

1. Launch electrum with "create a default wallet" wizard, hit "next".
2. Two devices are provided, trezor…webusb and trezor…bridge. Choose any. The behaviour is all the same.
3. Electrum asks for a password, hit "Enter" without filling any password (because the correct password in my case is "", an empty string).
4. get the message "if you use password, please ensure the password is correct".

Note that the Trezor perform correctly in the web browser (both Firefox and Chrome) when entered nothing in password field.

The console first half of the console output seems to have nothing to do with this specific complaint, but I  included the entire console output anyway. The phrase "Contraseña incorrecta" in the output simply means "Incorrect Password".

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 283, in choose_hw_device
        include_failing_clients=True)
      File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 510, in unpaired_device_infos
        raise Exception(message)
    Exception: Missing libraries for coldcard.
    Make sure you install it with python3
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 283, in choose_hw_device
        include_failing_clients=True)
      File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 510, in unpaired_device_infos
        raise Exception(message)
    Exception: Missing libraries for keepkey.
    Make sure you install it with python3
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 283, in choose_hw_device
        include_failing_clients=True)
      File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 510, in unpaired_device_infos
        raise Exception(message)
    Exception: Missing libraries for ledger.
    Make sure you install it with python3
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 283, in choose_hw_device
        include_failing_clients=True)
      File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 510, in unpaired_device_infos
        raise Exception(message)
    Exception: Missing libraries for safe_t.
    Make sure you install it with python3
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/installwizard.py", line 273, in select_storage
        self.run('choose_hw_device', HWD_SETUP_DECRYPT_WALLET)
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 96, in run
        f(*args)
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 317, in choose_hw_device
        self.choice_dialog(title=title, message=msg, choices=choices, run_next= lambda *args: self.on_device(*args, purpose=purpose))
      File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/installwizard.py", line 103, in func_wrapper
        run_next(*out)
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 317, in <lambda>
        self.choice_dialog(title=title, message=msg, choices=choices, run_next= lambda *args: self.on_device(*args, purpose=purpose))
      File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 349, in on_device
        self.storage.decrypt(password)
      File "/usr/local/lib/python3.6/dist-packages/electrum/storage.py", line 266, in decrypt
        s = zlib.decompress(ec_key.decrypt_message(self.raw, enc_magic))
      File "/usr/local/lib/python3.6/dist-packages/electrum/ecc.py", line 436, in decrypt_message
        raise InvalidPassword()
    electrum.util.InvalidPassword: Contraseña incorrecta
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 340, in init_gui
        self.gui.main()
      File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/__init__.py", line 309, in main
        if not self.start_new_window(path, self.config.get('url'), app_is_starting=True):
      File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/__init__.py", line 207, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/__init__.py", line 232, in start_new_window
        if wizard.select_storage(path, self.daemon.get_wallet):
      File "/usr/local/lib/python3.6/dist-packages/electrum/gui/qt/installwizard.py", line 280, in select_storage
        return self.run_and_get_wallet(get_wallet_from_daemon)
    TypeError: run_and_get_wallet() takes 1 positional argument but 2 were given

**Comment by SomberNight** [comment]
> `TypeError: run_and_get_wallet() takes 1 positional argument but 2 were given`

This exception is a recently introduced bug; will fix that.

However regarding the main issue; your wallet file is encrypted with a key derived from your seed words + passphrase (seed extension). To be able to decrypt and open it, the trezor needs to be initialised using the same seed words as when during wallet creation (I assume this is the case); and also you need to use the same passphrase as during wallet creation.

Another option is to simply create a new wallet file (for the same wallet conceptually).

**Comment by colourful-land** [comment]
@SomberNight 
> However regarding the main issue; your wallet file is encrypted with a key derived from your seed words + passphrase (seed extension). To be able to decrypt and open it, the trezor needs to be initialised using the same seed words as when during wallet creation (I assume this is the case); and also you need to use the same passphrase as during wallet creation.

Sorry that I am confused. You seem to be saying that the wallet file used by Electrum when accessing Trezor has to be encrypted just like the wallet file created without hardware wallet, is that right? I can see some reasons for that, e.g. the wallet file might contain a list of derivated Bitcoin addresses with balance on it, therefore should be treated as secret and encrypted, and that is just how Electrum works.

Since the encryption key for a wallet file to be used with Trezor depends on both the seed words + passphrase, Trezor has to be firstly reset, then re-initialised by Electrum (not through the web browser) in order for it to be used with Electrum, is that what you mean?

If so, this is a change of behaviour from previous versions. I didn't need to re-initialise Trezor in order to create a wallet in Electrum to use it, with or without a passphrase (seed extension), in 2018.

**Comment by SomberNight** [comment]
> the wallet file used by Electrum, despite having no private keys in it, has to be encrypted just like the wallet file created without hardware wallet, is that what you mean?

It **can** be encrypted; and by default it is.

> Trezor has to be firstly reset, then re-initialised in Electrum

No; you don't need to reset the Trezor.

The encryption key is derived from the seed words and the passphrase (seed extension).
To be able to open the wallet file, both of those need to be the same they were when the wallet file was created. Assuming you haven't reset your trezor since, just make sure the passphrase is the same.

Also, to circumvent the issue, you could just create a new wallet file.

**Comment by colourful-land** [comment]
@SomberNight I see. Okay so to resolve the issue I recreated the wallet. Thanks.
