### ISSUE TITLE
Electrum filled with non-working servers.

### ISSUE THREAD

**Issue by YourUsername3** [spesmilo/electrum#5163]
**Hello, I installed Electrum for Mac OS X today and my wallet is filled with non-working/malicious servers.** I can't synchronize my wallet because all the servers are synchronizing then it says No Connection and it repeats with all the servers.

**Comment by SomberNight** [comment]
Can you try launching Electrum from the terminal, and providing the `-v` flag?
So e.g. `/Applications/Electrum.app/Contents/MacOS/Electrum -v`

What do you see in the logs?

**Comment by YourUsername3** [comment]
Last login: Tue Feb 26 10:50:23 on console
Patryks-iMac:~ patryk$ /Applications/Electrum.app/Contents/MacOS/Electrum -v
[SimpleConfig] electrum directory /Users/patryk/.electrum
failed to connect to JSON-RPC server: [Errno 61] Connection refused
[p] registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
[p] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[p] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[p] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[p] registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
[p] registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
[p] registering wallet type ('2fa', 'trustedcoin')
[profiler] Plugins.__init__ 0.0086
[n] blockchains [0]
[FxThread] using exchange Coinbase
[n] starting network
[n] connecting to v22018121929279401.happysrv.de:50002:s as new interface
[profiler] Daemon.__init__ 0.0016
[Coinbase] getting fx quotes for USD
qt/history_list: could not import electrum.plot. This feature needs matplotlib to be installed.
[i][bauerjda5hnedjam.onion] disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(8, 'nodename nor servname provided, or not known'),)
[i][qtornadoklbgdyww.onion] disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(8, 'nodename nor servname provided, or not known'),)
[i][electrum9047810.rollerco.xyz] connection established. version: ['ElectrumX 1.8.12', '1.4']
[i][electrum9047810.rollerco.xyz] set blockchain with height 564779
[i][electrum9047810.rollerco.xyz] skipping header 564779
[n] no height for main interface
[Coinbase] received fx quotes
[i][e-1.claudioboxx.com] connection established. version: ['ElectrumX 1.8.12', '1.4']
[profiler] ElectrumGui.__init__ 0.3250
[WalletStorage] wallet path /Volumes/Untitled 1/bitcoin wallet
[i][v22018121929279401.happysrv.de] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][e-1.claudioboxx.com] set blockchain with height 564779
[i][e-1.claudioboxx.com] skipping header 564779
[n] no height for main interface
[n] switching to electrum9047810.rollerco.xyz:50017:s
[i][vmd27610.contaboserver.net] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][v22018121929279401.happysrv.de] set blockchain with height 564779
[i][v22018121929279401.happysrv.de] skipping header 564779
[i][vmd27610.contaboserver.net] set blockchain with height 564779
[i][vmd27610.contaboserver.net] skipping header 564779
[n] fee_histogram [[35, 100860], [27, 139758], [25, 106517], [11, 126017], [9, 322534], [8, 41426], [5, 157555], [4, 158394], [3, 346242], [2, 795002], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[WalletStorage] wallet path /Volumes/Untitled 1/bitcoin wallet
[WalletStorage] wallet path /Volumes/Untitled 1/bitcoin wallet
[i][electrumx.bot.nu] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrum.leblancnet.us] connection established. version: ['ElectrumX 1.8.12', '1.4']
[i][electrumx.ddns.net] connection established. version: ['ElectrumX 1.8.12', '1.4']
[i][electrum.mindspot.org] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrumx.bot.nu] set blockchain with height 564779
[i][electrumx.bot.nu] skipping header 564779
[i][electrum.leblancnet.us] set blockchain with height 564779
[i][electrum.leblancnet.us] skipping header 564779
[i][electrumx.ddns.net] set blockchain with height 564779
[i][electrumx.ddns.net] skipping header 564779
[i][electrum.mindspot.org] set blockchain with height 564779
[i][electrum.mindspot.org] skipping header 564779
[profiler] AddressSynchronizer.load_transactions 0.0005
[profiler] AddressSynchronizer.load_local_history 0.0001
[profiler] AddressSynchronizer.check_history 0.0000
[i][electrum9047810.rollerco.xyz] disconnecting due to: OSError(30, 'Read-only file system')
[profiler] Deterministic_Wallet.try_detecting_internal_addresses_corruption 0.0171
[profiler] ElectrumWindow.load_wallet 0.0408
[HistoryModel] refreshing... reason: update_tabs
[profiler] Abstract_Wallet.get_full_history 0.0006
[profiler] HistoryModel.refresh 0.0102
[n] switching to electrumx.bot.nu:50002:s
[n] fee_histogram [[35, 104197], [27, 143675], [25, 106940], [11, 127598], [9, 323317], [8, 41426], [5, 157555], [4, 158924], [3, 346838], [2, 792252], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 10073, 5: 12219, 2: 26825}
[i][electrumx.bot.nu] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrumx.ddns.net:50002:s
[n] fee_histogram [[36, 107739], [28, 115973], [26, 131684], [21, 123505], [10, 159812], [9, 236267], [6, 125922], [4, 237310], [3, 353888], [2, 807174], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 21192, 5: 21192, 2: 26889}
[i][yuio.top] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrumx.ddns.net] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to v22018121929279401.happysrv.de:50002:s
[n] fee_histogram [[35, 100860], [27, 138004], [25, 106517], [11, 125441], [9, 322534], [8, 41426], [5, 157555], [4, 157569], [3, 346016], [2, 794780], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][yuio.top] set blockchain with height 564779
[i][yuio.top] skipping header 564779
[i][orannis.com] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][v22018121929279401.happysrv.de] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to vmd27610.contaboserver.net:50002:s
[i][electrum2.eff.ro] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrum2.eff.ro] set blockchain with height 564779
[i][electrum2.eff.ro] skipping header 564779
[i][orannis.com] set blockchain with height 564779
[i][orannis.com] skipping header 564779
[i][vmd27610.contaboserver.net] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum.mindspot.org:50002:s
[i][helicarrier.bauerj.eu] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][helicarrier.bauerj.eu] set blockchain with height 564779
[i][helicarrier.bauerj.eu] skipping header 564779
[n] fee_histogram [[36, 101153], [28, 109194], [25, 153787], [14, 101470], [9, 357935], [8, 41426], [5, 158690], [4, 160752], [3, 349705], [2, 798565], [1, 2019941]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][electrum.peleion.com] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrum.peleion.com] set blockchain with height 564779
[i][electrum.peleion.com] skipping header 564779
[i][electrum.mindspot.org] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to e-1.claudioboxx.com:50002:s
[n] fee_histogram [[34, 101391], [27, 129123], [25, 103120], [10, 207270], [9, 235921], [8, 41087], [5, 156932], [3, 499194], [2, 794329], [1, 2025977]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][e-1.claudioboxx.com] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum2.eff.ro:50002:s
[i][electrum.vom-stausee.de] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrum.vom-stausee.de] set blockchain with height 564779
[i][electrum.vom-stausee.de] skipping header 564779
[n] fee_histogram [[36, 102032], [28, 109996], [26, 123302], [16, 128985], [9, 369638], [8, 41426], [6, 83798], [4, 236211], [3, 350118], [2, 798790], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][electrum2.eff.ro] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum.vom-stausee.de:50002:s
[i][VPS.hsmiths.com] connection established. version: ['ElectrumX 1.9.5', '1.4']
[n] fee_histogram [[36, 108109], [28, 117180], [26, 132938], [21, 124590], [10, 159812], [9, 236267], [6, 125922], [4, 237310], [3, 354112], [2, 807174], [1, 2028401], [0, 99587]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][VPS.hsmiths.com] set blockchain with height 564779
[i][VPS.hsmiths.com] skipping header 564779
[i][electrum.vom-stausee.de] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to orannis.com:50002:s
[i][electrum-unlimited.criptolayer.net] disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionRefusedError(61, "Connect call failed ('188.40.93.205', 50002)"),)
[n] fee_histogram [[36, 105678], [28, 113758], [26, 127544], [21, 119077], [10, 155402], [9, 236267], [6, 125638], [4, 236716], [3, 352693], [2, 799926], [1, 2050706], [0, 1474553]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[n] couldn't launch iface bauerjda5hnedjam.onion:50002:s -- TimeoutError()
[n] couldn't launch iface qtornadoklbgdyww.onion:50002:s -- TimeoutError()
[i][orannis.com] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum.leblancnet.us:50002:s
[i][109.202.107.15] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][109.202.107.15] set blockchain with height 564779
[i][109.202.107.15] skipping header 564777
[i][erbium1.sytes.net] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][erbium1.sytes.net] set blockchain with height 564779
[i][erbium1.sytes.net] skipping header 564779
[i][bitcoins.sk] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][bitcoins.sk] set blockchain with height 564779
[i][bitcoins.sk] skipping header 564779
[n] fee_histogram [[36, 100578], [27, 152792], [25, 108225], [12, 110575], [9, 347222], [8, 41426], [5, 158122], [4, 160752], [3, 349254], [2, 795218], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 20096, 5: 21194, 2: 26826}
[i][electrum.leblancnet.us] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to VPS.hsmiths.com:50002:s
[n] fee_histogram [[34, 100944], [27, 128087], [25, 103120], [10, 206252], [9, 235921], [8, 41087], [5, 156932], [3, 499005], [2, 791207], [1, 2025977]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][VPS.hsmiths.com] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum.peleion.com:50002:s
[n] invalid donation address from server: 
[n] fee_histogram [[36, 108467], [28, 117613], [26, 132938], [21, 124531], [10, 160037], [9, 236267], [6, 125922], [4, 237310], [3, 354112], [2, 807177], [1, 2006019]]
[n] fee_estimates {25: 2545, 10: 21189, 5: 21189, 2: 31307}
[i][electrum.taborsky.cz] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrum.taborsky.cz] set blockchain with height 564779
[i][electrum.taborsky.cz] skipping header 564779
[i][109.202.107.15] skipping header 564779
[i][electrum.peleion.com] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to erbium1.sytes.net:50002:s
[i][b.ooze.cc] disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 61] Connect call failed ('145.239.252.207', 50002), [Errno 65] No route to host",),)
[n] fee_histogram [[36, 101153], [27, 154713], [25, 108225], [14, 100756], [9, 357678], [8, 41426], [5, 158406], [4, 160752], [3, 349480], [2, 795218], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 21192, 5: 21192, 2: 26885}
[i][139.162.14.142] connection established. version: ['ElectrumX 1.8.12', '1.4']
[i][erbium1.sytes.net] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to helicarrier.bauerj.eu:50002:s
[n] fee_histogram [[36, 100443], [27, 152792], [25, 108225], [12, 110130], [9, 347222], [8, 41426], [5, 158122], [4, 160752], [3, 349254], [2, 798340], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][139.162.14.142] set blockchain with height 564779
[i][139.162.14.142] skipping header 564779
[i][helicarrier.bauerj.eu] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to 109.202.107.15:54183:s
[n] invalid donation address from server: 
[i][81-7-13-84.blue.kundencontroller.de] connection established. version: ['ElectrumX 1.9.5', '1.4']
[n] fee_histogram [[36, 100928], [27, 153700], [25, 108225], [13, 101391], [9, 356631], [8, 41426], [5, 158406], [4, 160752], [3, 349254], [2, 798340], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][81-7-13-84.blue.kundencontroller.de] set blockchain with height 564779
[i][81-7-13-84.blue.kundencontroller.de] skipping header 564779
[i][109.202.107.15] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to 81-7-13-84.blue.kundencontroller.de:50002:s
[i][109.232.227.149] connection established. version: ['ElectrumX 1.9.5', '1.4']
[n] fee_histogram [[34, 100570], [27, 127167], [24, 105502], [10, 191033], [9, 234879], [8, 41087], [4, 250669], [3, 227211], [2, 675995], [1, 1266453]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][109.232.227.149] set blockchain with height 564779
[i][109.232.227.149] skipping header 564779
[i][81-7-13-84.blue.kundencontroller.de] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to 109.232.227.149:54184:s
[n] invalid donation address from server: 
[n] fee_histogram [[35, 100860], [27, 139758], [25, 106517], [11, 125856], [9, 322534], [8, 41426], [5, 157555], [4, 157761], [3, 346242], [2, 795003], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][3smoooajg7qqac2y.onion] disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(8, 'nodename nor servname provided, or not known'),)
[i][109.232.227.149] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum.taborsky.cz:50002:s
[n] fee_histogram [[34, 102092], [27, 131877], [25, 104025], [10, 208873], [9, 235921], [8, 41426], [5, 157272], [3, 500082], [2, 791432], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][electrum.taborsky.cz] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to yuio.top:50002:s
[i][vmd30612.contaboserver.net] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][vmd30612.contaboserver.net] set blockchain with height 564779
[i][vmd30612.contaboserver.net] skipping header 564779
[n] fee_histogram [[36, 101153], [28, 109035], [25, 154196], [14, 100756], [9, 357935], [8, 41426], [5, 158406], [4, 160752], [3, 349705], [2, 798340], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][yuio.top] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to 139.162.14.142:50002:s
[i][electrum.hsmiths.com] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][kirsche.emzy.de] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][electrum.hsmiths.com] set blockchain with height 564779
[i][electrum.hsmiths.com] skipping header 564779
[i][kirsche.emzy.de] set blockchain with height 564779
[i][kirsche.emzy.de] skipping header 564779
[n] fee_histogram [[35, 100276], [27, 136678], [25, 105471], [11, 124798], [9, 322534], [8, 41426], [5, 157555], [4, 157378], [3, 345791], [2, 794780], [1, 2025992]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][139.162.14.142] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum.hsmiths.com:50002:s
[i][icarus.tetradrachm.net] disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 51] Connect call failed ('199.59.105.228', 50002), [Errno 65] No route to host",),)
[i][electrum3802306.fullhealth.net] connection established. version: ['ElectrumX 1.8.12', '1.4']
[n] fee_histogram [[35, 101645], [27, 143003], [25, 106716], [11, 126998], [9, 323317], [8, 41426], [5, 157555], [4, 158924], [3, 346838], [2, 792252], [1, 2026184]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][electrum3802306.fullhealth.net] set blockchain with height 564779
[i][electrum3802306.fullhealth.net] skipping header 564779
[i][electrum.hsmiths.com] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to bitcoins.sk:50002:s
[n] fee_histogram [[32, 106770], [26, 143012], [19, 81564], [9, 354001], [8, 39286], [6, 76808], [4, 224831], [3, 331055], [2, 782269], [1, 2007058]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][bitcoins.sk] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to kirsche.emzy.de:50002:s
[n] fee_histogram [[36, 106656], [28, 115143], [26, 130252], [21, 123344], [10, 158167], [9, 236267], [6, 125922], [4, 236716], [3, 353032], [2, 809844], [1, 2026183]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][bitcoin3nqy3db7c.onion] disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(8, 'nodename nor servname provided, or not known'),)
[i][kirsche.emzy.de] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum3802306.fullhealth.net:50003:s
[n] fee_histogram [[36, 109000], [28, 117748], [26, 132938], [21, 124814], [10, 162632], [9, 236267], [6, 126085], [4, 237310], [3, 354112], [2, 810296], [1, 2020225]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][electrum3802306.fullhealth.net] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to vmd30612.contaboserver.net:50002:s
[n] fee_histogram [[36, 109536], [28, 118722], [26, 132902], [21, 125047], [10, 136119], [9, 235416], [6, 113890], [4, 186559], [3, 236956], [2, 693079], [1, 1266660]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][vmd30612.contaboserver.net] disconnecting due to: OSError(30, 'Read-only file system')
[i][currentlane.lovebitco.in] connection established. version: ['ElectrumX 1.9.5', '1.4']
[n] connecting to vmd30612.contaboserver.net:50002:s as new interface
[i][wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion] disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(8, 'nodename nor servname provided, or not known'),)
[i][currentlane.lovebitco.in] set blockchain with height 564779
[i][currentlane.lovebitco.in] skipping header 564779
[n] no height for main interface
[i][vmd30612.contaboserver.net] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][E-X.not.fyi] connection established. version: ['ElectrumX 1.9.5', '1.4']
[i][vmd30612.contaboserver.net] set blockchain with height 564779
[i][vmd30612.contaboserver.net] skipping header 564779
[n] no height for main interface
[n] switching to currentlane.lovebitco.in:50002:s
[n] fee_histogram [[34, 101391], [27, 128623], [25, 103120], [10, 206252], [9, 235921], [8, 41087], [5, 156932], [3, 499005], [2, 794329], [1, 2025976]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][E-X.not.fyi] set blockchain with height 564779
[i][E-X.not.fyi] skipping header 564779
[i][currentlane.lovebitco.in] disconnecting due to: OSError(30, 'Read-only file system')
[i][electrum-server.ninja] connection established. version: ['ElectrumX 1.9.5', '1.4']
[n] switching to E-X.not.fyi:50002:s
[i][electrum-server.ninja] set blockchain with height 564779
[i][electrum-server.ninja] skipping header 564779
[n] fee_histogram [[34, 101965], [27, 131877], [25, 104025], [10, 208647], [9, 235921], [8, 41426], [5, 157272], [3, 500082], [2, 791432], [1, 2020229]]
[n] fee_estimates {25: 2545, 10: 20109, 5: 21192, 2: 26889}
[i][E-X.not.fyi] disconnecting due to: OSError(30, 'Read-only file system')
[n] switching to electrum-server.ninja:50002:s
[ElectrumWindow][/bitcoin wallet] close_wallet /Volumes/Untitled 1/bitcoin wallet
[profiler] AddressSynchronizer.save_transactions 0.0006
Traceback (most recent call last):
  File "electrum/gui/qt/main_window.py", line 3171, in closeEvent
  File "electrum/gui/qt/main_window.py", line 3192, in clean_up
  File "electrum/gui/qt/__init__.py", line 286, in close_window
  File "electrum/daemon.py", line 276, in stop_wallet
  File "electrum/address_synchronizer.py", line 172, in stop_threads
  File "electrum/util.py", line 367, in <lambda>
  File "electrum/util.py", line 363, in do_profile
  File "electrum/storage.py", line 122, in write
  File "electrum/storage.py", line 134, in _write
OSError: [Errno 30] Read-only file system: '/Volumes/Untitled 1/bitcoin wallet.tmp.892'
Abort trap: 6
Patryks-iMac:~ patryk$

**Comment by SomberNight** [comment]
The issue is `OSError(30, 'Read-only file system')`
Any idea about that error?

**Comment by YourUsername3** [comment]
That's because i closed the Wallet.

**Comment by YourUsername3** [comment]
This is closing the wallet:
[ElectrumWindow][/bitcoin wallet] close_wallet /Volumes/Untitled 1/bitcoin wallet
[profiler] AddressSynchronizer.save_transactions 0.0006
Traceback (most recent call last):
File "electrum/gui/qt/main_window.py", line 3171, in closeEvent
File "electrum/gui/qt/main_window.py", line 3192, in clean_up
File "electrum/gui/qt/**init**.py", line 286, in close_window
File "electrum/daemon.py", line 276, in stop_wallet
File "electrum/address_synchronizer.py", line 172, in stop_threads
File "electrum/util.py", line 367, in
File "electrum/util.py", line 363, in do_profile
File "electrum/storage.py", line 122, in write
File "electrum/storage.py", line 134, in _write
OSError: [Errno 30] Read-only file system: '/Volumes/Untitled 1/bitcoin wallet.tmp.892'
Abort trap: 6
Patryks-iMac:~ patryk$

**Comment by SomberNight** [comment]
No. It's all over the log. Electrum cannot write to its own data directory it seems.

**Comment by YourUsername3** [comment]
hmm

**Comment by YourUsername3** [comment]
Fixed. It's because the wallet was on an NTFS drive and Mac OS X can't write to NTFS.

**Comment by SomberNight** [comment]
Ok, great, thanks.
I will try to reproduce later, and see how this could be auto-detected and shown to the user. I will close the issue after that's handled.
