### ISSUE TITLE
problem loading wallet after update: "not enough values to unpack (expected 4, got 3)"

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#5177]
I just pulled master branch, now on #bf1c1c2a11d9ca91bcda2a826d44d9e251da0692

Opening any wallet (using -w flag) fails with:

```
[profiler] JsonDB.load_transactions 0.0035
[profiler] AddressSynchronizer.load_local_history 0.0080
[profiler] AddressSynchronizer.check_history 0.0028
Traceback (most recent call last):
  File "/home/nick/bitcoin/electrum/electrum/gui/qt/__init__.py", line 221, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/home/nick/bitcoin/electrum/electrum/daemon.py", line 256, in load_wallet
    wallet = Wallet(storage)
  File "/home/nick/bitcoin/electrum/electrum/wallet.py", line 1838, in __new__
    wallet = WalletClass(storage)
  File "/home/nick/bitcoin/electrum/electrum/wallet.py", line 1669, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/home/nick/bitcoin/electrum/electrum/wallet.py", line 1507, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/home/nick/bitcoin/electrum/electrum/wallet.py", line 195, in __init__
    AddressSynchronizer.__init__(self, storage)
  File "/home/nick/bitcoin/electrum/electrum/address_synchronizer.py", line 79, in __init__
    self.load_and_cleanup()
  File "/home/nick/bitcoin/electrum/electrum/wallet.py", line 221, in load_and_cleanup
    super().load_and_cleanup()
  File "/home/nick/bitcoin/electrum/electrum/address_synchronizer.py", line 91, in load_and_cleanup
    self.remove_local_transactions_we_dont_have()
  File "/home/nick/bitcoin/electrum/electrum/address_synchronizer.py", line 376, in remove_local_transactions_we_dont_have
    tx_height = self.get_tx_height(txid).height
  File "/home/nick/bitcoin/electrum/electrum/address_synchronizer.py", line 550, in get_tx_height
    verified_tx_mined_info = self.db.get_verified_tx(tx_hash)
  File "/home/nick/bitcoin/electrum/electrum/json_db.py", line 83, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nick/bitcoin/electrum/electrum/json_db.py", line 630, in get_verified_tx
    height, timestamp, txpos, header_hash = self.verified_tx[txid]
ValueError: not enough values to unpack (expected 4, got 3)
```

maybe I shouldn't be using master branch?

**Comment by SomberNight** [comment]
Thank you for reporting. I believe it is fixed now.

**Comment by molecular** [comment]
yep, fixed. Thanks!
