### ISSUE TITLE
electrum --testnet -g text, crash : ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by ArduinoMasterInfernal** [spesmilo/electrum#5213]
hi everybody, i got this error with "text" option on electrum, how to solve it ?

electrum --testnet -g text

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 339, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.6/site-packages/electrum/daemon.py", line 337, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/usr/local/lib/python3.6/site-packages/electrum/gui/text.py", line 3, in <module>
    import curses
  File "/usr/local/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by ArduinoMasterInfernal** [comment]
sudo -H pip install curses-menu
Requirement already satisfied: curses-menu in /usr/local/lib/python3.6/site-packages (0.5.0)

**Comment by ArduinoMasterInfernal** [comment]
myuserenv@mycompputer:~$ python3 -V
Python 3.6.3
myuserenv@mycompputer:~$ pip3 -V
pip 19.0.3 from /home/myuserenv/.local/lib/python3.5/site-packages/pip (python 3.5)

**Comment by ecdsa** [comment]
I think the package is named curses, not curses-menu

**Comment by ArduinoMasterInfernal** [comment]
sudo -H pip install curses
Collecting curses
  Could not find a version that satisfies the requirement curses (from versions: )
No matching distribution found for curses

**Comment by ecdsa** [comment]
it looks like your python install does not have the shared library for curses

**Comment by ArduinoMasterInfernal** [comment]
I got : 
/usr/lib/python2.7/curses/ 
but for python3
/usr/lib/python3/dist-packages/
no curses inside "dist-package",  can i copy curses from 2.7 folder to python3 ?

can i try this ?

cp /usr/lib/python2.7/curses/ /usr/lib/python3/dist-packages/

**Comment by ecdsa** [comment]
no you cannot do that.
see https://stackoverflow.com/questions/3478041/python-cant-compile-curses-module-on-debian-lenny

**Comment by SomberNight** [comment]
note: just realised the Python we build for the AppImage does not contain curses; but I assume from your traces you are not using the AppImage (?)

**Comment by ArduinoMasterInfernal** [comment]
no i dont use AppImage and i dont know what is AppImage

Simply install with : 

 pip3 install https://download.electrum.org/3.3.4/Electrum-3.3.4.tar.gz

**Comment by ArduinoMasterInfernal** [comment]
same error with appImage

myuserenv@vmstation:~$ ./electrum-3.3.4-x86_64.AppImage
qt.qpa.xcb: QXcbConnection: XCB error: 145 (Unknown), sequence: 176, resource id: 0, major code: 139 (Unknown), minor code: 20
myuserenv@vmstation:~$ ./electrum-3.3.4-x86_64.AppImage -g text
Traceback (most recent call last):
  File "/tmp/.mount_electrdqRbHl/usr/bin/electrum", line 339, in <module>
    d.init_gui(config, plugins)
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/site-packages/electrum/daemon.py", line 337, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/site-packages/electrum/gui/text.py", line 3, in <module>
    import curses
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/.mount_electrdqRbHl/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by SomberNight** [comment]
Yes I know there is the same error with the AppImage, that's what I said above. That is something we should fix.

But regarding the case when you use the system python, it's something you need to handle if you want it to work.

**Comment by ArduinoMasterInfernal** [comment]
im looking for solution with python i will post solution here when i will fix it

**Comment by ecdsa** [comment]
closing, not an issue with our code

**Comment by ecdsa** [comment]
note: you may try with our appimage
