### ISSUE TITLE
sync problems with electrum 3.3.4

### ISSUE THREAD

**Issue by blockonomics** [spesmilo/electrum#5258]
Today I reopened electrum serveral times and it is stuck on synchronizing. Sometimes it gives this

```

Traceback (most recent call last):
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/synchronizer.py", line 94, in subscribe_to_address
    await self.session.subscribe('blockchain.scripthash.subscribe', [h], self.status_queue)
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/interface.py", line 122, in subscribe
    result = await self.send_request(method, params)
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/interface.py", line 109, in send_request
    raise RequestTimedOut(f'request timed out: {args} (id: {msg_id})') from e
electrum.interface.RequestTimedOut: Network request timed out.
Task exception was never retrieved
future: <Task finished coro=<subscribe_to_address() done, defined at /home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/synchronizer.py:91> exception=RequestTimedOut("request timed out: ('blockchain.scripthash.subscribe', ['ee0f0c5ad574312d0140689097b687c892e64546d3f60257039bdd5d00c3e608']) (id: 49)",)>
Traceback (most recent call last):
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/interface.py", line 107, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

```

Sometimes it gives this
```
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/aiorpcx/curio.py", line 210, in join
    await self.cancel_remaining()
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/aiorpcx/curio.py", line 223, in cancel_remaining
    await task
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/synchronizer.py", line 94, in subscribe_to_address
    await self.session.subscribe('blockchain.scripthash.subscribe', [h], self.status_queue)
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/interface.py", line 122, in subscribe
    result = await self.send_request(method, params)
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/electrum/interface.py", line 107, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/enigma/venvs/electrum/lib/python3.6/site-packages/aiorpcx/session.py", line 469, in send_request
    raise result
aiorpcx.jsonrpc.RPCError: (1, 'server subscription limit 1,100 reached')
```

**Comment by SomberNight** [comment]
Try another server. Servers are being DDOS'ed.

Is this with auto connect enabled btw?

In the first trace, requests are timing out.

In the second, the operator set very low limits, probably because of the DDOS.

-------- Original Message --------

**Comment by blockonomics** [comment]
Not sure how to enable autoconnect or try other server. I am just launching default electrum without any arguments

**Comment by blockonomics** [comment]
Update: Here are the screenshots... its still having trouble synchrozing. If some servers are getting DDOSed is there an option to switch servers automaticaly
![Screenshot from 2019-04-08 15-36-37](https://user-images.githubusercontent.com/22165583/55716431-98263f80-5a14-11e9-950b-5daa7ef2c004.png)
![Screenshot from 2019-04-08 15-36-21](https://user-images.githubusercontent.com/22165583/55716433-98bed600-5a14-11e9-9e31-b95c51346f10.png)

**Comment by ecdsa** [comment]
we are testing anti-dos measures on some servers.
better disable auto-connect, and persist with the same server until it connects.

**Comment by SomberNight** [comment]
try servers at the top of https://1209k.com/bitcoin-eye/ele.php
try e.g. (all ssl)
```
electrum.hodlister.co:50002
arboghast.bauerj.eu:50002
btc.jochen-hoenicke.de:50002
fortress.qtornado.com:50002
```

**Comment by blockonomics** [comment]
After working for a while, again this is an issue today. I have tried servers from https://1209k.com/bitcoin-eye/ele.php namely
`
btc.jochen-hoenicke.de:50002
dedi.jochen-hoenicke.de
electrum.hodlister.co:50002`

Is there a proposed solution for this ? Maybe a captcha. Manual users that complete captcha should be given priority and and not face problem. Bots can be rate limited

**Comment by jhoenicke** [comment]
What currently works: connect to dedi.jochen-hoenicke.de, go to server "Overview" wait for servers to pop up, select one of them.

That server currently only delivers server information, not wallet information, so you cannot sync, but it should help you to find a good server.
