### ISSUE TITLE
Testnet No Problem, but MainNet aioxrpcx.jsonrpc.RPCError -101 excessive resource usage

### ISSUE THREAD

**Issue by yuriygeorge** [spesmilo/electrum#5279]
```python
Traceback (most recent call last):
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/electrum/util.py", line 918, in wrapper
   return await func(*args, **kwargs)
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/electrum/interface.py", line 296, in wrapper_func
   return await func(self, *args, **kwargs)
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/electrum/interface.py", line 316, in run
   await self.open_session(ssl_context)
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/electrum/interface.py", line 416, in open_session
   await group.spawn(self.monitor_connection)
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/aiorpcx/curio.py", line 240, in __aexit__
   await self.join()
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/aiorpcx/curio.py", line 207, in join
   raise task.exception()
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/electrum/interface.py", line 428, in ping
   await self.session.send_request('server.ping')
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/electrum/interface.py", line 107, in send_request
   timeout)
 File "/home//install/lib/python3.7/asyncio/tasks.py", line 412, in wait_for
   return fut.result()
 File "/home//PycharmProjects/node_controller/venv/lib/python3.7/site-packages/aiorpcx/session.py", line 526, in send_request
   raise result
aiorpcx.jsonrpc.RPCError: (-101, 'excessive resource usage')
```

Having this issue above. Seems to only occur when we run the code in Mainnet. During Testnet, we don't see this exception. Everything seems to work fine, but we worry this error could cause side effects.

We have our own project, and we import Electrum as a 3rd party library using pip install. We model similar to the quick_start examples.

Is this normal? Maybe the remote server is sending this if we send too many requests?

EDIT: Happening from master branch of electrum.

**Comment by ysangkok** [comment]
Remote server is likely DDOSed. Try running your own server instead.

**Comment by yuriygeorge** [comment]
Correct, we ran it with master electrum version, and this is indeed the case.
How do we run a personal electrum server, can you please provide link?
Or is this the correct article: https://bitcoinmagazine.com/articles/electrum-personal-server-will-give-users-full-node-security-they-need/
https://github.com/chris-belcher/electrum-personal-server

**Comment by yuriygeorge** [comment]
Bump - does electrum vouch for https://github.com/chris-belcher/electrum-personal-server
Or are we recommended to use something else if we want to connect to our own bitcoin/electrum full node?

**Comment by SomberNight** [comment]
There 3 maintained server implementations:
https://github.com/chris-belcher/electrum-personal-server
https://github.com/kyuupichan/electrumx
https://github.com/romanz/electrs

First one is aimed at personal use / single user usecase, as name suggests; other two can be used as public servers (but you can use those privately too ofc). You can try any of them.

> does electrum vouch for https://github.com/chris-belcher/electrum-personal-server

Well not sure exactly what kind of vouching you are looking for. I have not reviewed all the code there, only parts, but it looks good. Feedback from users has been positive. The maintainer, from online interactions, seems reasonable and trustworthy.

**Comment by yuriygeorge** [comment]
Thank you
