### ISSUE TITLE
partial txn format uses only 2 bytes for derivation path index. overflow

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5366]
https://github.com/spesmilo/electrum/blob/468c35e60548e82c22f1d276cbeb9f9855b79f75/electrum/keystore.py#L299-L304

In BIP32, path indices are allocated 4 bytes, but our custom partial transaction serialization format only allocated 2 bytes.
This effectively means that wallets with over 65535 addresses cannot spend some of their UTXOs.

**Comment by SomberNight** [comment]
`Jack` on IRC reported to have hit this limit today.
```
Traceback (most recent call last):
  File "electrum\gui\qt\main_window.py", line 1641, in do_send
  File "electrum\wallet.py", line 690, in make_unsigned_transaction
  File "electrum\wallet.py", line 929, in add_input_info
  File "electrum\wallet.py", line 1717, in add_input_sig_info
  File "electrum\keystore.py", line 285, in get_xpubkey
  File "electrum\keystore.py", line 285, in <lambda>
  File "electrum\bitcoin.py", line 206, in int_to_hex
OverflowError: cannot convert int 65738 to hex (2 bytes)
```
