### ISSUE TITLE
Can't bump fees, float being passed to int_to_hex

### ISSUE THREAD

**Issue by iDemonix** [spesmilo/electrum#5483]
When trying to bump a fee, Electrum crashes out with the following stack trace:

![image](https://user-images.githubusercontent.com/3519214/60662388-2a8f8100-9e54-11e9-969d-bc7ffabb080b.png)

Looks like you're passing a float where an int is expected. This is in the latest 3.3.7 release, on Mac. I would have reported in the app, but:

![image](https://user-images.githubusercontent.com/3519214/60662419-3c712400-9e54-11e9-9688-1848f9c89b59.png)

**Comment by SomberNight** [comment]
Thank you for reporting this. Looking into crash reporter issue now.

**Comment by iDemonix** [comment]
Thanks, as a heads up it might be cool to include a link to GitHub issues on that message, so that if auto reporting fails, people know where to go.

**Comment by SomberNight** [comment]
Indeed, good idea.

Crash report failure was related to us recently starting to use cloudflare; exception was:
```
E | gui.qt.exception_window.Exception_Window | There was a problem with the automatic reporting
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qt/util.py", line 716, in run
    result = task.task()
  File "/home/user/wspace/electrum/electrum/gui/qt/exception_window.py", line 113, in <lambda>
    task = lambda: BaseCrashReporter.send_report(self, self.main_window.network.asyncio_loop, proxy)
  File "/home/user/wspace/electrum/electrum/base_crash_reporter.py", line 73, in send_report
    response = asyncio.run_coroutine_threadsafe(coro, asyncio_loop).result(timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/user/wspace/electrum/electrum/base_crash_reporter.py", line 78, in do_post
    async with session.post(url, data=data) as resp:
  File "/home/user/wspace/electrum/packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/user/wspace/electrum/packages/aiohttp/client.py", line 528, in _request
    history[0].request_info, tuple(history))
aiohttp.client_exceptions.TooManyRedirects: 0, message=''
```
(will also add exception type to error message as `0, message=''` is useless...)
For now, disabled cloudflare for this domain, will need to investigate more.
