### ISSUE TITLE
[Lightning] 100% cpu usage with lightning daemon

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#5536]
What could cause almost 100% cpu usage when running ln daemon?(my a little bit modified electrum daemon, github.com/MrNaif2018/bitcart/tree/master/daemons/ln.py)? ![](https://usercontent.irccloud-cdn.com/file/ScZzzGf2/Screenshot_20190727-230339.png)
When I stopped it I saw some traceback, could it be the cause of this issue?
```
Traceback (most recent call last):
  File "/root/electrum/electrum/util.py", line 960, in wrapp
er
    return await func(*args, **kwargs)
  File "/root/electrum/electrum/lnpeer.py", line 202, in wra
pper_func
    return await func(self, *args, **kwargs)
  File "/root/electrum/electrum/lnpeer.py", line 218, in mai
n_loop
    await group.spawn(self.process_gossip())
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio
.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio
.py", line 211, in join
    raise task.exception()
  File "/root/electrum/electrum/lnpeer.py", line 403, in _me
ssage_loop
    self.process_message(msg)
  File "/root/electrum/electrum/lnpeer.py", line 125, in pro
cess_message
    execution_result = f(payload)
  File "/root/electrum/electrum/lnpeer.py", line 1282, in on
_update_fee
    chan.update_fee(feerate, False)
  File "/root/electrum/electrum/lnchannel.py", line 634, in
update_fee
    raise Exception("a fee update is already in progress")
Exception: a fee update is already in progress
```

**Comment by ysangkok** [comment]
What is `ln.py`? And why run as root?

**Comment by MrNaif2018** [comment]
I sent the link to ln.py, it is electrum daemon, the same but just accepting multiple wallets without load_wallet. Also running not as root won't change the traceback (:

**Comment by MrNaif2018** [comment]
Sorry, it was my bad. I shouldn't have used
```
while thread.is_running:
    pass
```
but 
```
while thread.is_running:
    time.sleep(1)
```
