### ISSUE TITLE
Appimage Linux Electrum doesn't work with portable wallet  - "read only filesystem"

### ISSUE THREAD

**Issue by hiviah** [spesmilo/electrum#5551]
Using latest Electrum 3.3.8 Appimage on Linux with the -P flag for portable wallet in electrum_data does not work most likely due to the mount-magic:

    ./electrum-3.3.8-x86_64.AppImage -P
    Traceback (most recent call last):
      File "/tmp/.mount_electrAO3gTQ/usr/bin/electrum", line 345, in <module>
        config = SimpleConfig(config_options)
      File "/tmp/.mount_electrAO3gTQ/usr/lib/python3.6/site-packages/electrum/simple_config.py", line 92, in __init__
        self.path = self.electrum_path()
      File "/tmp/.mount_electrAO3gTQ/usr/lib/python3.6/site-packages/electrum/simple_config.py", line 116, in electrum_path
        make_dir(path, allow_symlink=False)
      File "/tmp/.mount_electrAO3gTQ/usr/lib/python3.6/site-packages/electrum/util.py", line 924, in make_dir
        os.mkdir(path)
    OSError: [Errno 30] Read-only file system: '/tmp/.mount_electrAO3gTQ/usr/bin/electrum_data'

Even when specifying the electrum directory with -D or wallet -w, the error is the same:

    ./electrum-3.3.8-x86_64.AppImage -P -D electrum_data
    Traceback (most recent call last):
      File "/tmp/.mount_electrVmtKKU/usr/bin/electrum", line 345, in <module>
        config = SimpleConfig(config_options)
      File "/tmp/.mount_electrVmtKKU/usr/lib/python3.6/site-packages/electrum/simple_config.py", line 92, in __init__
        self.path = self.electrum_path()
      File "/tmp/.mount_electrVmtKKU/usr/lib/python3.6/site-packages/electrum/simple_config.py", line 116, in electrum_path
        make_dir(path, allow_symlink=False)
      File "/tmp/.mount_electrVmtKKU/usr/lib/python3.6/site-packages/electrum/util.py", line 924, in make_dir
        os.mkdir(path)
    OSError: [Errno 30] Read-only file system: '/tmp/.mount_electrVmtKKU/usr/bin/electrum_data'

**Workaround**: copy the wallet to the user electrum dir or use the open wallet dialog at start to access the wallet. This allows opening wallet, but maybe not import other settings.

**Comment by AbdussamadA** [comment]
Try with just -D not both -D and -P.

**Comment by hiviah** [comment]
OK, just `-D electrum_data` seems to work.
