### ISSUE TITLE
Crash when trying to use Cosigner pool

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#5557]
![image](https://user-images.githubusercontent.com/388716/62842212-8d0f4480-bc7e-11e9-88c1-db6915bae02d.png)

Then electrum disapear

**Comment by Transisto** [comment]
Eventually one of the 4 wallet gets a transaction from the pool, it then fail this way

![image](https://user-images.githubusercontent.com/388716/62842279-f4c58f80-bc7e-11e9-88bb-8104bc4c1bf0.png)

![image](https://user-images.githubusercontent.com/388716/62842267-e4adb000-bc7e-11e9-9744-ed2f929dfc9f.png)

**Comment by Transisto** [comment]
Send to pool fail
```
20190812T013544.929034Z |     INFO | transaction | is_complete False
20190812T013546.677983Z |    ERROR | plugins.cosigner_pool.qt.Plugin | on_failure
Traceback (most recent call last):
  File "electrum\gui\qt\util.py", line 718, in run
  File "C:\Users\T3\AppData\Local\Temp\_MEI130922\electrum\plugins\cosigner_pool\qt.py", line 191, in <lambda>
    task = lambda: server.put(_hash, message)
  File "xmlrpc\client.py", line 1112, in __call__
  File "xmlrpc\client.py", line 1452, in __request
  File "xmlrpc\client.py", line 1154, in request
  File "xmlrpc\client.py", line 1166, in single_request
  File "xmlrpc\client.py", line 1272, in send_request
  File "http\client.py", line 1108, in putrequest
http.client.CannotSendRequest: Request-sent

```



decrypt from pool fail, (was it ever sent?)
```
20190812T013230.614291Z |     INFO | interface.[enode.duckdns.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190812T013230.614818Z |     INFO | network | couldn't launch iface enode.duckdns.org:50002:s -- CancelledError()
20190812T013238.034182Z |    ERROR | plugins.cosigner_pool.qt.Plugin | 
Traceback (most recent call last):
  File "C:\Users\T3\AppData\Local\Temp\_MEI130922\electrum\plugins\cosigner_pool\qt.py", line 226, in on_receive
    message = bh2u(privkey.decrypt_message(message))
  File "electrum\ecc.py", line 447, in decrypt_message
electrum.util.InvalidPassword: Incorrect password
```

**Comment by Transisto** [comment]
Solved thanks to this issue https://github.com/spesmilo/electrum/issues/3080
