### ISSUE TITLE
Electrum doesn't connect with servers

### ISSUE THREAD

**Issue by streetcrypto7** [spesmilo/electrum#5565]
See log https://pastebin.com/miiiMqsw

**Comment by SomberNight** [comment]
So you have two traces:
```
20190815T220745.918411Z |    ERROR | interface.[electrumx.cpuchain.org:50002] | Exception in wrapper_func: NameError("name 'index' is not defined",)
Traceback (most recent call last):
  File "electrum\util.py", line 894, in wrapper
  File "electrum\interface.py", line 331, in wrapper_func
  File "electrum\interface.py", line 355, in run
  File "electrum\interface.py", line 462, in open_session
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\interface.py", line 499, in run_fetch_blocks
  File "electrum\interface.py", line 511, in _process_header_at_tip
  File "electrum\interface.py", line 569, in step
  File "electrum\interface.py", line 619, in _resolve_potential_chain_fork_given_forkpoint
  File "electrum\blockchain.py", line 262, in fork
  File "electrum\blockchain.py", line 186, in func_wrapper
  File "electrum\blockchain.py", line 456, in save_header
  File "electrum\blockchain.py", line 366, in swap_with_parent
  File "electrum\blockchain.py", line 384, in _swap_with_parent
  File "electrum\blockchain.py", line 186, in func_wrapper
  File "electrum\blockchain.py", line 600, in get_chainwork
  File "electrum\blockchain.py", line 578, in chainwork_of_header_at_height
NameError: name 'index' is not defined
```

```
20190815T220734.185452Z |    ERROR | interface.[electrumx.cpuchain.org:50002] | Exception in wrapper_func: AssertionError((0, 1),)
Traceback (most recent call last):
  File "electrum\util.py", line 894, in wrapper
  File "electrum\interface.py", line 331, in wrapper_func
  File "electrum\interface.py", line 355, in run
  File "electrum\interface.py", line 462, in open_session
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\interface.py", line 499, in run_fetch_blocks
  File "electrum\interface.py", line 511, in _process_header_at_tip
  File "electrum\interface.py", line 569, in step
  File "electrum\interface.py", line 619, in _resolve_potential_chain_fork_given_forkpoint
  File "electrum\blockchain.py", line 262, in fork
  File "electrum\blockchain.py", line 186, in func_wrapper
  File "electrum\blockchain.py", line 453, in save_header
AssertionError: (0, 1)
```
The line numbers don't match up; and there is no variable named `index` in that method, so I am assuming this is for an altcoin / fork. As such, we don't have the resources to help, sorry.

The second trace *could* potentially be a bug in Electrum too; though because the report is from a fork and I don't know what code was changed, it's impossible to tell for sure.
If you can reproduce with Electrum, please say so.
