### ISSUE TITLE
Windows Docker Build error on launch - "Failed to execute script run_electrum

### ISSUE THREAD

**Issue by xaya** [spesmilo/electrum#5599]
following the build-wine docker script (on ubuntu 18.04), on windows I get the error popup with portable 3.3.8 :

Fatal error detected
Failed to execute script run_electrum

**Comment by SomberNight** [comment]
Try building with `console=True`:
https://github.com/spesmilo/electrum/blob/6f333bd86d1aa26cc23f09947f74358367262cf8/contrib/build-wine/deterministic.spec#L137

**Comment by xaya** [comment]
thanks,..

```C:\Users\ac\Desktop>electrum-3.3.8-971-g10e186c1d-dirty-portable.exe
Traceback (most recent call last):
  File "run_electrum", line 80, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "electrum\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "electrum\daemon.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\jsonrpcserver\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\jsonrpcserver\async_dispatcher.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\jsonrpcserver\dispatcher.py", line 41, in <module>
  File "site-packages\pkg_resources\__init__.py", line 1157, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1401, in get_resource_string
  File "site-packages\pkg_resources\__init__.py", line 1569, in _get
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 475, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ac\\AppData\\Local\\Temp\\_MEI24282\\jsonrpcserver\\request-schema.json'
[36604] Failed to execute script run_electrum```
