### ISSUE TITLE
Bug in json output when running getrequest with an address that is not part of any existent request

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#5605]
$electrum getrequest $address

where $address belongs to the wallet, but there's no request containing it will return:

Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 418, in <module>
    result = server.run_cmdline(config_options)
  File "/home/ss/.local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 748, in __call__
    return self.__send(self.__name, args)
  File "/home/ss/.local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 630, in _request
    check_for_errors(response)
  File "/home/ss/.local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 1321, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/home/ss/.local/lib/python3.6/site-packages/electrum/commands.py", line 619, in getrequest | Exception: Request not found\n')

We should just output:
Request not found

**Comment by badhitman** [comment]
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L711

why does the request fail instead of returning an adequate response? can you return a response that the query was not found? normal jsonrpc response, but whatever it was that search that does not find?
