### ISSUE TITLE
Lightning: IndexError: index out of range

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#5677]
Just posting a traceback I got recently, maybe it will help to find some issue.
```
E | lnpeer.Peer.[142.93.16.32:9735] | Exception in wrapper_func: IndexError('index out of range',)
Traceback (most recent call last):
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 975, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 231, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 247, in main_loop
    await group.spawn(self.process_gossip())
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 443, in _message_loop
    self.process_message(msg)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 142, in process_message
    execution_result = f(payload)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 415, in on_reply_channel_range
    ids = self.decode_short_ids(encoded)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 401, in decode_short_ids
    if encoded[0] == 0:
IndexError: index out of range
```

**Comment by MrNaif2018** [comment]
Closing as I believe it is long fixed by now (:
