### ISSUE TITLE
KeyError('type') after updating electrum

### ISSUE THREAD

**Issue by JerzySpendel** [spesmilo/electrum#5681]
I have my version of electrum which is just cloned git repository. I haven't been updating it for a while and I have been using it successfully until today when I did `git pull`.

After the update I typed my password and the next thing I got was this:

![image](https://user-images.githubusercontent.com/1176069/66270827-06c74700-e858-11e9-976b-2926788a07f3.png)

Also I sent the bug report here https://github.com/spesmilo/electrum/issues/4176

The traceback:
```
Traceback (most recent call last):
  File "/home/jerzy/electrum/electrum/gui/qt/__init__.py", line 271, in start_new_window
    window = self._create_window_for_wallet(wallet)
  File "/home/jerzy/electrum/electrum/gui/qt/__init__.py", line 218, in _create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/home/jerzy/electrum/electrum/gui/qt/main_window.py", line 180, in __init__
    self.receive_tab = self.create_receive_tab()
  File "/home/jerzy/electrum/electrum/gui/qt/main_window.py", line 1011, in create_receive_tab
    self.request_list = RequestList(self)
  File "/home/jerzy/electrum/electrum/gui/qt/request_list.py", line 71, in __init__
    self.update()
  File "/home/jerzy/electrum/electrum/gui/qt/request_list.py", line 117, in update
    for req in self.wallet.get_sorted_requests():
  File "/home/jerzy/electrum/electrum/wallet.py", line 1464, in get_sorted_requests
    out = [self.get_request(x) for x in self.receive_requests.keys()]
  File "/home/jerzy/electrum/electrum/wallet.py", line 1464, in <listcomp>
    out = [self.get_request(x) for x in self.receive_requests.keys()]
  File "/home/jerzy/electrum/electrum/wallet.py", line 1361, in get_request
    if req['type'] == PR_TYPE_ONCHAIN:
KeyError: 'type'
```

**Comment by MrNaif2018** [comment]
Update again :P, it has already been fixed

**Comment by JerzySpendel** [comment]
I have the most recent version 0dc90491b2730c8c77d3a6816b513b81e5212971.

**Comment by MrNaif2018** [comment]
Oh indeed, it was fixed in one place, but not the other
