### ISSUE TITLE
[Lightning] Paying already paid invoice crashes Electrum

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#5765]
Feel free to close this without comment if is something you're already aware of and just haven't got round to handling gracefully yet.

Attempting to pay an LN invoice that's already been paid crashes Electrum. The process just exits and no warning is shown in the UI.

This is dumped to the terminal.

```
E | lnworker.LNWallet | Exception in _pay: PaymentFailure('This invoice has been paid already')                                                                                                                                        [1/811]
Traceback (most recent call last):
  File "/Users/lukechilds/dev/oss/electrum/electrum/util.py", line 988, in wrapper
    return await func(*args, **kwargs)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 854, in _pay
    raise PaymentFailure(_("This invoice has been paid already"))
electrum.lnutil.PaymentFailure: This invoice has been paid already
QObject::setParent: Cannot set parent, new parent is in a different thread
2019-11-17 13:45:34.315 Python[12498:5650864] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff3c54143d __exceptionPreprocess + 256
        1   libobjc.A.dylib                     0x00007fff6844f720 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff3c55aec1 -[NSException raise] + 9
        3   AppKit                              0x00007fff39a5f2a5 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
        4   AppKit                              0x00007fff39a5c68c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
        5   AppKit                              0x00007fff39b1cedf -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
        6   AppKit                              0x00007fff39a5c0b6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
        7   AppKit                              0x00007fff39b1ce94 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
        8   AppKit                              0x00007fff39d2f20c -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 52
        9   libqcocoa.dylib                     0x0000000117415475 qt_plugin_instance + 164165
        10  libqcocoa.dylib                     0x0000000117401f6b qt_plugin_instance + 85051
        11  libqcocoa.dylib                     0x00000001173fbd46 qt_plugin_instance + 59926
        12  libqcocoa.dylib                     0x00000001173fb81d qt_plugin_instance + 58605
        13  QtGui                               0x0000000112ad6b66 _ZN14QWindowPrivate6createEby + 134
        14  QtWidgets                           0x0000000113eed971 _ZN14QWidgetPrivate6createEv + 1201
        15  QtWidgets                           0x0000000113eec686 _ZN7QWidget6createEybb + 326
        16  QtWidgets                           0x0000000113eff32d _ZN14QWidgetPrivate10setVisibleEb + 189
        17  QtWidgets                           0x00000001140c0252 _ZN7QDialog10setVisibleEb + 258
        18  QtWidgets.so                        0x0000000113ac40bc _ZN14sipQMessageBox10setVisibleEb + 108
        19  QtWidgets                           0x00000001140bfab3 _ZN7QDialog4execEv + 243
        20  QtWidgets.so                        0x00000001139d9bdb _ZL18meth_QDialog_exec_P7_objectS0_ + 171
        21  Python                              0x000000010fa023af _PyMethodDef_RawFastCallKeywords + 235
        22  Python                              0x000000010fa01a38 _PyCFunction_FastCallKeywords + 41
        23  Python                              0x000000010fa96368 call_function + 628
        24  Python                              0x000000010fa8f343 _PyEval_EvalFrameDefault + 6767
        25  Python                              0x000000010fa96bc9 _PyEval_EvalCodeWithName + 1698
        26  Python                              0x000000010fa01a00 _PyFunction_FastCallKeywords + 212
        27  Python                              0x000000010fa963d5 call_function + 737
        28  Python                              0x000000010fa8f486 _PyEval_EvalFrameDefault + 7090
        29  Python                              0x000000010fa96bc9 _PyEval_EvalCodeWithName + 1698
        30  Python                              0x000000010fa01678 _PyFunction_FastCallDict + 444
        31  Python                              0x000000010fa0277f _PyObject_Call_Prepend + 131
        32  Python                              0x000000010fa01b45 PyObject_Call + 136
        33  Python                              0x000000010fa8f627 _PyEval_EvalFrameDefault + 7507
        34  Python                              0x000000010fa96bc9 _PyEval_EvalCodeWithName + 1698
        35  Python                              0x000000010fa01a00 _PyFunction_FastCallKeywords + 212
        36  Python                              0x000000010fa963d5 call_function + 737
        37  Python                              0x000000010fa8f343 _PyEval_EvalFrameDefault + 6767
        38  Python                              0x000000010fa96bc9 _PyEval_EvalCodeWithName + 1698
        39  Python                              0x000000010fa01a00 _PyFunction_FastCallKeywords + 212
        40  Python                              0x000000010fa963d5 call_function + 737
        41  Python                              0x000000010fa8f343 _PyEval_EvalFrameDefault + 6767
        42  Python                              0x000000010fa01e0c function_code_fastcall + 106
        43  Python                              0x000000010fa0277f _PyObject_Call_Prepend + 131
        44  Python                              0x000000010fa01b45 PyObject_Call + 136
        45  sip.so                              0x00000001135def68 call_method + 76
        46  sip.so                              0x00000001135dacf8 sip_api_call_procedure_method + 152
        47  QtCore.so                           0x00000001136cc6d4 _ZN10sipQThread3runEv + 84
        48  QtCore                              0x00000001130146e3 _ZN7QThread11qt_metacallEN11QMetaObject4CallEiPPv + 1155
        49  libsystem_pthread.dylib             0x00007fff6970f33d _pthread_body + 126
        50  libsystem_pthread.dylib             0x00007fff697122a7 _pthread_start + 70
        51  libsystem_pthread.dylib             0x00007fff6970e425 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      ./run_electrum
```

Tested on current tip of master: cbd146a

**Comment by ecdsa** [comment]
show_error is called from a non-gui thread

**Comment by lukechilds** [comment]
Can confirm this is now working for me with helpful error as of ade47e331a6c5ab9c386eedce1f67b766ecb4ec3 💪

<img width="1226" alt="Screenshot 2019-11-18 at 11 30 25" src="https://user-images.githubusercontent.com/2123375/69024812-fed1f980-09f6-11ea-97a2-bf46ed691532.png">
