### ISSUE TITLE
Is there a minimum amount for funding txs?

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#5795]
When trying to open a channel with `amount` at 0.0005455 (and apparently any smaller value) i get the following error:
```
E | lnpeer.Peer.[electrum_bob:9736] | Exception in channel_establishment_flow: Exception('reserve too high: 546, funding_sat: 54550')
Traceback (most recent call last):
  File "/srv/app/electrum/electrum/util.py", line 999, in wrapper
    return await func(*args, **kwargs)
  File "/srv/app/electrum/electrum/lnpeer.py", line 533, in channel_establishment_flow
at = self.validate_remote_reserve(payload["channel_reserve_satoshis"], remote_dust_limit_sat, funding_sat)
  File "/srv/app/electrum/electrum/lnpeer.py", line 700, in validate_remote_reserve
    raise Exception(f'reserve too high: {remote_reserve_sat}, funding_sat: {funding_sat}')
oo high: 546, funding_sat: 54550
E | lnworker.LNWallet | Exception in _open_channel_coroutine: Exception('reserve too high: 546, funding_sat: 54550')
Traceback (most recent call last):
  File "/srv/app/electrum/electrum/util.py", line 999, in wrapper
    return await func(*args, **kwargs)
  File "/srv/app/electrum/electrum/lnworker.py", line 820, in _open_channel_coroutine
    temp_channel_id=os.urandom(32))
  File "/srv/app/electrum/electrum/util.py", line 999, in wrapper
    return await func(*args, **kwargs)
  File "/srv/app/electrum/electrum/lnpeer.py", line 533, in channel_establishment_flow
    remote_reserve_sat = self.validate_remote_reserve(payload["channel_reserve_satoshis"], remote_dust_limit_sat, funding_sat)
  File "/srv/app/electrum/electrum/lnpeer.py", line 700, in validate_remote_reserve
    raise Exception(f'reserve too high: {remote_reserve_sat}, funding_sat: {funding_sat}')
Exception: reserve too high: 546, funding_sat: 54550
```
with `amount` at least 0.000546 all channels I tried were created successfully. It looks like there is a lower bound for the `amount` of a funding transaction. 

Is this an expected behavior?

**Comment by ecdsa** [comment]
yes, this is expected.
BOLT2 suggests (but does not enforce) a reserve of 1% of the channel funding total, and the reserve cannot be lower than the dust limit.
https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#rationale

**Comment by SomberNight** [comment]
Maybe we should have an explicit minimum; and give a better error.
(and also make sure that it is enforced in both directions)

**Comment by St333p** [comment]
Thanks
By both directions you mean that `dust <= push_amount <= funding_amount - dust` or ingoing/outgoing openchannel requests?

**Comment by SomberNight** [comment]
I mean incoming and outgoing openchannel requests.

> you mean that `dust <= push_amount <= funding_amount - dust `

Re very high `push_amount`, BOLT2 says what should be enforced is that there is still enough local balance left to pay for on-chain fees.

**Comment by St333p** [comment]
Is there any documentation on the related (to `push_amount` bounds) behavior in electrum?

**Comment by SomberNight** [comment]
No, you should check the code or test.
Some of these edge cases might not be properly handled yet. This is part of the reason there hasn't been a release yet.

**Comment by St333p** [comment]
Thank you very much. Issue can be closed as far as I'm concerned.
