### ISSUE TITLE
python3.8 incompatibility due to CancelledError changes

### ISSUE THREAD

**Issue by mercurytoxic** [spesmilo/electrum#5798]
Building from master electrum-git [3.3.8.r1316.gd430ec4bf-1 ](https://github.com/spesmilo/electrum/commit/d430ec4bfc2d4ffb7b43ae63297fa9fa492aac01) on Linux red 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux

Fails `electrum/tests/test_lnpeer.py::TestPeer::test_payment FAILED`

```========================================================================================= FAILURES =========================================================================================
__________________________________________________________________________________ TestPeer.test_payment ___________________________________________________________________________________

self = <electrum.tests.test_lnpeer.TestPeer testMethod=test_payment>

    def test_payment(self):
        p1, p2, w1, w2, _q1, _q2 = self.prepare_peers()
        pay_req = self.prepare_invoice(w2)
        async def pay():
            result = await LNWallet._pay(w1, pay_req)
            self.assertEqual(result, True)
            gath.cancel()
        gath = asyncio.gather(pay(), p1._message_loop(), p2._message_loop())
        async def f():
            await gath
        with self.assertRaises(asyncio.CancelledError):
>           run(f())

electrum/tests/test_lnpeer.py:243: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
electrum/tests/test_lnpeer.py:268: in run
    return asyncio.run_coroutine_threadsafe(coro, loop=asyncio.get_event_loop()).result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def result(self, timeout=None):
        """Return the result of the call that the future represents.
    
        Args:
            timeout: The number of seconds to wait for the result if the future
                isn't done. If None, then there is no limit on the wait time.
    
        Returns:
            The result of the call that the future represents.
    
        Raises:
            CancelledError: If the future was cancelled.
            TimeoutError: If the future didn't finish executing before the given
                timeout.
            Exception: If the call raised then that exception will be raised.
        """
        with self._condition:
            if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:
                raise CancelledError()
            elif self._state == FINISHED:
                return self.__get_result()
    
            self._condition.wait(timeout)
    
            if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:
>               raise CancelledError()
E               concurrent.futures._base.CancelledError

/usr/lib64/python3.8/concurrent/futures/_base.py:437: CancelledError
----------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
Ignoring channel save
----------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------
D | lnpeer.Peer.[alice] | Sending PING
D | lnpeer.Peer.[bob] | Sending PING
D | lnpeer.Peer.[bob] | Sending PONG
D | lnpeer.Peer.[alice] | Sending PONG
I | lnchannel.Channel.[bob] | sign_next_commitment 0
I | transaction | adding signature for 03c827f4bb4521c454c3bfccb54889ea41e4ac5339fa65db791bc15ead15ea24b5
D | transaction | is_complete False
I | lnchannel.Channel.[alice] | sign_next_commitment 0
I | transaction | adding signature for 024b8c059bedf42f7a8ecbab22ddace9863c2813e900db2888b273cb3f495fba28
D | transaction | is_complete False
I | simple_config.SimpleConfig | electrum directory /tmp/electrum-lnpeer-test-rt1sxxlo
I | channel_db.ChannelDB | SQL thread started
I | channel_db.ChannelDB | Creating database
I | simple_config.SimpleConfig | electrum directory /tmp/electrum-lnpeer-test-ty6fxa5i
I | channel_db.ChannelDB | SQL thread started
I | channel_db.ChannelDB | Creating database
D | lnchannel.Channel.[alice] | Setting channel state: FUNDED -> OPEN
D | channel_db.ChannelDB | add_channel_announcement: 1/1
I | lnpeer.Peer.[alice] | CHANNEL OPENING COMPLETED for 65793x65793x257
D | lnchannel.Channel.[bob] | Setting channel state: FUNDED -> OPEN
D | channel_db.ChannelDB | add_channel_announcement: 1/1
I | lnpeer.Peer.[bob] | CHANNEL OPENING COMPLETED for 65793x65793x257
D | util.profiler | LNPathFinder.find_path_for_payment 0.0002
D | lnpeer.Peer.[alice] | Sending INIT
D | lnpeer.Peer.[bob] | Sending INIT
I | lnchannel.Channel.[alice] | add_htlc
I | lnpeer.Peer.[alice] | starting payment. len(route)=1. route: [RouteEdge(node_id=b'\x02\xf4\x9a\xb6\xa2:\xc1\xb1\xad\xcc\x81\x96*l\xb0\x14T\xb9_Z\xe2\xfa\xab\xad\xa3\xe5va\xc32B\xa2\x9a', short_channel_id=<ShortChannelID: 65793x65793x257>, fee_base_msat=1000, fee_proportional_millionths=1, cltv_expiry_delta=144)]. htlc: UpdateAddHtlc(amount_msat=100000000, payment_hash=b"\x1b\xf7\xab\xe7\xb6\x0c\xe3\xafR\x9d\xd5\xc4\xbb\x0f\xa4\xa1'j\xf97\xfe\xb3\xf7\xeeE<\xbd\x11*\xc0p\xae", cltv_expiry=147, htlc_id=0, timestamp=1574728811)
D | lnpeer.Peer.[alice] | Sending UPDATE_ADD_HTLC
I | lnpeer.Peer.[alice] | send_commitment. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
I | lnchannel.Channel.[alice] | sign_next_commitment 1
I | transaction | adding signature for 024b8c059bedf42f7a8ecbab22ddace9863c2813e900db2888b273cb3f495fba28
D | transaction | is_complete False
D | lnpeer.Peer.[alice] | Sending COMMITMENT_SIGNED
D | lnpeer.Peer.[alice] | Sending PING
D | lnpeer.Peer.[bob] | Sending PING
I | lnpeer.Peer.[bob] | on_update_add_htlc. chan 65793x65793x257. htlc_id 0
I | lnchannel.Channel.[bob] | receive_htlc
D | lnpeer.Peer.[alice] | Sending PONG
I | lnpeer.Peer.[bob] | on_commitment_signed. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
I | lnchannel.Channel.[bob] | receive_new_commitment. ctn=1, len(htlc_sigs)=1
I | lnpeer.Peer.[bob] | send_revoke_and_ack. chan 65793x65793x257. ctn: 0
I | lnchannel.Channel.[bob] | revoke_current_commitment
D | lnpeer.Peer.[bob] | Sending REVOKE_AND_ACK
I | lnpeer.Peer.[bob] | send_commitment. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
I | lnchannel.Channel.[bob] | sign_next_commitment 1
I | transaction | adding signature for 03c827f4bb4521c454c3bfccb54889ea41e4ac5339fa65db791bc15ead15ea24b5
D | transaction | is_complete False
D | lnpeer.Peer.[bob] | Sending COMMITMENT_SIGNED
I | lnpeer.Peer.[alice] | on_revoke_and_ack. chan 65793x65793x257. ctn: 0
I | lnchannel.Channel.[alice] | receive_revocation
I | lnpeer.Peer.[bob] | _fulfill_htlc. chan 65793x65793x257. htlc_id 0
I | lnchannel.Channel.[bob] | settle_htlc
D | lnpeer.Peer.[bob] | Sending UPDATE_FULFILL_HTLC
D | lnpeer.Peer.[bob] | Sending PONG
I | lnpeer.Peer.[alice] | on_commitment_signed. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
I | lnchannel.Channel.[alice] | receive_new_commitment. ctn=1, len(htlc_sigs)=1
I | lnpeer.Peer.[alice] | send_revoke_and_ack. chan 65793x65793x257. ctn: 0
I | lnchannel.Channel.[alice] | revoke_current_commitment
D | lnpeer.Peer.[alice] | Sending REVOKE_AND_ACK
I | lnpeer.Peer.[alice] | on_update_fulfill_htlc. chan 65793x65793x257. htlc_id 0
I | lnchannel.Channel.[alice] | receive_htlc_settle
I | lnpeer.Peer.[bob] | on_revoke_and_ack. chan 65793x65793x257. ctn: 0
I | lnchannel.Channel.[bob] | receive_revocation
I | lnpeer.Peer.[bob] | send_commitment. chan 65793x65793x257. ctn: 2. old number htlcs: 1, new number htlcs: 0
I | lnchannel.Channel.[bob] | sign_next_commitment 2
I | transaction | adding signature for 03c827f4bb4521c454c3bfccb54889ea41e4ac5339fa65db791bc15ead15ea24b5
D | transaction | is_complete False
D | lnpeer.Peer.[bob] | Sending COMMITMENT_SIGNED
I | lnpeer.Peer.[alice] | on_commitment_signed. chan 65793x65793x257. ctn: 2. old number htlcs: 1, new number htlcs: 0
I | lnchannel.Channel.[alice] | receive_new_commitment. ctn=2, len(htlc_sigs)=0
I | lnpeer.Peer.[alice] | send_revoke_and_ack. chan 65793x65793x257. ctn: 1
I | lnchannel.Channel.[alice] | revoke_current_commitment
D | lnpeer.Peer.[alice] | Sending REVOKE_AND_ACK
I | lnpeer.Peer.[alice] | send_commitment. chan 65793x65793x257. ctn: 2. old number htlcs: 1, new number htlcs: 0
I | lnchannel.Channel.[alice] | sign_next_commitment 2
I | transaction | adding signature for 024b8c059bedf42f7a8ecbab22ddace9863c2813e900db2888b273cb3f495fba28
D | transaction | is_complete False
D | lnpeer.Peer.[alice] | Sending COMMITMENT_SIGNED
I | lnpeer.Peer.[bob] | on_revoke_and_ack. chan 65793x65793x257. ctn: 1
I | lnchannel.Channel.[bob] | receive_revocation
------------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------------
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending PING
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending PING
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending PONG
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending PONG
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:320 sign_next_commitment 0
INFO     electrum.transaction:transaction.py:1717 adding signature for 03c827f4bb4521c454c3bfccb54889ea41e4ac5339fa65db791bc15ead15ea24b5
DEBUG    electrum.transaction:transaction.py:1722 is_complete False
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:320 sign_next_commitment 0
INFO     electrum.transaction:transaction.py:1717 adding signature for 024b8c059bedf42f7a8ecbab22ddace9863c2813e900db2888b273cb3f495fba28
DEBUG    electrum.transaction:transaction.py:1722 is_complete False
INFO     electrum.simple_config.SimpleConfig:simple_config.py:118 electrum directory /tmp/electrum-lnpeer-test-rt1sxxlo
INFO     electrum.channel_db.ChannelDB:sql_db.py:32 SQL thread started
INFO     electrum.channel_db.ChannelDB:sql_db.py:34 Creating database
INFO     electrum.simple_config.SimpleConfig:simple_config.py:118 electrum directory /tmp/electrum-lnpeer-test-ty6fxa5i
INFO     electrum.channel_db.ChannelDB:sql_db.py:32 SQL thread started
INFO     electrum.channel_db.ChannelDB:sql_db.py:34 Creating database
DEBUG    electrum.lnchannel.Channel.[alice]:lnchannel.py:227 Setting channel state: FUNDED -> OPEN
DEBUG    electrum.channel_db.ChannelDB:channel_db.py:323 add_channel_announcement: 1/1
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:974 CHANNEL OPENING COMPLETED for 65793x65793x257
DEBUG    electrum.lnchannel.Channel.[bob]:lnchannel.py:227 Setting channel state: FUNDED -> OPEN
DEBUG    electrum.channel_db.ChannelDB:channel_db.py:323 add_channel_announcement: 1/1
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:974 CHANNEL OPENING COMPLETED for 65793x65793x257
DEBUG    electrum.util.profiler:util.py:411 LNPathFinder.find_path_for_payment 0.0002
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending INIT
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending INIT
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:283 add_htlc
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1147 starting payment. len(route)=1. route: [RouteEdge(node_id=b'\x02\xf4\x9a\xb6\xa2:\xc1\xb1\xad\xcc\x81\x96*l\xb0\x14T\xb9_Z\xe2\xfa\xab\xad\xa3\xe5va\xc32B\xa2\x9a', short_channel_id=<ShortChannelID: 65793x65793x257>, fee_base_msat=1000, fee_proportional_millionths=1, cltv_expiry_delta=144)]. htlc: UpdateAddHtlc(amount_msat=100000000, payment_hash=b"\x1b\xf7\xab\xe7\xb6\x0c\xe3\xafR\x9d\xd5\xc4\xbb\x0f\xa4\xa1'j\xf97\xfe\xb3\xf7\xeeE<\xbd\x11*\xc0p\xae", cltv_expiry=147, htlc_id=0, timestamp=1574728811)
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending UPDATE_ADD_HTLC
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1113 send_commitment. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:320 sign_next_commitment 1
INFO     electrum.transaction:transaction.py:1717 adding signature for 024b8c059bedf42f7a8ecbab22ddace9863c2813e900db2888b273cb3f495fba28
DEBUG    electrum.transaction:transaction.py:1722 is_complete False
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending COMMITMENT_SIGNED
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending PING
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending PING
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1215 on_update_add_htlc. chan 65793x65793x257. htlc_id 0
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:304 receive_htlc
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending PONG
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1175 on_commitment_signed. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:369 receive_new_commitment. ctn=1, len(htlc_sigs)=1
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1159 send_revoke_and_ack. chan 65793x65793x257. ctn: 0
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:426 revoke_current_commitment
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending REVOKE_AND_ACK
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1113 send_commitment. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:320 sign_next_commitment 1
INFO     electrum.transaction:transaction.py:1717 adding signature for 03c827f4bb4521c454c3bfccb54889ea41e4ac5339fa65db791bc15ead15ea24b5
DEBUG    electrum.transaction:transaction.py:1722 is_complete False
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending COMMITMENT_SIGNED
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1399 on_revoke_and_ack. chan 65793x65793x257. ctn: 0
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:447 receive_revocation
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1372 _fulfill_htlc. chan 65793x65793x257. htlc_id 0
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:602 settle_htlc
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending UPDATE_FULFILL_HTLC
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending PONG
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1175 on_commitment_signed. chan 65793x65793x257. ctn: 1. old number htlcs: 0, new number htlcs: 1
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:369 receive_new_commitment. ctn=1, len(htlc_sigs)=1
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1159 send_revoke_and_ack. chan 65793x65793x257. ctn: 0
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:426 revoke_current_commitment
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending REVOKE_AND_ACK
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1196 on_update_fulfill_htlc. chan 65793x65793x257. htlc_id 0
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:622 receive_htlc_settle
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1399 on_revoke_and_ack. chan 65793x65793x257. ctn: 0
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:447 receive_revocation
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1113 send_commitment. chan 65793x65793x257. ctn: 2. old number htlcs: 1, new number htlcs: 0
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:320 sign_next_commitment 2
INFO     electrum.transaction:transaction.py:1717 adding signature for 03c827f4bb4521c454c3bfccb54889ea41e4ac5339fa65db791bc15ead15ea24b5
DEBUG    electrum.transaction:transaction.py:1722 is_complete False
DEBUG    electrum.lnpeer.Peer.[bob]:lnpeer.py:101 Sending COMMITMENT_SIGNED
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1175 on_commitment_signed. chan 65793x65793x257. ctn: 2. old number htlcs: 1, new number htlcs: 0
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:369 receive_new_commitment. ctn=2, len(htlc_sigs)=0
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1159 send_revoke_and_ack. chan 65793x65793x257. ctn: 1
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:426 revoke_current_commitment
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending REVOKE_AND_ACK
INFO     electrum.lnpeer.Peer.[alice]:lnpeer.py:1113 send_commitment. chan 65793x65793x257. ctn: 2. old number htlcs: 1, new number htlcs: 0
INFO     electrum.lnchannel.Channel.[alice]:lnchannel.py:320 sign_next_commitment 2
INFO     electrum.transaction:transaction.py:1717 adding signature for 024b8c059bedf42f7a8ecbab22ddace9863c2813e900db2888b273cb3f495fba28
DEBUG    electrum.transaction:transaction.py:1722 is_complete False
DEBUG    electrum.lnpeer.Peer.[alice]:lnpeer.py:101 Sending COMMITMENT_SIGNED
INFO     electrum.lnpeer.Peer.[bob]:lnpeer.py:1399 on_revoke_and_ack. chan 65793x65793x257. ctn: 1
INFO     electrum.lnchannel.Channel.[bob]:lnchannel.py:447 receive_revocation
--------------------------------------------------------------------------------- Captured stderr teardown ---------------------------------------------------------------------------------
I | channel_db.ChannelDB | SQL thread terminated
I | channel_db.ChannelDB | SQL thread terminated
I | channel_db.ChannelDB | SQL thread terminated
I | channel_db.ChannelDB | SQL thread terminated
===================================================================================== warnings summary =====================================================================================
.tox/py38/lib/python3.8/site-packages/aiohttp/helpers.py:107
  /tmp/trizen-pizzaman/electrum-git/src/electrum/.tox/py38/lib/python3.8/site-packages/aiohttp/helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def noop(*args, **kwargs):  # type: ignore

electrum/tests/test_bolt11.py::TestBolt11::test_n_decoding
  /tmp/trizen-pizzaman/electrum-git/src/electrum/.tox/py38/lib/python3.8/site-packages/bitstring.py:3504: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    if not isinstance(pos, collections.Iterable):

electrum/tests/test_network.py::TestNetwork::test_can_connect_during_backward
electrum/tests/test_network.py::TestNetwork::test_chain_false_during_binary
electrum/tests/test_network.py::TestNetwork::test_fork_conflict
electrum/tests/test_network.py::TestNetwork::test_fork_noconflict
  /usr/lib64/python3.8/asyncio/events.py:81: RuntimeWarning: coroutine 'ignore_exceptions.<locals>.wrapper' was never awaited
    self._context.run(self._callback, *self._args)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================= 1 failed, 438 passed, 3 skipped, 6 warnings in 138.91s (0:02:18) =============================================================
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "/tmp/trizen-pizzaman/electrum-git/src/electrum/.tox/py38/lib/python3.8/site-packages/_pytest/capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/tmp/trizen-pizzaman/electrum-git/src/electrum/electrum/plugin.py", line 209, in run
    self.run_jobs()
  File "/tmp/trizen-pizzaman/electrum-git/src/electrum/electrum/util.py", line 369, in on_stop
    self.logger.info("stopped")
Message: 'stopped'
Arguments: ()
ERROR: InvocationError for command /tmp/trizen-pizzaman/electrum-git/src/electrum/.tox/py38/bin/coverage run --source=electrum '--omit=electrum/gui/*,electrum/plugins/*,electrum/scripts/*,electrum/tests/*' -m py.test -v (exited with code 1)
_________________________________________________________________________________________ summary __________________________________________________________________________________________
ERROR:   py38: commands failed
==> ERROR: A failure occurred in check().
    Aborting...
:: Unable to build electrum-git - makepkg exited with code: 4
```

**Comment by NikEyX** [comment]
I have the same error - nobody has a solution to this as of yet?

**Comment by SomberNight** [comment]
@NikEyX what python version do you have?

Is this specific to python 3.8?

**Comment by NikEyX** [comment]
3.8 indeed. Seems plausible that it's specific to 3.8, but I did not test
any other version

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/blob/d08ed6410a49302151ed4122fd4a5047595dc9eb/electrum/tests/test_lnpeer.py#L239

The actual exception being raised is `concurrent.futures.CancelledError`

[Starting with py3.8](https://github.com/python/cpython/commit/431b540bf79f0982559b1b0e420b1b085f667bb7), `concurrent.futures.CancelledError` != `asyncio.CancelledError`

-----

This change looks potentially troublesome, as I think the whole codebase might be using these CancelledErrors interchangeably...

ping @ysangkok

**Comment by SomberNight** [comment]
Even more specifically, the issue is caused by
`asyncio.run_coroutine_threadsafe`
which returns a `concurrent.futures.Future`
and when the inner coroutine gets cancelled, the other exception that will get raised is
`concurrent.futures.CancelledError`

To try to understand the implications of this breaking change in python 3.8, I grepped the whole codebase for `asyncio.run_coroutine_threadsafe` and `asyncio.CancelledError` and `asyncio.TimeoutError`.

To illustrate that really the whole codebase has to be grepped because of this change, see this example in the official python documentation that @ysangkok found that is making the ~same "mistake":
https://bugs.python.org/issue39027
