### ISSUE TITLE
This problem occurred when i upgraded the code

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5844]
This problem occurred when i upgraded the code

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "./run_electrum", line 84, in <module>
    from electrum.logging import get_logger, configure_logging
  File "/home/wls/electrum/electrum/__init__.py", line 3, in <module>
    from .wallet import Wallet
  File "/home/wls/electrum/electrum/wallet.py", line 65, in <module>
    from . import transaction, bitcoin, coinchooser, paymentrequest, ecc, bip32
  File "/home/wls/electrum/electrum/paymentrequest.py", line 47, in <module>
    from .network import Network
  File "/home/wls/electrum/electrum/network.py", line 63, in <module>
    if TYPE_CHECKING:
NameError: name 'TYPE_CHECKING' is not defined

**Comment by SomberNight** [comment]
It's defined here:
https://github.com/spesmilo/electrum/blob/01fc0484841fc8ced7e96798d5f4ca794b37cd41/electrum/network.py#L36

What commit are you on?
