### ISSUE TITLE
Can't decrypt (or possibly encrypt) messages in a multisig wallet

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#5856]
Repro:

1. Create a segwit multisig wallet 
2. Open the details of an address and copy a public key
3. Open the Encrypt/decrypt window
4. Put in some message (eg "test")
5. Paste the public key you copied in step 2
6. Encrypt
7. Clear the message input box to verify message decryption is working
8. Decrypt

Expected:

Either the decrypted message appears or an error message comes up telling me I don't have the corresponding private key (ie because I chose a cosigners key instead of my own - hard to tell with the UI).

Actual:

An error message comes up that says: "m 1, n 66"

**Comment by SomberNight** [comment]
I can reproduce.

Trace:
```
E | gui.qt.main_window.[test_ms_2of3_p2wsh_p2sh_cosigner_1] | on_error
Traceback (most recent call last):
  File "...\electrum\electrum\gui\qt\util.py", line 752, in run
    result = task.task()
  File "...\electrum\electrum\wallet.py", line 1741, in decrypt_message
    addr = self.pubkeys_to_address([pubkey])
  File "...\electrum\electrum\wallet.py", line 2291, in pubkeys_to_address
    redeem_script = self.pubkeys_to_scriptcode(pubkeys)
  File "...\electrum\electrum\wallet.py", line 2295, in pubkeys_to_scriptcode
    return transaction.multisig_script(sorted(pubkeys), self.m)
  File "...\electrum\electrum\transaction.py", line 473, in multisig_script
    assert 1 <= m <= n <= 15, f'm {m}, n {n}'
AssertionError: m 2, n 1
```
The root cause is that the wallet, given a pubkey, cannot find the corresponding private key.
What the code is trying to do atm will only work in Imported Wallets and in standard (single-signer) wallets.

**Comment by SomberNight** [comment]
(copy paste of brain dump from old notes:)
wallet/keystore: find derivation path for pubkey
- in keystore, new method for MasterPublicKeyMixin:
	- def find_path_for_pubkey(self, pubkey: bytes) -> Optional[Sequence[int]]
	(pubkey -> path)
- there is already MasterPublicKeyMixin.derive_pubkey (path -> pubkey),
	which is cached
- derive_pubkey cache should be made accessible internally (replace @lru_cache)
	and it should also create an inverted map (pubkey -> path)
- find_path_for_pubkey could then do lookups in the inverted map
- however, problem: this is just a cache; how does it get filled?
	- it should not be filled on startup, as even with libsecp256k1, it's too slow
- new field in keystore: underived_pubkey_paths_set
- in Deterministic_Wallet, override load_keystore
	- near the end, fill underived_pubkey_paths_set for all keystores
	(based on num receiving and num change addresses)
- note that Deterministic_Wallet.create_new_address is a non-issue as
	it already calls keystore.derive_pubkey
- when find_path_for_pubkey is called, it would
	- do a lookup in the pubkey -> path map, return on hit; or on miss:
	- call derive_pubkey on all items in underived_pubkey_paths_set
	- do a lookup in the pubkey -> path map
