### ISSUE TITLE
Fresh electrum portable crashes at launch

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#5888]
![image](https://user-images.githubusercontent.com/388716/72228201-ae989300-3572-11ea-8f78-d9d03453cb7e.png)

From windows 10 application event :  

```
Problem signature:
P1: electrum-3.3.8-portable.exe
P2: 0.0.0.0
P3: 00000000
P4: StackHash_2beb
P5: 0.0.0.0
P6: 00000000
P7: PCH_8F_FROM_ntdll+0x0007232C
P8: c0000005
P9: 00000008
P10: 
```

**Comment by SomberNight** [comment]
Can you try killing all electrum processes and then relaunching the exe?

**Comment by Transisto** [comment]
There is no other electrum process, fresh OS boot

**Comment by SomberNight** [comment]
What version of Windows are you using? Did it work before?

**Comment by Transisto** [comment]
Win 10, Yes it did work before, I'm investing what happened to my system
arroud the time it stopped working and removing apps and drivers one at a
time.

**Comment by SomberNight** [comment]
What version of Win10? (you can e.g. see a build number in `cmd`)
Do you have an antivirus?
How does Electrum crash? Could it be that it is just taking a long time to start?

**Comment by Transisto** [comment]
[Version 10.0.18363.592]

I've tried uninstalling antivirus and a few things, I tested every previous electrum version and anything above 3.1.0 crashes, 3.0.6 is fine.

only changes that sounds OS related in this release are.

* Windows: the binaries now include ZBar, and QR code scanning should work.
and 
* Semi-automated crash reporting

**Comment by Transisto** [comment]
So I created a config that enable the logs and swapped on the trouble machine.

```
20200119T062805.852201Z |     INFO | logging | Electrum version: 3.3.8 - https://electrum.org - https://github.com/spesmilo/electrum
20200119T062805.853331Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.16299
20200119T062805.853331Z |     INFO | logging | Logging to file: C:\Users\T3\Desktop\test all electrum\electrum_data\logs\electrum_log_20200119T062805Z_6332.log
20200119T062805.853331Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20200119T062808.859098Z |     INFO | daemon | failed to connect to JSON-RPC server: [WinError 10061] No connection could be made because the target machine actively refused it
20200119T062808.861227Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20200119T062808.862497Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20200119T062808.865424Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20200119T062808.867119Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20200119T062808.868398Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20200119T062808.869161Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20200119T062808.869161Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20200119T062808.870397Z |    DEBUG | util.profiler | Plugins.__init__ 0.0103
20200119T062808.873087Z |     INFO | network | blockchains [0]
20200119T062808.874087Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20200119T062808.874087Z |     INFO | network | starting network
20200119T062808.875228Z |     INFO | network | connecting to wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002:s as new interface
20200119T062808.877161Z |    DEBUG | util.profiler | Daemon.__init__ 0.0068
20200119T062809.024110Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20200119T062809.432127Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.4045
20200119T062809.433180Z |     INFO | storage.WalletStorage | wallet path c:\users\t3\desktop\test all electrum\electrum_data\wallets\default_wallet
20200119T062809.434129Z |    DEBUG | util.profiler | JsonDB._load_transactions 0.0000
20200119T062809.434129Z |    DEBUG | util.profiler | AddressSynchronizer.load_local_history 0.0000
20200119T062809.435277Z |    DEBUG | util.profiler | AddressSynchronizer.check_history 0.0000
20200119T062809.851203Z |    DEBUG | util.profiler | AddressList.update 0.0139
20200119T062809.931144Z |    DEBUG | util.profiler | ElectrumWindow.load_wallet 0.0460
20200119T062810.064228Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20200119T062810.066207Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0000
20200119T062810.066207Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0020
20200119T062810.070176Z |    DEBUG | util.profiler | AddressList.update 0.0030
20200119T062814.231015Z |     INFO | interface.[currentlane.lovebitco.in:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None),),)
20200119T062814.231962Z |     INFO | network | couldn't launch iface currentlane.lovebitco.in:50002:s -- CancelledError()
20200119T062814.995882Z |     INFO | interface.[helicarrier.bauerj.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('127.0.0.1', 50002)"),),)
20200119T062814.995882Z |     INFO | network | couldn't launch iface helicarrier.bauerj.eu:50002:s -- CancelledError()
20200119T062815.096975Z |     INFO | interface.[btc.asis.io:50002] | connection established. version: ['ElectrumX 1.8.2', '1.4']
20200119T062815.135083Z |     INFO | interface.[ndnd.selfhost.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None),),)
20200119T062815.135083Z |     INFO | network | couldn't launch iface ndnd.selfhost.eu:50002:s -- CancelledError()
20200119T062815.262901Z |     INFO | interface.[btc.asis.io:50002] | set blockchain with height 613496
20200119T062815.262901Z |     INFO | interface.[btc.asis.io:50002] | skipping header 613496
20200119T062815.264345Z |     INFO | network | no height for main interface
20200119T062815.566940Z |     INFO | interface.[electrumx.soon.it:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('185.11.145.76', 50002)"),),)
20200119T062815.567925Z |     INFO | network | couldn't launch iface electrumx.soon.it:50002:s -- CancelledError()
20200119T062817.911310Z |     INFO | interface.[wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20200119T062817.911310Z |     INFO | network | couldn't launch iface wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002:s -- CancelledError()
20200119T062817.995398Z |     INFO | network | switching to btc.asis.io:50002:s
20200119T062818.539193Z |     INFO | interface.[vmd30612.contaboserver.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20200119T062818.540361Z |     INFO | network | couldn't launch iface vmd30612.contaboserver.net:50002:s -- CancelledError()
20200119T062818.618217Z |     INFO | interface.[electrumx.ftp.sh:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20200119T062818.618217Z |     INFO | network | couldn't launch iface electrumx.ftp.sh:50002:s -- CancelledError()
20200119T062818.806713Z |     INFO | network | fee_histogram [[22, 102609], [11, 118355], [1, 176687]]
20200119T062818.806713Z |     INFO | network | fee_estimates {25: 1251, 10: 9118, 5: 11816, 2: 14140}
20200119T062818.806713Z |     INFO | network | fee_histogram [[22, 102609], [11, 118355], [1, 176687]]
20200119T062818.807739Z |     INFO | network | fee_estimates {25: 1251, 10: 9118, 5: 11816, 2: 14140}
20200119T062819.523696Z |     INFO | interface.[electrum.emzy.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None),),)
20200119T062819.524729Z |     INFO | network | couldn't launch iface electrum.emzy.de:50002:s -- CancelledError()
20200119T062820.114033Z |     INFO | interface.[electrum2.eff.ro:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('195.135.194.4', 50002)"),),)
20200119T062820.114863Z |     INFO | network | couldn't launch iface electrum2.eff.ro:50002:s -- CancelledError()
20200119T062821.036422Z |     INFO | interface.[e-1.claudioboxx.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('45.79.156.130', 50002)"),),)
20200119T062821.036422Z |     INFO | network | couldn't launch iface e-1.claudioboxx.com:50002:s -- CancelledError()
20200119T062822.929468Z |    DEBUG | util.profiler | WalletStorage.write 0.0000
20200119T062823.299332Z |    ERROR | interface.[btc.asis.io:50002] | Exception in wrapper_func: <UntrustedServerReturnedError original_exception: RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
  File "electrum\network.py", line 846, in wrapper
  File "electrum\network.py", line 1039, in get_history_for_scripthash
  File "electrum\interface.py", line 115, in send_request
  File "asyncio\tasks.py", line 339, in wait_for
  File "site-packages\aiorpcx\session.py", line 525, in send_request
  File "site-packages\aiorpcx\session.py", line 495, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\util.py", line 934, in wrapper
  File "electrum\interface.py", line 331, in wrapper_func
  File "electrum\interface.py", line 355, in run
  File "electrum\interface.py", line 462, in open_session
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 81, in _start_tasks
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 170, in _on_address_status
  File "electrum\network.py", line 833, in make_reliable_wrapper
  File "electrum\network.py", line 848, in wrapper
electrum.network.UntrustedServerReturnedError: The server returned an error.
20200119T062823.421375Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20200119T062823.421375Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0000
20200119T062823.422361Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0010
20200119T062823.424311Z |    DEBUG | util.profiler | AddressList.update 0.0020
20200119T062823.428304Z |     INFO | network | connecting to btc.asis.io:50002:s as new interface
20200119T062826.859673Z |     INFO | interface.[qtornadoklbgdyww.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20200119T062826.860881Z |     INFO | network | couldn't launch iface qtornadoklbgdyww.onion:50002:s -- CancelledError()
20200119T062827.028669Z |     INFO | interface.[fortress.qtornado.com:443] | succeeded in getting cert
20200119T062827.188653Z |     INFO | interface.[fn.48.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('5.79.90.70', 50002)"),),)
20200119T062827.188653Z |     INFO | network | couldn't launch iface fn.48.org:50002:s -- CancelledError()
20200119T062828.265622Z |     INFO | interface.[btc.asis.io:50002] | connection established. version: ['ElectrumX 1.8.2', '1.4']
20200119T062828.436677Z |     INFO | interface.[btc.asis.io:50002] | set blockchain with height 613496
20200119T062828.436677Z |     INFO | interface.[btc.asis.io:50002] | skipping header 613496
20200119T062828.437659Z |     INFO | network | no height for main interface
20200119T062828.438652Z |     INFO | network | switching to btc.asis.io:50002:s
20200119T062828.969665Z |     INFO | network | fee_histogram [[22, 102609], [11, 118355], [1, 176687]]
20200119T062828.969665Z |     INFO | network | fee_estimates {25: 1251, 10: 9118, 5: 11816, 2: 14140}
20200119T062829.250748Z |     INFO | interface.[electrum-unlimited.criptolayer.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('188.40.93.205', 50002)"),),)
20200119T062829.251676Z |     INFO | network | couldn't launch iface electrum-unlimited.criptolayer.net:50002:s -- CancelledError()
20200119T062829.665481Z |     INFO | interface.[electrumx4.poorcoding.com:50006] | succeeded in getting cert
20200119T062830.199460Z |    ERROR | interface.[btc.asis.io:50002] | Exception in wrapper_func: <UntrustedServerReturnedError original_exception: RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
  File "electrum\network.py", line 846, in wrapper
  File "electrum\network.py", line 1039, in get_history_for_scripthash
  File "electrum\interface.py", line 115, in send_request
  File "asyncio\tasks.py", line 339, in wait_for
  File "site-packages\aiorpcx\session.py", line 525, in send_request
  File "site-packages\aiorpcx\session.py", line 495, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\util.py", line 934, in wrapper
  File "electrum\interface.py", line 331, in wrapper_func
  File "electrum\interface.py", line 355, in run
  File "electrum\interface.py", line 462, in open_session
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 81, in _start_tasks
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 170, in _on_address_status
  File "electrum\network.py", line 833, in make_reliable_wrapper
  File "electrum\network.py", line 848, in wrapper
electrum.network.UntrustedServerReturnedError: The server returned an error.
20200119T062831.616380Z |     INFO | interface.[fortress.qtornado.com:443] | connection established. version: ['ElectrumX 1.13.0', '1.4']
20200119T062831.754556Z |     INFO | interface.[fortress.qtornado.com:443] | set blockchain with height 613496
20200119T062831.755615Z |     INFO | interface.[fortress.qtornado.com:443] | skipping header 613496
20200119T062831.755615Z |     INFO | network | no height for main interface
20200119T062831.809488Z |     INFO | network | switching to fortress.qtornado.com:443:s
20200119T062831.915401Z |     INFO | gui.qt.main_window.[default_wallet] | close_wallet c:\users\t3\desktop\test all electrum\electrum_data\wallets\default_wallet
20200119T062831.919504Z |     INFO | storage.WalletStorage | saved c:\users\t3\desktop\test all electrum\electrum_data\wallets\default_wallet
20200119T062831.919504Z |    DEBUG | util.profiler | WalletStorage.write 0.0031
20200119T062832.053411Z |     INFO | network | fee_histogram [[18, 100739], [3, 121183]]
20200119T062832.054367Z |     INFO | network | fee_estimates {25: 1251, 10: 9118, 5: 11816, 2: 14142}
20200119T062832.114432Z |     INFO | plugin.Plugins | stopped
20200119T062832.127551Z |     INFO | daemon.Daemon | shutting down network
20200119T062832.127551Z |     INFO | network | stopping network
20200119T062832.127551Z |     INFO | network | couldn't launch iface electrumx2.aspinall.io:50004:s -- CancelledError()
20200119T062832.131368Z |     INFO | network | couldn't launch iface e.keff.org:50002:s -- CancelledError()
20200119T062832.131368Z |     INFO | network | couldn't launch iface yuio.top:50002:s -- CancelledError()
20200119T062832.131368Z |     INFO | network | couldn't launch iface electrumx.aspinall.io:50002:s -- CancelledError()
20200119T062832.132376Z |     INFO | network | couldn't launch iface electrumx4.poorcoding.com:50006:s -- CancelledError()
20200119T062832.133527Z |     INFO | network | couldn't launch iface orannis.com:50002:s -- CancelledError()
20200119T062832.133527Z |     INFO | network | couldn't launch iface b.ooze.cc:50002:s -- CancelledError()
20200119T062832.135505Z |     INFO | network | couldn't launch iface green-gold.westeurope.cloudapp.azure.com:56002:s -- CancelledError()
20200119T062832.135505Z |     INFO | interface.[electrumx4.poorcoding.com:50006] | disconnecting due to: CancelledError()
20200119T062832.136477Z |     INFO | interface.[e.keff.org:50002] | disconnecting due to: CancelledError()
20200119T062832.136477Z |     INFO | network | couldn't launch iface ecdsa.net:110:s -- CancelledError()
20200119T062832.267442Z |     INFO | interface.[fortress.qtornado.com:443] | disconnecting due to: CancelledError()
20200119T062832.269408Z |     INFO | daemon.Daemon | stopped
```

**Comment by SomberNight** [comment]
From the logs it looks to me the application was running for around ~25 seconds. Is that what you meant by "electrum portable crashes at launch"?
The `electrum.network.UntrustedServerReturnedError` exception seems unrelated.

Or should I be looking at the shorter log?

**Comment by Transisto** [comment]
Sorry, EDITED, that log was from the machine I used to edit the config to enable logs,

**Comment by SomberNight** [comment]
Can you test with the other binaries besides the "portable"?

**Comment by Transisto** [comment]
Here, from 3.3.8 setup

```
20200119T065914.476848Z |     INFO | logging | Electrum version: 3.3.8 - https://electrum.org - https://github.com/spesmilo/electrum
20200119T065914.477350Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.18362-SP0
20200119T065914.477350Z |     INFO | logging | Logging to file: C:\Users\T3\AppData\Roaming\Electrum\logs\electrum_log_20200119T065914Z_2136.log
20200119T065914.477350Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20200119T065916.481121Z |     INFO | daemon | failed to connect to JSON-RPC server: [WinError 10061] No connection could be made because the target machine actively refused it
20200119T065916.484049Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20200119T065916.485040Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20200119T065916.488016Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20200119T065916.489505Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20200119T065916.490995Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20200119T065916.491489Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20200119T065916.492481Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20200119T065916.493475Z |    DEBUG | util.profiler | Plugins.__init__ 0.0114
20200119T065916.494961Z |     INFO | network | blockchains [0]
20200119T065916.495457Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20200119T065916.496452Z |     INFO | network | starting network
20200119T065916.496452Z |     INFO | network | connecting to btc.usebsv.com:50006:s as new interface
20200119T065916.500913Z |    DEBUG | util.profiler | Daemon.__init__ 0.0074
20200119T065916.653218Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20200119T065916.760817Z |     INFO | interface.[ecdsa.net:110] | certificate has expired: Certificate (ecdsa.net) has expired (at 2018-02-05 17:16:56 UTC).
```

**Comment by SomberNight** [comment]
> [Version 10.0.18363.592]

I've tried with this same version of Windows in a VM and could not reproduce :/

**Comment by SomberNight** [comment]
If I built a custom binary for you, would you run that? (or can you build a Windows binary yourself from [instructions](https://github.com/spesmilo/electrum/blob/master/contrib/build-wine/README.md)?)

**Comment by Transisto** [comment]
> If I built a custom binary for you, would you run that?

Yes I would.

**Comment by SomberNight** [comment]
Custom binary uploaded here: https://filebin.net/f7qza6v0q6u4o1na
As in signed message below, please check the hash/checksum before running it.
Note that it will open an additional cmd/terminal window; this is useful for detecting certain errors that could not be logged otherwise.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Re issue https://github.com/spesmilo/electrum/issues/5888
I built a custom windows binary for debugging as promised.

Please check the hash of the binary, it should match the following:

$ sha256sum electrum-*
92205dc9384031ae70a1c4bb426c3db4f9b3f817b2f68fe52902a62e41f04800  electrum-3.3.8-1456-ge35cfb1ef-portable.exe

// From commit https://github.com/SomberNight/electrum/commit/e35cfb1ef743d481d98f7f807fb2987a327a5bfa
// Note that Travis reproducibly built the same binary here:
// https://travis-ci.org/SomberNight/electrum/jobs/640515580#L5579

SomberNight,
2020-01-22
-----BEGIN PGP SIGNATURE-----

iQIyBAEBCAAdFiEEbXohFtqQngCsIRCLsztfIyxicekFAl4oflMACgkQsztfIyxi
ceksgw/47VSi6a8G1ZU2z0HHNd190QaTjqyUFaY7yghsncRUCGZwImb3EfHTd+Bf
mjMdHNW4twDODQkcxLbukeBFCRhixHLBE8WjE7Y8fpAob2oHANSP4Rf3sPqAWCMm
9X2gboCl8L1JtxZUuZTEujAAR6sdtUOZmSNTVcADSRQ8Y26hJ2ZpMKSXj3pNS5gC
4m/JvLmd4kkOHBhtNLSuxHIJANpLxc0vnXqT7bc02vc+VeiBI6RE3fuiK6XnW9rz
CAOcuivJlXsVsTRGSDDMojkPFTKxYk6kbHll/BtxD2IpaAy0KTwMkRWX0OoTf0YN
m5J7IL47QM9WGzjv2hAVtPRA3TwSM7QI9TuTTaCE3jBBiFdcjlNLe3aXbFkz6MjU
oe7o8Ym2Lq9UhE7ZHk7RbDcjiMH3V+yOrtf9f2FWTsFbKaC07rSynwGpaClPN82+
E5uaqpPT1iKBzkjs7kkc/c7D+WVhvWSfTgbH8mYy/ApIYDC5pJko4eK6Glc56tgm
kNKJOO/mYgZFQ8PigZCVW0pT7Oyyqq4zgY/jBp7uY+g0Cc+sBfsmcLGeFES5wH9i
+JNgom0Gj2q4eN1Pke/PqLVlohFF9cu5OBDn/fGIEYuNorp4H1UZoBvFFmAADOG6
mBO5gwR/fBTdoNiBTMmD0dr//cJLHsvPbfeNgvZc0H+1Te0HCw==
=qCbB
-----END PGP SIGNATURE-----
```

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/73124964-70867080-3f6f-11ea-9303-f2a3681ace3d.png)

**Comment by Transisto** [comment]
let me know if that helped

**Comment by SomberNight** [comment]
There was just now a user on IRC (`MrBen`) who seemingly had the same issue.
None of the 3.3.8 Windows binaries worked for him anymore on system where they used to work.

He also tried running from source, from the 3.3.8 official sdist, and got similar logs as OP:

```
C:\Electrum-3.3.8\packages\aiohttp\helpers.py:105: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
I | logging | Electrum version: 3.3.8 - https://electrum.org - https://github.com/spesmilo/electrum
I | logging | Python version: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]. On platform: Windows-10-10.0.18362-SP0
I | logging | Logging to file: None
I | logging | Log filters: verbosity '*', verbosity_shortcuts ''
C:\Electrum-3.3.8\packages\jsonrpclib\jsonrpc.py:570: DeprecationWarning: urllib.parse.splittype() is deprecated as of 3.8, use urllib.parse.urlparse() instead
  schema, uri = splittype(uri)
C:\Electrum-3.3.8\packages\jsonrpclib\jsonrpc.py:581: DeprecationWarning: urllib.parse.splithost() is deprecated as of 3.8, use urllib.parse.urlparse() instead
  self.__host, self.__handler = splithost(uri)
I | daemon | failed to connect to JSON-RPC server: [WinError 10061] No connection could be made because the target machine actively refused it
I/p | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
I/p | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
I/p | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
I/p | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
I/p | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
I/p | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
I/p | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
D | util.profiler | Plugins.__init__ 0.0136
I/n | network | blockchains [0]
I | exchange_rate.FxThread | using exchange CoinGecko
I/n | network | starting network
I/n | network | connecting to b.ooze.cc:50002:s as new interface
D | util.profiler | Daemon.__init__ 0.0040
I | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
 
C:\Electrum-3.3.8>
```

**Comment by SomberNight** [comment]
@Transisto 
> let me know if that helped

Thank you for the trace. Frankly I don't know if that trace is related to the original issue :/
Latest master know has a newer python version bundled in the binaries, I hope that at least fixes this newer trace (`ImportError: cannot import name '_overlapped'`).

I had originally thought that the issue in OP only affects the binaries, but that does not seem to be the case, given `MrBen`'s account.

If you know how and have the time, please try running latest git master from source.
Otherwise, I could build a new Windows binary for you to test with.
Either would be helpful.

**Comment by Transisto** [comment]
Electrum 4b0 fixed this.
