### ISSUE TITLE
Exception Kivy on linux 

### ISSUE THREAD

**Issue by roth-a** [spesmilo/electrum#5910]
I am not sure that it is a electrum issue, or a kivy issue... even on older master commits I get the same error:

```/home/username/.local/lib/python3.7/site-packages/google/protobuf/descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from google.protobuf.pyext import _message
W | ecc_fast | failed to load libsecp256k1: OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')
[INFO   ] [Logger      ] Record log in /home/username/.kivy/logs/kivy_20-01-26_3.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
[INFO   ] [Python      ] Interpreter at "/home/username/programs/anaconda3/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.2.1'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [Time to on_start] 1.579081841 <<<<<<<<
[INFO   ] [network event] status
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event5
[INFO   ] [MTD         ] Read event from </dev/input/event5>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event5". Please ensure you have the appropriate permissions.
[INFO   ] [GL          ] NPOT texture support is available
[ERROR  ] [Image       ] Error loading texture atlas://electrum/gui/kivy/theming/light/important
[ERROR  ] [Image       ] Error loading texture atlas://electrum/gui/kivy/theming/light/important
[ERROR  ] [Image       ] Error loading texture atlas://electrum/gui/kivy/theming/light/confirmed
[ERROR  ] [Image       ] Error loading texture atlas://electrum/gui/kivy/theming/light/important
[ERROR  ] [Image       ] Error loading texture atlas://electrum/gui/kivy/theming/light/important
[ERROR  ] [Image       ] Error loading texture atlas://electrum/gui/kivy/theming/light/confirmed
E | gui.kivy.uix.dialogs.crash_reporter.ExceptionHook | exception caught by crash reporter
Traceback (most recent call last):
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 345, in idle
    Builder.sync()
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/lang/builder.py", line 788, in sync
    call_fn(next_args[:-1], None, None)
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/lang/builder.py", line 76, in call_fn
    setattr(element, key, e_value)
  File "kivy/graphics/instructions.pyx", line 366, in kivy.graphics.instructions.VertexInstruction.source.__set__
  File "kivy/graphics/context_instructions.pyx", line 430, in kivy.graphics.context_instructions.BindTexture.source.__set__
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/image/__init__.py", line 561, in __init__
    self.filename = arg
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/image/__init__.py", line 756, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/image/__init__.py", line 427, in load
    raise Exception('Unable to found %r atlas' % afn)
Exception: Unable to found None atlas
[INFO   ] [network event] status
[INFO   ] [network event] wallet_updated
E | gui.kivy.uix.dialogs.crash_reporter.ExceptionHook | exception caught by crash reporter
Traceback (most recent call last):
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 345, in idle
    Builder.sync()
  File "/home/username/programs/anaconda3/lib/python3.7/site-packages/kivy/lang/builder.py", line 788, in sync
    call_fn(next_args[:-1], None, None)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by roth-a** [comment]
Ok, I forgot to run
`cd electrum/gui/kivy/; make theming`

Now it works.
