### ISSUE TITLE
sign_digest_deterministic() got an unexpected keyword argument 'extra_entropy'

### ISSUE THREAD

**Issue by roth-a** [spesmilo/electrum#5911]
When trying to sweep a private key (master 11452722aff3877b7033c2e873f73e906a110a78 )  I get the following error:

```
./run_electrum -g qt -P --testnet  
/home/username/.local/lib/python3.7/site-packages/google/protobuf/descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from google.protobuf.pyext import _message
W | ecc_fast | failed to load libsecp256k1: OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')
E | gui.qt.main_window.[testnet] | on_error
Traceback (most recent call last):
  File "/home/username/programs/electrum-org/electrum/gui/qt/util.py", line 772, in run
    result = task.task()
  File "/home/username/programs/electrum-org/electrum/transaction.py", line 1743, in sign
    sig = self.sign_txin(i, sec, bip143_shared_txdigest_fields=bip143_shared_txdigest_fields)
  File "/home/username/programs/electrum-org/electrum/transaction.py", line 1755, in sign_txin
    sig = privkey.sign_transaction(pre_hash)
  File "/home/username/programs/electrum-org/electrum/ecc.py", line 449, in sign_transaction
    sigdecode=get_r_and_s_from_der_sig)
  File "/home/username/programs/electrum-org/electrum/ecc.py", line 439, in sign
    r, s = private_key.sign_digest_deterministic(data, hashfunc=hashlib.sha256, sigencode=sig_encode_r_s, extra_entropy=extra_entropy)
TypeError: sign_digest_deterministic() got an unexpected keyword argument 'extra_entropy'

```

**Comment by roth-a** [comment]
Ok. I needed to upgrade from 0.13.2  -->  0.15   Now it works.
