### ISSUE TITLE
python-ecdsa (0.15) Point API changes if gmpy2 is available

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#5927]
After doing `sudo apt install libsecp256k1-0` in Ubuntu 18.04 and starting electrum (master) on testnet, I get the error (both with qt and kivy):

```
Traceback (most recent call last):
  File "/home/re/electrum/electrum/gui/qt/installwizard.py", line 288, in select_storage
    temp_storage.decrypt(password)
  File "/home/re/electrum/electrum/storage.py", line 212, in decrypt
    s = zlib.decompress(ec_key.decrypt_message(self.raw, enc_magic))
  File "/home/re/electrum/electrum/ecc.py", line 488, in decrypt_message
    ecdh_key = (ephemeral_pubkey * self.secret_scalar).get_public_key_bytes(compressed=True)
  File "/home/re/electrum/electrum/ecc.py", line 244, in __mul__
    ecdsa_point = self._pubkey.point * other
  File "/home/re/electrum/electrum/ecc_fast.py", line 167, in mul
    pubkey = _get_ptr_to_well_formed_pubkey_string_buffer_from_ecdsa_point(self)
  File "/home/re/electrum/electrum/ecc_fast.py", line 125, in _get_ptr_to_well_formed_pubkey_string_buffer_from_ecdsa_point
    public_pair_bytes = b'\4' + point.x().to_bytes(32, byteorder="big") + point.y().to_bytes(32, byteorder="big")
AttributeError: 'mpz' object has no attribute 'to_bytes'
```

Uninstalling  libsecp256k1-0 solves the problem.  Could it be that the version of   libsecp256k1-0  (0.1~20170810-1)  in Ubuntu 18.04 is too old?    Without libsecp256k1 however lightning cannot be enabled, see https://github.com/spesmilo/electrum/issues/5796 .

**Comment by SomberNight** [comment]
This happens with `python-ecdsa >= 0.15`, due to https://github.com/warner/python-ecdsa/commit/f7910cf6fd1c67fe3ea69dbd94926534c2945dda, if `gmpy2` is installed.

To reproduce,
```
sudo apt-get install libmpc-dev
python3 -m pip install --user gmpy2
```
