### ISSUE TITLE
issue with decode_short_ids

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#5980]
```
Traceback (most recent call last):
  File "/opt/electrum/electrum/util.py", line 1035, in wrapper
   return await func(*args, **kwargs)
  File "/opt/electrum/electrum/lnpeer.py", line 229, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/opt/electrum/electrum/lnpeer.py", line 245, in main_loop
    await group.spawn(self.process_gossip())
  File "/opt/electrum/packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/opt/electrum/packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/opt/electrum/electrum/lnpeer.py", line 440, in _message_loop
    self.process_message(msg)
  File "/opt/electrum/electrum/lnpeer.py", line 149, in process_message
    execution_result = f(payload)
  File "/opt/electrum/electrum/lnpeer.py", line 410, in on_reply_channel_range
    ids = self.decode_short_ids(encoded)
  File "/opt/electrum/electrum/lnpeer.py", line 399, in decode_short_ids
    decoded = zlib.decompress(encoded[1:])
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
```

**Comment by ecdsa** [comment]
Removing from 4.0 milestone. 
It was observed with a single peer only, it is possible that peer was misbehaving.

**Comment by ecdsa** [comment]
closing, I have not seen that anymore
