### ISSUE TITLE
lightning_history returns 500 status code

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#5984]
Calling `lightning_history` via CLI (b90cbeb) I get a 500 status code and the logs show:
```
E | aiohttp.server | Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/app/electrum/electrum/daemon.py", line 352, in handle
    response = await jsonrpcserver.async_dispatch(request, methods=self.methods)
  File "/usr/local/lib/python3.7/dist-packages/jsonrpcserver/async_dispatcher.py", line 103, in dispatch
    log_response(str(response), trim_log_values=trim_log_values)
  File "/usr/local/lib/python3.7/dist-packages/jsonrpcserver/response.py", line 133, in __str__
    return json.dumps(sort_dict_response(self.deserialized()))
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by ecdsa** [comment]
thanks, fixed
