### ISSUE TITLE
Error: missing 1 required positional argument: 'height'

### ISSUE THREAD

**Issue by frndxyz** [spesmilo/electrum#6005]
i get this error. but i assume this happen when header cant connect and consider block as bad.

any solution?

Log: 
```
20200302T112708.729841Z |     INFO | interface.[95.217.8.192:31337] | can't connect 1062712
20200302T112708.733429Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062711 in mode backward
20200302T112708.934401Z |     INFO | interface.[95.217.8.192:31337] | exiting backward mode at 1062711
20200302T112708.943065Z |     INFO | interface.[95.217.8.192:31337] | could connect 1062711
20200302T112708.945888Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062712 in mode catchup
20200302T112709.144490Z |     INFO | interface.[95.217.8.192:31337] | could connect 1062712
20200302T112709.169886Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20200302T112709.172224Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0015
20200302T112709.172940Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0034
20200302T112709.173547Z |     INFO | gui.qt.betting_history_list.BettingHistoryModel | refreshing... reason: update_tabs
20200302T112709.175737Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_betting_history 0.0015
20200302T112709.176478Z |    DEBUG | util.profiler | BettingHistoryModel.refresh 0.0029
20200302T112709.225733Z |    DEBUG | util.profiler | AddressList.update 0.0290
20200302T112710.310665Z |     INFO | interface.[155.138.217.7:31337] | skipping header 1062712
20200302T112744.534464Z |     INFO | network | network: retrying connections
20200302T112744.746486Z |     INFO | network | fee_histogram []
20200302T112744.747393Z |     INFO | network | fee_estimates {25: 396039, 10: 416666, 5: 416666, 2: 454545}
20200302T112844.778628Z |     INFO | network | network: retrying connections
20200302T112844.788637Z |  WARNING | interface.[155.138.217.7:31337] | disconnecting due to GracefulDisconnect(RPCError(-101, 'excessive resource usage'),)
20200302T112844.990296Z |     INFO | network | fee_histogram []
20200302T112844.991200Z |     INFO | network | fee_estimates {25: 396039, 10: 416666, 5: 416666, 2: 454545}
20200302T112858.953774Z |     INFO | interface.[95.217.8.192:31337] | can't connect 1062713
20200302T112858.955922Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062712 in mode backward
20200302T112859.149605Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062711 in mode backward
20200302T112859.344930Z |     INFO | interface.[95.217.8.192:31337] | exiting backward mode at 1062711
20200302T112859.351830Z |     INFO | interface.[95.217.8.192:31337] | binary step. good 1062711, bad 1062712, height 1062711
20200302T112859.352419Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062711 in mode binary
20200302T112859.562566Z |     INFO | interface.[95.217.8.192:31337] | binary search exited. good 1062711, bad 1062712
20200302T112859.566326Z |     INFO | interface.[95.217.8.192:31337] | new fork at bad height 1062712
20200302T113419.601644Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062713 in mode catchup
20200302T113419.608128Z |     INFO | network | network: retrying connections
20200302T113419.609541Z |     INFO | verifier.[default_wallet] | undoing verifications above height 1062711
20200302T113419.834524Z |     INFO | interface.[95.217.8.192:31337] | could connect 1062713
20200302T113419.852452Z |     INFO | blockchain.Blockchain | swapping 1062712 0
20200302T113420.430526Z |    ERROR | interface.[95.217.8.192:31337] | Exception in wrapper_func: TypeError("hash_raw_header() missing 1 required positional argument: 'height'",)
Traceback (most recent call last):
  File "/Users/pravin/Wagerr-Electrum/electrum/util.py", line 941, in wrapper
    return await func(*args, **kwargs)
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 331, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 355, in run
    await self.open_session(ssl_context)
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 462, in open_session
    await group.spawn(self.monitor_connection)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 499, in run_fetch_blocks
    await self._process_header_at_tip()
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 514, in _process_header_at_tip
    await self.sync_until(height)
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 535, in sync_until
    last, height = await self.step(height)
  File "/Users/pravin/Wagerr-Electrum/electrum/interface.py", line 565, in step
    self.blockchain.save_header(header)
  File "/Users/pravin/Wagerr-Electrum/electrum/blockchain.py", line 199, in func_wrapper
    return func(self, *args, **kwargs)
  File "/Users/pravin/Wagerr-Electrum/electrum/blockchain.py", line 473, in save_header
    self.swap_with_parent()
  File "/Users/pravin/Wagerr-Electrum/electrum/blockchain.py", line 384, in swap_with_parent
    if not self._swap_with_parent():
  File "/Users/pravin/Wagerr-Electrum/electrum/blockchain.py", line 428, in _swap_with_parent
    self._forkpoint_hash, parent._forkpoint_hash = parent._forkpoint_hash, hash_raw_header(bh2u(parent_data[:constants.net.COIN.get_header_size_height(parent.forkpoint + parent.size() - 1)]))
TypeError: hash_raw_header() missing 1 required positional argument: 'height'
```

**Comment by SomberNight** [comment]
What version are you running? Is this for a fork?
I can't find a `get_header_size_height` function in the source.

**Comment by frndxyz** [comment]
> What version are you running? Is this for a fork?
> I can't find a `get_header_size_height` function in the source.

yes its fork of 3.3.8 electrum

**Comment by frndxyz** [comment]
i see something weird here: 

 can't connect 1062713
20200302T112858.955922Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062712 in mode backward
20200302T112859.149605Z |     INFO | interface.[95.217.8.192:31337] | requesting block header 1062711 in mode backward
20200302T112859.344930Z |     INFO | interface.[95.217.8.192:31337] | exiting backward mode at 1062711

requesting 1062712, 1062711 both at once in parallel.

**Comment by ecdsa** [comment]
forks are weird :-)

**Comment by frndxyz** [comment]
> forks are weird :-)

yes , but error i talking about is related to electrum bitcoin code not issue with forks.

**Comment by frndxyz** [comment]
this happen when server goes in-responsive. "requesting block header 1062712" is ok , but before completing that cycle it execute another "requesting block header 1062711".

**Comment by frndxyz** [comment]
> this happen when server goes in-responsive. "requesting block header 1062712" is ok , but before completing that cycle it execute another "requesting block header 1062711".

there is no "could connect  1062712"
