### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by frndxyz** [spesmilo/electrum#6011]
getting this error : after whole blockchain download complete.

Traceback (most recent call last):
  File "/Users/pravin/Electrum/electrum/gui/qt/network_dialog.py", line 69, in on_update
    self.nlayout.update()
  File "/Users/pravin/Electrum/electrum/gui/qt/network_dialog.py", line 392, in update
    self.nodes_list_widget.update(self.network)
  File "/Users/pravin/Electrum/electrum/gui/qt/network_dialog.py", line 116, in update
    name = b.get_name()
  File "/Users/pravin/Electrum/electrum/blockchain.py", line 248, in get_name
    return self.get_hash(self.get_max_forkpoint()).lstrip('0')[0:10]
  File "/Users/pravin/Electrum/electrum/blockchain.py", line 518, in get_hash
    header = self.read_header(height)
  File "/Users/pravin/Electrum/electrum/blockchain.py", line 199, in func_wrapper
    return func(self, *args, **kwargs)
  File "/Users/pravin/Electrum/electrum/blockchain.py", line 484, in read_header
    name = self.path()
  File "/Users/pravin/Electrum/electrum/blockchain.py", line 199, in func_wrapper
    return func(self, *args, **kwargs)
  File "/Users/pravin/Electrum/electrum/blockchain.py", line 352, in path
    prev_hash = self._prev_hash.lstrip('0')
AttributeError: 'NoneType' object has no attribute 'lstrip'

Electrum 3.3.8
python version: 3.6.8
windows-7 SP1

**Comment by SomberNight** [comment]
Sorry but we don't have the resources to debug your modified code. There might be a bug there that affects Electrum, but the trace is clearly from a fork of Electrum and the affected code is exactly where forks usually modify stuff, making it likely that the bug was introduced at that point.
