### ISSUE TITLE
`open_channel` fails with an exception

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#6046]
Using electrum version 1448bfe93, a `open_channel` call fails, while logging:
```
E | lnworker.LNWallet | Exception in _open_channel_coroutine: TypeError("'>' not supported between instances of 'str' and 'int'")
Traceback (most recent call last):
  File "/srv/app/electrum/electrum/util.py", line 1049, in wrapper
    return await func(*args, **kwargs)
  File "/srv/app/electrum/electrum/lnworker.py", line 820, in _open_channel_coroutine
    temp_channel_id=os.urandom(32))
  File "/srv/app/electrum/electrum/util.py", line 1049, in wrapper
    return await func(*args, **kwargs)
  File "/srv/app/electrum/electrum/lnpeer.py", line 515, in channel_establishment_flow
    local_config = self.make_local_config(funding_sat, push_msat, LOCAL)
  File "/srv/app/electrum/electrum/lnpeer.py", line 484, in make_local_config
    addr = wallet.get_unused_address()
  File "/srv/app/electrum/electrum/wallet.py", line 1510, in wrapper
    addr = func(self, *args, **kwargs)
  File "/srv/app/electrum/electrum/wallet.py", line 1523, in get_unused_address
    addrs = self.get_unused_addresses()
  File "/srv/app/electrum/electrum/wallet.py", line 1517, in get_unused_addresses
    in_use_by_request = [k for k in self.receive_requests.keys() if self.get_request_status(k)[0] != PR_EXPIRED]
  File "/srv/app/electrum/electrum/wallet.py", line 1517, in <listcomp>
    in_use_by_request = [k for k in self.receive_requests.keys() if self.get_request_status(k)[0] != PR_EXPIRED]
  File "/srv/app/electrum/electrum/wallet.py", line 1593, in get_request_status
    if exp > 0 and time.time() > timestamp + exp:
TypeError: '>' not supported between instances of 'str' and 'int'

```

**Comment by ecdsa** [comment]
does `list_requests` work ?

**Comment by St333p** [comment]
Nope, same error.

**Comment by ecdsa** [comment]
you might have created a misformatted request using an older git commit.
it should go away if you delete your requests, with `clear_request`

**Comment by St333p** [comment]
Thanks, I just realized that on the other node I'm running at same version both calls work just fine.

Thanks, and sorry for bothering.
