### ISSUE TITLE
crash while requesting "lightning" payment.

### ISSUE THREAD

**Issue by h2o10** [spesmilo/electrum#6096]
Latest commit (cd199390e2d6376cdf9458c4a14906c564beea1c).

Network : regtest
After opening a channel with lnd and clicking on "lightning" button in "receive" tab the wallet crashes.

Below is the log:

```
Traceback
Traceback (most recent call last):
  File "/h2o/electrum/electrum/gui/qt/main_window.py", line 1087, in 
    self.create_lightning_invoice_button.clicked.connect(lambda: self.create_invoice(True))
  File "/h2o/electrum/electrum/gui/qt/main_window.py", line 1184, in create_invoice
    key = self.wallet.lnworker.add_request(amount, message, expiry)
  File "/h2o/electrum/electrum/lnworker.py", line 1049, in add_request
    return fut.result(timeout=5)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/h2o/electrum/electrum/util.py", line 1052, in wrapper
    return await func(*args, **kwargs)
  File "/h2o/electrum/electrum/lnworker.py", line 1056, in _add_request_coro
    routing_hints = await self._calc_routing_hints_for_invoice(amount_sat)
  File "/h2o/electrum/electrum/lnworker.py", line 1202, in _calc_routing_hints_for_invoice
    if not chan.can_receive(amount_sat, check_frozen=True):
  File "/h2o/electrum/electrum/lnchannel.py", line 760, in can_receive
    self._assert_can_add_htlc(htlc_proposer=REMOTE, amount_msat=amount_msat)
  File "/h2o/electrum/electrum/lnchannel.py", line 715, in _assert_can_add_htlc
    if amount_msat 


Additional information
Electrum version: 3.3.8-1990-gcd199390e-dirty
  
Python version: 3.6.9
[GCC 8.3.0]
  
Operating system: Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
  
Wallet type: standard
  
Locale: en_US
```

**Comment by SomberNight** [comment]
The end of the trace is missing (due to https://github.com/spesmilo/electrum/issues/6099):
```
    if amount_msat <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```
