### ISSUE TITLE
Remote peer fails during shutdown because 'Feerange below minimum acceptable'

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6216]
Not sure if the issue is with Electrum: BOLT 2 says that the receiving node must fail if the fee is too high, but it does not say anything about fee too low:

> otherwise, if fee_satoshis is greater than the base fee of the final commitment transaction as calculated in BOLT #3:
>     MUST fail the connection.

```
Traceback (most recent call last):
06-06 12:32:00.528 29442 29484 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/util.py", line 992, in wrapper
06-06 12:32:00.528 29442 29484 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/lnpeer.py", line 1470, in _shutdown
06-06 12:32:00.528 29442 29484 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/lnpeer.py", line 206, in wait_for_message
06-06 12:32:00.528 29442 29484 I python  : Exception: Remote peer reported error [DO NOT TRUST THIS MESSAGE]: b'Feerange 161sat-182sat below minimum acceptable 183sat'
06-06 12:32:00.529 29442 29484 I python  : E/P | lnpeer.Peer.[LNWallet, 24.84.152.187:9735] | Exception in close_channel: Exception("Remote peer reported error [DO NOT TRUST THIS MESSAGE]: b'Feerange 161sat-182sat below minimum acceptable 183sat'")

```

**Comment by ecdsa** [comment]
not sure if the issue is with Electrum

**Comment by SomberNight** [comment]
Remote is c-lightning:
https://github.com/ElementsProject/lightning/blob/0f568e18614ae3edd502f25cf5b9d9805641456a/closingd/closingd.c#L519

It might help if we logged the fee offers sent and received, to see if there is something weird there.
