### ISSUE TITLE
Electrum 4 - cannot connect to a TOR lightning node 

### ISSUE THREAD

**Issue by evildido** [spesmilo/electrum#6274]
Even using TOR websocket proxy, I'm not able to open a channel nor connect to a TOR node.

When I try to add peer 
> add_peer("02AD921D465E6ECFE493E90864275FFCF1B70C6050C76E6C33701B0C3686D687B9")

Electrum returns the following trace back.
```
Traceback (most recent call last):
  File "/home/jojo/tmpElectrum4/electrum/electrum/gui/qt/main_window.py", line 2081, in <lambda>
    **{**kwargs, 'wallet': self.wallet})
  File "/home/jojo/tmpElectrum4/electrum/electrum/commands.py", line 188, in _run
    result = fut.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/jojo/tmpElectrum4/electrum/electrum/commands.py", line 151, in func_wrapper
    return await func(*args, **kwargs)
  File "/home/jojo/tmpElectrum4/electrum/electrum/commands.py", line 965, in add_peer
    await lnworker.add_peer(connection_string)
  File "/home/jojo/tmpElectrum4/electrum/electrum/util.py", line 992, in wrapper
    return await func(*args, **kwargs)
  File "/home/jojo/tmpElectrum4/electrum/electrum/lnworker.py", line 414, in add_peer
    host, port, timestamp = self.choose_preferred_address(addrs)
  File "/home/jojo/tmpElectrum4/electrum/electrum/lnworker.py", line 395, in choose_preferred_address
    choice = random.choice(addr_list)
  File "/usr/lib/python3.6/random.py", line 261, in choice
    return seq[i]
TypeError: 'set' object does not support indexing
```

**Comment by SomberNight** [comment]
thanks
