### ISSUE TITLE
Exception: server response to get_history contains unconfirmed tx without fee

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#6308]
Master version: 0d7bcde2d

The Bug leads to infinite retries to the electrum server with crashes before it finishes.  
Same wallet with 3.3.8 has no problem.

Log output:
```
06-29 20:24:33.660 31116 31156 I python  : D | util.profiler | Abstract_Wallet.get_full_history 0.0555
06-29 20:24:34.025 31116 31163 I python  : I | synchronizer.[m2] | receiving history <here is an address> 1
06-29 20:24:34.633 31116 31163 I python  : E/i | interface.[<here is an onion address>.onion:50002] | Exception in wrapper_func: Exception('server response to get_history contains unconfirmed tx without fee')
06-29 20:24:34.634 31116 31163 I python  : Traceback (most recent call last):
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/util.py", line 1013, in wrapper
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/interface.py", line 424, in wrapper_func
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/interface.py", line 448, in run
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/interface.py", line 576, in open_session
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/packages/aiorpcx/curio.py", line 242, in __aexit__
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/packages/aiorpcx/curio.py", line 211, in join
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/synchronizer.py", line 82, in _start_tasks
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/packages/aiorpcx/curio.py", line 242, in __aexit__
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/packages/aiorpcx/curio.py", line 211, in join
06-29 20:24:34.634 31116 31163 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/synchronizer.py", line 179, in _on_address_status
06-29 20:24:34.634 31116 31163 I python  : Exception: server response to get_history contains unconfirmed tx without fee
06-29 20:24:34.641 31116 31163 I python  : [INFO   ] [network event] status
06-29 20:24:34.645 31116 31163 I python  : [INFO   ] [network event] network_updated
```

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/issues/6289

> The Bug leads to infinite retries to the electrum server with crashes before it finishes.

It should try different servers unless you have disabled auto_connect (in which case it obviously cannot try different servers).
The server you are connected to does not implement part of the protocol.

**Comment by SomberNight** [comment]
When you say it crashes, do you just mean it disconnects and logs that traceback?
Could you please confirm that you have auto_connect disabled (e.g. selected a trusted server)?

**Comment by relativisticelectron** [comment]
Yes I run my own electrs server over tor.

**Comment by relativisticelectron** [comment]
> When you say it crashes, do you just mean it disconnects and logs that traceback?

The above traceback above is 1 of (infinite) many that it creates. 
1. connects
2. syncs
3. exception
4. Shows offline
5. repeat from step 1.

**Comment by SomberNight** [comment]
Ok, in that case, while the UX could be better, there is no bug here.
The connected server does not implement the protocol properly; the client is set to only connect to that server. There is no good solution here.
You should update your server (see linked issue) and then it should start working again.

**Comment by relativisticelectron** [comment]
ok. thanks
