### ISSUE TITLE
Cooperative close without to_local output raises UnrelatedTransactionException (mutual close)

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6317]
I have an inbound channel where I have zero balance.
I have tried to close this channel but it raises: the closing tx is unrelated from the wallet (well ofc, neither inputs nor outputs touch my addresses).
(It raises quite late so the channel will get closed; assuming the counterparty broadcasts it, because we will not broadcast (due to this))

```
D/P | lnpeer.Peer.[LNWallet, 46.229.165.152:9735] | Sending SHUTDOWN
D | lnchannel.Channel | Setting channel state: SHUTDOWN -> SHUTDOWN
I | storage.WalletStorage | saved c:\users\user\appdata\roaming\electrum\wallets\test_segwit_asdasd
D | util.profiler | WalletStorage.write 0.0137
D/P | lnpeer.Peer.[LNWallet, 46.229.165.152:9735] | Sending CLOSING_SIGNED
D/P | lnpeer.Peer.[LNWallet, 46.229.165.152:9735] | Sending CLOSING_SIGNED
D/P | lnpeer.Peer.[LNWallet, 46.229.165.152:9735] | Sending CLOSING_SIGNED
E/P | lnpeer.Peer.[LNWallet, 46.229.165.152:9735] | Exception in _shutdown: UnrelatedTransactionException()
Traceback (most recent call last):
  File "...\electrum\electrum\util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 1521, in _shutdown
    self.lnworker.wallet.add_transaction(closing_tx)
  File "...\electrum\electrum\wallet.py", line 823, in add_transaction
    tx_was_added = super().add_transaction(tx, allow_unrelated=allow_unrelated)
  File "...\electrum\electrum\address_synchronizer.py", line 245, in add_transaction
    raise UnrelatedTransactionException()
electrum.address_synchronizer.UnrelatedTransactionException: Transaction is unrelated to this wallet.
E/P | lnpeer.Peer.[LNWallet, 46.229.165.152:9735] | Exception in close_channel: UnrelatedTransactionException()
Traceback (most recent call last):
  File "...\electrum\electrum\util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 1410, in close_channel
    txid = await self._shutdown(chan, payload, True)
  File "...\electrum\electrum\util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 1521, in _shutdown
    self.lnworker.wallet.add_transaction(closing_tx)
  File "...\electrum\electrum\wallet.py", line 823, in add_transaction
    tx_was_added = super().add_transaction(tx, allow_unrelated=allow_unrelated)
  File "...\electrum\electrum\address_synchronizer.py", line 245, in add_transaction
    raise UnrelatedTransactionException()
electrum.address_synchronizer.UnrelatedTransactionException: Transaction is unrelated to this wallet.
  File "...\electrum\electrum\gui\qt\util.py", line 832, in run
    result = task.task()
  File "...\electrum\electrum\gui\qt\channels_list.py", line 103, in task
    return self.network.run_from_another_thread(coro)
  File "...\electrum\electrum\network.py", line 358, in run_from_another_thread
    return fut.result(timeout)
  File "...\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "...\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "...\electrum\electrum\lnworker.py", line 1347, in close_channel
    return await peer.close_channel(chan_id)
  File "...\electrum\electrum\util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 1410, in close_channel
    txid = await self._shutdown(chan, payload, True)
  File "...\electrum\electrum\util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 1521, in _shutdown
    self.lnworker.wallet.add_transaction(closing_tx)
  File "...\electrum\electrum\wallet.py", line 823, in add_transaction
    tx_was_added = super().add_transaction(tx, allow_unrelated=allow_unrelated)
  File "...\electrum\electrum\address_synchronizer.py", line 245, in add_transaction
    raise UnrelatedTransactionException()
```

**Comment by SomberNight** [comment]
Note: re original motivation for `UnrelatedTransactionException` in `wallet.add_transaction`, see
https://github.com/spesmilo/electrum/commit/8676e870f3ccccd2837f3a72ac59b1b22697df26
(it was re local transactions)

**Comment by ecdsa** [comment]
note that the closing tx is related to lnwatcher (AddressSynchronizer). 
We would not have that issue if we saved that synchronizer's state in the wallet
