### ISSUE TITLE
attrs: ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute

### ISSUE THREAD

**Issue by chippsmith** [spesmilo/electrum#6322]
Electrum was running fine but when I updated to the most recent branch, 2db0ad1, I am getting an error I don't know how to resolve.  I am running ubuntu version 19.10.  Thanks for the help.

```
/usr/lib/python3/dist-packages/google/protobuf/internal/api_implementation.py:154: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from google.protobuf.pyext import _message
/usr/lib/python3/dist-packages/google/protobuf/internal/containers.py:182: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  MutableMapping = collections.MutableMapping
Traceback (most recent call last):
  File "./run_electrum", line 84, in <module>
    from electrum.logging import get_logger, configure_logging
  File "/home/jeff/Projects/electrum/electrum/__init__.py", line 16, in <module>
    from .wallet import Wallet
  File "/home/jeff/Projects/electrum/electrum/wallet.py", line 65, in <module>
    from .storage import StorageEncryptionVersion, WalletStorage
  File "/home/jeff/Projects/electrum/electrum/storage.py", line 36, in <module>
    from .wallet_db import WalletDB
  File "/home/jeff/Projects/electrum/electrum/wallet_db.py", line 36, in <module>
    from .invoices import PR_TYPE_ONCHAIN, Invoice
  File "/home/jeff/Projects/electrum/electrum/invoices.py", line 146, in <module>
    class LNInvoice(Invoice):
  File "/home/jeff/.local/lib/python3.7/site-packages/attr/_make.py", line 959, in attrs
    return wrap(maybe_cls)
  File "/home/jeff/.local/lib/python3.7/site-packages/attr/_make.py", line 906, in wrap
    is_exc,
  File "/home/jeff/.local/lib/python3.7/site-packages/attr/_make.py", line 472, in __init__
    cls, these, auto_attribs, kw_only
  File "/home/jeff/.local/lib/python3.7/site-packages/attr/_make.py", line 416, in _transform_attrs
    "Attribute in question: {a!r}".format(a=a)
ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute (unless they are init=False).  Attribute in question: Attribute(name='invoice', default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False)
```

**Comment by SomberNight** [comment]
duplicate of https://github.com/spesmilo/electrum/issues/6258#issuecomment-648406969 ?

you should update [attrs](https://pypi.org/project/attrs/)

just rerun pip install for electrum:
```
python3 -m pip install --user -e .
```

**Comment by chippsmith** [comment]
Thanks for your help!
