### ISSUE TITLE
Electrum 4.0.2 connected to local Electrs server keeps synchronizing over and over

### ISSUE THREAD

**Issue by BTCBellyButton** [spesmilo/electrum#6428]
I updated to Electrum 4.0.2 on Ubuntu 20.04 LTS connected locally to Electrs 0.8.3 by following the instructions "Installation from Python sources".

The previous version of Electrum 3.3.8 worked perfectly on this machine.

After making the first transaction with the new version from a pre-existing wallet, it seems to have entered an endless loop. Synchronizing from 0/314 up to 314/314 and then starting all over again.

This is the only ERROR section (repeating over and over) that I found in the log:

20200721T003507.793687Z |   ERROR | interface.[localhost:50001] | Exception in wrapper_func: RequestCorrupted("required field 'fee' missing from dict")
Traceback (most recent call last):
  File "/home/go/.local/lib/python3.8/site-packages/electrum/util.py", line 1037, in wrapper
   return await func(*args, **kwargs)
  File "/home/go/.local/lib/python3.8/site-packages/electrum/interface.py", line 466, in wrapper_func
   return await func(self, *args, **kwargs)
  File "/home/go/.local/lib/python3.8/site-packages/electrum/interface.py", line 490, in run
   await self.open_session(ssl_context)
  File "/home/go/.local/lib/python3.8/site-packages/electrum/interface.py", line 630, in open_session
   await group.spawn(self.monitor_connection)
  File "/home/go/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
   await self.join()
  File "/home/go/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
   raise task.exception()
  File "/home/go/.local/lib/python3.8/site-packages/electrum/synchronizer.py", line 82, in _start_tasks
   await group.spawn(self.main())
  File "/home/go/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
   await self.join()
  File "/home/go/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
   raise task.exception()
  File "/home/go/.local/lib/python3.8/site-packages/electrum/synchronizer.py", line 171, in _on_address_status
   result = await self.interface.get_history_for_scripthash(h)
  File "/home/go/.local/lib/python3.8/site-packages/electrum/interface.py", line 922, in get_history_for_scripthash
   assert_dict_contains_field(tx_item, field_name='fee')
  File "/home/go/.local/lib/python3.8/site-packages/electrum/interface.py", line 118, in assert_dict_contains_field
   raise RequestCorrupted(f'required field {field_name!r} missing from dict')
electrum.interface.RequestCorrupted: required field 'fee' missing from dict

**Comment by SomberNight** [comment]
related:
https://github.com/spesmilo/electrum/issues/6289
https://github.com/spesmilo/electrum/issues/6308
you should update electrs

please search existing issues before opening new ones.

**Comment by BTCBellyButton** [comment]
Thanks!
