### ISSUE TITLE
[Kivy] BuilderException when running "gui --gui kivy" from source on desktop

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#6484]
When running `run_electrum gui --gui kivy --testnet` from either a Windows or Linux desktop a "BuilderException" is raised when attempting to reference the file `electrum/gui/kivy/theming/light/card_bottom`

The referenced path [electrum/gui/kivy/theming/light](https://github.com/spesmilo/electrum/tree/master/electrum/gui/kivy/theming/light) only contains PNG files.

```
kivy.lang.builder.BuilderException: Parser: File "/src/electrum.git/electrum/gui/kivy/main.kv", line 214:
...
    212:            rgba: 0.192, .498, 0.745, 1
    213:        BorderImage:
>>  214:            source: 'atlas://electrum/gui/kivy/theming/light/card_bottom'
    215:            size: self.size
    216:            pos: self.pos
...
Exception: Unable to found None atlas
```

<details>
<summary>Expand for full Ubuntu Kivy log</summary>
<pre>[INFO   ] Logger: Record log in /usr/.kivy/logs/kivy_20-08-05_1.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/python3.6/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609]
[INFO   ] Python: Interpreter at "/python3.6/bin/python"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: pygame(['window_egl_rpi'] ignored)
[WARNING] Deprecated: Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /python3.6/lib/python3.6/site-packages/kivy/core/window/window_pygame.py line 42.Called from /python3.6/lib/python3.6/site-packages/kivy/core/__init__.py line 71 by core_select_lib().
[WARNING] WinPygame: Video: failed (multisamples=2)
[WARNING] WinPygame: trying without antialiasing
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] GL: OpenGL vendor <b'VMware, Inc.'>
[INFO   ] GL: OpenGL renderer <b'llvmpipe (LLVM 6.0, 256 bits)'>
[INFO   ] GL: OpenGL parsed version: 3, 0
[INFO   ] GL: Shading version <b'1.30'>
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <32>
[WARNING] Deprecated: Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /python3.6/lib/python3.6/site-packages/kivy/core/image/img_pygame.py line 27.Called from /python3.6/lib/python3.6/site-packages/kivy/core/image/__init__.py line 460 by load().
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: pygame
[INFO   ] Clipboard: Provider: xclip
[INFO   ] CutBuffer: cut buffer support enabled
[WARNING] Deprecated: Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /python3.6/lib/python3.6/site-packages/kivy/core/text/text_pygame.py line 36.Called from /python3.6/lib/python3.6/site-packages/kivy/core/text/markup.py line 94 by __init__().
[WARNING] Deprecated: Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /python3.6/lib/python3.6/site-packages/kivy/core/text/text_pygame.py line 36.Called from /python3.6/lib/python3.6/site-packages/kivy/uix/label.py line 349 by _create_label().</pre>
</details>

<details>
<summary>Expand for full Ubuntu Python Traceback</summary>
<pre>Traceback (most recent call last):
  File "run_electrum", line 381, in <module>
    d.run_gui(config, plugins)
  File "/src/electrum.git/electrum/daemon.py", line 560, in run_gui
    self.gui_object.main()
  File "/src/electrum.git/electrum/gui/kivy/__init__.py", line 67, in main
    w.run()
  File "/python3.6/lib/python3.6/site-packages/kivy/app.py", line 829, in run
    root = self.build()
  File "/src/electrum.git/electrum/gui/kivy/main_window.py", line 544, in build
    return Builder.load_file('electrum/gui/kivy/main.kv')
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 301, in load_file
    return self.load_string(data, **kwargs)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 405, in load_string
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
    child, crule, rootrule, rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 657, in _apply_rule
    root=rctx['ids']['root'], rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/uix/widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 538, in apply
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
    child, crule, rootrule, rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 657, in _apply_rule
    root=rctx['ids']['root'], rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/uix/widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 538, in apply
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
    child, crule, rootrule, rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 657, in _apply_rule
    root=rctx['ids']['root'], rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/uix/widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 538, in apply
    rule_children=rule_children)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 592, in _apply_rule
    rule.canvas_before, rootrule)
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 926, in _build_canvas
    '{}: {}'.format(e.__class__.__name__, e), cause=tb)
kivy.lang.builder.BuilderException: Parser: File "/src/electrum.git/electrum/gui/kivy/main.kv", line 214:
...
    212:            rgba: 0.192, .498, 0.745, 1
    213:        BorderImage:
>>  214:            source: 'atlas://electrum/gui/kivy/theming/light/card_bottom'
    215:            size: self.size
    216:            pos: self.pos
...
Exception: Unable to found None atlas
  File "/python3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 921, in _build_canvas
    setattr(instr, key, value)
  File "kivy/graphics/instructions.pyx", line 366, in kivy.graphics.instructions.VertexInstruction.source.__set__
  File "kivy/graphics/context_instructions.pyx", line 430, in kivy.graphics.context_instructions.BindTexture.source.__set__
  File "/python3.6/lib/python3.6/site-packages/kivy/core/image/__init__.py", line 561, in __init__
    self.filename = arg
  File "/python3.6/lib/python3.6/site-packages/kivy/core/image/__init__.py", line 756, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "/python3.6/lib/python3.6/site-packages/kivy/core/image/__init__.py", line 427, in load
    raise Exception('Unable to found %r atlas' % afn)</pre>
</details>

<details>
<summary>Expand for full Windows Kivy log</summary>
<pre>[INFO   ] Logger: Record log in P:\.kivy\logs\kivy_20-08-01_0.txt
[INFO   ] deps: Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "S:\src\electrum\.venv\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "S:\src\electrum\.venv\Scripts\python.exe"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.6.13559 Compatibility Profile Context 26.20.12028.2'>
[INFO   ] GL: OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] GL: OpenGL renderer <b'Radeon RX 580 Series'>
[INFO   ] GL: OpenGL parsed version: 4, 6
[INFO   ] GL: Shading version <b'4.60'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] Clipboard: Provider: winctypes</pre>
</details>

<details>
<summary>Expand for full Windows Python Traceback</summary>
<pre>Traceback (most recent call last):
  File "run_electrum", line 381, in <module>
    d.run_gui(config, plugins)
  File "S:\src\electrum\electrum\daemon.py", line 560, in run_gui
    self.gui_object.main()
  File "S:\src\electrum\electrum\gui\kivy\__init__.py", line 67, in main
    w.run()
  File "S:\src\electrum\.venv\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "S:\src\electrum\electrum\gui\kivy\main_window.py", line 544, in build
    return Builder.load_file('electrum/gui/kivy/main.kv')
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
    return self.load_string(data, **kwargs)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 405, in load_string
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 659, in _apply_rule
    child, crule, rootrule, rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 657, in _apply_rule
    root=rctx['ids']['root'], rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 659, in _apply_rule
    child, crule, rootrule, rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 657, in _apply_rule
    root=rctx['ids']['root'], rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 659, in _apply_rule
    child, crule, rootrule, rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 657, in _apply_rule
    root=rctx['ids']['root'], rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 592, in _apply_rule
    rule.canvas_before, rootrule)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
    '{}: {}'.format(e.__class__.__name__, e), cause=tb)
kivy.lang.builder.BuilderException: Parser: File "S:\src\electrum\electrum\gui\kivy\main.kv", line 214:
...
    212:            rgba: 0.192, .498, 0.745, 1
    213:        BorderImage:
>>  214:            source: 'atlas://electrum/gui/kivy/theming/light/card_bottom'
    215:            size: self.size
    216:            pos: self.pos
...
Exception: Unable to found None atlas
  File "S:\src\electrum\.venv\lib\site-packages\kivy\lang\builder.py", line 921, in _build_canvas
    setattr(instr, key, value)
  File "kivy\graphics\instructions.pyx", line 366, in kivy.graphics.instructions.VertexInstruction.source.__set__
  File "kivy\graphics\context_instructions.pyx", line 430, in kivy.graphics.context_instructions.BindTexture.source.__set__
  File "S:\src\electrum\.venv\lib\site-packages\kivy\core\image\__init__.py", line 561, in __init__
    self.filename = arg
  File "S:\src\electrum\.venv\lib\site-packages\kivy\core\image\__init__.py", line 756, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "S:\src\electrum\.venv\lib\site-packages\kivy\core\image\__init__.py", line 427, in load
    raise Exception('Unable to found %r atlas' % afn)</pre>
</details>

**Comment by ecdsa** [comment]
did you run 'make theming'?
this is in the android Readme, but it is actually needed for desktop too
maybe we should print it at runtime

**Comment by brianddk** [comment]
> did you run 'make theming'?

@ecdsa , Thx, I had thought I scrubbed the android FAQ, but I obviously missed that.  Thanks for pointing it outl.

> maybe we should print it at runtime

Well it wil it will show up on an issue search if anyone misses it in the future
