### ISSUE TITLE
crash when closing 1 of 2 running instances (hidapi, libusb, threading, segfault)

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#6554]
Electrum 4.0.2 appimage on debian

Create an 8 of 8 multisig with 8 hardware devices: trezor one, trezor T, Nano S, Nano X, BitBox01, BitBox02, Coldcard Mk1, Coldcard Mk2

Create a 1 of 8 multisig with same 8 hardware devices

Open the 8 of 8 wallet and unlock all 8 plugged in devices

Then open the 1 of 8 wallet.

The close the 8 of 8 wallet and wait for a few seconds until both instances crash. I've repeated this process several times and get different errors.

```
$ ~/Downloads/apps/electrum-4.0.2-x86_64.AppImage --testnet
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
E | plugin.DeviceMgr | failed to create client for bitbox02 at b'0001:0009:01': Exception('No BitBox02 detected')
E | plugins.coldcard.coldcard.Coldcard_KeyStore | 
Traceback (most recent call last):
  File "/tmp/.mount_electrcFBIsQ/usr/lib/python3.7/site-packages/electrum/plugins/coldcard/coldcard.py", line 383, in sign_transaction
    resp = client.sign_transaction_poll()
  File "/tmp/.mount_electrcFBIsQ/usr/lib/python3.7/site-packages/electrum/plugins/coldcard/coldcard.py", line 233, in sign_transaction_poll
    return self.dev.send_recv(CCProtocolPacker.get_signed_txn(), timeout=None)
  File "/tmp/.mount_electrcFBIsQ/usr/lib/python3.7/site-packages/ckcc/client.py", line 139, in send_recv
    buf = self.dev.read(64, timeout_ms=(timeout or 0))
  File "hid.pyx", line 123, in hid.device.read
OSError: read error
double free or corruption (fasttop)
Aborted
```

```
$ ~/Downloads/apps/electrum-4.0.2-x86_64.AppImage --testnet
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
E | plugin.DeviceMgr | failed to create client for bitbox02 at b'0001:0009:01': Exception('No BitBox02 detected')
libusb: error [usbi_handle_transfer_completion] failed to set timer for next timeout, errno=9
libusb: error [handle_events] backend handle_events failed with error -99
Segmentation fault
```

**Comment by SomberNight** [comment]
Does it only crash when you close one of the wallets?
Sounds like threading issue in relation to hidapi or libusb.

Thanks for the reproduction steps although it is not exactly practical :)

**Comment by jlopp** [comment]
Confirmed, it only crashes when I try to close either of the open wallets. Otherwise I'm able to use all of the functionality in either wallet including signing and broadcasting transactions without any issues.

Stress testing FTW!

**Comment by jlopp** [comment]
Here's a new error I ran into when I had 3 wallets open and closed one.

```
I | storage.WalletStorage | saved /home/jameson/.electrum/testnet/wallets/testnet_stash
D | util.profiler | WalletStorage.write 0.0237
I | verifier.[testnet_stash] | verified 6b57e46da37aa8363d01568b2f76289d51a7098f236b678540ab8b5946787f51
I/w | wallet.Standard_Wallet.[testnet_stash] | set_up_to_date: False
I/i | interface.[TN.not.fyi:55002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 50.2.0.0/16')
I/n | network | couldn't launch iface TN.not.fyi:55002:s -- CancelledError()
I/w | wallet.Standard_Wallet.[testnet_stash] | set_up_to_date: True
I | storage.WalletStorage | saved /home/jameson/.electrum/testnet/wallets/testnet_stash
D | util.profiler | WalletStorage.write 0.0185
I | gui.qt.main_window.[stress_test_1_of_8] | close_wallet /home/jameson/.electrum/testnet/wallets/stress_test_1_of_8
I | plugins.trezor.clientbase.TrezorClientBase | closing client
I | plugins.trezor.clientbase.TrezorClientBase | clear session: My Trezor/27D2331A2E2A479FFDB960EC
python3.7: ../../libusb/io.c:2116: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.
Aborted
```

**Comment by jlopp** [comment]
This is a similar but likely different issue I once again encountered while having multiple hardware based wallets open. Then I clicked the X button to close one of them.

However, instead of all the wallets instantly crashing, Electrum froze up, pegged the CPU, and had to be force killed

```
I | gui.qt.main_window.[stress_test_3_of_5_2] | close_wallet /home/jameson/.electrum/testnet/wallets/stress_test_3_of_5_2
I | plugins.trezor.clientbase.TrezorClientBase | closing client
I | plugins.trezor.clientbase.TrezorClientBase | clear session: My TREZOR/3CACA102802D487ADDB685AC
Killed
```

**Comment by SomberNight** [comment]
Any chance you could test with https://github.com/spesmilo/electrum/pull/6561 ?

**Comment by jlopp** [comment]
Looks good to me; closing one of several open wallets no longer crashes all the open wallets.

**Comment by SomberNight** [comment]
hopefully fixed by https://github.com/spesmilo/electrum/pull/6561
