### ISSUE TITLE
Lightning channels issues (upgrading)

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#6583]
As discussed in IRC, I will comment on all issues I had while upgrading from 1773bd6cd6b9aaa693c6c1cb865f88fc3597e09f to 4.0.3.
Mostly they are related to lightning channels.

# open_channel
When testing on regtest, for simplicity, I want to open channel with the same node I use (to not start multiple nodes).
But when using `open_channel`, it fails with insufficient funds error. It is not related to the testing of sending payments before that. But not sending additional funds to the wallet before tests start makes this error occur less frequently, but it still occurs.
Test case:
```
async def test_open_channel(regtest_wallet, wait_for_balance):
    result = await regtest_wallet.open_channel(await regtest_wallet.node_id, 0.002)
```

Where `wait_for_balance` fixture ensures that wallet balance is at least 5 btc.
But it still raises insufficent funds error.
Log:
```
Traceback (most recent call last):
  File "/mnt/D/github/bitcart/daemons/base.py", line 362, in handle_request
    xpub, req_method, req_args, req_kwargs, exec_method, custom, wallet=wallet, config=config
  File "/mnt/D/github/bitcart/daemons/base.py", line 337, in get_exec_result
    return await result if inspect.isawaitable(result) else result
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/commands.py", line 151, in func_wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/commands.py", line 997, in open_channel
    funding_tx = wallet.mktx(outputs = [dummy_output], rbf=False, sign=False, nonlocal_only=True)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/wallet.py", line 1234, in mktx
    change_addr=change_addr)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/wallet.py", line 1202, in make_unsigned_transaction
    dust_threshold=self.dust_threshold())
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/coinchooser.py", line 332, in make_tx
    self.penalty_func(base_tx, tx_from_buckets=tx_from_buckets))
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/coinchooser.py", line 426, in choose_buckets
    candidates = self.bucket_candidates_prefer_confirmed(buckets, sufficient_funds)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/coinchooser.py", line 420, in bucket_candidates_prefer_confirmed
    raise NotEnoughFunds()
electrum.util.NotEnoughFunds: Insufficient funds
```
 `getbalance` output: 
`{'confirmed': Decimal('481.86162'), 'unconfirmed': Decimal('-0.004552'), 'unmatured': Decimal('0'), 'lightning': Decimal('0')}`

# close_channel
When closing channel created above, with force=False, it always fails. Force-close works.
Test code:
```
async def test_close_channel(regtest_wallet):
    channels = await regtest_wallet.list_channels()
    channel_id = channels[-1]["channel_point"]  # last channel is last in the list
    assert isinstance(
        await regtest_wallet.close_channel(channel_id, force=False), str
    )
```
Debug logs:
```
D/P | lnpeer.Peer.[LNWallet, responder] | Sending SHUTDOWN
D | lnchannel.Channel | Setting channel state: OPENING -> SHUTDOWN
I | storage.WalletStorage | saved /home/alex/.electrum/regtest/wallets/**redacted**
D | util.profiler | WalletStorage.write 0.0049
D/P | lnpeer.Peer.[LNWallet, 0.0.0.0:9735] | Sending SHUTDOWN
D | lnchannel.Channel | Setting channel state: SHUTDOWN -> SHUTDOWN
D/P | lnpeer.Peer.[LNWallet, 0.0.0.0:9735] | Sending CLOSING_SIGNED
D/P | lnpeer.Peer.[LNWallet, responder] | Sending CLOSING_SIGNED
E/P | lnpeer.Peer.[LNWallet, 0.0.0.0:9735] | Exception in _shutdown: Exception('failed to verify their signature',)
Traceback (most recent call last):
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1499, in _shutdown
    raise Exception('failed to verify their signature')
Exception: failed to verify their signature
E/P | lnpeer.Peer.[LNWallet, 0.0.0.0:9735] | Exception in on_shutdown: Exception('failed to verify their signature',)
Traceback (most recent call last):
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1428, in on_shutdown
    txid = await self._shutdown(chan, payload, False)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1499, in _shutdown
    raise Exception('failed to verify their signature')
Exception: failed to verify their signature
E | asyncio | Task exception was never retrieved
future: <Task finished coro=<log_exceptions.<locals>.wrapper() done, defined at /home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py:1034> exception=Exception('failed to verify their signature',)>
Traceback (most recent call last):
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1428, in on_shutdown
    txid = await self._shutdown(chan, payload, False)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1499, in _shutdown
    raise Exception('failed to verify their signature')
Exception: failed to verify their signature
E/P | lnpeer.Peer.[LNWallet, responder] | Exception in _shutdown: Exception('failed to verify their signature',)
Traceback (most recent call last):
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1499, in _shutdown
    raise Exception('failed to verify their signature')
Exception: failed to verify their signature
E/P | lnpeer.Peer.[LNWallet, responder] | Exception in close_channel: Exception('failed to verify their signature',)
Traceback (most recent call last):
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1410, in close_channel
    txid = await self._shutdown(chan, payload, True)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1499, in _shutdown
    raise Exception('failed to verify their signature')
Exception: failed to verify their signature
Traceback (most recent call last):
  File "/mnt/D/github/bitcart/daemons/base.py", line 356, in handle_request
    xpub, req_method, req_args, req_kwargs, exec_method, custom, wallet=wallet, config=config
  File "/mnt/D/github/bitcart/daemons/base.py", line 330, in get_exec_result
    return await result if inspect.isawaitable(result) else result
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/commands.py", line 151, in func_wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/commands.py", line 1080, in close_channel
    return await coro
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnworker.py", line 1347, in close_channel
    return await peer.close_channel(chan_id)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1410, in close_channel
    txid = await self._shutdown(chan, payload, True)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/lnpeer.py", line 1499, in _shutdown
    raise Exception('failed to verify their signature')
Exception: failed to verify their signature

I/g | lnworker.LNGossip | adding peer 03dd92f766f914933be39095dd6b8f443a9b33fdf309abdf8d8746181b267ddd06@0.0.0.0:9735
D/P | lnpeer.Peer.[LNGossip, 0.0.0.0:9735] | Sending INIT
D/P | lnpeer.Peer.[LNWallet, responder] | Sending INIT
I/P | lnpeer.Peer.[LNGossip, 0.0.0.0:9735] | Disconnecting: GracefulDisconnect("Failed to initialize: IncompatibleLightningFeatures('remote does not support <LnFeatures.GOSSIP_QUERIES_REQ: 64>',)",)
I/P | lnpeer.Peer.[LNWallet, responder] | Disconnecting: GracefulDisconnect('Failed to initialize: IncompatibleLightningFeatures("remote wanted feature we don\'t have: <LnFeatures.GOSSIP_QUERIES_REQ: 64>",)',)
```
# Question
Before electrum 4.0, at that intermediate commit, lightning worked globally per daemon. Now it works per-wallet. Is that the reason why only segwit is supported now?

**Comment by SomberNight** [comment]
> Question
> Before electrum 4.0, at that intermediate commit, lightning worked globally per daemon. Now it works per-wallet. Is that the reason why only segwit is supported now?

No, lightning did not work globally per daemon.

An `LNWorker` instance is a lightning node, as per BOLT spec.
There is a single global `LNGossip(LNWorker)` instance that does gossiping to build a channel graph, and there is a one-per-wallet `LNWallet(LNWorker)` instance that has channels (but does not gossip).

The reason we decided to only allow lightning for p2wpkh wallets for now is due to how [`option_static_remotekey`](https://github.com/lightningnetwork/lightning-rfc/blob/master/09-features.md) works. If the wallet has p2wpkh addresses, then with `option_static_remotekey` the `to_remote` commitment transaction output can directly pay a wallet address backed up by the seed.

> close_channel
> When closing channel created above, with force=False, it always fails. Force-close works.

Hmmm. We have a test for this that passes:
https://github.com/spesmilo/electrum/blob/261ad804cad9c8a4f9dbc6595727a35cadc0204e/electrum/tests/test_lnpeer.py#L572
and I have just closed two channels on testnet to test it, and they worked without issue.

**Comment by MrNaif2018** [comment]
Ok, got it.
About `close_channel`, this test seems to be more of a unit test than a real test.
Our tests are run in regtest, using commands API, using setup scripts similar to the ones electrum uses:
https://github.com/bitcartcc/bitcart-sdk/blob/electrum-4.0.3/tests/regtest/start_bitcoind.sh
https://github.com/bitcartcc/bitcart-sdk/blob/electrum-4.0.3/tests/regtest/start_electrumx.sh
https://github.com/bitcartcc/bitcart-sdk/blob/electrum-4.0.3/tests/regtest/regtest.sh
https://github.com/bitcartcc/bitcart-sdk/blob/electrum-4.0.3/tests/regtest.py#L30
`regtest.py` is the actual file running the tests.
It adds some balance to the wallet on regtest, then runs `payto` tests, then `open_channel`, and then `close_channel`.
May it be because it is a channel with the same node? (channel to `nodeid` result)

**Comment by SomberNight** [comment]
> when using open_channel, it fails with insufficient funds error

from IRC:

```
<mrnaif> Balance is more than enough, but no utxos are picked up
<mrnaif> Found out why. get_unspendable_coins' nonlocal_only param. open_channel passes True, which makes it pick 0 utxos. Is it expected?
<ghost43> are you sure? have you tried setting it to False and logging what it picks up?
<mrnaif> Yes, I set it to false and now it works just fine. Logs:
<mrnaif> mktx() found 5 with value=25000000000 balance=(25000000000, 0, 0)
<mrnaif> make_tx() called with 5 utxos. value=25000000000
<mrnaif> mktx() found 1 with value=24999723500 balance=(25000000000, -276500, 0)
<mrnaif> make_tx() called with 1 utxos. value=24999723500
[...]
<ghost43> your tests are not isolated
<ghost43> the first test spends all your UTXOs and adds the spending tx as local to the wallet
<ghost43> when the second test runs, it only has local UTXOs.
<mrnaif> But shouldn't mining new blocks fix it? Ideally I want tests to run in new regtest state, as well as in already used regtest state. So it's expected, just my tests issue, right>
<ghost43> the issue is that the tx is local. you cannot open a channel from a local utxo. local means only your client knows about it
<ghost43> the tx should be broadcast; and when the server sends back a notification about updated history, that's when the tx will turn into unconfirmed
```

> When testing on regtest, for simplicity, I want to open channel with the same node I use (to not start multiple nodes).
> [...]
> close_channel
> When closing channel created above, with force=False, it always fails. Force-close works.

we should probably add a check and disallow opening channels with the same node... there is no point in doing that. I guess it's not unexpected that it can lead to problems

**Comment by MrNaif2018** [comment]
So, in conclusion, I should wait until I have fresh utxos, which are nonlocal (and in real use cases it should be so) before calling `open_channel` - my tests issue, calling `listunspent` and waiting helped.
and in `close_channel` - I should not close/open channel with same node, and start a new separate node for testing channels. It might be prevented on channel opening to avoid problems.
All issues solved, thank you. I will probably leave issue open until `open_channel` has a check for connecting to same node.

**Comment by SomberNight** [comment]
> leave issue open until open_channel has a check for connecting to same node

done in https://github.com/spesmilo/electrum/commit/35f1f2905b79550fe062fe9db8ec1fa160eda121
