### ISSUE TITLE
Electrum GUI unsigned transactions appear incompatible with Electrum CLI

### ISSUE THREAD

**Issue by nsclong** [spesmilo/electrum#6584]
I have just upgraded (from a previously working v3.3.8 on both GUI and CLI) to version 4.0.3. I am trying to create an unsigned transaction from a GUI Electrum (v4.0.3) running on Debian 10, for signing on an offline CLI Electrum (v4.0.3) running on Raspbian.

I note that exporting the unsigned transaction from GUI, the file is now exported as .psbt format compared to the .txn format of v3.3.8. However when I try and sign the unsigned.psbt using the python3 command line version of Electrum I receive the following error;

**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4: Invalid start byte**

Does this suggest that the output format from the GUI version is not compatible with the CLI python3 version? Both are version 4.0.3 Electrum.

**Comment by SomberNight** [comment]
What is the exact command you are running for the CLI?

**Comment by ecdsa** [comment]
could it be that you passed to the command line a psbt saved in binary format?

**Comment by nsclong** [comment]
Hi, I am using the following:

cat unsigned.txn | python3 Electrum-4.0.3/run_electrum signtransaction -w WALLETNAME - > signed.txn

**Comment by nsclong** [comment]
> could it be that you passed to the command line a psbt saved in binary format?

I am using the Electrum GUI to export the .psbt file so it gives me no choices regarding format.

**Comment by SomberNight** [comment]
> could it be that you passed to the command line a psbt saved in binary format?

Yes indeed that is that is the cause.

```
$ cat ~/wspace/tmp/test_segwit_2-20200913-1752.psbt | ./run_electrum --testnet signtransaction -w ~/.electrum/testnet/wallets/test_segwit_2 -
Traceback (most recent call last):
  File "./run_electrum", line 294, in <module>
    sys.argv[i] = sys.stdin.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4: invalid start byte
```

@nsclong Electrum 4.0.x ditched the custom partial tx format we have been using for years in favour of the PSBT (BIP-174) standard format. The PSBT spec specifies that when saved into a file, the [PSBT should be encoded as binary](https://github.com/bitcoin/bips/blob/68bb026c56162b016494bdea8caf3aeb9c39ef7b/bip-0174.mediawiki#Encoding). This is the root cause.

**Comment by nsclong** [comment]
OK thanks for the fast response - and it is good to know the cause. However, that leaves me (and I suspect many others) unable to sign from an offline wallet.

Is this something that will be fixed in the next release? And is there a temporary fix we can use from the python CLI in the meantime?

Any help much appreciated. Thank you!

**Comment by SomberNight** [comment]
I don't know if we can fix this.
We've never liked this encoding part of the spec either, so what we implemented is that Electrum's output conforms to the spec, but the for inputs we have greatly relaxed the requirements. When inputting a tx to Electrum, almost all encodings are accepted.
Although in this specific case, the issue is that python itself can't decode the binary data piped in.

-----

One workaround is that in the GUI you could copy the tx to clipboard (so that you get text, base64 in particular) and then paste that text into a file. This file would then not conform to the BIP-174 spec but Electrum would still accept it; and this file can easily be piped just as you have tried.

-----

Another workaround is that you can convert the binary file to e.g. hex with a few extra pipes, and Electrum will happily accept that too (despite a PSBT in hex format not conforming the spec either). For example:
replace `cat ~/wspace/tmp/test_segwit_2-20200913-1752.psbt`
with `cat ~/wspace/tmp/test_segwit_2-20200913-1752.psbt | xxd -p | tr -d \\n`

```
cat ~/wspace/tmp/test_segwit_2-20200913-1752.psbt | xxd -p | tr -d \\n | ./run_electrum --testnet -o signtransaction -w ~/.electrum/testnet/wallets/test_segwit_2 -
```

**Comment by nsclong** [comment]
OK - copying text to clipboard works. Phew! Thank you for your quick help.

Please can I recommend that the instructions on at https://electrum.readthedocs.io/en/latest/coldstorage_cmdline.html are updated to mention this problem - or should I request that change direct on GitHub?

**Comment by yashithac618** [comment]
Hi maintainers,
I'd like to work on improving this documentation if the issue is still available.
Thanks!

**Comment by SomberNight** [comment]
Sure, feel free to open a PR. The mentioned file is at https://github.com/spesmilo/electrum-docs/blob/master/coldstorage_cmdline.rst
