### ISSUE TITLE
4.0.5 always shows "No FX rate available"

### ISSUE THREAD

**Issue by shawnz** [spesmilo/electrum#6748]
After upgrading to 4.0.5, I see "No FX rate available" in the status bar. Switching back to 4.0.4 shows the correct value. This impacts all currencies for me.

I am not using tor or a VPN or anything like that.

**Comment by ecdsa** [comment]
I cannot reproduce this on linux.
the screenshot seems to have been taken on windows.

Note: it is not recommended to open the same wallet simultaneously in two Electrum instances. 
If you use lightning, it could corrupt your channels.

**Comment by 144** [comment]
> 
> 
> I cannot reproduce this on linux.
> the screenshot seems to have been taken on windows.
> 
> Note: it is not recommended to open the same wallet simultaneously in two Electrum instances.
> If you use lightning, it could corrupt your channels.

I'm using Electrum on windows as single instance without lightning and i'm experiencing the same issue.

**Comment by shawnz** [comment]
Thank you for the note ecdsa. However I only did that for demonstration purposes and the bug still occurs with single instances. Is there some kind of debug logging I can enable to get more details?

**Comment by 144** [comment]
After enabling "write logs to file" i found this thing in logs:
`20201119T132933.096143Z |     INFO | exchange_rate.BitcoinAverage | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")`

**Comment by SomberNight** [comment]
I've tested with the Windows binary, and e.g. CAD/CoinGecko works for me.
@shawnz could you check [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) if there are some hints there?

-----

>  20201119T132933.096143Z | INFO | exchange_rate.BitcoinAverage | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")

@144 that looks interesting. I cannot reproduce though. How are you running Electrum? (which OS, binaries/source, etc?)

**Comment by 144** [comment]
> 
> 
> I've tested with the Windows binary, and e.g. CAD/CoinGecko works for me.
> @shawnz could you check [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) if there are some hints there?
> 
> > `20201119T132933.096143Z | INFO | exchange_rate.BitcoinAverage | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")`
> 
> @144 that looks interesting. I cannot reproduce though. How are you running Electrum? (which OS, binaries/source, etc?)

binaries from electrum.org, the installer one. Windows 10 x64 1909 - 18363.1198

**Comment by shawnz** [comment]
Hi @SomberNight , I enabled the log files and I have the same error as @144 .

```
20201119T210321.600812Z |     INFO | gui.qt.ElectrumGui | Qt GUI starting up... Qt=5.14.2, PyQt=5.14.2
20201119T210321.648636Z |     INFO | exchange_rate.CoinGecko | failed fx history: TypeError("__init__() got multiple values for keyword argument 'timer'")
20201119T210321.648636Z |    ERROR | asyncio | Unclosed connection
client_connection: Connection<ConnectionKey(host='api.coingecko.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=892630978)>
20201119T210321.649612Z |     INFO | exchange_rate.CoinGecko | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")
20201119T210321.649612Z |    ERROR | asyncio | Unclosed connection
client_connection: Connection<ConnectionKey(host='api.coingecko.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=892630978)>
20201119T210321.781372Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.1825
```

**Comment by SomberNight** [comment]
It is unfortunate that the debug logs don't contain a traceback... I will fix that separately but for now, we should monkey patch the code at runtime to see one.

Could you please go to the `Console` tab and run this (just once):
```
electrum.exchange_rate.CoinGecko.get_rates = electrum.util.log_exceptions(electrum.exchange_rate.CoinGecko.get_rates)
```

Take note that it is exchange specific, so e.g. if you use BitcoinAverage, then run this instead:

```
electrum.exchange_rate.BitcoinAverage.get_rates = electrum.util.log_exceptions(electrum.exchange_rate.BitcoinAverage.get_rates)
```

Then, either wait ~3 minutes for the periodic refresh, or manually trigger one via fiddling with the network settings (e.g. enable and then disable proxy).

With this change, the debug logs should contain a full traceback.

**Comment by 144** [comment]
> 
> 
> It is unfortunate that the debug logs don't contain a traceback... I will fix that separately but for now, we should monkey patch the code at runtime to see one.
> 
> Could you please go to the `Console` tab and run this (just once):
> 
> ```
> electrum.exchange_rate.CoinGecko.get_rates = electrum.util.log_exceptions(electrum.exchange_rate.CoinGecko.get_rates)
> ```
> 
> Take note that it is exchange specific, so e.g. if you use BitcoinAverage, then run this instead:
> 
> ```
> electrum.exchange_rate.BitcoinAverage.get_rates = electrum.util.log_exceptions(electrum.exchange_rate.BitcoinAverage.get_rates)
> ```
> 
> Then, either wait ~3 minutes for the periodic refresh, or manually trigger one via fiddling with the network settings (e.g. enable and then disable proxy).
> 
> With this change, the debug logs should contain a full traceback.

`20201120T004634.780451Z |    ERROR | exchange_rate.BitcoinAverage | Exception in get_rates: TypeError("__init__() got multiple values for keyword argument 'timer'")
Traceback (most recent call last):
  File "electrum\util.py", line 1039, in wrapper
  File "electrum\exchange_rate.py", line 154, in get_rates
  File "electrum\exchange_rate.py", line 64, in get_json
  File "aiohttp\client.py", line 1124, in __aenter__
  File "aiohttp\client.py", line 544, in _request
  File "aiohttp\client_proto.py", line 160, in set_response_params
  File "aiohttp\_http_parser.pyx", line 566, in aiohttp._http_parser.HttpResponseParser.__init__
TypeError: __init__() got multiple values for keyword argument 'timer'
20201120T004634.781447Z |     INFO | exchange_rate.BitcoinAverage | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")`

**Comment by shawnz** [comment]
Same stack trace here:

```
20201120T004731.576120Z |    ERROR | exchange_rate.CoinGecko | Exception in get_rates: TypeError("__init__() got multiple values for keyword argument 'timer'")
Traceback (most recent call last):
  File "electrum\util.py", line 1039, in wrapper
  File "electrum\exchange_rate.py", line 302, in get_rates
  File "electrum\exchange_rate.py", line 64, in get_json
  File "aiohttp\client.py", line 1124, in __aenter__
  File "aiohttp\client.py", line 544, in _request
  File "aiohttp\client_proto.py", line 160, in set_response_params
  File "aiohttp\_http_parser.pyx", line 566, in aiohttp._http_parser.HttpResponseParser.__init__
TypeError: __init__() got multiple values for keyword argument 'timer'
20201120T004731.579047Z |     INFO | exchange_rate.CoinGecko | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")
20201120T004731.579047Z |    ERROR | asyncio | Unclosed connection
client_connection: Connection<ConnectionKey(host='api.coingecko.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=892630978)>
```

**Comment by SomberNight** [comment]
> binaries from electrum.org, the installer one. Windows 10 x64 1909 - 18363.1198

@shawnz Have you also used the installer (setup.exe)?

Do both of you have a folder at `%programfiles(x86)%/Electrum/aiohttp` that includes .pyd files?

Did you use the setup.exe to install Electrum on top of an existing older version?
Could it be that you started the setup.exe while Electrum was already running, and only stopped Electrum when getting an error from the setup wizard?

If yes to all, I think I know what is going on.
Try uninstalling and reinstalling Electrum.

**Comment by 144** [comment]
> 
> 
> > binaries from electrum.org, the installer one. Windows 10 x64 1909 - 18363.1198
> 
> Do both of you have a folder at `%programfiles(x86)%/Electrum/aiohttp` that includes .pyd files?
> 
> Did you use the setup.exe to install Electrum on top of an existing older version?
> Could it be that you started the setup.exe while Electrum was already running, and only stopped Electrum when getting an error from the setup wizard?
> 
> If yes to all, I think I know what is going on.
> Try uninstalling and reinstalling Electrum.

I got the files at /aiohttp.
I installed Electrum on top of an existing version in order to update it.
I don't really remember if i started it while Electrum was running.

Re-installing doesn't seem to fix the issue, atleast for me.

**Comment by SomberNight** [comment]
Ok, in that case I know what is going on. I can reproduce.

- The user needs to have a previous version of Electrum installed using the NSIS installer that unpacks a pyinstaller one-folder binary.
- User downloads the new version of Electrum (same kind of binary: NSIS + pyinstaller one-folder).
- While old version of Electrum .exe is running in background, the new setup.exe is launched.
- The setup.exe tries to clear the install folder but fails to delete many files which are in use. The deletion of files only fails silently and the [installer proceeds](https://github.com/spesmilo/electrum/blob/dfcdcb8d6410958e8533817f81a6d17bdc463280/contrib/build-wine/electrum.nsi#L105-L113).
- It starts to unpack the new files but now gets another failure when trying to overwrite the files that are in use. This failure is not silent: it opens a popup asking the user whether to re-try or abort.
- The user realises Electrum is still running and closes it now; then goes back to the installer and selects retry.
- The installer succeeds.
- At this point the user will have a semi-corrupt state of files in the install dir: all old files that have a newer variant are overwritten however some old files that should have been deleted (as they no longer exists in new version) are still there.

Then as to the specific issue here:
Electrum 4.0.4 bundled the aiohttp 3.6.3 win32 binary wheel, while Electrum 4.0.5 bundles the aiohttp 3.7.2 sdist tar.gz.
So an Electrum 4.0.4 install has pyd files for aiohttp 3.6.3, while Electrum 4.0.5 should have no pyd files for aiohttp.
The aiohttp 3.6.3 pyd files interfere with the pure python aiohttp 3.7.2.

-----

We should add some logic into the nsis installer to detect that Electrum is running.

**Comment by SomberNight** [comment]
> We should add some logic into the nsis installer to detect that Electrum is running.

Some related links

- https://nsis.sourceforge.io/Docs/Chapter4.html
- https://nsis.sourceforge.io/Check_whether_your_application_is_running
- https://github.com/qbittorrent/qBittorrent/pull/7132
- https://github.com/qbittorrent/qBittorrent/blob/b249216db6c8da8133ef812e21984647ab9117b2/dist/windows/installer.nsi#L211
- https://github.com/qbittorrent/qBittorrent/blob/b249216db6c8da8133ef812e21984647ab9117b2/dist/windows/options.nsi#L97
- https://nsis.sourceforge.io/FindProcDLL_plug-in

**Comment by shawnz** [comment]
You got it exactly right. I did try and install 4.0.5 while 4.0.4 was still running and it did cause an error which I had to retry. I totally forgot all about that. Reinstalling fixed the issue here too.
