### ISSUE TITLE
Electrum suppressing errors from my server

### ISSUE THREAD

**Issue by CodeForcer** [spesmilo/electrum#6903]
My usual sweeping process is failing suddenly with the following:
```
$ cat sweep-privs-01-01-2021 | electrum sweep - <address>
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 384, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 748, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 630, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 1321, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 783, in wrapper | electrum.network.UntrustedServerReturnedError: The server returned an error.\n')
```

I'm sweeping valid private keys with funds on them. I understand this was implemented to suppress the phishing messages, but I'm running my own ElectrumX server.

Is there a way to see what the error message actually is so I can diagnose what is causing this problem?

**Comment by ecdsa** [comment]
yes, you can see it in the logs. (enable logs in your preferences)

**Comment by CodeForcer** [comment]
Thanks
