### ISSUE TITLE
Android app crashes when USB device is connected (Trezor, yubikey, headphone DAC)

### ISSUE THREAD

**Issue by gordonel** [spesmilo/electrum#6907]
To reproduce:
1. Connect and unlock Trezor to an Android device (pixel 3, Android 11 in my case)
2. Launch Electrum

OR

1. Launch Electrum
2. Connect and unlock Trezor

<details>
<summary>Catlog</summary>

```bash
01-03 19:48:55.975  1463  1923 D UsbHostManager: USB device attached: vidpid 1209:53c1 mfg/product/ver/serial SatoshiLabs/TREZOR/2.00/29F14E60288CC82115C334F6 hasAudio/HID/Storage: false/true/false
01-03 19:48:55.977  1463  1923 I chatty  : uid=1000(system) UsbService host expire 1 line
01-03 19:48:55.979  1463  1923 D UsbHostManager: Added device UsbDevice[mName=/dev/bus/usb/001/002,mVendorId=4617,mProductId=21441,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=SatoshiLabs,mProductName=TREZOR,mVersion=2.00,mSerialNumberReader=com.android.server.usb.UsbSerialReader@f144fa3, mHasAudioPlayback=false, mHasAudioCapture=false, mHasMidi=false, mHasVideoCapture=false, mHasVideoPlayback=false, mConfigurations=[
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=50,mInterfaces=[
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbInterface[mId=0,mAlternateSetting=0,mName=TREZOR Interface,mClass=255,mSubclass=0,mProtocol=0,mEndpoints=[
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbEndpoint[mAddress=129,mAttributes=3,mMaxPacketSize=64,mInterval=1]
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbEndpoint[mAddress=1,mAttributes=3,mMaxPacketSize=64,mInterval=1]]
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbInterface[mId=1,mAlternateSetting=0,mName=TREZOR Interface,mClass=3,mSubclass=0,mProtocol=0,mEndpoints=[
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbEndpoint[mAddress=130,mAttributes=3,mMaxPacketSize=64,mInterval=1]
01-03 19:48:55.979  1463  1923 D UsbHostManager: UsbEndpoint[mAddress=2,mAttributes=3,mMaxPacketSize=64,mInterval=1]]]]
01-03 19:48:55.992 26024 26024 D AndroidRuntime: Shutting down VM
01-03 19:48:55.993 26024 26024 E AndroidRuntime: FATAL EXCEPTION: main
01-03 19:48:55.993 26024 26024 E AndroidRuntime: Process: org.electrum.electrum, PID: 26024
01-03 19:48:55.993 26024 26024 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000010 (has extras) } in org.libsdl.app.HIDDeviceManager$1@722cb8
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1590)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-03 19:48:55.993 26024 26024 E AndroidRuntime: Caused by: java.lang.SecurityException: User has not given 10152/org.electrum.electrum permission to access device /dev/bus/usb/001/002
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2357)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2340)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2282)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:157)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at org.libsdl.app.HIDDeviceUSB.getSerialNumber(HIDDeviceUSB.java:54)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.connectHIDDeviceUSB(HIDDeviceManager.java:368)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.handleUsbDeviceAttached(HIDDeviceManager.java:332)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager.access$000(HIDDeviceManager.java:26)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at org.libsdl.app.HIDDeviceManager$1.onReceive(HIDDeviceManager.java:69)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        ... 8 more
01-03 19:48:55.993 26024 26024 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at com.android.server.usb.UsbUserPermissionManager.checkPermission(UsbUserPermissionManager.java:654)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:98)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:84)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1154)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:1123)
01-03 19:48:55.993 26024 26024 E AndroidRuntime:
01-03 19:48:55.997  1463 26229 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-03 19:48:55.998  1463  3426 W ActivityTaskManager:   Force finishing activity org.electrum.electrum/org.kivy.android.PythonActivity
01-03 19:48:56.024  1463  1489 D UsbDeviceManager: Clear notification
01-03 19:48:56.025 26024 26024 I Process : Sending signal. PID: 26024 SIG: 9
```
</details>

Important bits:
```bash
01-03 19:48:55.993 26024 26024 E AndroidRuntime: FATAL EXCEPTION: main
01-03 19:48:55.993 26024 26024 E AndroidRuntime: Process: org.electrum.electrum, PID: 26024
01-03 19:48:55.993 26024 26024 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000010 (has extras) } in org.libsdl.app.HIDDeviceManager$1@722cb8
...
01-03 19:48:55.993 26024 26024 E AndroidRuntime: Caused by: java.lang.SecurityException: User has not given 10152/org.electrum.electrum permission to access device /dev/bus/usb/001/002
```

**Comment by SomberNight** [comment]
I get the same crash when connecting a USB-C to 3.5mm DAC for headphones.

```
01-04 20:18:12.716 23235 23235 V pythonutil: Loading library: python3.8
01-04 20:18:12.717 23235 23235 V pythonutil: Loading library: python3.9
01-04 20:18:12.717 23235 23235 V pythonutil: Library loading error: dlopen failed: library "libpython3.9.so" not found
01-04 20:18:12.717 23235 23235 V pythonutil: Loading library: main
01-04 20:18:12.717 23235 23235 V pythonutil: Loaded everything!
01-04 20:18:12.718 23235 23235 V SDL     : nativeSetupJNI()
01-04 20:18:12.718 23235 23235 V SDL     : AUDIO nativeSetupJNI()
01-04 20:18:12.718 23235 23235 V SDL     : CONTROLLER nativeSetupJNI()
01-04 20:18:12.726 23235 23235 D AndroidRuntime: Shutting down VM
--------- beginning of crash
01-04 20:18:12.726 23235 23235 E AndroidRuntime: FATAL EXCEPTION: main
01-04 20:18:12.726 23235 23235 E AndroidRuntime: Process: org.electrum.electrum, PID: 23235
01-04 20:18:12.726 23235 23235 E AndroidRuntime: java.lang.SecurityException: User has not given 10472/org.electrum.electrum permission to access device /dev/bus/usb/002/002
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3007)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2990)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2932)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:126)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:157)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.HIDDeviceUSB.getSerialNumber(HIDDeviceUSB.java:54)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.HIDDeviceManager.connectHIDDeviceUSB(HIDDeviceManager.java:368)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.HIDDeviceManager.handleUsbDeviceAttached(HIDDeviceManager.java:332)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.HIDDeviceManager.initializeUSB(HIDDeviceManager.java:228)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.HIDDeviceManager.<init>(HIDDeviceManager.java:152)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.HIDDeviceManager.acquire(HIDDeviceManager.java:35)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.libsdl.app.SDLActivity.finishLoad(SDLActivity.java:264)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.kivy.android.PythonActivity.access$200(PythonActivity.java:43)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:121)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:102)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8741)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at com.android.server.usb.UsbUserPermissionManager.checkPermission(UsbUserPermissionManager.java:741)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:98)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:89)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1316)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1280)
01-04 20:18:12.726 23235 23235 E AndroidRuntime: 
01-04 20:18:12.736 23235 23235 I Process : Sending signal. PID: 23235 SIG: 9
```

https://github.com/spesmilo/electrum/issues/6991 also reported a crash when connecting a yubikey.

-----

Based on the trace, it is related to SDL2.
And indeed I get the crash with the kivy-based android app, but not with the qml app.

**Comment by SomberNight** [comment]
Closing as the kivy GUI was removed in https://github.com/spesmilo/electrum/pull/8591
