### ISSUE TITLE
decode_invoice: Server got itself in trouble

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#7078]
Trying to decode a lightning invoice from either CLI or RPC i get a plaintext error (also with 'Application/json' accept header):
```
Error: 500 Internal Server Error

Server got itself in trouble
```
In the meanwhile, the daemon logs:
```
E | aiohttp.server | Error handling request
Traceback (most recent call last):
  File "/srv/app/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/app/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/app/.local/lib/python3.7/site-packages/electrum/daemon.py", line 216, in handle
    return web.json_response(response)
  File "/srv/app/.local/lib/python3.7/site-packages/aiohttp/web_response.py", line 773, in json_response
    text = dumps(data)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
```
### Notes
- I tested it on both regtest and testnet.
- The call to `decode_invoice` works correctly if I add the `--offline` CLI flag 
- I'm able to decode and pay invoices from the graphical interface without issues.

**Comment by St333p** [comment]
I looked a bit into the code and it seems that this issue comes from the fact that `self.__lnaddr.amount` is a `Decimal` inside `LNInvoice.to_debug_json()` in `invoices.py`. From a quick test it seems to be enough to cast it to float before performing json encoding, so line 202 would become:
```
'amount_BTC': float(self._lnaddr.amount),
```
If you agree with the proposed fix I can also open a PR

**Comment by ecdsa** [comment]
it should actually be cast to `str`, not `float`. I will take care of that.
