### ISSUE TITLE
channel_establishment_flow fails: assert chan.is_static_remotekey_enabled()

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7122]
I've tried to open a channel with the Electrum trampoline node on mainnet, running latest master.
Gossip disabled.
Wallet has existing channels; some open, some closed, some of the old closed ones did not have static remote key enabled, but that should not matter.

```
I/P | lnpeer.Peer.[LNWallet, 144.76.99.209:9740] | received funding_signed
I | lnchannel.Channel | receive_new_commitment. ctn=0, len(htlc_sigs)=0
D | lnchannel.Channel | Setting channel state: PREOPENING -> OPENING
I | storage.WalletStorage | saved c:\users\user\appdata\roaming\electrum\wallets\mywallet
D | util.profiler | WalletDB._write 0.0549
I | storage.WalletStorage | saved c:\users\user\appdata\roaming\electrum\wallets\mywallet
D | util.profiler | WalletDB._write 0.0454
D | util.profiler | WalletDB._load_transactions 0.2407
D | lnchannel.Channel | Setting channel state: OPENING -> REDEEMED
I | storage.WalletStorage | saved c:\users\user\appdata\roaming\electrum\wallets\mywallet
D | util.profiler | WalletDB._write 0.0483
E/P | lnpeer.Peer.[LNWallet, 144.76.99.209:9740] | Exception in channel_establishment_flow: AssertionError()
Traceback (most recent call last):
  File "...\electrum\electrum\util.py", line 1099, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 563, in wrapper
    return await func(self, *args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 744, in channel_establishment_flow
    self.lnworker.add_new_channel(chan)
  File "...\electrum\electrum\lnworker.py", line 1008, in add_new_channel
    self.wallet.save_backup(backup_dir)
  File "...\electrum\electrum\wallet.py", line 323, in save_backup
    channel_backups[chan_id.hex()] = self.lnworker.create_channel_backup(chan_id)
  File "...\electrum\electrum\lnworker.py", line 2032, in create_channel_backup
    assert chan.is_static_remotekey_enabled()
AssertionError
E | lnworker.LNWallet.[mywallet] | Exception in _open_channel_coroutine: AssertionError()
Traceback (most recent call last):
  File "...\electrum\electrum\util.py", line 1099, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnworker.py", line 984, in _open_channel_coroutine
    chan, funding_tx = await asyncio.wait_for(coro, LN_P2P_NETWORK_TIMEOUT)
  File "...\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "...\electrum\electrum\util.py", line 1099, in wrapper
    return await func(*args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 563, in wrapper
    return await func(self, *args, **kwargs)
  File "...\electrum\electrum\lnpeer.py", line 744, in channel_establishment_flow
    self.lnworker.add_new_channel(chan)
  File "...\electrum\electrum\lnworker.py", line 1008, in add_new_channel
    self.wallet.save_backup(backup_dir)
  File "...\electrum\electrum\wallet.py", line 323, in save_backup
    channel_backups[chan_id.hex()] = self.lnworker.create_channel_backup(chan_id)
  File "...\electrum\electrum\lnworker.py", line 2032, in create_channel_backup
    assert chan.is_static_remotekey_enabled()
AssertionError
```

**Comment by SomberNight** [comment]
>  Wallet has existing channels; some open, some closed, some of the old closed ones did not have static remote key enabled, but that should not matter.

Ahh it matters because we try to backup all channels...
https://github.com/spesmilo/electrum/blob/d86c45edac16e458829b84249fc66f6f412ba089/electrum/wallet.py#L317-L323

**Comment by ecdsa** [comment]
not really a bug: channels without static_remote were never created by an official Electrum release.
instead of adding extra logic to deal with that case, it would be better stop supporting them.

**Comment by SomberNight** [comment]
Ok; let's not fix this.
