### ISSUE TITLE
AttributeError: 'SilentTaskGroup' object has no attribute '_closed' sys:1: RuntimeWarning: coroutine 'LNWorker.maybe_listen' was never awaited

### ISSUE THREAD

**Issue by Geremia** [spesmilo/electrum#7130]
After starting Electrum 4.0.9 and entering my wallet's password, Electrum throws this error:

```
/usr/lib64/python3.9/asyncio/base_events.py:1875: RuntimeWarning: coroutine 'ignore_exceptions.<locals>.wrapper' was never awaited
  handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1679, resource id: 20971843, major code: 40 (TranslateCoords), minor code: 0
/usr/lib64/python3.9/site-packages/electrum/lnworker.py:616: RuntimeWarning: coroutine 'ignore_exceptions.<locals>.wrapper' was never awaited
  tg_coro = self.taskgroup.spawn(coro)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.9/site-packages/electrum/lnworker.py:616: RuntimeWarning: coroutine 'LNWallet.reestablish_peers_and_channels' was never awaited
  tg_coro = self.taskgroup.spawn(coro)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.9/site-packages/electrum/lnworker.py:616: RuntimeWarning: coroutine 'log_exceptions.<locals>.wrapper' was never awaited
  tg_coro = self.taskgroup.spawn(coro)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
E | daemon.Daemon | GUI raised exception: AttributeError("'SilentTaskGroup' object has no attribute '_closed'"). shutting down.
E | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "/usr/bin/electrum", line 398, in handle_cmd
    d.run_gui(config, plugins)
  File "/usr/lib64/python3.9/site-packages/electrum/daemon.py", line 573, in run_gui
    self.gui_object.main()
  File "/usr/lib64/python3.9/site-packages/electrum/gui/qt/__init__.py", line 361, in main
    if not self.start_new_window(path, self.config.get('url'), app_is_starting=True):
  File "/usr/lib64/python3.9/site-packages/electrum/gui/qt/__init__.py", line 245, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/electrum/gui/qt/__init__.py", line 269, in start_new_window
    wallet = self._start_wizard_to_select_or_create_wallet(path)
  File "/usr/lib64/python3.9/site-packages/electrum/gui/qt/__init__.py", line 326, in _start_wizard_to_select_or_create_wallet
    wallet.start_network(self.daemon.network)
  File "/usr/lib64/python3.9/site-packages/electrum/wallet.py", line 367, in start_network
    self.lnworker.start_network(network)
  File "/usr/lib64/python3.9/site-packages/electrum/lnworker.py", line 616, in start_network
    tg_coro = self.taskgroup.spawn(coro)
  File "/usr/lib64/python3.9/site-packages/electrum/util.py", line 1122, in spawn
    if self._closed:
AttributeError: 'SilentTaskGroup' object has no attribute '_closed'
sys:1: RuntimeWarning: coroutine 'LNWorker.maybe_listen' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
I'm running Slackware (-current) with Linux kernel 5.11.8.

**Comment by Geremia** [comment]
Duplicate of #7131
