### ISSUE TITLE
kivy GUI broken when using kivy master (StringProperty vs i18n)

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7156]
kivy master recently changed `StringProperty` to only accept objects of type `str` (and not accept objects that have a subclass as type), in https://github.com/kivy/kivy/pull/7439/files#diff-36f1031172a712de39a71ff3aa2644bcff77d03f5f371f47bc2066e9a8e682e0R796

All our translated strings are subclasses of `str` but don't have `type(x) is str`:
https://github.com/spesmilo/electrum/blob/38111581695ef906431e0641d23345b2ce56fe94/electrum/gui/kivy/i18n.py#L1-L9

Traceback:
```
03-31 20:48:52.598 23636 24568 I python  : E | __main__ | daemon.run_gui errored
03-31 20:48:52.598 23636 24568 I python  : Traceback (most recent call last):
03-31 20:48:52.598 23636 24568 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/main.py", line 400, in handle_cmd
03-31 20:48:52.598 23636 24568 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/daemon.py", line 579, in run_gui
03-31 20:48:52.598 23636 24568 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/gui/kivy/__init__.py", line 68, in main
03-31 20:48:52.598 23636 24568 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/gui/kivy/main_window.py", line 401, in __init__
03-31 20:48:52.598 23636 24568 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/gui/kivy/main_window.py", line 144, in update_proxy_str
03-31 20:48:52.598 23636 24568 I python  :   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
03-31 20:48:52.598 23636 24568 I python  :   File "kivy/properties.pyx", line 564, in kivy.properties.Property.set
03-31 20:48:52.598 23636 24568 I python  :   File "kivy/properties.pyx", line 555, in kivy.properties.Property.set
03-31 20:48:52.598 23636 24568 I python  :   File "kivy/properties.pyx", line 797, in kivy.properties.StringProperty.check
03-31 20:48:52.598 23636 24568 I python  : ValueError: ElectrumWindow.proxy_str accept only str

```

**Comment by SomberNight** [comment]
Note; the relevant change in https://github.com/kivy/kivy/pull/7439 might get reverted in https://github.com/kivy/kivy/pull/7459

**Comment by SomberNight** [comment]
note: still open as we are still using an older version of kivy
https://github.com/spesmilo/electrum/blob/d52afee6357475fbae194724ca9b3f0b5e4e5ac0/contrib/android/p4a_recipes/kivy/__init__.py#L8-L10
but the change got reverted upstream so if we update and test, we could close this.

**Comment by SomberNight** [comment]
Closing as the kivy GUI was removed in https://github.com/spesmilo/electrum/pull/8591
