### ISSUE TITLE
missing mnemonic misreported as error "trezor: Installed: 0.12.2, Needed: 0.12.0 <= x < 0.13"

### ISSUE THREAD

**Issue by colourful-land** [spesmilo/electrum#7224]
Trying to use Trezor and got this error on the console:

````W | gui.qt.installwizard.InstallWizard | error getting device infos for trezor: Library version for 'trezor' is incompatible. // Installed: 0.12.2, Needed: 0.12.0 <= x < 0.13 // Make sure you install it with python3````

This is puzzling because 0.12.2 fits perfectly between 0.12.0 and 0.13.

![imagen](https://user-images.githubusercontent.com/548435/115242186-fab68800-a164-11eb-82eb-9639c7418275.png)

**Comment by SomberNight** [comment]
Is there a traceback or similar in the [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

**Comment by SomberNight** [comment]
How did you install electrum?

**Comment by colourful-land** [comment]
> How did you install electrum?

This: note that it did not auto install mnemonic:

````
$ sudo pip3 install /tmp/Electrum-4.1.2.tar.gz 
Processing /tmp/Electrum-4.1.2.tar.gz
Requirement already satisfied: aiohttp<4.0.0,>=3.3.0 in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (3.7.4.post0)
Requirement already satisfied: aiohttp_socks>=0.3 in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (0.6.0)
Requirement already satisfied: aiorpcx<0.19,>=0.18.7 in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (0.18.7)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (20.3.0)
Requirement already satisfied: bitstring in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (3.1.7)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from Electrum==4.1.2) (2019.11.28)
Collecting dnspython<2.1,>=2.0
  Downloading dnspython-2.0.0-py3-none-any.whl (208 kB)
     |████████████████████████████████| 208 kB 2.6 MB/s 
Requirement already satisfied: protobuf>=3.12 in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (3.15.6)
Requirement already satisfied: qdarkstyle<2.9 in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (2.8.1)
Requirement already satisfied: qrcode in /usr/local/lib/python3.8/dist-packages (from Electrum==4.1.2) (6.1)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<4.0.0,>=3.3.0->Electrum==4.1.2) (3.0.4)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>=3.3.0->Electrum==4.1.2) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>=3.3.0->Electrum==4.1.2) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>=3.3.0->Electrum==4.1.2) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/lib/python3/dist-packages (from aiohttp<4.0.0,>=3.3.0->Electrum==4.1.2) (3.7.4.1)
Requirement already satisfied: python-socks[asyncio]>=1.2.2 in /usr/local/lib/python3.8/dist-packages (from aiohttp_socks>=0.3->Electrum==4.1.2) (1.2.3)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf>=3.12->Electrum==4.1.2) (1.14.0)
Requirement already satisfied: qtpy>=1.9 in /usr/local/lib/python3.8/dist-packages (from qdarkstyle<2.9->Electrum==4.1.2) (1.9.0)
Requirement already satisfied: helpdev>=0.6.10 in /usr/local/lib/python3.8/dist-packages (from qdarkstyle<2.9->Electrum==4.1.2) (0.7.1)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.3.0->Electrum==4.1.2) (2.8)
Building wheels for collected packages: Electrum
  Building wheel for Electrum (setup.py) ... done
  Created wheel for Electrum: filename=Electrum-4.1.2-py3-none-any.whl size=9246221 sha256=4f91044e86d3dad7557858d773a407773da5ec9c47da31b0ad864d5dc4106be1
  Stored in directory: /root/.cache/pip/wheels/a5/92/42/aa46cf88a48e07fec3b7420472dd810f74b93b83580b7576e0
Successfully built Electrum
Installing collected packages: dnspython, Electrum
  Attempting uninstall: dnspython
    Found existing installation: dnspython 2.1.0
    Uninstalling dnspython-2.1.0:
      Successfully uninstalled dnspython-2.1.0
  Attempting uninstall: Electrum
    Found existing installation: Electrum 4.0.9
    Uninstalling Electrum-4.0.9:
      Successfully uninstalled Electrum-4.0.9
Successfully installed Electrum-4.1.2 dnspython-2.0.0
````

**Comment by SomberNight** [comment]
> note that it did not auto install mnemonic

well it is only a dependency of python-trezor; electrum does not need it.

How did you install python-trezor?

**Comment by colourful-land** [comment]
> > note that it did not auto install mnemonic
> 
> well it is only a dependency of python-trezor; electrum does not need it.
> 
> How did you install python-trezor?

That was far back since this problem was triggered by using new Eletreum (was using 4.0.9 without issue), while I installed trezor through pip3 when I installed 4.0.9.

I couldn't have used the Ubuntu apt package since that wouldn't satisfy > 0.12 rule.

**Comment by SomberNight** [comment]
python-trezor correctly specifies the dependency on the `mnemonic` package, so when you installed that, it should have pulled that in.
https://github.com/trezor/trezor-firmware/blob/4200692930cb0ea51da050ca9beb7eda9193461e/python/setup.py#L10

**Comment by SomberNight** [comment]
> After some struggling I resolved this issue by
> `$ sudo apt-get install python3-mnemonic`

How did you figure out that package was missing?

**Comment by SomberNight** [comment]
This is what I get in the terminal, even without running with `-v`, after pip installing `trezor` and then pip uninstalling `mnemonic`:

```
E | plugins.trezor.trezor | error importing trezor plugin deps
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/plugins/trezor/trezor.py", line 28, in <module>
    from .clientbase import TrezorClientBase
  File "/home/user/wspace/electrum/electrum/plugins/trezor/clientbase.py", line 13, in <module>
    from trezorlib.client import TrezorClient, PASSPHRASE_ON_DEVICE
  File "/home/user/.local/lib/python3.8/site-packages/trezorlib/client.py", line 22, in <module>
    from mnemonic import Mnemonic
ModuleNotFoundError: No module named 'mnemonic'
W | plugins.trezor.qt.Plugin | Library version for 'trezor' is incompatible.
Installed: 0.12.2, Needed: 0.12.0 <= x < 0.13
```

Did you not see the same message?
This already looks like fairly useful debugging information to me.

Note that the situation can only occur if you are running from source and installing packages yourself (as the binaries have all these packages bundled), so checking either stderr or the logs seems to be a reasonable expectation.

If you wanted to improve the error message in the GUI, you could open a PR.
