### ISSUE TITLE
Coutld not open channel: TimeoutError()

### ISSUE THREAD

**Issue by alexander-koval** [spesmilo/electrum#7240]
Hello! I'm trying to open new channel with "endurance" node, but error occurs. 
Stacktrace:
```
E/P | lnpeer.Peer.[LNWallet, 34.250.234.192:9735] | Exception in main_loop: Exception('not accepting channels')
Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1091, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 317, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 335, in main_loop
    await group.spawn(self.process_gossip())
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 790, in on_open_channel
    raise Exception('not accepting channels')
Exception: not accepting channels
E | lnworker.LNWallet.[skintest] | Exception in _open_channel_coroutine: TimeoutError()
Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1091, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 573, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 651, in channel_establishment_flow
    payload = await self.wait_for_message('accept_channel', temp_channel_id)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 236, in wait_for_message
    name, payload = await asyncio.wait_for(q.get(), LN_P2P_NETWORK_TIMEOUT)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 468, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1091, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnworker.py", line 997, in _open_channel_coroutine
    chan, funding_tx = await asyncio.wait_for(coro, LN_P2P_NETWORK_TIMEOUT)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by SomberNight** [comment]
Looks like just after you start opening a channel with the remote node, the remote node itself tries to start opening a new channel with you REUSING the temporary channel id we had set...
