### ISSUE TITLE
App wont start after config

### ISSUE THREAD

**Issue by walesc** [spesmilo/electrum#7270]
Hi everyone,
Here's the report:
Traceback (most recent call last):
  File "electrum\util.py", line 851, in run_with_except_hook
  File "threading.py", line 864, in run
  File "C:\Users\Wal\AppData\Local\Temp\_MEI72322\electrum\plugins\trustedcoin\trustedcoin.py", line 474, in f
    return func(self, *args, **kwargs)
  File "C:\Users\Wal\AppData\Local\Temp\_MEI72322\electrum\plugins\trustedcoin\trustedcoin.py", line 495, in request_billing_info
    raise Exception(f'unexpected trustedcoin billing address: '
Exception: unexpected trustedcoin billing address: calculated fc1q2rd98lqjkz9wszwshsgjt9dpca35eqwzu4yh5e, received bc1q2rd98lqjkz9wszwshsgjt9dpca35eqwzx3kd5c
 
Any idea please ?
Thx a lot

**Comment by wakiyamap** [comment]
Since the address is fc1~, I assume that it is `electrum-ftc(feathercoin)` or `electrum-fjc(fujicoin)`.
Trustedcoin doesn't support anything but bitcoin.

I think you should ask each of them here.
electrum-ftc https://github.com/Feathercoin-Foundation/electrum-ftc
electrum-fjc https://github.com/fujicoin/electrum-fjc

**Comment by walesc** [comment]
Thanks for the answer

**Comment by ecdsa** [comment]
it is really annoying to see all those posts about shitcoins...

**Comment by walesc** [comment]
Maybe you can enlighten me and tell me which ones are not shitcoins ?
