### ISSUE TITLE
Label syncs, Should they eventually update without going in tool/plugin/labelsync/force download.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7273]
I find myself doing these multiple clickings very often.

**Comment by SomberNight** [comment]
The updates should normally happen automatically yes.
Do you have anything related in your logs?

**Comment by OEsmir** [comment]
Hi, 
I have multiple multisig wallets which for a while are not synchronizing the labels (for the watchonly wallets).

Can anyone help here by any chance? 
Sorry if this was resolved somewhere else, I was not able to find any solution. 


This an extract of the logs: 

20220926T065312.525676Z |    ERROR | plugins.labels.qt.Plugin | Error synchronising labels
Traceback (most recent call last):
  File "electrum\gui\qt\util.py", line 1216, in run
  File "C:\Program Files (x86)\Electrum\electrum\plugins\labels\labels.py", line 181, in push
    return asyncio.run_coroutine_threadsafe(self.push_thread(wallet), wallet.network.asyncio_loop).result()
  File "concurrent\futures\_base.py", line 446, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "C:\Program Files (x86)\Electrum\electrum\plugins\labels\labels.py", line 124, in push_thread
    await self.do_post("/labels", bundle)
  File "C:\Program Files (x86)\Electrum\electrum\plugins\labels\labels.py", line 101, in do_post
    async with session.post(url, json=data) as result:
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 559, in _request
  File "aiohttp\client_reqrep.py", line 913, in start
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

**Comment by OEsmir** [comment]
another thing I discovered today, which could be related, is that when I export the labels and open the json file, a lot of recent labels are missing and they're matching (in most cases) with the one missing in the other wallet I have issues syncing

**Comment by accumulator** [comment]
Still getting timeouts when submitting labels. Fetch from the same endpoint succeeds, so it is likely a server problem.

**Comment by accumulator** [comment]
Adding bug label, as the UI never notifies the user this failed (unless a manual upload is triggered by the user)
