### ISSUE TITLE
Error running from source

### ISSUE THREAD

**Issue by paulrm** [spesmilo/electrum#7336]
After installing Development version, when running I get this error:

```
python3 Electrum-4.1.2/run_electrum
Traceback (most recent call last):
  File "Electrum-4.1.2/run_electrum", line 39, in <module>
    import asyncio
  File "/usr/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/usr/lib/python3/dist-packages/apt/package.py", line 44, in <module>
    from typing import (Any, Iterable, Iterator, List, Optional, Set,
  File "/home/paul.messina/.local/lib/python2.7/site-packages/typing.py", line 782, in <module>
    AnyStr = TypeVar('AnyStr', bytes, unicode)
NameError: name 'unicode' is not defined

Original exception was:
Traceback (most recent call last):
  File "Electrum-4.1.2/run_electrum", line 39, in <module>
    import asyncio
  File "/usr/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

The same error appears after install with `python3 -m pip install --user Electrum-4.1.2.tar.gz`

Versions:

- Ubuntu 18.04.5 LTS
- Python 3.6.9
- Electrum-4.1.2

**Comment by SomberNight** [comment]
Your python installation is corrupted somehow, nothing to do with Electrum itself.
Look at the trace: python 3.6 stdlib is importing python 2.7 stdlib...
```
  File "/usr/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
```
