### ISSUE TITLE
Unable to open wallet after update to 4.1.4

### ISSUE THREAD

**Issue by m4rimekko** [spesmilo/electrum#7390]
Hi everybody!

Hope you are well. After updating to 4.1.4 from 2.x, I'm unable to access my wallet. On Windows 10, Electrum just closes after entering the PW and on OS X it just freezes and crashes. 

Since the app already upgraded the wallet, it can't be opened in the legacy versions anymore either. Stupidly, I lost access to my seed. Any help on how to restore the wallet or decrypt the seed from it would be highly appreciated.

Thank you!

**EDIT://** I was able to recover an older version of the wallet. When trying to open it with testnet, I get the following error: 

_InvalidMasterKeyVersionBytes('Invalid extended key format: 0x488b21e')_

**Comment by SomberNight** [comment]
Please try to [obtain debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) and share them here.

> EDIT:// I was able to recover an older version of the wallet. When trying to open it with testnet, I get the following error:
>
> `InvalidMasterKeyVersionBytes('Invalid extended key format: 0x488b21e')`

That's expected. A mainnet wallet cannot be opened in testnet mode and vice-versa.

**Comment by m4rimekko** [comment]
Thanks for your reply, @SomberNight t! Just obtained the log:

```
20210706T091754.651544Z |     INFO | simple_config.SimpleConfig | electrum directory C:\Users\XXX\AppData\Roaming\Electrum
20210706T091754.654545Z |     INFO | logging | Electrum version: 4.1.4 - https://electrum.org - https://github.com/spesmilo/electrum
20210706T091754.654545Z |     INFO | logging | Python version: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:08:11) [MSC v.1928 32 bit (Intel)]. On platform: Windows-10-10.0.19041-SP0
20210706T091754.654545Z |     INFO | logging | Logging to file: C:\Users\XXX\AppData\Roaming\Electrum\logs\electrum_log_20210706T091754Z_9860.log
20210706T091754.655442Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20210706T091754.656453Z |     INFO | plugin.Plugins | registering hardware bitbox02: ('hardware', 'bitbox02', 'BitBox02')
20210706T091754.657454Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20210706T091754.658454Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20210706T091754.661455Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20210706T091754.662455Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20210706T091754.663455Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20210706T091754.664455Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20210706T091754.665456Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20210706T091754.665456Z |    DEBUG | util.profiler | Plugins.__init__ 0.0100
20210706T091754.666456Z |     INFO | network | blockchains [0]
20210706T091754.667456Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20210706T091754.668456Z |     INFO | network | starting network
20210706T091754.668456Z |    DEBUG | util.profiler | Daemon.__init__ 0.0030
20210706T091754.669476Z |     INFO | daemon.Daemon | launching GUI: qt
20210706T091754.669476Z |     INFO | network | setting proxy None
20210706T091754.670477Z |     INFO | network | connecting to bitcoin.lukechilds.co:50002:s as new interface
20210706T091754.670477Z |     INFO | daemon.Daemon | starting taskgroup.
20210706T091754.671487Z |     INFO | network | starting taskgroup.
20210706T091754.721937Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20210706T091754.731941Z |     INFO | gui.qt.ElectrumGui | Qt GUI starting up... Qt=5.15.2, PyQt=5.15.4
20210706T091754.878762Z |     INFO | interface.[vmd63185.contaboserver.net:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091754.903075Z |     INFO | interface.[vmd63185.contaboserver.net:50002] | set blockchain with height 689862
20210706T091754.903075Z |     INFO | interface.[vmd63185.contaboserver.net:50002] | skipping header 689862
20210706T091754.904077Z |     INFO | network | no height for main interface
20210706T091754.919217Z |     INFO | interface.[bitcoin.lukechilds.co:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091754.925498Z |     INFO | network | fee_estimates {25: 12258, 10: 71584, 5: 71584, 2: 79468}
20210706T091754.945504Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.2186
20210706T091754.946504Z |     INFO | storage.WalletStorage | wallet path c:\users\XXX\appdata\roaming\electrum\wallets\throwaway
20210706T091755.147994Z |     INFO | interface.[bitcoin.lukechilds.co:50002] | set blockchain with height 689862
20210706T091755.147994Z |     INFO | interface.[bitcoin.lukechilds.co:50002] | skipping header 689862
20210706T091755.147994Z |     INFO | network | no height for main interface
20210706T091755.147994Z |     INFO | network | switching to vmd63185.contaboserver.net:50002:s
20210706T091755.149993Z |     INFO | network | fee_estimates {25: 15723, 10: 71584, 5: 71584, 2: 79468}
20210706T091755.159995Z |     INFO | storage.WalletStorage | wallet path c:\users\XXX\appdata\roaming\electrum\wallets\throwaway
20210706T091755.228741Z |     INFO | network | fee_histogram [[75.7, 100001], [71.8, 123585], [11.1, 167880], [3.0, 268396], [2.4, 213127], [1.8, 244015], [1.1, 27317], [1.0, 6804304]]
20210706T091755.464262Z |     INFO | interface.[e.keff.org:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20210706T091755.499427Z |     INFO | interface.[electrum.privateservers.network:50002] | succeeded in getting cert
20210706T091755.504001Z |     INFO | interface.[e.keff.org:50002] | set blockchain with height 689862
20210706T091755.505003Z |     INFO | interface.[e.keff.org:50002] | skipping header 689862
20210706T091755.552001Z |     INFO | network | fee_estimates {25: 19188, 10: 71584, 5: 71584, 2: 79468}
20210706T091755.591866Z |     INFO | interface.[E-X.not.fyi:50002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 45.154.0.0/16')
20210706T091755.591866Z |     INFO | network | couldn't launch iface E-X.not.fyi:50002:s -- CancelledError()
20210706T091755.600532Z |     INFO | interface.[electrum.privateservers.network:50002] | connection established. version: ['ElectrumX 1.15.0', '1.4']
20210706T091755.624665Z |     INFO | interface.[electrum.privateservers.network:50002] | set blockchain with height 689862
20210706T091755.624665Z |     INFO | interface.[electrum.privateservers.network:50002] | skipping header 689862
20210706T091755.670531Z |     INFO | interface.[68.183.188.105:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091755.685534Z |     INFO | interface.[ec2-3-142-117-237.us-east-2.compute.amazonaws.com:50002] | connection established. version: ['Fulcrum 1.5.2', '1.4']
20210706T091755.808746Z |     INFO | interface.[ec2-3-142-117-237.us-east-2.compute.amazonaws.com:50002] | set blockchain with height 689862
20210706T091755.808746Z |     INFO | interface.[ec2-3-142-117-237.us-east-2.compute.amazonaws.com:50002] | skipping header 689862
20210706T091755.933282Z |     INFO | interface.[68.183.188.105:50002] | set blockchain with height 689862
20210706T091755.934293Z |     INFO | interface.[68.183.188.105:50002] | skipping header 689862
20210706T091756.069515Z |     INFO | interface.[korea.electrum-server.com:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091756.367974Z |     INFO | interface.[korea.electrum-server.com:50002] | set blockchain with height 689862
20210706T091756.368974Z |     INFO | interface.[korea.electrum-server.com:50002] | skipping header 689862
20210706T091816.225163Z |     INFO | storage.WalletStorage | wallet path c:\users\XXX\desktop\mywallet
20210706T091816.344703Z |     INFO | interface.[xray587.startdedicated.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(OSError(22, 'Das Zeitlimit für die Semaphore wurde erreicht', None, 121, None)))
20210706T091816.344703Z |     INFO | network | couldn't launch iface xray587.startdedicated.de:50002:s -- CancelledError()
20210706T091816.392367Z |     INFO | interface.[ndnd.selfhost.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(OSError(22, 'Das Zeitlimit für die Semaphore wurde erreicht', None, 121, None)))
20210706T091816.392367Z |     INFO | network | couldn't launch iface ndnd.selfhost.eu:50002:s -- CancelledError()
20210706T091816.498623Z |     INFO | interface.[kittycp2gatrqhlwpmbczk5rblw62enrpo2rzwtkfrrr27hq435d4vid.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
20210706T091816.499624Z |     INFO | network | couldn't launch iface kittycp2gatrqhlwpmbczk5rblw62enrpo2rzwtkfrrr27hq435d4vid.onion:50002:s -- CancelledError()
20210706T091816.743643Z |     INFO | interface.[electrum.hodlister.co:50002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 45.154.0.0/16')
20210706T091816.744169Z |     INFO | network | couldn't launch iface electrum.hodlister.co:50002:s -- CancelledError()
20210706T091816.780258Z |     INFO | interface.[electrumx.ddns.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
20210706T091816.781260Z |     INFO | network | couldn't launch iface electrumx.ddns.net:50002:s -- CancelledError()
20210706T091817.553536Z |     INFO | interface.[fedaykin.goip.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(OSError(22, 'Das Zeitlimit für die Semaphore wurde erreicht', None, 121, None)))
20210706T091817.553536Z |     INFO | network | couldn't launch iface fedaykin.goip.de:50002:s -- CancelledError()
20210706T091818.038652Z |     INFO | interface.[e03.srvmin.network:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091819.143215Z |     INFO | interface.[e03.srvmin.network:50002] | set blockchain with height 689862
20210706T091819.143215Z |     INFO | interface.[e03.srvmin.network:50002] | skipping header 689862
20210706T091819.619007Z |     INFO | interface.[tomscryptos.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(22, 'Der Remotecomputer hat die Netzwerkverbindung abgelehnt', None, 1225, None)))
20210706T091819.619007Z |     INFO | network | couldn't launch iface tomscryptos.com:50002:s -- CancelledError()
20210706T091819.761169Z |     INFO | interface.[148.251.22.104:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091819.781494Z |     INFO | interface.[148.251.22.104:50002] | set blockchain with height 689862
20210706T091819.781494Z |     INFO | interface.[148.251.22.104:50002] | skipping header 689862
20210706T091822.186084Z |     INFO | interface.[electrum.eff.ro:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(22, 'Der Remotecomputer hat die Netzwerkverbindung abgelehnt', None, 1225, None)))
20210706T091822.186532Z |     INFO | network | couldn't launch iface electrum.eff.ro:50002:s -- CancelledError()
20210706T091822.327210Z |     INFO | interface.[ex.btcmp.com:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20210706T091822.335080Z |     INFO | interface.[ex.btcmp.com:50002] | set blockchain with height 689862
20210706T091822.336083Z |     INFO | interface.[ex.btcmp.com:50002] | skipping header 689862
20210706T091824.494031Z |     INFO | wallet_db.WalletDB | upgrading wallet format
20210706T091824.498673Z |    ERROR | daemon.Daemon | GUI raised exception: ValueError('too many values to unpack (expected 2)'). shutting down.
20210706T091824.498673Z |     INFO | daemon.Daemon | on_stop() entered. initiating shutdown
20210706T091824.498673Z |     INFO | gui.qt.ElectrumGui | closing GUI
20210706T091824.498673Z |     INFO | daemon.Daemon | stopping all wallets
20210706T091824.499683Z |     INFO | daemon.Daemon | stopping network and taskgroup
20210706T091824.499683Z |     INFO | network | stopping network
20210706T091824.501683Z |     INFO | daemon.Daemon | taskgroup stopped.
20210706T091824.506684Z |     INFO | interface.[ex.btcmp.com:50002] | disconnecting due to: CancelledError()
20210706T091824.520802Z |     INFO | interface.[148.251.22.104:50002] | disconnecting due to: CancelledError()
20210706T091824.523803Z |     INFO | interface.[electrum.privateservers.network:50002] | disconnecting due to: CancelledError()
20210706T091824.524803Z |     INFO | interface.[vmd63185.contaboserver.net:50002] | disconnecting due to: CancelledError()
20210706T091824.529734Z |     INFO | interface.[e03.srvmin.network:50002] | disconnecting due to: CancelledError()
20210706T091824.538846Z |     INFO | interface.[e.keff.org:50002] | disconnecting due to: CancelledError()
20210706T091824.549222Z |     INFO | interface.[bitcoin.lukechilds.co:50002] | disconnecting due to: CancelledError()
20210706T091824.763224Z |     INFO | interface.[68.183.188.105:50002] | disconnecting due to: CancelledError()
20210706T091824.798668Z |     INFO | interface.[korea.electrum-server.com:50002] | disconnecting due to: CancelledError()
20210706T091826.512383Z |     INFO | daemon.Daemon | removing lockfile
20210706T091826.513398Z |     INFO | daemon.Daemon | stopped
20210706T091826.513398Z |    ERROR | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "run_electrum", line 407, in handle_cmd
  File "electrum\daemon.py", line 584, in run_gui
  File "electrum\gui\qt\__init__.py", line 414, in main
  File "electrum\gui\qt\__init__.py", line 291, in wrapper
  File "electrum\gui\qt\__init__.py", line 316, in start_new_window
  File "electrum\gui\qt\__init__.py", line 361, in _start_wizard_to_select_or_create_wallet
  File "electrum\wallet_db.py", line 73, in __init__
  File "electrum\wallet_db.py", line 106, in load_data
  File "electrum\util.py", line 412, in <lambda>
  File "electrum\util.py", line 408, in do_profile
  File "electrum\wallet_db.py", line 175, in upgrade
  File "electrum\wallet_db.py", line 540, in _convert_version_24
ValueError: too many values to unpack (expected 2)
20210706T091826.574322Z |     INFO | plugin.Plugins | stopped

```

If I try to open the wallet from the already running app I get this error:

```
Traceback
Traceback (most recent call last):
  File "electrum\gui\qt\__init__.py", line 291, in wrapper
  File "electrum\gui\qt\__init__.py", line 316, in start_new_window
  File "electrum\gui\qt\__init__.py", line 361, in _start_wizard_to_select_or_create_wallet
  File "electrum\wallet_db.py", line 73, in __init__
  File "electrum\wallet_db.py", line 106, in load_data
  File "electrum\util.py", line 412, in <lambda>
  File "electrum\util.py", line 408, in do_profile
  File "electrum\wallet_db.py", line 175, in upgrade
  File "electrum\wallet_db.py", line 540, in _convert_version_24
ValueError: too many values to unpack (expected 2)
 
Additional information
Electrum version: 4.1.4 
Python version: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:08:11) [MSC v.1928 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041-SP0 
Wallet type: standard 
```

**Comment by m4rimekko** [comment]
@SomberNight Do you think there is any hope of restoring the wallet or seed? Any help would be extremely appreciated.

In the meantime, I've tried running [btcrecover ](https://github.com/gurnec/btcrecover )but wasn't successful, unfortunately.

**Comment by SomberNight** [comment]
so this is probably the same as https://github.com/spesmilo/electrum/issues/6349
see https://github.com/spesmilo/electrum/issues/6349#issuecomment-754158457

I suspect you opened the wallet file with new electrum, which upgraded it,
then for some reason you tried opening the same file again with old electrum, which corrupted it,
and now neither version can open it.

Does that match what you remember to have happened?

> Do you think there is any hope of restoring the wallet or seed? 

Yes, it can probably be recovered, but it is a bit involved. Make sure you have a copy of the wallet file saved.

**Comment by m4rimekko** [comment]
@SomberNight Thanks for your quick reply, I really appreciate your help! Yes, I think it's the same issue as #6349 

> I suspect you opened the wallet file with new electrum, which upgraded it,
> then for some reason you tried opening the same file again with old electrum, which corrupted it,
> and now neither version can open it.

Exactly. Since I wasn't sure if updating electrum would overwrite my old wallet, I kept both versions and must have accidentally opened the wallet with the wrong one. 

> Yes, it can probably be recovered, but it is a bit involved. Make sure you have a copy of the wallet file saved.

That's great to hear. Can you recommend any steps I can try to recover it?

**Comment by m4rimekko** [comment]
In case anybody is having the same problem: A wallet recovery service was able to recover my seed. So before giving up on your coins, it might be worth a try to get in touch with a service you trust. Just be sure to do your research before sending over anything.

**Comment by m4rimekko** [comment]
In case anybody is having the same problem: A wallet recovery service was able to recover my seed. So before giving up on your coins, it might be worth a try to get in touch with a service you trust. Just be sure to do your research before sending over anything.
