### ISSUE TITLE
CLI: add_request breaks without digits as first param

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#7404]
$ electrum add_rrequest help

command will output:

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 472, in <module>
    main()
  File "/usr/local/bin/electrum", line 311, in main
    args = parser.parse_args()
  File "/usr/lib/python3.7/argparse.py", line 1758, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1999, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1955, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.7/argparse.py", line 1864, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.7/dist-packages/electrum/commands.py", line 1392, in subparser_call
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1999, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1955, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.7/argparse.py", line 1848, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.7/argparse.py", line 2378, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.7/argparse.py", line 2411, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.7/dist-packages/electrum/commands.py", line 1325, in <lambda>
    'amount': lambda x: str(Decimal(x)) if x != '!' else '!',
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by SomberNight** [comment]
Note that to access the help/manpage, you would want to run:
`$ electrum help add_request`

Indeed if you run `$ electrum add_request help` instead then you get the long traceback and error because it tries to parse the first argument as an amount.
To be clear, the issue here is that the error message should be made clearer, right?

**Comment by gits7r** [comment]
Yes, exactly. no need for this trace back in a just wrong ordered otherwise valid command (IMO).
