### ISSUE TITLE
Bitbox02 PaytoMany Invalid Message (101)

### ISSUE THREAD

**Issue by lc0des** [spesmilo/electrum#7440]
Version:Version 4.1.5  
Type: Linux, AppImage, Ubuntu  
Method: Pay to Many  

Description:  

Using electrum together with bitbox02 as HW wallet. Trying to sign transaction of method "Pay to many". After "Finalize", there is 
a window with a sign button. Pressing the sign button ends in the error message below. As a result "pay to many" seems not possible with electrum wallet and bitbox02.

Error Message at Terminal:
```

bitbox02.communication.bitbox_api_protocol.Bitbox02Exception: error code: 101, message: invalid input
E | plugins.bitbox02.bitbox02.BitBox02_KeyStore | 
Traceback (most recent call last):
  File "/tmp/.mount_electrMQ24Kn/usr/lib/python3.7/site-packages/electrum/plugins/bitbox02/bitbox02.py", line 602, in sign_transaction
    client.sign_transaction(self, tx, self.handler.get_wallet())
  File "/tmp/.mount_electrMQ24Kn/usr/lib/python3.7/site-packages/electrum/plugin.py", line 362, in wrapper
    return run_in_hwd_thread(partial(func, *args, **kwargs))
  File "/tmp/.mount_electrMQ24Kn/usr/lib/python3.7/site-packages/electrum/plugin.py", line 352, in run_in_hwd_thread
    return func()
  File "/tmp/.mount_electrMQ24Kn/usr/lib/python3.7/site-packages/electrum/plugins/bitbox02/bitbox02.py", line 518, in sign_transaction
    version=tx.version,
  File "/tmp/.mount_electrMQ24Kn/usr/lib/python3.7/site-packages/bitbox02/bitbox02/bitbox02.py", line 541, in btc_sign
    request, expected_response="btc_sign_next"
  File "/tmp/.mount_electrMQ24Kn/usr/lib/python3.7/site-packages/bitbox02/communication/bitbox_api_protocol.py", line 639, in _msg_query
    raise Bitbox02Exception(response.error.code, response.error.message)
bitbox02.communication.bitbox_api_protocol.Bitbox02Exception: error code: 101, message: invalid input
```

Thank yo

**Comment by benma** [comment]
I'll take a look and provide a solution.

**Comment by benma** [comment]
@lc0des 

I tried with master and v4.1.5, and for me everything worked as expected.

Can you share more details about the transaction? What types of recipient addresses did you use and how many?

Also try updating the bitbox02 package:

`pip3 install -U bitbox02`
