### ISSUE TITLE
Unable to open a new LN channel with a node I'd previously had a channel with

### ISSUE THREAD

**Issue by chris-belcher** [spesmilo/electrum#7599]
When using electrum lightning, I tried to open a channel with a node i had previously had a channel with, but i got this error:

```
E | lnworker.LNWallet.[lnwallet] | Exception in _open_channel_coroutine: Exception("Remote peer reported error [DO NOT TRUST THIS MESSAGE]: b'Parsing funding_created'")
Traceback (most recent call last):
  File "/home/username/coding/electrum/git-electrum/electrum/util.py", line 1161, in wrapper
    return await func(*args, **kwargs)
  File "/home/username/coding/electrum/git-electrum/electrum/lnworker.py", line 1007, in _open_channel_coroutine
    chan, funding_tx = await asyncio.wait_for(coro, LN_P2P_NETWORK_TIMEOUT)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/username/coding/electrum/git-electrum/electrum/util.py", line 1161, in wrapper
    return await func(*args, **kwargs)
  File "/home/username/coding/electrum/git-electrum/electrum/lnpeer.py", line 582, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/username/coding/electrum/git-electrum/electrum/lnpeer.py", line 746, in channel_establishment_flow
    payload = await self.wait_for_message('funding_signed', channel_id)
  File "/home/username/coding/electrum/git-electrum/electrum/lnpeer.py", line 241, in wait_for_message
    raise Exception('Remote peer reported error [DO NOT TRUST THIS MESSAGE]: ' + repr(payload.get('error')))
Exception: Remote peer reported error [DO NOT TRUST THIS MESSAGE]: b'Parsing funding_created'
```

I was at commit 7354feeffecc34bc9f15838662f9211dd686d04f

Opening a channel with a brand new node worked though.

The other node was running c-lightning 0.10.2.

There were about 106 confirmations between the previous channel close transaction and my attempt to open a new channel.

**Comment by jezreel89** [comment]
tengo el mismo problema

**Comment by jezreel89** [comment]
lo resolviste?
