### ISSUE TITLE
protobuf → "TypeError: bases must be types"

### ISSUE THREAD

**Issue by Geremia** [spesmilo/electrum#7825]
Electrum tries importing something that throws an error. Here's the context:
```python3
Traceback (most recent call last):
  File "/usr/bin/electrum", line 82, in <module>
    check_imports()
  File "/usr/bin/electrum", line 73, in check_imports
    from google.protobuf import descriptor
  File "/usr/lib64/python3.9/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```
Protobuf version Version: 3.20.1
Electrum 4.2.1

<sup>Perhaps this is only [a Protobuf issue](https://github.com/protocolbuffers/protobuf/issues/10012)?</sup>

**Comment by SomberNight** [comment]
I cannot reproduce.
Maybe your protobuf install is broken somehow. Try reinstalling it.

Test this:
```
user@user-VirtualBox:~/wspace/tmp$ python3 -m venv env
user@user-VirtualBox:~/wspace/tmp$ source env/bin/activate
(env) user@user-VirtualBox:~/wspace/tmp$ pip install protobuf==3.20.1
Collecting protobuf==3.20.1
  Using cached protobuf-3.20.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Installing collected packages: protobuf
Successfully installed protobuf-3.20.1
(env) user@user-VirtualBox:~/wspace/tmp$ python
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor
>>> import google.protobuf
>>> google.protobuf.__version__
'3.20.1'
```

**Comment by Geremia** [comment]
@SomberNight That works.

**Comment by SomberNight** [comment]
So as the freshly installed isolated protobuf 3.20.1 works for you but the system-wide installed protobuf 3.20.1 does not, that further suggests that there is some brokage on your system.

Try uninstalling and reinstalling protobuf.

**Comment by SomberNight** [comment]
Can you try running `pip uninstall..` a few times, until it complains it cannot find the package anymore:
```
python3 -m pip uninstall protobuf
python3 -m pip uninstall protobuf
python3 -m pip uninstall protobuf
python3 -m pip uninstall protobuf
```
and then installing protobuf again:
```
python3 -m pip install --user protobuf==3.20.1
```
