### ISSUE TITLE
Error in function parameter set payto()

### ISSUE THREAD

**Issue by LexProfi** [spesmilo/electrum#8008]
The function takes a number of parameters, but it is not possible to pass the value 'None' from the console
```
async def payto(self, destination, amount, fee=None, feerate=None, from_addr=None, from_coins=None, change_addr=None,
                    nocheck=False, unsigned=False, rbf=None, password=None, locktime=None, addtransaction=False, wallet: Abstract_Wallet = None):

```
Tried different options:
```
payto('tb1q3jwkqtwmpmlrd7jm95kv0txp3txe0apvhje334','0.0002','1000','0','tb1q5668s2sxewk0jlzt3kqw9vf3xl8ffy7462ujdh')
payto('tb1q3jwkqtwmpmlrd7jm95kv0txp3txe0apvhje334','0.0002','1000','None','tb1q5668s2sxewk0jlzt3kqw9vf3xl8ffy7462ujdh')
payto('tb1q3jwkqtwmpmlrd7jm95kv0txp3txe0apvhje334','0.0002','1000','','tb1q5668s2sxewk0jlzt3kqw9vf3xl8ffy7462ujdh')

```
But the result is always the same:
```
Traceback (most recent call last):
  File "electrum\commands.py", line 191, in _run
  File "concurrent\futures\_base.py", line 446, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "electrum\commands.py", line 154, in func_wrapper
  File "electrum\commands.py", line 687, in payto
  File "electrum\wallet.py", line 2718, in create_transaction
Exception: Cannot specify both 'fee' and 'feerate' at the same time!
```

**Comment by LexProfi** [comment]
The problem was in quotes:
`
payto('tb1q3jwkqtwmpmlrd7jm95kv0txp3txe0apvhje334','0.0002','1000',None,'tb1q5668s2sxewk0jlzt3kqw9vf3xl8ffy7462ujdh')
`
