### ISSUE TITLE
LN Error: Exception closing channel

### ISSUE THREAD

**Issue by dolcalmi** [spesmilo/electrum#8012]
I initiated the close of a channel but now peer appears disconnected. I tested adding peer again and using `list_peers` to validate but it shows the node and then disappears.

Logs:
```
20221012T051432.822678Z |     INFO | lnpeer.Peer.[LNWallet, 0225XXX14c8] | channel_reestablish (75XX76xXXXXx0): received channel_reestablish with (their_next_local_ctn=9, their_oldest_unrevoked_remote_ctn=8)
20221012T051432.834608Z |     INFO | lnpeer.Peer.[LNWallet, 0225XXX14c8] | saved remote channel_update gossip msg for chan 73XX77xXXXXx1
20221012T051432.846069Z |     INFO | lnpeer.Peer.[LNWallet, 0225XXX14c8] | saved remote channel_update gossip msg for chan 75XX76xXXXXx0
20221012T051432.856983Z |    DEBUG | lnpeer.Peer.[LNWallet, 0225XXX14c8] | Received CLOSING_SIGNED
20221012T051432.858953Z |    ERROR | lnpeer.Peer.[LNWallet, 0225XXX14c8] | Exception in _shutdown: Exception('scriptpubkey does not conform to any template: 512019c...b85883')
Traceback (most recent call last):
  File "/tmp/.mount_electrE9Fp2M/usr/lib/python3.9/site-packages/electrum/util.py", line 1239, in wrapper
    return await func(*args, **kwargs)
  File "/tmp/.mount_electrE9Fp2M/usr/lib/python3.9/site-packages/electrum/lnpeer.py", line 2142, in _shutdown
    their_fee, their_fee_range, their_sig, drop_remote = await receive_closing_signed()
  File "/tmp/.mount_electrE9Fp2M/usr/lib/python3.9/site-packages/electrum/lnpeer.py", line 2067, in receive_closing_signed
    transaction.check_scriptpubkey_template_and_dust(their_scriptpubkey, to_remote_amount)
  File "/tmp/.mount_electrE9Fp2M/usr/lib/python3.9/site-packages/electrum/transaction.py", line 480, in check_scriptpubkey_template_and_dust
    raise Exception(f'scriptpubkey does not conform to any template: {scriptpubkey.hex()}')
```

is there any way to fix this or should I do a force close?

**Comment by ecdsa** [comment]
> `Exception('scriptpubkey does not conform to any template: 512019c...b85883')`

It looks like the remote want to close on a taproot address (version 1 segwit script).
According to the spec, version>0 scripts are allowed if `option_shutdown_anysegwit`.
Since we have that freture flag, we should allow that.

**Comment by dolcalmi** [comment]
I was not using it but it worked :) 

thanks for your help
