### ISSUE TITLE
Label sync issue - plugin + Addresses tab

### ISSUE THREAD

**Issue by OEsmir** [spesmilo/electrum#8033]
Hello, 

I am having some issues with my electrum client.

short intro: I have 3 multisig wallets which utilize cold storage to sign.

I have created some requests (a dozen more or less, with descriptions) under the Receive tab some time ago. 
Now when I create a new request, it shows me an address from a previously created request (and this happens for all the addresses previously created).

Furthermore, I think related to this, when I try to force LabelSync, it throws an error. here from the logs: 

20221024T085840.002964Z |    ERROR | plugins.labels.qt.Plugin | Error synchronising labels
Traceback (most recent call last):
  File "electrum\gui\qt\util.py", line 1223, in run
  File "C:\Program Files (x86)\Electrum\electrum\plugins\labels\labels.py", line 181, in push
    return asyncio.run_coroutine_threadsafe(self.push_thread(wallet), wallet.network.asyncio_loop).result()
  File "concurrent\futures\_base.py", line 446, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "C:\Program Files (x86)\Electrum\electrum\plugins\labels\labels.py", line 124, in push_thread
    await self.do_post("/labels", bundle)
  File "C:\Program Files (x86)\Electrum\electrum\plugins\labels\labels.py", line 101, in do_post
    async with session.post(url, json=data) as result:
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 559, in _request
  File "aiohttp\client_reqrep.py", line 913, in start
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

Is anyone please able to help? It's heavily affecting my usage of the wallets and creating big inconveniences.

**Comment by OEsmir** [comment]
Hi @SomberNight - all the wallets are online. 
The watch-only are only used to visualize and share the transaction history with others (and now the labels are not syncing for a long time)
Cold storage: hardware devices (trezor/ledger)
