### ISSUE TITLE
import x509 error

### ISSUE THREAD

**Issue by venzen** [spesmilo/electrum#804]
On Ubuntu 14.04 running python 2.7 and just cloned the master branch of Electrum.

Installed repo packages for `slowaes`, `pyasn1` and `tlslite`.

Execute `./electrum` in the local directory: 

``` bash
Traceback (most recent call last):
  File "./electrum", line 42, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/home/venzen/sourcecode/electrum/lib/__init__.py", line 6, in <module>
    from network import Network, DEFAULT_SERVERS, DEFAULT_PORTS, pick_random_server
  File "/home/venzen/sourcecode/electrum/lib/network.py", line 4, in <module>
    import interface
  File "/home/venzen/sourcecode/electrum/lib/interface.py", line 30, in <module>
    import x509
  File "/home/venzen/sourcecode/electrum/lib/x509.py", line 64, in <module>
    class X509(tlslite.X509):
AttributeError: 'module' object has no attribute 'X509'
```

**Comment by danindiana** [comment]
Can confirm that sudo apt-get install pyqt4-dev-tools was necessary for me to get electrum up and running on Ubuntu 14.04.
