### ISSUE TITLE
QML channel list filtering bug

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#8205]
that issue is still there:

```
Traceback (most recent call last):
  File "/opt/electrum/electrum/gui/qml/qemodelfilter.py", line 29, in filterAcceptsRow
    d = parent_model.data(parent_model.index(s_row, 0, s_parent), self.filterRole())
  File "/opt/electrum/electrum/gui/qml/qechannellistmodel.py", line 67, in data
    value = tx[self._ROLE_NAMES[role_index]]
IndexError: tuple index out of range

```

**Comment by accumulator** [comment]
I'm unable to reproduce the issue, and I have no clue how it could happen.

The only reason I can think of is that there's maybe an issue with your version of PyQt5..

Can you reproduce it on android?

**Comment by ecdsa** [comment]
could not reproduce on android. closing.
