### ISSUE TITLE
"bad file descriptor" on broadcast when disconnected

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#835]
Tried broadcasting a tx in disconnected (red blobb) state. Getting this on each click on "broadcast" button in tx preview page:

```
Traceback (most recent call last):
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/util.py", line 300, in _send
    sent = self.socket.send(out)
  File "/usr/lib64/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

**Comment by ecdsa** [comment]
I guess it's fixed now
