### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by spidy0x0** [spesmilo/electrum#8640]
i installed electrum with python

```bash
wget https://download.electrum.org/4.4.6/Electrum-4.4.6.tar.gz
wget https://download.electrum.org/4.4.6/Electrum-4.4.6.tar.gz.asc
gpg --verify Electrum-4.4.6.tar.gz.asc
python3 -m pip install --user Electrum-4.4.6.tar.gz
```

then i run ```electrum```

```
Traceback (most recent call last):
  File "/home/spidy/.local/bin/electrum", line 94, in <module>
    from electrum.logging import get_logger, configure_logging  # import logging submodule first
  File "/home/spidy/.local/lib/python3.9/site-packages/electrum/__init__.py", line 19, in <module>
    from .util import format_satoshis
  File "/home/spidy/.local/lib/python3.9/site-packages/electrum/util.py", line 59, in <module>
    import dns.resolver
  File "/home/spidy/.local/lib/python3.9/site-packages/dns/resolver.py", line 38, in <module>
    import dns.query
  File "/home/spidy/.local/lib/python3.9/site-packages/dns/query.py", line 43, in <module>
    from requests_toolbelt.adapters.source import SourceAddressAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 56, in <module>
    from requests.packages.urllib3.contrib.pyopenssl \
  File "/home/spidy/.local/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

how do i fix this?

**Comment by spidy0x0** [comment]
fixed it by running
```pip install pyopenssl --upgrade```
