### ISSUE TITLE
Export Private keys bug

### ISSUE THREAD

**Issue by Tafelpoot** [spesmilo/electrum#884]
I got this error when exporting my private keys in the Qt electrum version.
It is an xpub (seed v10) wallet with no password, containing 27 keys. It has received 1 single transaction.
UI gets stuck on the 26th key.

    Exception in thread Thread-22:
    Traceback (most recent call last):
      File "C:\WinPython-32bit-2.7.6.3\python-2.7.6\lib\threading.py", line 810, in
    __bootstrap_inner
        self.run()
      File "C:\WinPython-32bit-2.7.6.3\python-2.7.6\lib\threading.py", line 763, in
    run
        self.__target(*self.__args, **self.__kwargs)
      File "C:\Users\xxxxxxxxxxxxxx\Documents\GIT\electrum\gui\qt\main_window.py",
    line 2306, in privkeys_thread
        private_keys[addr] = "\n".join(self.wallet.get_private_key(addr, password))
      File "C:\Users\xxxxxxxxxxxxx\Documents\GIT\electrum\lib\wallet.py", line 359
    , in get_private_key
        return self.accounts[account_id].get_private_key(sequence, self, password)
    KeyError: '1'

**Comment by ecdsa** [comment]
fixed in da968b60e474a39bcea99c498010a478a7d75748
