### ISSUE TITLE
ImportError: No module named pbkdf2

### ISSUE THREAD

**Issue by ixcoin123** [spesmilo/electrum#889]
I just cloned the repository on my computer (OS X) and tried to launch Electrum `./electrum`. I'm getting this error:

``` bash
$ ./electrum                                                      [master]
Traceback (most recent call last):
  File "./electrum", line 42, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/Users/ixcoin/Code/peatio/electrum/lib/__init__.py", line 3, in <module>
    from wallet import WalletSynchronizer, WalletStorage
  File "/Users/ixcoin/Code/peatio/electrum/lib/wallet.py", line 40, in <module>
    from mnemonic import Mnemonic
  File "/Users/ixcoin/Code/peatio/electrum/lib/mnemonic.py", line 27, in <module>
    import pbkdf2
ImportError: No module named pbkdf2
```

I tried `pip install pbkdf2` but still getting the error.

**Comment by aswordok** [comment]
如果你是在虚拟环境中按装失败，先到系统环境中安装一遍，再回到虚拟环境中安装一遍。
