### ISSUE TITLE
Unable to initialize/create seed with a Trezor Safe 3

### ISSUE THREAD

**Issue by zx9r** [spesmilo/electrum#8892]
I am running trezorlib 0.13.8 and Electum 4.5.2

I installed trezorlib with:

pip3 install --upgrade trezor
pip3 install --upgrade trezor[hidapi]

Connected a new Trezor Safe 3 and it seems Electrum recognizes it well. However when creating a new wallet and initalizing the device (just before the step when the 12 seed words would be created) Electrum says this error:

> RuntimeError('UnexpectedMessage: Unexpected message')

and nothing else happens, it doesnt initiate the seed creation

**Comment by SomberNight** [comment]
I can reproduce. The error happens when I try to initialise a new device, and looks specific to the safe 3 (does not happen with previous models).

<details>
 <summary>Traceback</summary>

```
 13.54 | E | plugins.trezor.qt.WCTrezorInit | RuntimeError('UnexpectedMessage: Unexpected message')
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/plugins/trezor/clientbase.py", line 264, in reset_device
    return trezorlib.device.reset(self.client, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 285, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 308, in wrapped_f
    return f(client, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/trezorlib/device.py", line 202, in reset
    resp = client.call(msg)
  File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 308, in wrapped_f
    return f(client, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/trezorlib/client.py", line 268, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: UnexpectedMessage: Unexpected message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/plugins/trezor/qt.py", line 889, in initialize_device_task
    self.plugin._initialize_device(settings, method, device_id, handler)
  File "/home/user/wspace/electrum/electrum/plugin.py", line 406, in wrapper
    return run_in_hwd_thread(partial(func, *args, **kwargs))
  File "/home/user/wspace/electrum/electrum/plugin.py", line 399, in run_in_hwd_thread
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/wspace/electrum/electrum/plugins/trezor/trezor.py", line 234, in _initialize_device
    client.reset_device(
  File "/home/user/wspace/electrum/electrum/plugin.py", line 406, in wrapper
    return run_in_hwd_thread(partial(func, *args, **kwargs))
  File "/home/user/wspace/electrum/electrum/plugin.py", line 396, in run_in_hwd_thread
    return func()
  File "/home/user/wspace/electrum/electrum/plugins/trezor/clientbase.py", line 263, in reset_device
    with self.run_flow():
  File "/home/user/wspace/electrum/electrum/plugins/trezor/clientbase.py", line 85, in __exit__
    raise RuntimeError(str(e)) from e
RuntimeError: UnexpectedMessage: Unexpected message
```
</details>

i.e. `device.reset` in trezorlib raises here:
https://github.com/trezor/trezor-firmware/blob/4e11b166741476d3f592f439571d148412e06c3a/python/src/trezorlib/device.py#L202

I can also reproduce using hwi 2.4.0:
```
$ hwi enumerate
[{"type": "trezor", "path": "webusb:001:2", "label": null, "model": "trezor_safe 3", "needs_pin_sent": null, "needs_passphrase_sent": false, "error": "Not initialized", "code": -18}]
$ hwi --device-path webusb:001:2 --device-type trezor --interactive setup
{"error": "UnexpectedMessage: Unexpected message", "code": -13}
```

**Comment by SomberNight** [comment]
Ah ok, I see, this happens if there is no firmware installed on the device :P

**Comment by SomberNight** [comment]
I've added a better error message for this case in https://github.com/spesmilo/electrum/commit/130baf13c83f14061003601d5780eb60ae05f6b2.
@zx9r to be clear, this is not really a bug, electrum expects the device to already have a firmware installed. You need to use the Trezor's tooling to do this. Either use their webwallet, the trezor suite desktop app, or the trezorctl command-line tool.
