### ISSUE TITLE
Inability to run Appimage

### ISSUE THREAD

**Issue by RampantDespair** [spesmilo/electrum#9142]
When running the Appimage `4.5.5` I get the following error:
```
Error: Symbol sqlite3_total_changes not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016050 (0x60a6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_user_data not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b0160b8 (0x6176) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_result_text not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b0160e8 (0x61d6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_trace_v2 not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b0160f8 (0x61f6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_create_collation not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016278 (0x64f6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_bind_text not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b0163f0 (0x67e6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_progress_handler not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016400 (0x6806) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_bind_blob not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016408 (0x6816) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_set_authorizer not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016460 (0x68c6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_result_blob not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b0164a0 (0x6946) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_create_function_v2 not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016550 (0x6aa6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: Symbol sqlite3_backup_pagecount not found, cannot apply R_X86_64_JUMP_SLOT @0x3f2b016570 (0x6ae6) in /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Error: relocating Plt symbols in elf _sqlite3.cpython-310-x86_64-linux-gnu.so
Error initializing needed lib /tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/tmp/.mount_electr3MiLFc/usr/bin/electrum", line 94, in <module>
    from electrum.logging import get_logger, configure_logging  # import logging submodule first
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/__init__.py", line 20, in <module>
    from .wallet import Wallet
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/wallet.py", line 84, in <module>
    from .lnworker import LNWallet
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/lnworker.py", line 52, in <module>
    from .lnpeer import Peer, LN_P2P_NETWORK_TIMEOUT
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/lnpeer.py", line 30, in <module>
    from .lnrouter import RouteEdge
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/lnrouter.py", line 39, in <module>
    from .channel_db import ChannelDB, Policy, NodeInfo
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/channel_db.py", line 40, in <module>
    from .sql_db import SqlDB, sql
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/site-packages/electrum/sql_db.py", line 5, in <module>
    import sqlite3
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/tmp/.mount_electr3MiLFc/usr/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: Cannot dlopen("/tmp/.mount_electr3MiLFc/usr/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so"/0x6155e720, 2)
```
I've tried manually installing `libsqlite3-dev` and reinstalling `python3`, but that didn't work.
Did I miss a step in the setup?

**Comment by SomberNight** [comment]
Could you re-test with latest release (4.5.8)?
Also, which Linux distro are you using? What version of glibc do you have?
