### ISSUE TITLE
dumpprivkeys() KeyError: '1'

### ISSUE THREAD

**Issue by xilanma** [spesmilo/electrum#935]
Steps to reproduce:

1. Create new wallet
2. Go to the console tab and type: `dumpprivkeys()`

```python
>> 
Welcome to Electrum!
>> dumpprivkeys()
Traceback (most recent call last):
  File "/Users/xilanma/electrum/gui/qt/main_window.py", line 1693, in <lambda>
    return lambda *args: apply( f, (method, args, self.password_dialog ))
  File "/Users/xilanma/electrum/lib/commands.py", line 129, in _run
    result = f(*args)
  File "/Users/xilanma/electrum/lib/commands.py", line 205, in dumpprivkeys
    return [self.wallet.get_private_key(address, self.password) for address in addresses]
  File "/Users/xilanma/electrum/lib/wallet.py", line 355, in get_private_key
    return self.accounts[account_id].get_private_key(sequence, self, password)
KeyError: '1'
>> 
``` 

For some reason, this bug doesn't happen with my old wallet file, only if I create a new one.

**Comment by ecdsa** [comment]
fixed in da968b60e474a39bcea99c498010a478a7d75748
