### ISSUE TITLE
Cannot export private keys in dev version

### ISSUE THREAD

**Issue by hamboy** [spesmilo/electrum#959]
When the dialog is open after entering the password, it counts up until it's stuck ("Please wait... 23/24"):

```
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/bin/electrum/gui/qt/main_window.py", line 2350, in privkeys_thread
    private_keys[addr] = "\n".join(self.wallet.get_private_key(addr, password))
  File "/home/user/bin/electrum/lib/wallet.py", line 356, in get_private_key
    return self.accounts[account_id].get_private_key(sequence, self, password)
KeyError: u'1'
```

**Comment by ecdsa** [comment]
fixed in da968b60e474a39bcea99c498010a478a7d75748
